Update Playbook page layout
mainmatter/mainmatter.com pull request #1002
Opened 2020-03-16 23:48 UTC by locks

2020-03-20 13:41 UTC, ghislaineguerin commented
@locks we also need the negative margin on the bottom shape
![image](https://user-images.githubusercontent.com/845767/77168852-d21f1300-6ab8-11ea-8fc2-f83667f3a547.png)

2020-03-20 13:46 UTC, marcoow requested changes
This looks like in Abstract of course but I think it's a bit strange since _"Organization of this book"_ is actually closer to the previous section than the one it actually belongs to…

<img width="1088" alt="Bildschirmfoto 2020-03-20 um 14 41 37" src="https://user-images.githubusercontent.com/1510/77169354-a2243f80-6ab9-11ea-8bbb-90b008f557b5.png">

2020-03-20 13:46 UTC, marcoow commented on src/ui/components/PagePlaybook/stylesheet.css
> +.accent {
This does not seem to be used anywhere?

2020-03-20 13:46 UTC, marcoow commented on src/ui/components/ShapePlaybook/component-test.ts
> +module('Component: ShapeFeature', function(hooks) {
```suggestion
module('Component: ShapePlaybook', function(hooks) {
```

2020-03-20 13:46 UTC, marcoow commented on src/ui/components/ShapePlaybook/component-test.ts
> +    await render(hbs`<ShapeFeature />`);
```suggestion
    await render(hbs`<ShapePlaybook />`);
```

2020-03-20 13:46 UTC, marcoow commented on src/ui/components/ShapePlaybook/component-test.ts
> +  module('when invoked with a @srcset', function() {
This should not be needed

2020-03-20 13:46 UTC, marcoow commented on src/ui/components/ShapePlaybook/component-test.ts
> +  module('when invoked without a @srcset', function() {
This should not be needed

2020-03-20 13:46 UTC, marcoow commented on src/ui/components/ShapeQuoteTrainline/component-test.ts
> +module('Component: ShapeQuoteCardstack', function(hooks) {
```suggestion
module('Component: ShapeQuoteTrainline', function(hooks) {
```

2020-03-20 13:46 UTC, marcoow commented on src/ui/components/ShapeQuoteTrainline/component-test.ts
> +    await render(hbs`<ShapeQuoteCardstack />`);
```suggestion
    await render(hbs`<ShapeQuoteTrainline />`);
```

2020-03-20 13:46 UTC, marcoow commented on src/ui/components/ShapeQuoteTrainline/stylesheet.css
> +  block-name: ShapeQuoteCardstack;
```suggestion
  block-name: ShapeQuoteTrainline;
```

2020-03-20 13:46 UTC, marcoow commented on src/ui/components/ShapeQuoteTrainline/template.hbs
> +  @srcAlt="Cardstack"
```suggestion
  @srcAlt="Trainline"
```

2020-03-20 14:21 UTC, locks commented on src/ui/components/PagePlaybook/stylesheet.css
> +.accent {
It is used in the "Organization of this book" numbering:

```
      <div block:class="accent">
        01
      </div>
```

2020-03-20 14:28 UTC, marcoow commented on src/ui/components/PagePlaybook/stylesheet.css
> +.accent {
Ah, missed that. We should not set font sizes in `px` thought but be consistent in using `rem`.

2020-03-20 14:33 UTC, locks commented
@ghislaineguerin do you have mobile viewport designs for the playbook download shape?

2020-03-20 14:51 UTC, locks commented
> @locks we also need the negative margin on the bottom shape
Apologies @ghislaineguerin, I do not understand which shape this applies to.

2020-03-23 09:41 UTC, ghislaineguerin commented
@locks 
here's the mobile version
https://share.goabstract.com/d8bc6dbd-34f7-4249-a655-342aa6758535?mode=design&sha=fbe8b5e3307cb0f350275d304dd046e389cfb16a

2020-04-14 12:18 UTC, marcoow commented
@ghislaineguerin please review but don't merge yet

2020-04-14 12:21 UTC, marcoow approved these changes

2020-04-14 13:36 UTC, ghislaineguerin approved these changes
looks good

2020-04-14 13:38 UTC, merged