Create pwa-features-2020-comparison.md
mainmatter/mainmatter.com pull request #1135
Opened 2020-06-04 10:14 UTC by arthurp1

I've added 2 different Markdown styles because I don't know how they would render well.

2020-06-04 10:22 UTC, marcoow commented
@arthurp1 this requires some fixes but I can take over, don't worry about understanding all of the (rather complex) stuff here…

2020-06-04 13:19 UTC, marcoow commented
@arthurp1 I fixed the markdown, reviewed the text etc. – please check again. I think we should publish tomorrow.

@ghislaineguerin can you add an og-image please?

2020-06-04 13:33 UTC, marcoow commented
@arthurp1 please also give me your author image

2020-06-05 10:21 UTC, arthurp1 commented
[author_image_AP](https://media-exp1.licdn.com/dms/image/C4E03AQGPk_OhWwSqig/profile-displayphoto-shrink_400_400/0?e=1596672000&v=beta&t=cWlVq5ViTd2iyPd2BGj6ZnWOSqj_DrSprUxVJ1rABd8)

2020-06-05 11:44 UTC, marcoow requested changes

2020-06-05 11:44 UTC, marcoow commented on _posts/2020-06-05-pwa-features-2020-comparison.md
> +with the native user interactions offered by the operating software. For example, native push
```suggestion
with the native user interactions offered by the operating system. For example, native push
```

2020-06-05 11:44 UTC, marcoow commented on _posts/2020-06-05-pwa-features-2020-comparison.md
> +is on an iPhone or iPad. So it really depends on what audience you try to serve.
```suggestion
are on iPhones or iPads. So it really depends on what audience you try to serve.
```

To me that sounds better than referring to singular devices.

2020-06-10 10:43 UTC, arthurp1 commented
I resolved the requested changes. I see the percy/simplabs.com checks are unsuccessful. Is this important, could you check it? Anything else before we could post it?

2020-06-10 10:52 UTC, marcoow reviewed
@arthurp1 I'd suggest a more expressive title?

2020-06-10 10:52 UTC, marcoow commented on _posts/2020-06-05-pwa-features-2020-comparison.md
> +title: 'PWA support on mobile and desktop in 2020'
```suggestion
title: 'The state of PWA support on mobile and desktop in 2020'
```

2020-06-10 11:27 UTC, arthurp1 commented
Can I merge it?

2020-06-10 11:38 UTC, marcoow commented
@arthurp1 no, the `og:image` is missing – see https://app.abstract.com/projects/c2d6fda0-836d-4507-92b5-635b3e333b4d/branches/3ad212eb-81a6-44ec-98fa-25b40c5f3c09

2020-06-10 11:41 UTC, marcoow approved these changes

2020-06-10 12:00 UTC, merged

2020-06-10 12:04 UTC, arthurp1 commented
> @arthurp1 no, the `og:image` is missing – see https://app.abstract.com/projects/c2d6fda0-836d-4507-92b5-635b3e333b4d/branches/3ad212eb-81a6-44ec-98fa-25b40c5f3c09

@ghislaineguerin can you help with this?