wording fixes
mainmatter/mainmatter.com pull request #119
Opened 2017-08-14 13:58 UTC by marcoow

2017-08-14 14:29 UTC, jayjayjpg reviewed
Just a few minor comments from my side 💬

2017-08-14 14:29 UTC, jessica-jordan commented on work/index.html
> +          <p><strong>Ember.js, Elixir and Phoenix</strong> as well as Ruby on Rails are the foundation of our toolbox. The <strong>conventions-based approach</strong> that they all share make them a
I believe it's either `convention based` or `convention-based` here, but it would be good to have @geekygrappler 's look on that as well

2017-08-14 14:29 UTC, jessica-jordan commented on services/index.html
> +          <p>Having <strong>years of experience with Ember.js</strong>, Ruby on Rails, distributed systems, scaling of large applications and related technologies, we can <strong>plan and review arch
I think it would also be really cool to mention that we actually work on performance improvements ourselves once the `performance bottlenecks` have been found as well. What are your thoughts on this @geekygrappler and @marcoow ?

2017-08-14 14:29 UTC, jessica-jordan commented on clients/index.html
> +        <p>We have a track record of <strong>projects for international clients</strong> from small startups to established businesses.</p>
That sounds smooth

2017-08-14 14:32 UTC, marcoow commented on services/index.html
> +          <p>Having <strong>years of experience with Ember.js</strong>, Ruby on Rails, distributed systems, scaling of large applications and related technologies, we can <strong>plan and review arch
makes sense - added that

2017-08-28 11:28 UTC, marcoow commented
@jessica-jordan, @geekygrappler: any updates?

2017-08-28 18:24 UTC, jessica-jordan commented on work/index.html
> +          <p><strong>Ember.js, Elixir and Phoenix</strong> as well as Ruby on Rails are the foundation of our toolbox. The <strong>conventions-based approach</strong> that they all share make them a
This is the only thing I'm wondering about, otherwise it's good to go from my side :thumbsup:

2017-08-29 07:19 UTC, marcoow commented on work/index.html
> +          <p><strong>Ember.js, Elixir and Phoenix</strong> as well as Ruby on Rails are the foundation of our toolbox. The <strong>conventions-based approach</strong> that they all share make them a
I think @oliverbarnes suggested that. I think he and/or @geekygrappler can clarify?

2017-08-29 07:45 UTC, jayjayjpg commented on work/index.html
> +          <p><strong>Ember.js, Elixir and Phoenix</strong> as well as Ruby on Rails are the foundation of our toolbox. The <strong>conventions-based approach</strong> that they all share make them a
See also 
- ["Getting started with convention-based part [...]"](https://blogs.msdn.microsoft.com/bclteam/2011/11/01/getting-started-with-convention-based-part-registration-in-mef-2-nick/)
- ["Convention based syntactic [...]"](http://ieeexplore.ieee.org/document/5170425/?reload=true)
- ["Convention Based Routing in [...]"](https://modernweb.com/convention-based-routing-in-javascript-apps/)
- ["A call to set up convention-based routes might look like [...]"](https://exceptionnotfound.net/attribute-routing-vs-convention-routing/)

2017-08-29 16:08 UTC, oliverbarnes commented on clients/index.html
> +        <p>We have a track record of <strong>projects for international clients</strong> from small startups to established businesses.</p>
👍

2017-08-29 16:10 UTC, oliverbarnes commented on work/index.html
> +          <p><strong>Ember.js, Elixir and Phoenix</strong> as well as Ruby on Rails are the foundation of our toolbox. The <strong>conventions-based approach</strong> that they all share make them a
convention-based does sound better, if I suggested the plural version, I retract :)

2017-08-29 16:13 UTC, oliverbarnes requested changes

2017-08-29 16:13 UTC, oliverbarnes commented on services/index.html
> +        <p>We offer <strong>Software Engineering</strong>, Technology Consulting as well as Individual and Group <strong>Training</strong>.</p>
I'd have these in lowercase

2017-08-29 16:13 UTC, oliverbarnes commented on services/index.html
> +          <p>For clients that have an in-house engineering team already, we can <strong>augment that team</strong> to help reach delivery deadlines or improve quality. By working closely with our exp
`engineers` instead of `developers` is a nice touch as well 👍

2017-08-29 18:08 UTC, marcoow commented on services/index.html
> +          <p>For clients that have an in-house engineering team already, we can <strong>augment that team</strong> to help reach delivery deadlines or improve quality. By working closely with our exp
Yeah, I think that's something we should do in general.

2017-08-29 18:10 UTC, marcoow commented on work/index.html
> +          <p><strong>Ember.js, Elixir and Phoenix</strong> as well as Ruby on Rails are the foundation of our toolbox. The <strong>conventions-based approach</strong> that they all share make them a
fixed

2017-08-29 18:11 UTC, marcoow commented on services/index.html
> +        <p>We offer <strong>Software Engineering</strong>, Technology Consulting as well as Individual and Group <strong>Training</strong>.</p>
fixed

2017-08-30 09:48 UTC, oliverbarnes approved these changes

2017-08-30 09:49 UTC, merged