[Case Studies] Qonto
mainmatter/mainmatter.com pull request #1228
Opened 2020-08-10 14:42 UTC by locks

This PR intends to ship the Qonto case study page using the current design.
This is so that we can quickly ship the case study and re-use as much of the current code as possible, with a follow-up task taking care of the redesign.

## Tasks
- Create qonto case study page component
- Add route map entry for page
- Fill in final copy
- Implement quote section
- Add optimized images for 600px and 1200px breakpoint

##  Resources
- [Abstract](https://share.goabstract.com/1592c316-fa9d-412d-8cf9-0849b379e0f9)

2020-08-11 14:19 UTC, marcoow reviewed
This looks nice. There seem to be a bunch of unrelated changes in this PR though. Also there are 2 things that are not in line with the design I think:

<img width="1209" alt="Bildschirmfoto 2020-08-11 um 16 13 42" src="https://user-images.githubusercontent.com/1510/89908528-46845b00-dbee-11ea-828b-1b4cb440465e.png">
The image seems to be higher than the text – maybe additional offset before the text?

<img width="616" alt="Bildschirmfoto 2020-08-11 um 16 13 50" src="https://user-images.githubusercontent.com/1510/89908581-556b0d80-dbee-11ea-988f-b17e48331ed2.png">
I think the background of the text should be purple on mobile.

2020-08-11 14:19 UTC, marcoow commented on package.json
> +  }
Can we move this into a separate PR?

2020-08-11 14:19 UTC, marcoow commented on public/assets/images/card/qonto.svg
> +</svg>
Can you run this  through svgo?

2020-08-11 14:19 UTC, marcoow commented on src/ui/components/PageCaseDdWrt/template.hbs
>    <Footer />
All changes to this file seem unrelated?

2020-08-11 14:19 UTC, marcoow commented on src/ui/components/PageCaseStudyQonto/component-test.ts
> +    await render(hbs`<PageCaseDdWrt />`);
```suggestion
    await render(hbs`<PageCaseStudyQonto />`);
```

2020-08-11 14:19 UTC, marcoow commented on src/ui/components/PageCaseStudyQonto/stylesheet.css
> +  block-name: PageCaseStudyTrainline;
```suggestion
  block-name: PageCaseStudyQonto;
```

2020-08-11 14:19 UTC, marcoow commented on src/ui/components/PageCaseStudyTimify/template.hbs
>    <div layout:class="side" block:class="vertical-offset" offset:class="after-21">
These changes all seem to be unrelated?

2020-08-11 14:26 UTC, izelnakri commented on src/ui/components/PageCaseDdWrt/template.hbs
>    <Footer />
Ricardo had these changes in the PR, would you like me to move them to smw else? Might be better to keep them in this PR, since after pairing with Mar, we've added few mobile adjustments to other case study pages.

2020-08-11 14:38 UTC, locks commented
The unrelated formatting changes are likely from opening the file in my editor and it running the formatting plugin, sorry!

2020-08-11 15:15 UTC, marcoow commented on src/ui/components/PageCaseDdWrt/template.hbs
>    <Footer />
As discussed in our call, we'll move all changes that are not essential to the Qonto case out into separate PRs.

2020-08-13 08:38 UTC, marcoow requested changes
Looks good – just 2 small things that I commented and one visual error:

<img width="616" alt="Bildschirmfoto 2020-08-13 um 10 36 03" src="https://user-images.githubusercontent.com/1510/90113099-228d5a80-dd51-11ea-92ea-c1d215af6fa7.png">

(the background of the quote should be purple on mobile – see Abstract)

2020-08-13 08:38 UTC, marcoow commented on src/ui/components/PageCaseStudyQonto/template.hbs
> +  <ShapeFeatureTimify />
This should be Trainline:

```suggestion
  <ShapeFeatureTrainline />
```

2020-08-13 08:38 UTC, marcoow commented on src/ui/components/Footer/template.hbs
> +          </li>
I think we should add this on the top since it's our most important case.

2020-08-13 08:39 UTC, marcoow commented
@izelnakri would be good to add a screenshot to this PR – see https://github.com/simplabs/playbook/tree/master/src/development-process#pull-requests

2020-08-13 08:43 UTC, marcoow commented
@izelnakri I compressed all the images

2020-08-13 12:13 UTC, izelnakri commented
> (the background of the quote should be purple on mobile – see Abstract)

@marcoow this one is tricky to implement since the styling needs to happen in a container div with media queries unlike the actual background styling we apply to svgs inside the component with inline styling of the color. I'll try once more.

2020-08-13 16:06 UTC, izelnakri commented
@marcoow issues with the svg clipping and the css-block yielding described here: https://github.com/simplabs/simplabs.github.io/pull/1234

2020-08-13 17:36 UTC, marcoow requested changes
Just 2 more things:

* I don't think qonto-alternative@600.jpg is used anywhere? If so we should remove it
* qonto-alternative@1200.jpg looks pixelated – I think it needs to be 1800px at least or so

2020-08-14 08:19 UTC, izelnakri commented
- All other ShapeWorks had 2 image types in public folder thats why I guess they were there initially but you're right @600 is not used, so I'll remove it.
- The biggest image we have for qonto-alternative@1200.jpg is 2400x1256(instead of 1800x1350 as we normally have), so I'll crop it at 1674.248x1256 to keep the same aspect ratio.

2020-08-14 12:00 UTC, marcoow approved these changes

2020-08-14 12:01 UTC, marcoow commented
@izelnakri only 1 linting error left – feel free to merge once resolved

2020-08-14 14:36 UTC, merged