Case study pages tweaks
mainmatter/mainmatter.com pull request #1231
Opened 2020-08-11 16:27 UTC by izelnakri

2020-08-12 12:20 UTC, izelnakri commented on src/ui/styles/blocks/layout.block.css
> +    flex-direction: column;
I also cherry-picked this change, do we want this change @locks ? Heres the percy diff: https://percy.io/simplabs-com/simplabs.com/builds/6473278?utm_campaign=simplabs-com&utm_content=simplabs.com&utm_source=github_status_private

2020-08-12 12:47 UTC, marcoow requested changes
I don't think this is quiet right yet – also left some comments on Percy

2020-08-12 12:47 UTC, marcoow commented on src/ui/components/SidebarQuote/template.hbs
> +    Peter Steinhäuser, embeDD CEO
This needs to be dynamic as well.

2020-08-12 13:28 UTC, izelnakri commented
after talking with Ricardo, we've decided to keep Ricardo's changes on #1144

2020-08-13 08:24 UTC, marcoow approved these changes

2020-08-13 08:24 UTC, merged