WIP: Landing page
mainmatter/mainmatter.com pull request #128
Opened 2017-09-18 09:56 UTC by EmanuelaTrabaldoLena

Is the blue quote-banner too much?

2017-09-18 10:03 UTC, marcoow reviewed
Nice. This should really look the same as the home page though, only with different text and the quote instead of the client logos (without the blue background).

2017-09-18 10:03 UTC, marcoow commented on Gemfile.lock
> +   1.16.0.pre.2
These changes are all unrelated

2017-09-18 10:03 UTC, marcoow commented on _config.yml
> +plugins:
This is unrelated

2017-09-18 10:03 UTC, marcoow commented on disruptors/index.html
> +        <h3>Recent Case Studies</h3>
This header is not needed

2017-09-18 10:03 UTC, marcoow commented on disruptors/index.html
> +          <h6>ruby on rails, custom engineering, consulting</h6>
We should not be using these tags

2017-09-18 10:03 UTC, marcoow commented on disruptors/index.html
> +title: Disruptors
We should use the same title that we use for the home page here

2017-09-19 14:43 UTC, marcoow approved these changes

2017-09-19 15:01 UTC, pangratz commented on disruptors/index.html
> +          <p>Disrupting a market is hard enough - <strong>let an experienced partner handle the Engineering for you so you can concentrate on your core business</strong>. Our team of technology exper
Not a native speaker, but the capitalized `Engineering` caught my eye... cc @oliverbarnes @geekygrappler

2017-09-19 15:01 UTC, pangratz commented on disruptors/index.html
> +          <p>Timify is an <strong>online appointment scheduling calendar</strong> for businesses that connects service providers with clients. We <strong>helped them to ship a stable, high quality ap
IMHO `for businesses that connects service providers with clients` reads a bit halting (if that's the right word https://www.dict.cc/?s=holprig). My suggestion is something like:

> Timify is a calendar system which allows clients to schedule an appointment online.

2017-09-19 15:02 UTC, marcoow commented on disruptors/index.html
> +          <p>Timify is an <strong>online appointment scheduling calendar</strong> for businesses that connects service providers with clients. We <strong>helped them to ship a stable, high quality ap
_" connecting sellers and clients"_ is almost stereotypic startup talk though…

2017-09-19 15:03 UTC, oliverbarnes requested changes
Also, the contact footer would also be better as a regular sentence with only the first word capitalized: `Do you have a project in mind?` instead of `Do you Have a Project in Mind?`

2017-09-19 15:03 UTC, oliverbarnes commented on disruptors/index.html
> +          <p>Disrupting a market is hard enough - <strong>let an experienced partner handle the Engineering for you so you can concentrate on your core business</strong>. Our team of technology exper
**engineering** (lowercase) :)

2017-09-19 15:07 UTC, marcoow commented on disruptors/index.html
> +          <p>Disrupting a market is hard enough - <strong>let an experienced partner handle the Engineering for you so you can concentrate on your core business</strong>. Our team of technology exper
fixed

2017-09-19 15:08 UTC, marcoow commented
> instead of Do you Have a Project in Mind?

Ouch, wasn't aware we were writing it like that 🤦‍♂️ Will fix in a separate PR.

2017-09-19 15:53 UTC, oliverbarnes approved these changes

2017-09-19 19:39 UTC, niklaslong commented on disruptors/index.html
> +          <p>Timify is an <strong>online appointment scheduling calendar</strong> for businesses that connects service providers with clients. We <strong>helped them to ship a stable, high quality ap
This is a detail, but I think `We helped them ship a stable, high quality app` reads better than `to ship`.

2017-09-20 04:49 UTC, marcoow commented on disruptors/index.html
> +          <p>Timify is an <strong>online appointment scheduling calendar</strong> for businesses that connects service providers with clients. We <strong>helped them to ship a stable, high quality ap
agree

2017-09-20 09:07 UTC, jayjayjpg approved these changes
:sparkles: This looks great @EmanuelaTrabaldoLena

2017-09-21 10:50 UTC, merged

2017-09-21 10:52 UTC, marcoow commented on css/app.scss
> +
This is duplicate now: https://github.com/simplabs/simplabs.github.io/blob/master/css/app.scss#L121

2017-09-21 10:52 UTC, marcoow commented on css/typography.scss
> +}
This is now duplicate as well: https://github.com/simplabs/simplabs.github.io/blob/master/css/typography.scss#L26