[Blog] The HTML-first approach of Glimmer components
mainmatter/mainmatter.com pull request #1293
Opened 2020-09-23 14:09 UTC by locks

- [ ] Replace placeholder banner
- [ ] Prose reviewed

2020-09-24 10:28 UTC, nickschot requested changes, later dismissed
Nice post! I commented mostly linguistic changes. I'll read it again for the overall story later today.

2020-09-24 10:28 UTC, nickschot commented on _posts/2020-09-28-html-first-gllimmer-components.md
> +Glimmer components, which go hand in hand for reasons you will see later. While
I'm not sure about the "for reasons you will see later" bit of this sentence. Not sure how to rewrite it though.

2020-09-24 10:28 UTC, nickschot commented on _posts/2020-09-28-html-first-gllimmer-components.md
> +I'll be introducing Glimmer components as they relate to classic components.
With the last bit of this sentence do you mean how Glimmer Components compare/relate to Classic Components? Currently it could be read as "they are related".

2020-09-24 10:28 UTC, nickschot commented on _posts/2020-09-28-html-first-gllimmer-components.md
> +The first thing that jumps to the eye is that Glimmer components have a
"catches the eye" (I think)
```suggestion
The first thing that catches the eye is that Glimmer components have a
```

2020-09-24 10:28 UTC, nickschot commented on _posts/2020-09-28-html-first-gllimmer-components.md
> +How you define component actions also suffers an adjustment. First, a bit of
Not sure if "suffers" is the right word here? "requires" maybe?

2020-09-24 10:28 UTC, nickschot commented on _posts/2020-09-28-html-first-gllimmer-components.md
> +But now that Glimmer components have a quite a small API (roughly `willDestroy`,
```suggestion
But now that Glimmer components have quite a small API surface (roughly `willDestroy`,
```

2020-09-24 10:28 UTC, nickschot commented on _posts/2020-09-28-html-first-gllimmer-components.md
> +the component, and then refer to them directly in the template.
So my comma knowledge in English is a bit rusty, but I think a comma is not necessary before "and"
```suggestion
the component and then refer to them directly in the template.
```

2020-09-24 10:28 UTC, nickschot commented on _posts/2020-09-28-html-first-gllimmer-components.md
> +I won't go into default on the `action` to `on` modifier changes, but notice how
```suggestion
I won't go into detail on the `action` to `on` modifier changes, but notice how
```

2020-09-24 10:28 UTC, nickschot commented on _posts/2020-09-28-html-first-gllimmer-components.md
> +getter, and we defined the action handler as a decorated method. You might also
Same thing with the ", and" here as above.
```suggestion
getter and we defined the action handler as a decorated method. You might also
```

2020-09-24 10:28 UTC, nickschot commented on _posts/2020-09-28-html-first-gllimmer-components.md
> +like `{{this.something}}` and `{{@something}}` in the template.
I would somewhat rewrite this sentence to make the transition from "as it's explicit in the class what is a property" smoother.

Maybe: "as what is a property ... and what is an argument ... is explicitly defined in the class"

2020-09-24 10:28 UTC, nickschot commented on _posts/2020-09-28-html-first-gllimmer-components.md
> +component. Ember components have a very distinct characteristic, the component's
```suggestion
components. Ember components have a very distinct characteristic, the component's
```

2020-09-24 10:28 UTC, nickschot commented on _posts/2020-09-28-html-first-gllimmer-components.md
> +button component that receive a `primary` CSS class, and can receive a
```suggestion
button component that receives a `primary` CSS class, and can receive a
```

2020-09-24 10:28 UTC, nickschot commented on _posts/2020-09-28-html-first-gllimmer-components.md
> +and functionality, Ember has diminished the uncertain of whether a certain
```suggestion
and functionality, Ember has diminished the uncertainty of whether a certain
```

2020-09-24 10:28 UTC, nickschot commented on _posts/2020-09-28-html-first-gllimmer-components.md
> +for you, and at the very least gave you a renewed appreciation for the Octane
```suggestion
for you and at the very least gave you a renewed appreciation for the Octane
```

2020-09-24 15:30 UTC, marcoow reviewed
Nice post! I left a few comments.

2020-09-24 15:30 UTC, marcoow commented on _posts/2020-09-28-html-first-gllimmer-components.md
> +and streamlined APIs. At the core of the release are tracked properties and
could we add a link to the guide for tracked properties?

2020-09-24 15:30 UTC, marcoow commented on _posts/2020-09-28-html-first-gllimmer-components.md
> +Glimmer components, which go hand in hand for reasons you will see later. While
I think it could just be leaved out?

2020-09-24 15:30 UTC, marcoow commented on _posts/2020-09-28-html-first-gllimmer-components.md
> +Octane, and subsequently Glimmer components, has been out for quite some time,
```suggestion
Octane, and subsequently Glimmer components, have been out for quite some time,
```

?

2020-09-24 15:30 UTC, marcoow commented on _posts/2020-09-28-html-first-gllimmer-components.md
> +you are likely using Ember (or classic) components in your application. To give
```suggestion
you are likely using Ember (or _"classic"_) components in your application. To give
```

I think that makes it clearer what you're trying to say here.

2020-09-24 15:30 UTC, marcoow commented on _posts/2020-09-28-html-first-gllimmer-components.md
> +- Glimmer components do not extend from EmberObject, and use the native `class`
```suggestion
- Glimmer components do not extend from `EmberObject`, and use the native `class`
```

2020-09-24 15:30 UTC, marcoow commented on _posts/2020-09-28-html-first-gllimmer-components.md
> +component no longer inherits from EmberObject. Now you should use native getters
```suggestion
component no longer inherits from `EmberObject`. Now you should use native getters
```

2020-09-24 15:30 UTC, marcoow commented on _posts/2020-09-28-html-first-gllimmer-components.md
> +component no longer inherits from EmberObject. Now you should use native getters
```suggestion
component no longer inherits from EmberObject. Now you can use native getters
```

sounds more positive?

2020-09-24 15:30 UTC, marcoow commented on _posts/2020-09-28-html-first-gllimmer-components.md
> +`isDestroying` and `isDestroyed`), we can go back to defining them as methods in
```suggestion
`isDestroying` and `isDestroyed` methods only), we can go back to defining them as methods in
```

2020-09-24 15:30 UTC, marcoow commented on _posts/2020-09-28-html-first-gllimmer-components.md
> +But now that Glimmer components have a quite a small API (roughly `willDestroy`,
```suggestion
But now that Glimmer components have a quite a small API (essentially the `willDestroy`,
```

2020-09-24 15:30 UTC, marcoow commented on _posts/2020-09-28-html-first-gllimmer-components.md
> +the component, and then refer to them directly in the template.
```suggestion
the component, and then refer to them directly in the template without risking unintentional overrides.
```

?

2020-09-24 15:30 UTC, marcoow commented on _posts/2020-09-28-html-first-gllimmer-components.md
> +value from within the component.
Would this benefit of some added information about what the negative consequences of that are?

2020-09-24 15:30 UTC, marcoow commented on _posts/2020-09-28-html-first-gllimmer-components.md
> +component tree isn't accidentally two-way bound.
Would this benefit of some added information about what the negative consequences of two-way bindings are?

2020-09-24 15:30 UTC, marcoow commented on _posts/2020-09-28-html-first-gllimmer-components.md
> +like `{{this.something}}` and `{{@something}}` in the template.
Would it also make things clearer to use `this.pasta`, `this.args.pasta` etc. vs. `something`?

2020-09-24 15:30 UTC, marcoow commented on _posts/2020-09-28-html-first-gllimmer-components.md
> +<MyButton>Click me</MyButton>                                                   {{!-- renders --}} <button class="primary">Click me</button>
```suggestion
<MyButton>Click me</MyButton>
{{!-- renders <button class="primary">Click me</button>  --}}
```

You won't see the comment when the line is super long. I'd change the others like this as well.

2020-09-24 15:30 UTC, marcoow commented on _posts/2020-09-28-html-first-gllimmer-components.md
> +<MultipleClasses class="two" />
Would it be easier to use the above button as an example here?

2020-09-24 15:30 UTC, marcoow commented on _posts/2020-09-28-html-first-gllimmer-components.md
> +<MyButton>Click me</MyButton>                                               {{!-- renders --}} <button class="primary">Click me</button>
```suggestion
<MyButton>Click me</MyButton>
{{!-- renders <button class="primary">Click me</button> --}}
```

see above – I'd change like this for all of the invocations.

2020-09-24 15:30 UTC, marcoow commented on _posts/2020-09-28-html-first-gllimmer-components.md
> +called "magic". This is when something the framework does something for you that
```suggestion
called "magic". This is when something the framework does for you that
```

2020-09-24 15:30 UTC, marcoow commented on _posts/2020-09-28-html-first-gllimmer-components.md
> +title: 'The HTML-first approach of Glimmer components'
Is this a fitting title? HTML-first is really only one point in the post after all and comes more at the end. Maybe something like

```suggestion
title: 'How Glimmer components makes working with components in Ember simpler and more powerful'
```

or so?

2020-09-28 14:44 UTC, locks commented on _posts/2020-09-28-html-first-gllimmer-components.md
> +<MyButton>Click me</MyButton>                                               {{!-- renders --}} <button class="primary">Click me</button>
I moved the "renders" to a newline but kept the markup outside of the handlebars comment so they get syntax highlighting.

2020-09-28 14:47 UTC, locks commented on _posts/2020-09-28-html-first-gllimmer-components.md
> +Octane, and subsequently Glimmer components, has been out for quite some time,
Re-ordered for clarity.

2020-09-28 14:53 UTC, locks commented on _posts/2020-09-28-html-first-gllimmer-components.md
> +like `{{this.something}}` and `{{@something}}` in the template.
Re-wrote this in a more direct way. I think it is clearer now.

2020-09-28 14:53 UTC, locks commented on _posts/2020-09-28-html-first-gllimmer-components.md
> +and streamlined APIs. At the core of the release are tracked properties and
Added.

2020-09-28 14:54 UTC, locks commented on _posts/2020-09-28-html-first-gllimmer-components.md
> +I'll be introducing Glimmer components as they relate to classic components.
Re-wrote this sentence. Let me know if it's clearer @nickschot.

2020-09-28 15:02 UTC, locks commented on _posts/2020-09-28-html-first-gllimmer-components.md
> +title: 'The HTML-first approach of Glimmer components'
"Simpler and more powerful components in Ember Octane with Glimmer Components"?

2020-09-28 15:13 UTC, marcoow commented on _posts/2020-09-28-html-first-gllimmer-components.md
> +title: 'The HTML-first approach of Glimmer components'
sounds good to me 👍

2020-09-28 15:36 UTC, marcoow reviewed
nice 👍

2020-09-28 15:36 UTC, marcoow commented on _posts/2020-09-28-html-first-gllimmer-components.md
> +[Bringing clarity to templates through Ember Octane](../../../../2020/09/28/clarity-in-templates/),
The link doesn't seem to be correct. I'd recommend using an absolute link `/blog/2020/…`

2020-09-28 15:36 UTC, marcoow commented on _posts/2020-09-28-html-first-gllimmer-components.md
> +`this.args.pasta` in the class or `{{@pasta}}` in the template. If you need to
This is not really a comment on the post but is there any difference between `{{@pasta}}` and `{{this.args.pasta}}`?

2020-09-28 15:38 UTC, marcoow commented
@locks there's still some unresolved comments above but hidden by default

2020-09-29 08:22 UTC, mansona approved these changes
Great blog 🎉  I think it's a perfect balance of details and overview 😍 

I added a few minor things that should be looked at before releasing 👍

2020-09-29 08:22 UTC, mansona commented on _posts/2020-09-28-html-first-glimmer-components.md
> +I won't go into default on the `action` to `on` modifier changes, but notice how
Should this be: 
```suggestion
I won't go into details on the `action` to `on` modifier changes, but notice how
```
🤔

2020-09-29 08:22 UTC, mansona commented on _posts/2020-09-28-html-first-glimmer-components.md
> +it clear which is which. If you need access to the argument you do
```suggestion
it clear which is which. If you need access to the argument you use
```

2020-09-29 08:22 UTC, mansona commented on _posts/2020-09-28-html-first-glimmer-components.md
> +access the property, you do `this.pasta` in the class and `{{this.pasta}}` in
```suggestion
access the property, you use `this.pasta` in the class and `{{this.pasta}}` in
```

2020-09-29 08:22 UTC, mansona commented on _posts/2020-09-28-html-first-glimmer-components.md
> +<button class="one two">Multiple classes</button>
```suggestion
<button class="primary two">Multiple classes</button>
```

2020-09-29 08:22 UTC, mansona commented on _posts/2020-09-28-html-first-glimmer-components.md
> +<MyButton disabled={{true}}>Click me</MyButton>
does this work? 
```suggestion
<MyButton disabled>Click me</MyButton>
```

2020-09-29 08:22 UTC, mansona commented on _posts/2020-09-28-html-first-glimmer-components.md
> +edition design effort.
I'm not sure about this one but isn't "Octane Edition" used like a proper-name in most places 🤔 
```suggestion
Edition design effort.
```

2020-09-29 08:48 UTC, mansona commented on _posts/2020-09-28-html-first-glimmer-components.md
> +[Bringing clarity to templates through Ember Octane](/blog/2020/09/28/clarity-in-templates/),
I noticed the link seems to be going to a 404 too 🤔  I'm not sure if the suggestion is correct, might be worth double checking 
```suggestion
[Bringing clarity to templates through Ember Octane](/blog/2019/12/20/clarity-in-templates/),
```

2020-09-29 11:50 UTC, locks commented on _posts/2020-09-28-html-first-gllimmer-components.md
> +`this.args.pasta` in the class or `{{@pasta}}` in the template. If you need to
There is a slight difference. `{{@pasta}}` is directly the reference that was passed to the component, while `{{this.args.pasta}}` will only work if you have a JavaScrip instance (so no template-only components), and the component has to read the reference and then wrap it again to pass it into the instance `args`.

2020-09-30 11:25 UTC, locks commented on _posts/2020-09-28-html-first-gllimmer-components.md
> +[Bringing clarity to templates through Ember Octane](../../../../2020/09/28/clarity-in-templates/),
Link has been fixed.

2020-09-30 11:26 UTC, locks commented
I think I got everything this time. Thanks everyone, let me know if there's any further improvement!

2020-09-30 11:35 UTC, marcoow commented
@locks seems good but the image still has to be replaced. Did you check off the other tasks listed in Notion and sync with @Kristina2007 as well?

2020-09-30 12:09 UTC, locks commented
I had reached out to Mar for the og and illustration, but not to @Kristina2007. Coordinating.

2020-10-05 08:12 UTC, marcoow approved these changes

2020-10-05 09:10 UTC, merged