add ember marketing post
mainmatter/mainmatter.com pull request #1423
Opened 2021-01-08 15:04 UTC by marcoow

This is the first draft for the Ember marketing post I had meant to write for some time. I want to ask some of our friends and clients to get some quote since I think that'd be very good to have (e.g. Qonto, Clark or so, maybe Gavin from Intercom). So although this is not yet 100% complete, would be great to get some feedback!

2021-01-08 15:07 UTC, marcoow commented on _posts/2021-01-08-Ember.js-in-2021---a-beacon-of-productivity.md
> +  image: /assets/images/posts/2020-12-29-built-to-last-2-joel-kelly/og-image.png
This needs to be replaced with the real `og:image`.

2021-01-08 17:19 UTC, izelnakri approved these changes

2021-01-14 15:26 UTC, Mikek2252 commented on _posts/2021-01-08-Ember.js-in-2021---a-beacon-of-productivity.md
> +because of that is worth sharing.
```suggestion
because of that it is worth sharing.
```
I wish i could explain why but just felt like it needed an `it`

2021-01-14 15:39 UTC, Mikek2252 commented on _posts/2021-01-08-Ember.js-in-2021---a-beacon-of-productivity.md
> +[safety of the herd](https://embermap.com/notes/62-safety-of-the-herd).
maybe worth mentioning this https://upgrade.emberjs.com/ that helps show changes between version to help upgrade

2021-01-14 15:50 UTC, Mikek2252 commented on _posts/2021-01-08-Ember.js-in-2021---a-beacon-of-productivity.md
> +  [Qonto](https://qonto.com) (another successful Ember user) is building
```suggestion
  until relatively recently, e.g. Gmail or an online banking dashboard like
  what [Qonto](https://qonto.com) (another successful Ember user) is building
```
When i read this i feel like the sentence should end at `Qonto` so to me it makes the `is building` sound a little strange. But if i'm honest i'm not 100% sold on adding `what` so will have a little think about it.

2021-01-14 15:55 UTC, Mikek2252 commented on _posts/2021-01-08-Ember.js-in-2021---a-beacon-of-productivity.md
> +  [Qonto](https://qonto.com) (another successful Ember user) is building
also as a small thing, British english treats company names as collective nouns so personally i would say `are building` but i dont think that is the case in US english. To be honest this might be dumb comment because it is probably US english that is used.

2021-01-14 16:04 UTC, Mikek2252 approved these changes
I have commented a few picky things but on the whole it seems good to me, interesting about the complexity fetish bit, i wonder if the desire of complexity could be moved up stream to package contributions. i get the impression most developers consume rather than contribute but that need for complexity could be fulfilled there.

2021-01-14 18:19 UTC, pichfl reviewed
I think there are lots of brackets in this text which do not necessarily improve the reading flow. I would recommend trying to incorporate most of the sentences in brackets straight into the normal text. 

Otherwise this is a text that is easy for me to agree with and that makes good arguments for Ember overall. 👍

2021-01-14 18:19 UTC, pichfl commented on _posts/2021-01-08-Ember.js-in-2021---a-beacon-of-productivity.md
> +framework has never been among the cool kids that received all the hype but
Not sure about the "cool kids" thing. Maybe this or something like this works better? 
`While never loud and flashy it quietly…`

2021-01-14 18:19 UTC, pichfl commented on _posts/2021-01-08-Ember.js-in-2021---a-beacon-of-productivity.md
> +on shipping vs. getting lost in low-level rabbit holes where little value is to
I would replace 'vs.' with 'without', but maybe a native speaker can chime in.

2021-01-14 18:19 UTC, pichfl commented on _posts/2021-01-08-Ember.js-in-2021---a-beacon-of-productivity.md
>  ## The Complexity Fetish
I do get the connotation here, but I think "The complexity obsession" or something similar would work better and allow to use "fetish" in the paragraph without duplication

2021-01-14 18:19 UTC, pichfl commented on _posts/2021-01-08-Ember.js-in-2021---a-beacon-of-productivity.md
> +That might be driven partly by the Node community's (highly questionable in my
I recommend dropping the brackets. Either the statement is important enough to be written out as part of the paragraph or it is unnecessary.

2021-01-14 18:19 UTC, pichfl commented on _posts/2021-01-08-Ember.js-in-2021---a-beacon-of-productivity.md
> +Contrary to that, Ember takes these unimportant low level decisions out of the
I think the term "[bike-shedding](https://en.wikipedia.org/wiki/Law_of_triviality)" should be in there somewhere as it the most commonly used term to describe what Ember provides. Not sure where to put it though.

2021-01-14 18:19 UTC, pichfl commented on _posts/2021-01-08-Ember.js-in-2021---a-beacon-of-productivity.md
> +## The right tool for the right job
I can't wait to share this part with so many people. 👍

2021-01-14 18:19 UTC, pichfl commented on _posts/2021-01-08-Ember.js-in-2021---a-beacon-of-productivity.md
> +  long-time Ember user for their dashboard app btw)
Not sure I like seeing "btw" in prose. Maybe: "(Who in turn are a long-time Ember users with their dashboard app)"

2021-01-14 18:36 UTC, nickschot commented on _posts/2021-01-08-Ember.js-in-2021---a-beacon-of-productivity.md
> +on shipping vs. getting lost in low-level rabbit holes where little value is to
or "instead of"

2021-01-14 18:40 UTC, nickschot commented on _posts/2021-01-08-Ember.js-in-2021---a-beacon-of-productivity.md
> +([some people are even writing their CSS in JS now 🙀](https://en.wikipedia.org/wiki/CSS-in-JS)).
😱

2021-01-14 18:41 UTC, Turbo87 commented on _posts/2021-01-08-Ember.js-in-2021---a-beacon-of-productivity.md
> +- moving away from the `Ember` global to ES2015 modules
soooo... technically we're still using the global 😅

2021-01-14 18:42 UTC, Turbo87 approved these changes

2021-01-14 18:43 UTC, nickschot commented on _posts/2021-01-08-Ember.js-in-2021---a-beacon-of-productivity.md
> +underestimate.
Hmm I think this sentence could be improved.

At the very least:
> The level of churn that adopting new approaches over-eagerly **brings**, only to realize later the hypetrain has changed direction again and what you bet on is turning into a dead-end, is super easy to underestimate.

2021-01-14 18:45 UTC, nickschot commented on _posts/2021-01-08-Ember.js-in-2021---a-beacon-of-productivity.md
> +that's driven mainly be two sentiments. One is simply ego. As the virologists
```suggestion
that's driven mainly by two sentiments. One is simply ego. As the virologists
```

2021-01-14 18:46 UTC, nickschot commented on _posts/2021-01-08-Ember.js-in-2021---a-beacon-of-productivity.md
> +engineering he was talking to at a conference. They understood and completely
```suggestion
engineer he was talking to at a conference. They understood and completely
```

2021-01-14 18:47 UTC, nickschot commented on _posts/2021-01-08-Ember.js-in-2021---a-beacon-of-productivity.md
> +engineering he was talking to at a conference. They understood and completely
or should it have been "engineering team"?

2021-01-14 18:48 UTC, nickschot commented on _posts/2021-01-08-Ember.js-in-2021---a-beacon-of-productivity.md
> +from the 20th floor vs. with laying the baseplate. Yet they said, they would
```suggestion
from the 20th floor instead of beginning with laying the foundation. Yet they said, they would
```

2021-01-14 18:49 UTC, nickschot commented on _posts/2021-01-08-Ember.js-in-2021---a-beacon-of-productivity.md
> +preferences of the engineer(s) setting up the project really.
I'm not entirely sure what the "really" is for in this sentence.

2021-01-14 18:50 UTC, nickschot commented on _posts/2021-01-08-Ember.js-in-2021---a-beacon-of-productivity.md
> +I think there's also another, historical reason though that plays into this to
```suggestion
I think there's also another, historical reason that plays into this to
```

2021-01-14 18:54 UTC, nickschot commented on _posts/2021-01-08-Ember.js-in-2021---a-beacon-of-productivity.md
> +problem one is solving but introduced as part of the solution really. Adding two
```suggestion
problem one is solving but introduced as part of the solution. Adding two
```

I think we can drop the really here.

2021-01-14 18:55 UTC, nickschot commented on _posts/2021-01-08-Ember.js-in-2021---a-beacon-of-productivity.md
> +accidental complexity associated to these aspects out of the hands of the
```suggestion
accidental complexity associated with these aspects out of the hands of the
```

2021-01-14 18:59 UTC, nickschot commented on _posts/2021-01-08-Ember.js-in-2021---a-beacon-of-productivity.md
> +codemods for automating the task) to the new models. So instead of every single
```suggestion
codemods for automating the task) to the new paradigms. So instead of every single
```

2021-01-14 19:00 UTC, nickschot commented on _posts/2021-01-08-Ember.js-in-2021---a-beacon-of-productivity.md
> +- replacing the core rendering engine of the framework (resulting in Glimmer VM
Didn't this technically happen not once but twice? 😬

2021-01-14 19:01 UTC, nickschot commented on _posts/2021-01-08-Ember.js-in-2021---a-beacon-of-productivity.md
> +to follow along. The entire ecosystem resolving around one defined set of
```suggestion
to follow along. The entire ecosystem revolving around one defined set of
```

2021-01-14 19:03 UTC, nickschot commented on _posts/2021-01-08-Ember.js-in-2021---a-beacon-of-productivity.md
> +hiearchies and understand what initializers are when the application they are
```suggestion
hierarchies and understand what initializers are when the application they are
```

2021-01-14 19:04 UTC, nickschot commented on _posts/2021-01-08-Ember.js-in-2021---a-beacon-of-productivity.md
> +or project in the above list – full-on web applications. There are plenty of
```suggestion
of project in the above list – full-on web applications. There are plenty of
```

2021-01-14 19:06 UTC, nickschot commented on _posts/2021-01-08-Ember.js-in-2021---a-beacon-of-productivity.md
> +way to tackle that task maybe – still, doesn't mean it's a bad rocket, maybe a
```suggestion
way to tackle that task maybe – still, that doesn't mean it's a bad rocket, maybe a
```

2021-01-14 19:09 UTC, nickschot requested changes
Nice post! Left mostly textual suggestions.

2021-01-15 08:44 UTC, marcoow commented on _posts/2021-01-08-Ember.js-in-2021---a-beacon-of-productivity.md
> +  [Qonto](https://qonto.com) (another successful Ember user) is building
rephrased it slightly

2021-01-15 09:09 UTC, marcoow commented on _posts/2021-01-08-Ember.js-in-2021---a-beacon-of-productivity.md
> +  long-time Ember user for their dashboard app btw)
I'll just drop the _"btw"_ – not necessary anyway

2021-01-15 09:10 UTC, marcoow commented on _posts/2021-01-08-Ember.js-in-2021---a-beacon-of-productivity.md
> +- moving away from the `Ember` global to ES2015 modules
🙊

2021-01-15 11:26 UTC, marcoow commented on _posts/2021-01-08-Ember.js-in-2021---a-beacon-of-productivity.md
> +engineering he was talking to at a conference. They understood and completely
no, should have been _"engineer"_

2021-01-15 11:31 UTC, marcoow commented on _posts/2021-01-08-Ember.js-in-2021---a-beacon-of-productivity.md
> +- replacing the core rendering engine of the framework (resulting in Glimmer VM
🙊

2021-01-15 12:34 UTC, patsy-issa reviewed
Nice article! I think adding in example and metrics could help depending on the target audience.

2021-01-15 12:34 UTC, patsy-issa commented on _posts/2021-01-08-Ember.js-in-2021---a-beacon-of-productivity.md
> +are now widely accepted and adopted. While frontend engineering was something
Could we list examples here such as the angular cli being forked over from the ember cli, the ember router being used for the react router.

2021-01-15 12:34 UTC, patsy-issa commented on _posts/2021-01-08-Ember.js-in-2021---a-beacon-of-productivity.md
> +challenging than backend development) but also its significance due to the
I don't think the text in the `()` adds value to the statement, one could argue that we are comparing apples to oranges.

2021-01-15 12:34 UTC, patsy-issa commented on _posts/2021-01-08-Ember.js-in-2021---a-beacon-of-productivity.md
> +- removing the custom object model and adopting native classes
If the target audience is not the ember community I think elaborating here and adding in links to the codemods and glimmer might give a glimpse into how we upgrade things within the ember world.

2021-01-15 12:34 UTC, patsy-issa commented on _posts/2021-01-08-Ember.js-in-2021---a-beacon-of-productivity.md
> +  which is probably the most advanced rendering pipeline available)
Is it possible to add objective metrics to back up this claim?

2021-01-15 12:38 UTC, marcoow commented on _posts/2021-01-08-Ember.js-in-2021---a-beacon-of-productivity.md
> +challenging than backend development) but also its significance due to the
Yes, good point

2021-01-15 12:40 UTC, marcoow commented on _posts/2021-01-08-Ember.js-in-2021---a-beacon-of-productivity.md
> +are now widely accepted and adopted. While frontend engineering was something
I think that'd be misleading – the point here is that general concepts for building web frontends as used by Ember, React etc. are now widely adopted, e.g. building apps out of components, the fact that there should be a client-side router etc. It's not really relevant where these concepts originated, who copied etc. for that.

2021-01-15 12:41 UTC, marcoow commented on _posts/2021-01-08-Ember.js-in-2021---a-beacon-of-productivity.md
> +  which is probably the most advanced rendering pipeline available)
I don't think so – it's also not a really relevant point that the Glimmer VM is great here really

2021-01-15 13:23 UTC, patsy-issa commented on _posts/2021-01-08-Ember.js-in-2021---a-beacon-of-productivity.md
> +  which is probably the most advanced rendering pipeline available)
Would be in favour of removing the statement as it is not relevant to the point being made

2021-01-15 13:25 UTC, patsy-issa commented on _posts/2021-01-08-Ember.js-in-2021---a-beacon-of-productivity.md
> +are now widely accepted and adopted. While frontend engineering was something
The point I wanted to highlight was that practices that were cited as the reason why people don't want ember ended up being adopted by other frameworks i.e the cli.

2021-01-22 23:01 UTC, buschtoens commented on _posts/2021-01-08-Ember.js-in-2021---a-beacon-of-productivity.md
> +than essential complexity and generating product value.
We at @ClarkSource finished the upgrade from Ember 3.14 to 3.23 today and I celebrated with three tweets, that appear to match this section quite well:

> We've updated our huuuuge app from @emberjs 3.14 (over 14 months old!) to 3.23. And there were almost no changes necessary. SemVer. 💕

— https://twitter.com/buschtoens/status/1352648462450483203

> And what amazes me even more is that we were already able to pretty much use all new features of 3.23 in our 3.14 app — thanks to the *awesome* polyfills maintained by the community.
>
> Ember.js: no app gets left behind. 💕

— https://twitter.com/buschtoens/status/1352649518873980931

> Our @emberjs app is over 5 years old by now. Not once did we have to do a hold-the-world-big-bang-rewrite.
>
> We still have some code left from these days and — unbelievably — it still works. All the while we are using cutting-edge features in our new code.

— https://twitter.com/buschtoens/status/1352734272675840006

2021-01-22 23:40 UTC, buschtoens commented
IMO another major plus point for Ember.js is the community. Maybe you'd want to expand on this a bit more in the post?

Even though it may not be the largest community, it is the most helpful, friendly, inclusive and open tech community I know. Core team members actively encourage us "mere mortals" to get involved in the evolution of the frmework and take the time to patiently answer any questions.

2021-01-24 19:50 UTC, marcoow commented on _posts/2021-01-08-Ember.js-in-2021---a-beacon-of-productivity.md
> +than essential complexity and generating product value.
Yep, saw that and was considering adding those already :)

2021-01-24 19:51 UTC, marcoow commented
Thanks for the feedback @buschtoens! Community is a good point. I'll add something around that towards the end – seems like something that could well go in the closing note in some form.

2021-02-01 21:14 UTC, marcoow commented
I ended up not adding a section on community. While I agree with the points the main point I'm trying to make here really is Ember makes it easier to focus on shipping and the freedom you give up for that isn't freedom that has any real (business) value anyway. The openness/friendliness/supportiveness etc. isn't really an important factor for that and talking about how the community engages everyone to contribute to the evolution of the framework itself could even be seen contradicting the point potentially.

2021-02-16 17:53 UTC, dcyriller commented on _posts/2021-01-08-Ember.js-in-2021---a-beacon-of-productivity.md
> +[Qonto](https://qonto.com) and [CLARK](http://clark.de) are two great examples
With Ember we have built a consistent codebase of a couple apps and and addons. It is shared by 25 front-end engineers, spread over a few teams. In a early phase, we could focus on providing new features for our clients. Later, while keeping this focus, we could evolve the codebase in a non-disruptive way. 

Ember and its ecosystem have given us enough stability to invest in our product and in the development of our engineers' skills.

2021-02-19 10:54 UTC, marcoow commented on _posts/2021-01-08-Ember.js-in-2021---a-beacon-of-productivity.md
> +[Qonto](https://qonto.com) and [CLARK](http://clark.de) are two great examples
Thanks @dcyriller! Do you have a Twitter account I could link to form the quote? I couldn't find you there…

2021-02-22 11:12 UTC, dcyriller commented on _posts/2021-01-08-Ember.js-in-2021---a-beacon-of-productivity.md
> +[Qonto](https://qonto.com) and [CLARK](http://clark.de) are two great examples
I don't have a Twitter account 🙂

2021-02-24 13:24 UTC, dcyriller approved these changes

2021-03-04 20:10 UTC, izelnakri commented on _posts/2021-03-12-Ember.js-in-2021---a-beacon-of-productivity.md
> +
We can add something here along the lines of:


Ember historically is the first frontend framework to introduce an comprehensive yet flexible frontend build system(named [ember-cli](https://cli.emberjs.com).
This build system aimed to improve the developer experience at a time when the common practice was to 
write custom build and testing scripts or processes in order to bundle many files of frontend code
with [Rails Asset Pipeline](https://guides.rubyonrails.org/asset_pipeline.html) or with command-line tools such as Gulp](https://gulpjs.com) or [Grunt](https://gruntjs.com). 
This attention and focus for developer experience allowed ember to build an addon and developer ecosystem that solidified common best practices/solutions for new and existing teams & projects.
Popular ember addons today are generally well maintained, works across major version upgrades with smooth deprecation and standardized testing processes. 
This decision to introduce a build system to generate common boilerplate files, test runner and addons were well received in the frontend web application space.
Even higher profile frameworks of that time such as angular.js [built its own build system by forking ember-cli](https://github.com/angular/angular-cli/issues/16#issuecomment-124863297)
. Today every major frontend application framework or library offers starter boilerplate kits or generators.
Over the last few years, ember fell behind compared to rest of JavaScript community when it comes to
bundling javascript code for the browsers. Since its bundling system predates ES Module bundlers such as webpack, 
rollup and the newest ones like esbuild.
However it is just a minor concern for ember developers because today it is
possible to use any npm module in any ember application with [ember-auto-import](https://github.com/ef4/ember-auto-import).
Currently [Ember is under a modernization process for its build system]((https://github.com/emberjs/rfcs/blob/master/text/0519-2019-2020-roadmap.md#modernize-our-build-system))
which will unblock shipping internal modules of the ember framework and ember addons as standalone & independent npm packages.


Feel free to edit this as you wish :)

2021-03-09 09:46 UTC, marcoow commented on _posts/2021-03-12-Ember.js-in-2021---a-beacon-of-productivity.md
> +
Hm, I think the not-so-technical aspects of this are already covered extensively in the post? The more technical aspects I'd rather not include – the idea of the post is to not go into any particular details but remain at a higher level, focused on the idea of how Ember enables focusing on what matters vs. what might be exciting for engineers.

2021-03-09 10:00 UTC, nickschot approved these changes

2021-03-12 11:45 UTC, merged