Blogpost: Trying your Github Actions locally
mainmatter/mainmatter.com pull request #1477
Opened 2021-03-04 13:55 UTC by sdebarros

2021-03-08 08:26 UTC, marcoow reviewed
Nice post! I think the topic is also pretty cool and something I didn't know about but very helpful.

I left some comments on a few things and of course it's a nit-pick but I think it's _"GitHub"_, at least that's how they write it themselves :)

2021-03-08 08:26 UTC, marcoow commented on _posts/2021-03-08-trying-your-github-actions-locally.md
> +title: 'Trying your Github Actions locally'
```suggestion
title: 'Trying your GitHub Actions locally'
```

2021-03-08 08:26 UTC, marcoow commented on _posts/2021-03-08-trying-your-github-actions-locally.md
> +Github Actions is an API from Github that allows you to automate certain tasks
```suggestion
Github Actions is a service from Github that allows you to automate certain tasks
```

API sounds a bit strange to me in this context?

2021-03-08 08:26 UTC, marcoow commented on _posts/2021-03-08-trying-your-github-actions-locally.md
> +Github to run it, to see if it works, it's not the most convenient. In my case,
```suggestion
Github to run it, to see if it works, is not the most convenient. In my case,
```

?

2021-03-08 08:26 UTC, marcoow commented on _posts/2021-03-08-trying-your-github-actions-locally.md
> +`act -l`, or fun `act event_name -l` to see all the actions run for a specific
```suggestion
`act -l`, or run `act event_name -l` to see all the actions run for a specific
```

2021-03-08 08:26 UTC, marcoow commented on _posts/2021-03-08-trying-your-github-actions-locally.md
> +```
I think it might be good to add a one sentence summary of this – _"on every push to a tag, we release whatever is in that tag to npm"_ or so…

2021-03-08 08:26 UTC, marcoow commented on _posts/2021-03-08-trying-your-github-actions-locally.md
> +To try it out, we can either do `act push` or `act -j release` which uses the
Would `act push` not check that we're pushing a tag here?

2021-03-08 08:26 UTC, marcoow commented on _posts/2021-03-08-trying-your-github-actions-locally.md
> +description: 'Samanta de Barros on how to try locally your Github Actions'
```suggestion
description: 'Samanta de Barros on how to try locally your GitHub Actions'
```

2021-03-08 08:26 UTC, marcoow commented on _posts/2021-03-08-trying-your-github-actions-locally.md
> +If, like me, configuring [Github Actions](https://docs.github.com/en/actions) is
```suggestion
If, like me, configuring [GitHub Actions](https://docs.github.com/en/actions) is
```

2021-03-08 08:26 UTC, marcoow commented on _posts/2021-03-08-trying-your-github-actions-locally.md
> +pushing it to Github (and having to see the effects on real-life), follow this
```suggestion
pushing it to GitHub (and having to see the effects on real-life), follow this
```

2021-03-08 08:26 UTC, marcoow commented on _posts/2021-03-08-trying-your-github-actions-locally.md
> +step by step of how to run your Github Actions on your own computer.
```suggestion
step by step of how to run your GitHub Actions on your own computer.
```

2021-03-08 08:26 UTC, marcoow commented on _posts/2021-03-08-trying-your-github-actions-locally.md
> +![Trying your Github Actions locally illustration](/assets/images/posts/2021-03-08-trying-github-actions-locally/illustration.svg#full)
```suggestion
![Trying your GitHub Actions locally illustration](/assets/images/posts/2021-03-08-trying-github-actions-locally/illustration.svg#full)
```

2021-03-08 08:26 UTC, marcoow commented on _posts/2021-03-08-trying-your-github-actions-locally.md
> +Github Actions is an API from Github that allows you to automate certain tasks
```suggestion
GitHub Actions is an API from GitHub that allows you to automate certain tasks
```

2021-03-08 08:26 UTC, marcoow commented on _posts/2021-03-08-trying-your-github-actions-locally.md
> +do a dry run of the action from Github, but I found
```suggestion
do a dry run of the action from GitHub, but I found
```

2021-03-08 08:26 UTC, marcoow commented on _posts/2021-03-08-trying-your-github-actions-locally.md
> +[act](https://github.com/nektos/act), a library that lets you run your Github
```suggestion
[act](https://github.com/nektos/act), a library that lets you run your GitHub
```

2021-03-12 12:23 UTC, nickschot requested changes

2021-03-12 12:23 UTC, nickschot commented on _posts/2021-03-08-trying-your-github-actions-locally.md
> +branch, or do a deployment when code is merged to master.
I would remove the event examples from the parens as you're also giving similar examples in the sentence directly after.

2021-03-12 12:23 UTC, nickschot commented on _posts/2021-03-08-trying-your-github-actions-locally.md
> +Github to run it, to see if it works, it's not the most convenient. In my case,
I'd also go for something with less commas like:
> You may run into the situation where you have to change your action and then have to push and wait for GitHub to run the action to see if your changes work as intended.

2021-03-12 13:27 UTC, sdebarros commented on _posts/2021-03-08-trying-your-github-actions-locally.md
> +Github Actions is an API from Github that allows you to automate certain tasks
Yes, that makes more sense.

2021-03-15 10:59 UTC, sdebarros commented on _posts/2021-03-08-trying-your-github-actions-locally.md
> +```
Added below.

2021-03-15 11:00 UTC, sdebarros commented on _posts/2021-03-08-trying-your-github-actions-locally.md
> +Github to run it, to see if it works, it's not the most convenient. In my case,
I went with a sentence closer to @nickschot's suggestion. Still added commas though, I think it's simpler than saying `and then... and...` etc. Let me know what you think.

2021-03-15 11:00 UTC, sdebarros commented on _posts/2021-03-08-trying-your-github-actions-locally.md
> +branch, or do a deployment when code is merged to master.
Done

2021-03-15 11:02 UTC, sdebarros commented on _posts/2021-03-08-trying-your-github-actions-locally.md
> +To try it out, we can either do `act push` or `act -j release` which uses the
It doesn't. I can remove that example and just leave `act -j release` though, if it's more clear.

2021-03-15 11:24 UTC, marcoow approved these changes
Nice 👍 

Can you just change the post date (and thus folder names) to whatever date this is going to be published on?

Also, fyi: I went ahead and compressed the images to save some bytes

2021-03-15 12:46 UTC, marcoow commented on _posts/2021-03-08-trying-your-github-actions-locally.md
> +To try it out, we can either do `act push` or `act -j release` which uses the
Maybe that would be better in that case, yes – I was a bit confused reading this as the config says the job runs for pushes on tags only but then this is a regular push so it's unclear why this would trigger the job.

2021-03-15 13:30 UTC, nickschot approved these changes

2021-03-15 14:13 UTC, sdebarros commented on _posts/2021-03-08-trying-your-github-actions-locally.md
> +To try it out, we can either do `act push` or `act -j release` which uses the
Done.

2021-03-22 10:52 UTC, merged