[Blog] Validations in Ember using yup
mainmatter/mainmatter.com pull request #1630
Opened 2021-11-17 21:30 UTC by BobrImperator

2021-11-17 22:51 UTC, locks requested changes, later dismissed
You were missing `/images/` in the path of your `gif`s.
You also need to put a profile picture under `/public/assets/images/authors/BobrImperator.jpg` (has to match your GitHub username).
With those changes I think the crawler will be happy!

2021-11-17 22:51 UTC, locks commented on _posts/2021-11-23-validations-in-ember-apps.md
> +![Internationalized user fields demo](/assets/posts/2021-11-23-validations-in-ember-apps/form-user-1.gif)
```suggestion
![Internationalized user fields demo](/assets/images/posts/2021-11-23-validations-in-ember-apps/form-user-1.gif)
```

2021-11-17 22:51 UTC, locks commented on _posts/2021-11-23-validations-in-ember-apps.md
> +![Internationalized user and pet fields demo](/assets/posts/2021-11-23-validations-in-ember-apps/form-user-with-pets-2.gif)
```suggestion
![Internationalized user and pet fields demo](/assets/images/posts/2021-11-23-validations-in-ember-apps/form-user-with-pets-2.gif)
```

2021-11-17 22:51 UTC, locks commented on _posts/2021-11-23-validations-in-ember-apps.md
> +![Internationalized user and pet fields demo](/assets/posts/2021-11-23-validations-in-ember-apps/conditional-form-user-3.gif)
```suggestion
![Internationalized user and pet fields demo](/assets/images/posts/2021-11-23-validations-in-ember-apps/conditional-form-user-3.gif)
```

2021-11-17 23:07 UTC, BobrImperator commented
Indeed it is happy now, thank you very much @locks!

2021-11-18 12:03 UTC, emmasofiah2o requested changes
I have reviewed half of this (I only corrected grammar and readability ofc). I'll submit another review tomorrow for the rest of the post!

2021-11-18 12:03 UTC, emmasofiah2o commented on _posts/2021-11-23-validations-in-ember-apps.md
> +
This introduction isn't very clear. Maybe something like: "Since the release of the last Octane update, ember-cp-validations stopped working with Glimmer components, making ember-changeset feel outdated. While validations are likely to be modernized in the near future and should not be left aside yet, I have still decided to look for valid temporary alternatives. In this blog post, I will show you how to integrate a third-party validation library in an Ember project."

2021-11-18 12:03 UTC, emmasofiah2o commented on _posts/2021-11-23-validations-in-ember-apps.md
> +
(Yup or yup?)
"Yup is based on a variety of schemas for all JavaScript data types and it relies on a builder pattern to define schema constraints.
The following code imports `string` schema, and calls `required` and `email` methods to define what type of data is allowed. Here we can read that `emailRequired` has to be "a valid non-empty string that matches email pattern."

2021-11-18 12:03 UTC, emmasofiah2o commented on _posts/2021-11-23-validations-in-ember-apps.md
> +
Again, this is a bit unclear, but I don't think I could formulate it differently because I don't really know what it means :D

2021-11-18 12:03 UTC, emmasofiah2o commented on _posts/2021-11-23-validations-in-ember-apps.md
> +
"Yup also works excellent as a casting library, making it a great tool for data parsing, and is recursive, meaning it can handle trees quite well."

2021-11-18 12:03 UTC, emmasofiah2o commented on _posts/2021-11-23-validations-in-ember-apps.md
> +
Why did you use "but" here? :)

2021-11-18 12:03 UTC, emmasofiah2o commented on _posts/2021-11-23-validations-in-ember-apps.md
> +
* a model instance, and yup

2021-11-18 12:03 UTC, emmasofiah2o commented on _posts/2021-11-23-validations-in-ember-apps.md
> +
Unclear 😶‍🌫️

2021-11-18 12:03 UTC, emmasofiah2o commented on _posts/2021-11-23-validations-in-ember-apps.md
> +- `validate` is an asynchronous method that in turn calls `validate` on our
in turn?

2021-11-18 12:03 UTC, emmasofiah2o commented on _posts/2021-11-23-validations-in-ember-apps.md
> +  which is not desired. Another important thing here is that `validate` receives
"Furthermore/moreover/in addition to that, "validate"..."

2021-11-19 08:08 UTC, emmasofiah2o requested changes, later dismissed
Done reviewing. Sorry for the number of comments, but there were a couple of grammar mistakes and some sentences that needed to be changed. Please try to make the way you write "Yup", "Pet", "User" and so on consistent (so either with a capital letter at the beginning or not).

2021-11-19 08:08 UTC, emmasofiah2o commented on _posts/2021-11-23-validations-in-ember-apps.md
> +  to grab data from `context` with the help of `getProperties`.
e.g.

2021-11-19 08:08 UTC, emmasofiah2o commented on _posts/2021-11-23-validations-in-ember-apps.md
> +
"concatenation: this is not interesting for us since we normally use "ember-intl" for translating text."

2021-11-19 08:08 UTC, emmasofiah2o commented on _posts/2021-11-23-validations-in-ember-apps.md
> +  by yup to produce our messages. The first argument it takes is a translation
a function that is later used by

2021-11-19 08:08 UTC, emmasofiah2o commented on _posts/2021-11-23-validations-in-ember-apps.md
> +  `field.invalid`. The second argument is a list of fields it should get from
e.g.

2021-11-19 08:08 UTC, emmasofiah2o commented on _posts/2021-11-23-validations-in-ember-apps.md
> +  `min` and `max` that would be passed to `ember-intl` `t` helper.
*parameters (avoid using abbreviations :) )

2021-11-19 08:08 UTC, emmasofiah2o commented on _posts/2021-11-23-validations-in-ember-apps.md
> +
"the produced messaged will look something like this:"

2021-11-19 08:08 UTC, emmasofiah2o commented on _posts/2021-11-23-validations-in-ember-apps.md
> +need to do:
"we need to do in order for that to happen:"

2021-11-19 08:08 UTC, emmasofiah2o commented on _posts/2021-11-23-validations-in-ember-apps.md
> +
"let's take a look at the code (?) for connecting User and Pet. This will allow Pets to be validated when a User is also validated."

2021-11-19 08:08 UTC, emmasofiah2o commented on _posts/2021-11-23-validations-in-ember-apps.md
> +
*tests:

2021-11-19 08:08 UTC, emmasofiah2o commented on _posts/2021-11-23-validations-in-ember-apps.md
> +
I'd remove "with" from the last sentence

2021-11-19 08:08 UTC, emmasofiah2o commented on _posts/2021-11-23-validations-in-ember-apps.md
> +schema. When `relationship` is called, it adds a custom test that receives
*to the 'object' schema

2021-11-19 08:08 UTC, emmasofiah2o commented on _posts/2021-11-23-validations-in-ember-apps.md
> +
"which is an instance of a model." (or usually is, Idk)

"After that, it's just a matter..."

2021-11-19 08:08 UTC, emmasofiah2o commented on _posts/2021-11-23-validations-in-ember-apps.md
> +difference is that first the hasMany promise-proxy needs to be transformed into
"'belongsTo'. The only difference is that the HasMany promise-proxy needs to be transformed into an array by calling "toArray" before Yup is able to handle it."

2021-11-19 08:08 UTC, emmasofiah2o commented on _posts/2021-11-23-validations-in-ember-apps.md
> +
"them. Lastly, we can check if every validation was "true"."

2021-11-19 08:08 UTC, emmasofiah2o commented on _posts/2021-11-23-validations-in-ember-apps.md
> +
*its validations

2021-11-19 08:08 UTC, emmasofiah2o commented on _posts/2021-11-23-validations-in-ember-apps.md
> +different state. Here we'll have a really weird requirement where `pet.name` is
*some conditional validations

2021-11-19 08:08 UTC, emmasofiah2o commented on _posts/2021-11-23-validations-in-ember-apps.md
> +
*the modified

2021-11-19 08:08 UTC, emmasofiah2o commented on _posts/2021-11-23-validations-in-ember-apps.md
> +Pet now implements conditional `name` validation by calling `when` method of a
*the conditional

2021-11-19 08:08 UTC, emmasofiah2o commented on _posts/2021-11-23-validations-in-ember-apps.md
> +`string` schema, yup's branching is a really cool thing, the `when` method
"schema. The 'when' method accepts..."

2021-11-19 08:08 UTC, emmasofiah2o commented on _posts/2021-11-23-validations-in-ember-apps.md
> +specifies that "when is true then string is not required", "otherwise string is
*and an object

2021-11-19 08:08 UTC, emmasofiah2o commented on _posts/2021-11-23-validations-in-ember-apps.md
> +now it's easier than ever to integrate with 3rd party libraries with mostly just
*apps. Now...

2021-11-19 08:08 UTC, emmasofiah2o commented on _posts/2021-11-23-validations-in-ember-apps.md
> +something like yup for teams that work in many environments, yup might as well
*environments. (remove the last bit)

2021-11-19 10:30 UTC, BobrImperator commented on _posts/2021-11-23-validations-in-ember-apps.md
> +- `validate` is an asynchronous method that in turn calls `validate` on our
Yes, I mean to say here that `validate` method calls `validate` method of another validations schema.

2021-11-19 10:35 UTC, emmasofiah2o commented on _posts/2021-11-23-validations-in-ember-apps.md
> +- `validate` is an asynchronous method that in turn calls `validate` on our
I'd remove "in turn" then, it makes the sentence a bit unclear

2021-11-19 10:48 UTC, BobrImperator commented on _posts/2021-11-23-validations-in-ember-apps.md
> +  `field.invalid`. The second argument is a list of fields it should get from
Do you mean to move `e.g` to the beginning of the line?
If so, the markdown formatter does automatically puts `e.g` in the line above.

2021-11-19 10:52 UTC, emmasofiah2o commented on _posts/2021-11-23-validations-in-ember-apps.md
> +  `field.invalid`. The second argument is a list of fields it should get from
No, I meant that e.g. is written with a point after each letter :D

2021-11-19 11:35 UTC, BobrImperator commented on _posts/2021-11-23-validations-in-ember-apps.md
> +- `validate` is an asynchronous method that in turn calls `validate` on our
Done.

2021-11-19 11:37 UTC, BobrImperator commented on _posts/2021-11-23-validations-in-ember-apps.md
> +
Changed.

2021-11-19 11:44 UTC, BobrImperator commented on _posts/2021-11-23-validations-in-ember-apps.md
> +
Changed.

Question regarding the proposed text. "Yup is based on a variety of schemas for all JavaScript data types" sounds like Yup has multiple schemas for a single data type, or am I understanding it wrong?

2021-11-19 12:30 UTC, marcoow commented
@BobrImperator
<img width="359" alt="Bildschirmfoto 2021-11-19 um 13 29 41" src="https://user-images.githubusercontent.com/1510/142623129-e2d02701-0e47-4b09-bb2b-5f6ee7b4e1b4.png">

🙏

2021-11-19 16:04 UTC, marcoow reviewed
I think this is a good start but also think it would benefit from a bit of work on the flow. Consider starting with the status quo and motivation for working on validations at all: removal of the Ember object model makes it easier to interface with standard JS libraries, current solutions have drawbacks, etc. Then it might be good to first introduce the solution you're aiming for high-level before describing its implementation. I feel currently this is a bit hard to follow 😬

2021-11-19 16:04 UTC, marcoow commented on _posts/2021-11-23-validations-in-ember-apps.md
> +Since Octane edition it's much easier to integrate with third-party libraries,
```suggestion
Since Ember's Octane edition it's much easier to integrate with third-party libraries,
```

2021-11-19 16:04 UTC, marcoow commented on _posts/2021-11-23-validations-in-ember-apps.md
> +Since Octane edition it's much easier to integrate with third-party libraries,
I think the question is also why it's easier (and the answer is no more custom object model).

2021-11-19 16:04 UTC, marcoow commented on _posts/2021-11-23-validations-in-ember-apps.md
> +around Yup validations library.
```suggestion
around the Yup validations library.
```

2021-11-19 16:04 UTC, marcoow commented on _posts/2021-11-23-validations-in-ember-apps.md
> +relies on builder pattern to define schema constraints, the following code
```suggestion
relies on the builder pattern to define schema constraints, the following code
```

2021-11-19 16:04 UTC, marcoow commented on _posts/2021-11-23-validations-in-ember-apps.md
> +relies on builder pattern to define schema constraints, the following code
```suggestion
relies on builder pattern to define schema constraints. The following code
```

2021-11-19 16:04 UTC, marcoow commented on _posts/2021-11-23-validations-in-ember-apps.md
> +imports `string` schema, and calls `required` and `email` methods to describe
```suggestion
imports the `string` schema, and calls `required` and `email` methods to describe
```

2021-11-19 16:04 UTC, marcoow commented on _posts/2021-11-23-validations-in-ember-apps.md
> +valid non-empty string that matches email pattern".
Is `emailRequired` a function? I don't understand how it'd be used?

2021-11-19 16:04 UTC, marcoow commented on _posts/2021-11-23-validations-in-ember-apps.md
> +valid non-empty string that matches email pattern".
I think it'd be good to add an example for how it would be used to the codeblock as well

2021-11-19 16:04 UTC, marcoow commented on _posts/2021-11-23-validations-in-ember-apps.md
> +
```suggestion
```

This doesn't work with our renderer currently – see Netlify

2021-11-19 16:04 UTC, marcoow commented on _posts/2021-11-23-validations-in-ember-apps.md
> +can handle trees quite well.
I have a hard time understanding what the previous quote and paragraph are trying to say. Why is it so important to understand and how is it important that something is a type error?

2021-11-19 16:04 UTC, marcoow commented on _posts/2021-11-23-validations-in-ember-apps.md
> +```
Would it be better to use `async`/`await` here?

2021-11-19 16:04 UTC, marcoow commented on _posts/2021-11-23-validations-in-ember-apps.md
> +I'd imagine it to be used at high level.
At this point I'm not sure it's clear what the goal is – we're now starting to write a wrapper but I'm not sure where we want to go in the end/what we'll end up using that wrapper for?

2021-11-19 16:04 UTC, marcoow commented on _posts/2021-11-23-validations-in-ember-apps.md
> +We instantiate YupValidations and pass it some arguments, a User model instance,
I feel `YupValidations` comes a bit out of the blue? I'm not sure what it is? Would it be possible to introduce it earlier (I assume it's essentially what the previous blocks contain anyway)?

2021-11-19 16:51 UTC, BobrImperator commented on _posts/2021-11-23-validations-in-ember-apps.md
> +can handle trees quite well.
Was thinking about removing this section and it looks like we both agree on that.

2021-11-19 17:15 UTC, BobrImperator commented on _posts/2021-11-23-validations-in-ember-apps.md
> +  `field.invalid`. The second argument is a list of fields it should get from
Apparently I'm blind, didn't notice the dot 🙈

2021-11-22 09:08 UTC, BobrImperator commented on _posts/2021-11-23-validations-in-ember-apps.md
> +```
I think Promise chain is ok here, makes more sense to me when used outside a function.

2021-11-24 12:11 UTC, BobrImperator commented on _posts/2021-11-23-validations-in-ember-apps.md
> +I'd imagine it to be used at high level.
I've this bit above the usage.

2021-11-24 12:21 UTC, BobrImperator commented
I think this can be taken look at @marcoow @emmasofiah2o

2021-11-24 15:26 UTC, marcoow reviewed
This has much improved since last time I think – much easier to follow the flow now. I left a bunch of comments but mostly related to formatting and precise wording to improve readability.

2021-11-24 15:26 UTC, marcoow commented on _posts/2021-11-23-validations-in-ember-apps.md
> +libraries, because of that I've been searching for alternatives to
```suggestion
libraries. Because of that I've been searching for alternatives to
```

2021-11-24 15:26 UTC, marcoow commented on _posts/2021-11-23-validations-in-ember-apps.md
> +to be "a valid non-empty string that matches email pattern".
```suggestion
describe what type of data is allowed. The returned function `emailRequired` validates values to be "non-empty string that match an email pattern".
```

`emailRequired` doesn't have to be a non-empty string etc. but is a function that checks its arguments are non-empty strings?

2021-11-24 15:26 UTC, marcoow commented on _posts/2021-11-23-validations-in-ember-apps.md
> +some example found in Yup docs:
```suggestion
some example found in the Yup docs:
```

2021-11-24 15:26 UTC, marcoow commented on _posts/2021-11-23-validations-in-ember-apps.md
> +There are 4 class fields defined `context`, `schema`, `shape` and `error` which
```suggestion
There are 4 properties defined `context`, `schema`, `shape` and `error` which
```

?

2021-11-24 15:26 UTC, marcoow commented on _posts/2021-11-23-validations-in-ember-apps.md
> +  we'll fetch data from.
```suggestion
- `context` is either the data or the whole instance of the object we're validating.
```

seems clearer?

2021-11-24 15:26 UTC, marcoow commented on _posts/2021-11-23-validations-in-ember-apps.md
> +- `shape` the data shape which is later used to create `schema`
```suggestion
- `shape` the expected shape of the data; this is used to create `schema`
```

2021-11-24 15:26 UTC, marcoow commented on _posts/2021-11-23-validations-in-ember-apps.md
> +- `error` is a `ValidationError` thrown by `schema.validate()` when it fails.
```suggestion
- `error` is a `ValidationError` thrown by `schema.validate()` when the data does not validate.
```

2021-11-24 15:26 UTC, marcoow commented on _posts/2021-11-23-validations-in-ember-apps.md
> +The class constructor takes 2 arguments `context` and `shape`, we set those on
```suggestion
The constructor takes 2 arguments `context` and `shape`, we set those on
```

_"class constructor"_ has a very specific meaning in C I think but in JS it should just be constructor?

2021-11-24 15:26 UTC, marcoow commented on _posts/2021-11-23-validations-in-ember-apps.md
> +  reducing a list of errors returned from `ValidationError` when `schema` is
```suggestion
  reducing a list of errors returned from `ValidationError` when the data is
```

The data is what's validated (against the schema)?

2021-11-24 15:26 UTC, marcoow commented on _posts/2021-11-23-validations-in-ember-apps.md
> +result.
```suggestion
`YupValidations#validate` method which returns a Promise that resolves to a Boolean.
```

2021-11-24 15:26 UTC, marcoow commented on _posts/2021-11-23-validations-in-ember-apps.md
> +Further on, there's `ErrorMessage` component that receives a **list** of error
```suggestion
Further on, there's an `ErrorMessage` component that receives a **list** of error
```

2021-11-24 15:26 UTC, marcoow commented on _posts/2021-11-23-validations-in-ember-apps.md
> +and some way of concatenation, it's not interesting for us because in Ember apps
```suggestion
and some way of concatenation. That's not an option for us though because in Ember apps
```

2021-11-24 15:26 UTC, marcoow commented on _posts/2021-11-23-validations-in-ember-apps.md
> +- `locale` is a higher order function that returns a function that is later used
```suggestion
`locale` is a higher order function that returns a function that is later used
```

This doesn't actually seem to be a list?

2021-11-24 15:26 UTC, marcoow commented on _posts/2021-11-23-validations-in-ember-apps.md
> +![Internationalized user fields demo](/assets/images/posts/2021-11-23-validations-in-ember-apps/form-user-1.gif)
I'd add a quick explanation before this that summarizes what model you're validating in the screen recording – it's not necessarily entirely clear I think.

2021-11-24 15:26 UTC, marcoow commented on _posts/2021-11-23-validations-in-ember-apps.md
> +- Create validations for Pet model
```suggestion
- Create validations for the `Pet` model
```

2021-11-24 15:26 UTC, marcoow commented on _posts/2021-11-23-validations-in-ember-apps.md
> +- Validate Pets when User is validated similarly to how ember-model-validator
```suggestion
- Validate pets when the user is validated similarly to how ember-model-validator
```

2021-11-24 15:26 UTC, marcoow commented on _posts/2021-11-23-validations-in-ember-apps.md
> +  behaves
```suggestion
- Validate Pets when User is validated
```

I'm not sure anyone know how ember-model-validator behaves? I personally don't know anything about that addon…

2021-11-24 15:26 UTC, marcoow commented on _posts/2021-11-23-validations-in-ember-apps.md
> +Here's the Pet model implementation which includes the validations wrapper.
```suggestion
Here's the `Pet` model implementation which includes the validations wrapper.
```

2021-11-24 15:26 UTC, marcoow commented on _posts/2021-11-23-validations-in-ember-apps.md
> +Here's the Pet model implementation which includes the validations wrapper.
```suggestion
Here's the Pet model implementation with validations.
```

not sure what _"validations wrapper"_ refers to?

2021-11-24 15:26 UTC, marcoow commented on _posts/2021-11-23-validations-in-ember-apps.md
> +Now let's take a look at the code for connecting User and Pet. This will
```suggestion
Now let's take a look at the code for connecting the validations for `User` and `Pet`. This will
```

2021-11-24 15:26 UTC, marcoow commented on _posts/2021-11-23-validations-in-ember-apps.md
> +validate pets when a User is validated.
```suggestion
validate a user's pets when the user itself is validated.
```

2021-11-24 15:26 UTC, marcoow commented on _posts/2021-11-23-validations-in-ember-apps.md
> +  has to return a promise that returns true or false.
```suggestion
  has to return a promise that returns `true` or `false`.
```

2021-11-24 15:26 UTC, marcoow commented on _posts/2021-11-23-validations-in-ember-apps.md
> +Collection of relationships is pretty much the same as `belongsTo`. The only
```suggestion
`hasMany` relationships are pretty much the same as `belongsTo`. The only
```

2021-11-24 15:26 UTC, marcoow commented on _posts/2021-11-23-validations-in-ember-apps.md
> +array that Yup will be able to handle it's done by calling `toArray`. Then the
```suggestion
array that Yup will be able to handle which is done by calling `toArray`. Then the
```

2021-11-24 15:26 UTC, marcoow commented on _posts/2021-11-23-validations-in-ember-apps.md
> +    const validations = await Promise.all(
```suggestion
    const validations = await Promise.allSettled(
```

With `Promise.all` wouldn't this throw as soon as one of the validations fail?

2021-11-24 15:26 UTC, marcoow commented on _posts/2021-11-23-validations-in-ember-apps.md
> +    return validations.every((validation) => validation === true);
```suggestion
    return validations.every((validation) => validation);
```

don't think we actually need `===`?

2021-11-24 15:26 UTC, marcoow commented on _posts/2021-11-23-validations-in-ember-apps.md
> +awaiting them. Lastly we can check if every validation was `true`.
```suggestion
array that Yup will be able to handle it's done by calling `toArray`. Then the
test validates all objects in the array and checks whether all validations return `true`.
```

seems to be a bit too much detail otherwise?

2021-11-24 15:26 UTC, marcoow commented on _posts/2021-11-23-validations-in-ember-apps.md
> +That's it now we need to modify the User model by adding `pets` to its
```suggestion
That's it now we need to modify the `User` model by adding `pets` to its
```

2021-11-24 15:26 UTC, marcoow commented on _posts/2021-11-23-validations-in-ember-apps.md
> +Here's the modified Pet model:
```suggestion
Here's the modified `Pet` model:
```

2021-11-24 15:26 UTC, marcoow commented on _posts/2021-11-23-validations-in-ember-apps.md
> +  @belongsTo('user') owner;
```suggestion
  @belongsTo('user') user;
```

I think `owner` can be confusing since that's also the container in Ember?

2021-11-24 15:26 UTC, marcoow commented on _posts/2021-11-23-validations-in-ember-apps.md
> +  get isAllergic() {
I'd consider renaming this to `isUserAllergic` or so to make clear this comes from the `User` model?

2021-11-24 15:26 UTC, marcoow commented on _posts/2021-11-23-validations-in-ember-apps.md
> +Pet now implements the conditional `name` validation by calling `when` method of
```suggestion
`Pet` now implements the conditional `name` validation by calling the `when` method of
```

2021-11-24 15:26 UTC, marcoow commented on _posts/2021-11-23-validations-in-ember-apps.md
> +a `string` schema. The `when` method accepts a list of names of dependent
```suggestion
the `string` schema. The `when` method accepts a list of names of dependent
```

2021-11-24 15:26 UTC, marcoow commented on _posts/2021-11-23-validations-in-ember-apps.md
> +string is not required", "otherwise string is required".
```suggestion
properties, then we pass an object which specifies that the `name` attribute is not required when `isAllergic` is `true` but only otherwise.
```

2021-11-24 15:47 UTC, BobrImperator commented on _posts/2021-11-23-validations-in-ember-apps.md
> +result.
Thanks!

2021-11-24 15:58 UTC, BobrImperator commented on _posts/2021-11-23-validations-in-ember-apps.md
> +  behaves
I thought it'd be nice to include in case someone familiar with it reads the post. So it's like "Hey! This could be an alternative to the ember-model-validator".

But I don't feel strongly about it so I'll remove it.

2021-11-24 16:04 UTC, BobrImperator commented on _posts/2021-11-23-validations-in-ember-apps.md
> +    return validations.every((validation) => validation === true);
True, the validate methods returns only booleans

2021-11-24 16:13 UTC, BobrImperator commented on _posts/2021-11-23-validations-in-ember-apps.md
> +  @belongsTo('user') owner;
The container can't be accessed like that any longer I don't think.
I think you're going a bit deep here :D

I've changed it anyways since user might be a better name here.

2021-11-25 06:43 UTC, emmasofiah2o commented on _posts/2021-11-23-validations-in-ember-apps.md
> +
Not sure if this is still relevant?

To me it means that Yup has many schemas for many different data types :)

2021-11-25 07:39 UTC, marcoow commented on _posts/2021-11-23-validations-in-ember-apps.md
> +
I think Yup provides factory methods for different data types that you use to construct your particular schema for your particular data on the fly.

2021-11-25 13:15 UTC, BobrImperator commented on _posts/2021-11-23-validations-in-ember-apps.md
> +
I've changed it to what Emma proposed, I dunno what I was smoking at the time of reading her suggestion, it makes total sense to me right now :D.

2021-11-25 13:25 UTC, marcoow commented on _posts/2021-11-23-validations-in-ember-apps.md
> +
I don't think it's correct like this. Yup doesn't provide schemas or is based on schemas but it is a schema builder that provides functions to build your own schema that you can then use to validate data against. Check their website for more: https://github.com/jquense/yup#yup

2021-11-25 13:54 UTC, BobrImperator commented on _posts/2021-11-23-validations-in-ember-apps.md
> +
What you're saying is true as well, but I don't see how what we're saying in the blog post isn't correct either.
I don't feel the need to explain what is Yup and how it works exactly, it doesn't matter.

What matters is how I use it and what can I do with it.

2021-11-25 14:18 UTC, marcoow commented on _posts/2021-11-23-validations-in-ember-apps.md
> +
> Yup is based on a variety of schemas…

and 

> …imports the `string` schema…

are simply not correct :) Yup is not based on schemas but helps you define schemas and `string` isn't a schema but a module that provides builder functions to create schemas with strings.

Both things are not huge deals, just not actually correct.

2021-11-29 10:55 UTC, BobrImperator commented on _posts/2021-11-23-validations-in-ember-apps.md
> +
changed

2021-11-30 07:51 UTC, marcoow reviewed
Except for your preference to skip articles I think this is a very good read now :)

2021-11-30 07:51 UTC, marcoow commented on _posts/2021-11-23-validations-in-ember-apps.md
> +imports the `string` schema, and calls `required` and `email` methods to
```suggestion
imports the `string` schema, and calls the `required` and `email` methods to
```

2021-11-30 07:51 UTC, marcoow commented on _posts/2021-11-23-validations-in-ember-apps.md
> +validates values to be "a valid non-empty string that matches email pattern".
```suggestion
validates values to be "a valid non-empty string that matches an email pattern".
```

2021-11-30 07:51 UTC, marcoow commented on _posts/2021-11-23-validations-in-ember-apps.md
> +  reducing a list of errors returned from `ValidationError` when the data is
```suggestion
  reducing a list of errors read from `ValidationError` when the data is
```

_"returned from"_ sounds like `ValidationError` was a function?

2021-11-30 07:51 UTC, marcoow commented on _posts/2021-11-23-validations-in-ember-apps.md
> +  validated against the schema is validated.
I find this last sentence a bit confusing. All this error handling happens **after** the data has been validated. I think what you're trying to say is that the `error` property (which is of type `ValidationError`) is only set if the data is invalid?

I think you can just skip this sentence altogether as it's clear that the error is only set if the data is invalid anyway?

2021-11-30 07:51 UTC, marcoow commented on _posts/2021-11-23-validations-in-ember-apps.md
> +  `abortEarly: false` option is passed to `schema.validate()` as otherwise if
```suggestion
  the `abortEarly: false` option is passed to `schema.validate()` as otherwise if
```

2021-11-30 07:51 UTC, marcoow commented on _posts/2021-11-23-validations-in-ember-apps.md
> +  `abortEarly: false` option is passed to `schema.validate()` as otherwise if
```suggestion
  `abortEarly: false` option is passed to `schema.validate()` as otherwise, if
```

2021-11-30 07:51 UTC, marcoow commented on _posts/2021-11-23-validations-in-ember-apps.md
> +  correctly support proxies e.g Ember-Data models, we need to grab data from
```suggestion
  correctly support proxies, e.g Ember-Data models, we need to grab data from
```

2021-11-30 07:51 UTC, marcoow commented on _posts/2021-11-23-validations-in-ember-apps.md
> +Let's see what messages are returned after `User` model is validated when the
```suggestion
Let's see what messages are returned after the `User` model is validated when the
```

2021-11-30 07:51 UTC, marcoow commented on _posts/2021-11-23-validations-in-ember-apps.md
> +- Validate pets when User is validated.
```suggestion
- Validate pets when the user is validated.
```

2021-11-30 07:51 UTC, marcoow commented on _posts/2021-11-23-validations-in-ember-apps.md
> +- Validate pets when User is validated.
or

```suggestion
- Validate pets when `User`s are validated.
```

2021-11-30 07:51 UTC, marcoow commented on _posts/2021-11-23-validations-in-ember-apps.md
> +- Validate pets when User is validated.
or

```suggestion
- Validate pets when a `User` is validated.
```

2021-11-30 07:51 UTC, marcoow commented on _posts/2021-11-23-validations-in-ember-apps.md
> +`Pet`. This will validate pets when a User is validated.
```suggestion
`Pet`. This will validate pets when a `User` is validated.
```

2021-11-30 07:51 UTC, marcoow commented on _posts/2021-11-23-validations-in-ember-apps.md
> +That's it now we need to modify the `User` model by adding `pets` to its
```suggestion
That's it – now we need to modify the `User` model by adding `pets` to its
```

or some other way of separating the _"That't it"_ from the next sentencen

2021-11-30 07:51 UTC, marcoow commented on _posts/2021-11-23-validations-in-ember-apps.md
> +only required when user is not allergic.
```suggestion
only required when the user is not allergic.
```

2021-11-30 11:56 UTC, BobrImperator commented
@marcoow 
> Except for your preference to skip articles...

I don't know what you mean?

> ...I think this is a very good read now :)
You guys wrote it for me, kudos to you 🙈

2021-11-30 12:42 UTC, marcoow commented
@BobrImperator e.g. https://github.com/simplabs/simplabs.github.io/pull/1630#discussion_r758998201

2021-11-30 12:44 UTC, marcoow approved these changes

2021-12-08 11:16 UTC, merged

2021-12-08 12:53 UTC, BobrImperator commented on _posts/2021-12-06-validations-in-ember-apps.md
> +Since Ember's Octane edition it's much easiesr to integrate with third-party
Isn't this a typo?
Should say 'easier' @emmasofiah2o

2021-12-08 12:57 UTC, BobrImperator commented on _posts/2021-12-06-validations-in-ember-apps.md
> +Since Ember's Octane edition it's much easiesr to integrate with third-party
https://github.com/simplabs/simplabs.github.io/pull/1648