Created first open-source post
mainmatter/mainmatter.com pull request #1641
Opened 2021-11-30 12:48 UTC by emmasofiah2o

- Created file
- Added content from slack channel
- Copy/pasted Tobi's part

To dos: add og:image, change author (?), check descriptions

2021-11-30 13:04 UTC, Turbo87 commented on _posts/2021-12-05-this-week-in-os-1.md
> +- [Issue:] ESLint error: `TypeError: Cannot read property 'name' of undefined`
- these seems to be unrelated to Yarn, so I'm not sure they fit within the "Yarn" section
- I think I would probably also rename the section to "GitHub Actions caching" (@oscard0m any thoughts on that)
- the sections are now somewhat grouped by developer instead of by topic. I'm aware that there is quite a bit of overlap, but I think we shouldn't highlight quite as much which developer worked on which topics
- in my original post draft I've included the PR author after the title of the PR, but they seem to be missing for most/all of the other PRs

2021-11-30 13:04 UTC, Turbo87 commented on _posts/2021-12-05-this-week-in-os-1.md
> +- [https://github.com/buschtoens/ember-link/pull/678]https://github.com/buschtoens/ember-link/pull/678
```suggestion
- [https://github.com/buschtoens/ember-link/pull/678](https://github.com/buschtoens/ember-link/pull/678)
```

and I would suggest to also include the PR title and author like I did for the other PR links above

2021-11-30 13:18 UTC, BobrImperator requested changes, later dismissed
I see that there things mixed up.

Crates.io section has some conduit work, Ember.js has several addon projects, both community and 'official' ones.

We should decide how do we want to scope things.
Is a simple list of PRs for a language/technology enough?
e.g
```
- Rust
Tobi1
Tobi2
Tobi3
```

By project?

```
- Crates.io
Tobi1
Tobi2
- Conduit-rust
Tobi10
```

Or both?

```
- Rust
  - Crates.io
     -  Tobi1
     -  Tobi2 
```

2021-11-30 13:18 UTC, BobrImperator commented on _posts/2021-12-05-this-week-in-os-1.md
> +Senior software engineer [Bartłomiej Dudzik] has been busy doing some
```suggestion
Software engineer [Bartłomiej Dudzik] has been busy doing some
```
I actually feel strongly about this, I'm no Senior, nor an Engineer, but my title can't be just a 'Developer' either.

2021-11-30 13:18 UTC, BobrImperator commented on _posts/2021-12-05-this-week-in-os-1.md
> +for embroider and typescript users.
```suggestion
In ESA 4.1, he implemented a session #setup method: a first step to migrate away
from custom initializers and to allow removing mixins. Additionally this fixes build issues for typescript users.
```

2021-11-30 13:21 UTC, oscard0m commented on _posts/2021-12-05-this-week-in-os-1.md
> +- [Issue:] ESLint error: `TypeError: Cannot read property 'name' of undefined`
> * these seems to be unrelated to Yarn, so I'm not sure they fit within the "Yarn" section

I did this proposal on Slack, once clarified the author/non-author I will post a commit suggestion here:
![image](https://user-images.githubusercontent.com/2574275/144054365-f4af9ca4-3403-4819-be49-39f65f3107e9.png)

> * I think I would probably also rename the section to "GitHub Actions caching" (@oscard0m any thoughts on that)

I would group this by repository, even if those changes are `setup-node`, each of them impacts different projects (ghostjs, strapi...)

> * the sections are now somewhat grouped by developer instead of by topic. I'm aware that there is quite a bit of overlap, but I think we shouldn't highlight quite as much which developer worked on which topics
> * in my original post draft I've included the PR author after the title of the PR, but they seem to be missing for most/all of the other PRs

+1 to not grouping by author. What will happen when we have co-authors?
In general, I don't think it is necessary to put the authors, you can get that info from the PR/issue/discussion.

2021-11-30 13:30 UTC, Turbo87 commented
@BobrImperator FWIW `conduit` is closely related to crates.io, which is why I originally put it in the same category :)

2021-11-30 13:32 UTC, oscard0m commented
> I see that there things mixed up.
> 
> Crates.io section has some conduit work, Ember.js has several addon projects, both community and 'official' ones.
> 
> We should decide how do we want to scope things. Is a simple list of PRs for a language/technology enough? e.g
> 
> ```
> - Rust
> Tobi1
> Tobi2
> Tobi3
> ```
> 
> By project?
> 
> ```
> - Crates.io
> Tobi1
> Tobi2
> - Conduit-rust
> Tobi10
> ```
> 
> Or both?
> 
> ```
> - Rust
>   - Crates.io
>      -  Tobi1
>      -  Tobi2 
> ```

I like the third option:
```
- Rust
   - Crates.io
      -  Tobi1
      -  Tobi2 
 ```

---

Something that connects somehow with this topic:

I would suggest to follow a single approach on how to share PR/Issue links for the contributions. Right now I see 3 kind of links:
* `<link repo> <PR/issue link>`: ![image](https://user-images.githubusercontent.com/2574275/144055703-81040f5e-2552-4e48-aa07-ab46ecfea7df.png)
* `<PR/issue link>`: ![image](https://user-images.githubusercontent.com/2574275/144055961-2585a779-0825-4f69-9d69-4c5b50fbef4d.png)
* `<PR/issue title>`: ![image](https://user-images.githubusercontent.com/2574275/144056010-b7ae0a7e-b819-4184-8060-56979943e6c2.png)

---

2021-11-30 13:35 UTC, marcoow commented on _posts/2021-12-05-this-week-in-os-1.md
> +## Ember-simple-auth
```suggestion
## ember-simple-auth
```

2021-11-30 13:35 UTC, marcoow commented on _posts/2021-12-05-this-week-in-os-1.md
> +Senior software engineer [Bartłomiej Dudzik] has been busy doing some
We can also leave out the titles entirely here and just use people's names

2021-11-30 13:35 UTC, marcoow commented on _posts/2021-12-05-this-week-in-os-1.md
> +In ESA 4.0, he refactored the services to use Ember’s DI, which makes things
I'm not entirely sure what we mean by "…the services…" but since there's only one service in ESA, we can't say what we want to say just like this :) @BobrImperator can you add some context?

2021-11-30 13:35 UTC, marcoow commented on _posts/2021-12-05-this-week-in-os-1.md
> +from custom initializers and to allow removing mixins. The method excludes the
> …and to allow removing mixins.

I'm not sure that's correct. Mixins have been deprecated already and we should be able to drop them in the next release?

2021-11-30 13:35 UTC, marcoow commented on _posts/2021-12-05-this-week-in-os-1.md
> +ApplicationRoute that ESA adds automatically and that is causing build issues
```suggestion
application route that ESA adds automatically and that is causing build issues
```

2021-11-30 13:35 UTC, marcoow commented on _posts/2021-12-05-this-week-in-os-1.md
> +most needed. In this blog post, we have collected some of the work they have
> …where it's most needed.

sounds a bit over the top tbh :) Let's tone it down a bit?

2021-11-30 17:29 UTC, BobrImperator commented on _posts/2021-12-05-this-week-in-os-1.md
> +In ESA 4.0, he refactored the services to use Ember’s DI, which makes things
Well, by services I also meant the stores that ESA uses inside the `session` service you talk about. That's about it

2021-12-01 07:44 UTC, marcoow commented on _posts/2021-12-05-this-week-in-os-1.md
> +In ESA 4.0, he refactored the services to use Ember’s DI, which makes things
_"Service"_ has a very specific meaning in Ember though and the stores are not services :)

2021-12-01 07:45 UTC, marcoow commented on _posts/2021-12-05-this-week-in-os-1.md
> +tests setup.
```suggestion
For ESA 4.0, he refactored the internals of the addon to use Ember’s dependency injection, which makes things
simpler and easier to test, successfully removed a lot of code, and simplified
tests setup.
```

2021-12-06 07:45 UTC, emmasofiah2o commented on _posts/2021-12-05-this-week-in-os-1.md
> +- [Issue:] ESLint error: `TypeError: Cannot read property 'name' of undefined`
I don't see the commit suggestion for this one yet @oscard0m.

Regarding @Turbo87's comments: I simply copy-pasted the links as they were sent to me in the slack channel (so without an author). I kinda used the author's name to group the section, because I didn't have another way to group. In the proposal I did ask to get grouped links because I know nothing about these topics, but that never came :D

2021-12-06 07:48 UTC, emmasofiah2o commented on _posts/2021-12-05-this-week-in-os-1.md
> +most needed. In this blog post, we have collected some of the work they have
So without the "most"?

2021-12-06 07:52 UTC, emmasofiah2o commented on _posts/2021-12-05-this-week-in-os-1.md
> +- [https://github.com/buschtoens/ember-link/pull/678]https://github.com/buschtoens/ember-link/pull/678
Should all links have a title and author?

2021-12-06 14:44 UTC, marcoow commented on _posts/2021-12-05-this-week-in-os-1.md
> +most needed. In this blog post, we have collected some of the work they have
I'm not sure about the notion of us bringing in our knowledge where it's needed. In the end, it's about what we're interested in etc. Maybe just leave that part out completely?

2021-12-08 09:05 UTC, emmasofiah2o commented
I have just changed the link structure so now all links match. Can someone help me with the grouping? I think I would need to name the section where I put @oscard0m's links differently. Also, I am not adding any more links and will put everything after the 26th of November in the next post (possibly next week so it doesn't accumulate).

2021-12-09 04:51 UTC, BobrImperator commented on _posts/2021-12-05-this-week-in-os-1.md
> +for embroider and typescript users.
```suggestion
In ESA 4.1, he implemented a session #setup method: a first step to migrate away
from custom initializers. The method excludes the
application route that ESA adds automatically and that is causing build issues
for embroider and typescript users.
```

2021-12-09 17:19 UTC, oscard0m commented on _posts/2021-12-05-this-week-in-os-1.md
> +- [Issue:] ESLint error: `TypeError: Cannot read property 'name' of undefined`
> I don't see the commit suggestion for this one yet @oscard0m.

@emmasofiah2o I was on vacation sorry. Is there an agreement on how to group entries? If so, I can do the commit suggestion.

2021-12-09 17:25 UTC, oscard0m commented on _posts/2021-12-05-this-week-in-os-1.md
> +  chore(deps): update @types dependencies ([@Turbo87])
```suggestion
- [buschtoens/ember-link] [#678](https://github.com/buschtoens/ember-link/pull/678)
  Adjust @glimmer/tracking dependency to use semver ([@Turbo87])
- [buschtoens/ember-link] [#675](https://github.com/buschtoens/ember-link/pull/675)
  Use pnpm package manager ([@Turbo87])
- [buschtoens/ember-link] [#674](https://github.com/buschtoens/ember-link/pull/674)
  Release via CI ([@Turbo87])
- [buschtoens/ember-link] [#672](https://github.com/buschtoens/ember-link/pull/672)
  chore(deps): update @types dependencies ([@Turbo87])
```

2021-12-09 18:18 UTC, oscard0m commented
> I have just changed the link structure so now all links match. Can someone help me with the grouping? I think I would need to name the section where I put @oscard0m's links differently. Also, I am not adding any more links and will put everything after the 26th of November in the next post (possibly next week so it doesn't accumulate).

I created a PR from this branch:
* add/fix some links missing
* added proposal to group `oscard0m's` contributions

Let me know your thoughts and we can merge that into this branch.

2021-12-09 18:19 UTC, oscard0m commented
2 things I would like to talk about:

* How to group contributions ([reference](https://github.com/simplabs/simplabs.github.io/pull/1641#issuecomment-982640209))
* The format of `[repo](link) [#PR/#Issue](link) PR/Issue title ([author](link))` is a bit overwhelming IMO, what do you think about this format:

```markdown
## [Project](link to project)

### [Repo1](link to repo)
* Title PR/issue [#PR/#Issue](link) [@author](link)
* Title2 PR/issue [#PR/#Issue](link) [@author](link)

### [Repo2](link to repo)
* Title PR/issue [#PR/#Issue](link) [@author](link)
* Title2 PR/issue [#PR/#Issue](link) [@author](link)
```

Any thoughts?

2021-12-10 07:15 UTC, emmasofiah2o commented
> 2 things I would like to talk about:
> 
> * How to group contributions ([reference](https://github.com/simplabs/simplabs.github.io/pull/1641#issuecomment-982640209))
> * The format of `[repo](link) [#PR/#Issue](link) PR/Issue title ([author](link))` is a bit overwhelming IMO, what do you think about this format:
> 
> ```gfm
> ## [Project](link to project)
> 
> ### [Repo1](link to repo)
> * Title PR/issue [#PR/#Issue](link) [@author](link)
> * Title2 PR/issue [#PR/#Issue](link) [@author](link)
> 
> ### [Repo2](link to repo)
> * Title PR/issue [#PR/#Issue](link) [@author](link)
> * Title2 PR/issue [#PR/#Issue](link) [@author](link)
> ```
> 
> Any thoughts?

Sounds good to me, but I really want to get this out today... I don't know if maybe we want to change this for the next post?

2021-12-10 07:17 UTC, emmasofiah2o commented
The grouping could also work. I'll try restructuring in a few minutes so I can finally post

2021-12-10 07:50 UTC, Turbo87 commented
> * The format of `[repo](link) [#PR/#Issue](link) PR/Issue title ([author](link))` is a bit overwhelming IMO, what do you think about this format:
> 
> ```gfm
> ## [Project](link to project)
> 
> ### [Repo1](link to repo)
> * Title PR/issue [#PR/#Issue](link) [@author](link)
> * Title2 PR/issue [#PR/#Issue](link) [@author](link)
> 
> ### [Repo2](link to repo)
> * Title PR/issue [#PR/#Issue](link) [@author](link)
> * Title2 PR/issue [#PR/#Issue](link) [@author](link)
> ```

That would create a second layer of categories and we often have cases where there is only a single PR for a repo, which then causes that one PR to take significantly more space. The reason why I've put the project name at the start was that the rest behind it is then aligned and it's easy to ignore the first "column" if you don't care about it.

2021-12-10 08:00 UTC, emmasofiah2o commented
> > * The format of `[repo](link) [#PR/#Issue](link) PR/Issue title ([author](link))` is a bit overwhelming IMO, what do you think about this format:
> > 
> > ```
> > ## [Project](link to project)
> > 
> > ### [Repo1](link to repo)
> > * Title PR/issue [#PR/#Issue](link) [@author](link)
> > * Title2 PR/issue [#PR/#Issue](link) [@author](link)
> > 
> > ### [Repo2](link to repo)
> > * Title PR/issue [#PR/#Issue](link) [@author](link)
> > * Title2 PR/issue [#PR/#Issue](link) [@author](link)
> > ```
> 
> That would create a second layer of categories and we often have cases where there is only a single PR for a repo, which then causes that one PR to take significantly more space. The reason why I've put the project name at the start was that the rest behind it is then aligned and it's easy to ignore the first "column" if you don't care about it.

I have started changing this already... I think it makes sense for most projects (for example crates.io). Let me finish and push changes and you can tell me what you think

2021-12-10 08:06 UTC, emmasofiah2o commented
Just pushed, please let me know if I need to change this again (hopefully not).

2021-12-10 08:18 UTC, emmasofiah2o commented
![2021-10-12-this-week-in-os](https://user-images.githubusercontent.com/83696750/145540596-a02324d1-0814-4346-b5f4-3cb66c5ebb17.png)
I've just created the og-image. Does this work or did you have something else in mind?

2021-12-10 08:57 UTC, Turbo87 commented on _posts/2021-12-05-this-week-in-os-1.md
> +### [simplabs/ember-simple-auth](https://github.com/simplabs/ember-simple-auth)
this feels like unnecessary duplication to me now

2021-12-10 08:58 UTC, Turbo87 commented on _posts/2021-12-05-this-week-in-os-1.md
> +  ([@BobrImperator])
```suggestion
- put internal-session into DI system
  [#2315](https://github.com/simplabs/ember-simple-auth/pull/2315)
  ([@BobrImperator])
```

or was there a reason why that number was in the front? 🤔

2021-12-10 08:59 UTC, Turbo87 commented on _posts/2021-12-05-this-week-in-os-1.md
> +  Remove obsolete extern crate http instructions ([@Turbo87])
these still have the project in the front

2021-12-10 09:00 UTC, Turbo87 commented
> Just pushed

still not a big fan of this new format. it feels too verbose to me. 🤷‍♂️

2021-12-10 09:04 UTC, emmasofiah2o commented on _posts/2021-12-05-this-week-in-os-1.md
> +  ([@BobrImperator])
It was in the title of the PR

2021-12-10 09:04 UTC, emmasofiah2o commented on _posts/2021-12-05-this-week-in-os-1.md
> +  Remove obsolete extern crate http instructions ([@Turbo87])
Oh oops, thanks for telling me

2021-12-10 09:05 UTC, emmasofiah2o commented
> > Just pushed
> 
> still not a big fan of this new format. it feels too verbose to me. 🤷‍♂️

What do you mean by that? We actually reduced the number of words for most links. Like the crates.io stuff had a ton of repetitions.

2021-12-10 12:44 UTC, marcoow requested changes, later dismissed

2021-12-10 12:44 UTC, marcoow commented on _posts/2021-12-10-this-week-in-os-1.md
> +author: 'Simplabs'
```suggestion
author: 'simplabs'
```

Always lowercase

2021-12-10 13:16 UTC, oscard0m approved these changes

2021-12-10 13:25 UTC, merged