Add "Making your dynamic Ember components work with Embroider" blog post
mainmatter/mainmatter.com pull request #1706
Opened 2022-02-04 16:01 UTC by nickschot

2022-02-07 08:24 UTC, marcoow reviewed
Nice post 🙌 

I think a few parts assume more knowledge of ember-promise-modals than can be expected maybe and a few clarifications might be helpful. Otherwise I think this gives a great overview!

2022-02-07 08:24 UTC, marcoow commented on _posts/2022-02-04-dynamic-components-embroider.md
> +Embroider's routes-plitting feature.
```suggestion
Embroider's route-splitting feature.
```

unless this is a joke I don't understand :)

2022-02-07 08:24 UTC, marcoow commented on _posts/2022-02-04-dynamic-components-embroider.md
> +post will outline how we converted ember-promise-modals to be compatible with
consider linking ember-promise-modals?

2022-02-07 08:24 UTC, marcoow commented on _posts/2022-02-04-dynamic-components-embroider.md
> +that is the dasherized string representation of the component path:
Technically I think it's not the path but the container key that's usually based on the path (not sure that's actually relevant here and I might be wrong about it :) )?

2022-02-07 08:24 UTC, marcoow commented on _posts/2022-02-04-dynamic-components-embroider.md
> +post will outline how we converted ember-promise-modals to be compatible with
Might also make sense to add 1 sentence quickly describing what promise-modals is?

2022-02-07 08:24 UTC, marcoow commented on _posts/2022-02-04-dynamic-components-embroider.md
> +call, meaning there is no way to know this at build time.
Isn't the simpler example that the component name is in a variable or argument (e.g. the argument of the `open` method above) and that's already enough to make it sufficiently hard to statically analyze it so it can't really be done? Or would Embroider be able to detect that the above example is an invocation of the `<MyComponent>` component?

2022-02-07 08:24 UTC, marcoow commented on _posts/2022-02-04-dynamic-components-embroider.md
> +provide the route-splitting feature, which is not guaranteed with the component
Not sure this is immediately obvious to everyone – might make sense to include a brief explanation here: you need to know which components are used so you can leave all others out of the bundle etc.

2022-02-07 08:24 UTC, marcoow commented on _posts/2022-02-04-dynamic-components-embroider.md
> +`ember new my-app --embroider) your `ember-cli-build.js` file will contain a
```suggestion
`ember new my-app --embroider`) your `ember-cli-build.js` file will contain a
```

2022-02-07 08:24 UTC, marcoow commented on _posts/2022-02-04-dynamic-components-embroider.md
> +```
I'm not following where this is coming from tbh. Is this error coming from something like

```js
this.modals.open('epm-modal');
```

2022-02-07 12:42 UTC, emmasofiah2o reviewed
Left a few suggestions: mainly commas, a few "yet" out of place, and some word choices :D

2022-02-07 12:42 UTC, emmasofiah2o commented on _posts/2022-02-04-dynamic-components-embroider.md
> +This is great for addons like ember-promise-modals as it allows us to, in this
"This is great for addons like ember-promise-modals as in this case it allows us to open a modal from javascript. "

2022-02-07 12:42 UTC, emmasofiah2o commented on _posts/2022-02-04-dynamic-components-embroider.md
> +Fortunately Embroider provides a few tools for us to make this work.
```suggestion
Fortunately, Embroider provides a few tools for us to make this work.
```

2022-02-07 12:42 UTC, emmasofiah2o commented on _posts/2022-02-04-dynamic-components-embroider.md
> +yet to be fully Embroider optimized. By default Embroider currently ships
```suggestion
to be fully Embroider optimized yet. By default Embroider currently ships
```

2022-02-07 12:42 UTC, emmasofiah2o commented on _posts/2022-02-04-dynamic-components-embroider.md
> +Embroider's flags to ensure it will work. Normally you would do this one by one,
```suggestion
Embroider's flags. Normally you would do this one by one,
```

2022-02-07 12:42 UTC, emmasofiah2o commented on _posts/2022-02-04-dynamic-components-embroider.md
> +project from using a fully enabled Embroider with addons that do not yet have
```suggestion
project from using a fully enabled Embroider with addons that do not have
```

2022-02-07 12:42 UTC, emmasofiah2o commented on _posts/2022-02-04-dynamic-components-embroider.md
> +full Embroider support.
```suggestion
full Embroider support yet.
```

2022-02-07 12:42 UTC, emmasofiah2o commented on _posts/2022-02-04-dynamic-components-embroider.md
> +In order to let Embroider know how to handle our dynamic modal component we need
```suggestion
In order to let Embroider know how to handle our dynamic modal component, we need
```

2022-02-07 12:42 UTC, emmasofiah2o commented on _posts/2022-02-04-dynamic-components-embroider.md
> +the template. If just the name of a component is passed it will use the old
```suggestion
the template. If just the name of a component is passed, it will use the old
```

2022-02-07 12:42 UTC, emmasofiah2o commented on _posts/2022-02-04-dynamic-components-embroider.md
> +curly component resolver to get the component definition but also throw a
```suggestion
curly component resolver to get the component definition, but also throw a
```

2022-02-07 12:42 UTC, emmasofiah2o commented on _posts/2022-02-04-dynamic-components-embroider.md
> +Embroider. For comprehensive documentation see the
```suggestion
Embroider. For comprehensive documentation see:
```

2022-02-07 12:42 UTC, emmasofiah2o commented on _posts/2022-02-04-dynamic-components-embroider.md
> +documentation.
```suggestion

```

2022-02-07 12:42 UTC, emmasofiah2o commented on _posts/2022-02-04-dynamic-components-embroider.md
> +If we were to start our app now (with `staticComponents: false`) we will get the
```suggestion
If we were to start our app now (with `staticComponents: false`), we would get the
```

2022-02-07 12:42 UTC, emmasofiah2o commented on _posts/2022-02-04-dynamic-components-embroider.md
> +following deprecation message.
```suggestion
following deprecation message:
```

2022-02-07 12:42 UTC, emmasofiah2o commented on _posts/2022-02-04-dynamic-components-embroider.md
> +deprecation message go away. Note that this will _only_ work for co-located
```suggestion
deprecation message disappear. Note that this will _only_ work for co-located
```

2022-02-07 12:42 UTC, emmasofiah2o commented on _posts/2022-02-04-dynamic-components-embroider.md
> +file to use `@embroider/router`.
```suggestion
file to use `@embroider/router`...
```

2022-02-07 12:42 UTC, emmasofiah2o commented on _posts/2022-02-04-dynamic-components-embroider.md
> +And by configuring the `splitAtRoutes` feature in `ember-cli-build.js`. We can
```suggestion
...and by configuring the `splitAtRoutes` feature in `ember-cli-build.js`. We can
```

2022-02-07 12:42 UTC, emmasofiah2o commented on _posts/2022-02-04-dynamic-components-embroider.md
> +do this by adding the route names you want to split or by providing a regex. Our
```suggestion
do this by adding the route names we want to split or by providing a regex. Our
```

2022-02-07 12:42 UTC, emmasofiah2o commented on _posts/2022-02-04-dynamic-components-embroider.md
> +full configuration will now look like:
```suggestion
full configuration will now look like this:
```

2022-02-07 12:42 UTC, emmasofiah2o commented on _posts/2022-02-04-dynamic-components-embroider.md
> +If we now start our Embroider enabled app we will see that our `<ExampleModal/>`
```suggestion
If we now start our Embroider enabled app, we will see that our `<ExampleModal/>`
```

2022-02-18 13:21 UTC, nickschot commented on _posts/2022-02-04-dynamic-components-embroider.md
> +yet to be fully Embroider optimized. By default Embroider currently ships
I've just dropped the `yet` here  :P

2022-02-18 13:28 UTC, nickschot commented on _posts/2022-02-04-dynamic-components-embroider.md
> +```
not directly, it is caused by the component helper being invoked with a dynamic variable (`@modal._name`)

2022-02-18 13:29 UTC, nickschot commented on _posts/2022-02-04-dynamic-components-embroider.md
> +full Embroider support.
Also dropped the yet here

2022-02-18 13:37 UTC, nickschot commented on _posts/2022-02-04-dynamic-components-embroider.md
> +call, meaning there is no way to know this at build time.
Yeah might be, I think theoretically you could analyze that situation, but as far as I'm aware Embroider doesn't support it.

2022-02-18 13:39 UTC, nickschot commented on _posts/2022-02-04-dynamic-components-embroider.md
> +that is the dasherized string representation of the component path:
Hmmmm I'm not 100% sure how it strictly speaking is defined, there's nothing really in the ember docs about it. Maybe someone else knows?

2022-02-18 14:05 UTC, nickschot commented on _posts/2022-02-04-dynamic-components-embroider.md
> +post will outline how we converted ember-promise-modals to be compatible with
Oh yeah it was already meant to be a link, I just didn't reference it. I will also add a description.

2022-03-14 15:26 UTC, marcoow requested changes, later dismissed
Can we change the path names to reflect the actual posting date?

2022-03-14 15:26 UTC, marcoow commented on _posts/2022-02-04-dynamic-components-embroider.md
> +---
This is missing `description:` – maybe something like:

```suggestion
description: Nick Schot explains how to make dynamic component invocation work with Embroider's static analysis.
---
```

2022-03-14 15:26 UTC, marcoow commented on _posts/2022-02-04-dynamic-components-embroider.md
> +topic: javascript
```suggestion
topic: ember
```

2022-03-14 15:26 UTC, marcoow commented on _posts/2022-02-04-dynamic-components-embroider.md
> +```
Would it be helpful to show the respective line in ember-promise-modal's source for context?

2022-03-17 09:33 UTC, marcoow approved these changes

2022-03-17 09:48 UTC, merged