Journey/Tips from a Junior Software Engineer
mainmatter/mainmatter.com pull request #1722
Opened 2022-02-17 12:20 UTC by inesilva

I'm not sure about the title.
I was also not so sure about the topic, initially, I was planning to write 'React vs Plain JS', after asking the opinion of some of my friends they told me they would prefer to read about my journey.
So my idea was to try to sum up my biggest challenges so far and try to give tips based on them.

2022-05-09 08:11 UTC, emmasofiah2o requested changes
Done reviewing. I had quite a few changes to make. It is an interesting post, just needed a few corrections :)

2022-05-09 08:11 UTC, emmasofiah2o commented on _posts/2022-02-17-journey-of-a-junior-software-engineer.md
> +My journey in _Simplabs_ started in July of 2021, soon it will be 8 months that I’m here. This post has in mind all the future junior software-engineers. I will write how it has been like, how it is
```suggestion
My journey at _Simplabs_ started in July of 2021: soon it will be 8 months that I’m here. This post has in mind all the future junior software engineers. I will describe what it has been like and how it is now, and try to give some tips on the way based on the challenges I faced 💪
```

2022-05-09 08:11 UTC, emmasofiah2o commented on _posts/2022-02-17-journey-of-a-junior-software-engineer.md
> +Before landing here, I did 4 months internship as a ruby backend engineer 💎
```suggestion
Before landing here, I did a 4 months internship as a Ruby backend engineer 💎 
```

2022-05-09 08:11 UTC, emmasofiah2o commented on _posts/2022-02-17-journey-of-a-junior-software-engineer.md
> +I started looking for fullstack job positions - I wanted to get better at both things and discover the frontend world (that I had so little insight before).
```suggestion
I started looking for full-stack job positions. I wanted to get better at both things and discover the frontend world (that I had so little insight into before).
```

2022-05-09 08:11 UTC, emmasofiah2o commented on _posts/2022-02-17-journey-of-a-junior-software-engineer.md
> +I started looking for fullstack job positions - I wanted to get better at both things and discover the frontend world (that I had so little insight before).
Also, what are "both things"? It's a bit unclear

2022-05-09 08:11 UTC, emmasofiah2o commented on _posts/2022-02-17-journey-of-a-junior-software-engineer.md
> +I can stop here for the **#1 tip** - **if you don’t know,** **start as fullstack.** So you can get better on both things and eventually find what fits you better, or just stay in both worlds.
Again, "both things" is unclear

2022-05-09 08:11 UTC, emmasofiah2o commented on _posts/2022-02-17-journey-of-a-junior-software-engineer.md
> +Here, I started working in a website for an IT security company. The stack was - Next.js & Typescript.
```suggestion
Here, I immediately started working on a website for an IT security company. The stack was Next.js & Typescript.
```

2022-05-09 08:11 UTC, emmasofiah2o commented on _posts/2022-02-17-journey-of-a-junior-software-engineer.md
> +As I said before I had very little experience with the frontend world, and apparently with git 😅
```suggestion
As I said before I had very little experience with the frontend world, and apparently with git. 😅
```

2022-05-09 08:11 UTC, emmasofiah2o commented on _posts/2022-02-17-journey-of-a-junior-software-engineer.md
> +My first struggles were git-related problems - I feel this is the thing that developers tend to be overconfident about their expertise on it.
```suggestion
My first struggles were git-related problems - I feel this is the thing that developers tend to be overconfident about.
```

2022-05-09 08:11 UTC, emmasofiah2o commented on _posts/2022-02-17-journey-of-a-junior-software-engineer.md
> +In university, everytime, we started a project using git we would drop it at some point and we would go to the archaic system of copy-pasting code between us 🥲
```suggestion
In university, every time we started a project using git we would drop it at some point and we would go to the archaic system of copy-pasting code between us. 🥲
```

2022-05-09 08:11 UTC, emmasofiah2o commented on _posts/2022-02-17-journey-of-a-junior-software-engineer.md
> +You will never be alone in a project, so force yourself to learn tools that will make you more efficient to work as a team. Most of my colleagues always use the terminal so I found it easier to get a
```suggestion
You will never be alone in a project, so force yourself to learn tools that will make you more efficient at working as a team. Most of my colleagues always use the terminal so I found it easier to go along with this method (plus it gives you that hacker look) 😎 but there is an interface option [Github Desktop](https://desktop.github.com/). Since I was documenting all of my git struggles, I will give you a glimpse at what my notion notes were looking like in my second week here 😂:
```

2022-05-09 08:11 UTC, emmasofiah2o commented on _posts/2022-02-17-journey-of-a-junior-software-engineer.md
> +Git merge vs Git rebase were a frequent debate, and according to my notes I found this video enlightening on the [topic](https://www.youtube.com/watch?v=CRlGDDprdOQ&ab_channel=Academind).
```suggestion
Git merge vs Git rebase was a frequent debate, and according to my notes, I found this enlightening video on the [topic](https://www.youtube.com/watch?v=CRlGDDprdOQ&ab_channel=Academind).
```

2022-05-09 08:11 UTC, emmasofiah2o commented on _posts/2022-02-17-journey-of-a-junior-software-engineer.md
> +Then, when I was finally becoming more confortable with which commands should I use, they tell me - tidy your git history 🧹 - [this post](https://simplabs.com/blog/2021/05/26/keeping-a-clean-git-hist
```suggestion
Then, when I was finally becoming more comfortable with which commands I should use, they told me to tidy my git history 🧹 - [this post](https://simplabs.com/blog/2021/05/26/keeping-a-clean-git-history/) done by Chris came in handy.
```

2022-05-09 08:11 UTC, emmasofiah2o commented on _posts/2022-02-17-journey-of-a-junior-software-engineer.md
> +I believe the junior phase can be the most overwhelming one - your learning curve is on sky rocket mode 🚀 - with all this new info coming all the time, I find out helpful to write it down as a way to
```suggestion
I believe the junior phase can be the most overwhelming one: your learning curve is in skyrocket mode 🚀! With all this new info coming all the time, I find it helpful to write everything down as a way to organize the new content in my head.
```

2022-05-09 08:11 UTC, emmasofiah2o commented on _posts/2022-02-17-journey-of-a-junior-software-engineer.md
> +Also, a lot of errors I was seeing, they would show up again, I could find what I did & apply it again.
```suggestion
Also, since a lot of errors I was seeing would show up again, I could find what I did & re-apply it.
```

2022-05-09 08:11 UTC, emmasofiah2o commented on _posts/2022-02-17-journey-of-a-junior-software-engineer.md
> +Nowadays, I do it less and less, also the pace slowed it down from week logs to month logs 😆 as you can see by my notion pages:
```suggestion
Nowadays, I need to take notes less and less and even the pace slowed down from week logs to month logs 😆 as you can see by my notion pages:
```

2022-05-09 08:11 UTC, emmasofiah2o commented on _posts/2022-02-17-journey-of-a-junior-software-engineer.md
> +After git problems, the 2nd position in the podium of challenges goes to testing 🏆
```suggestion
After git problems, the second position on the podium of challenges goes to testing 🏆
```

2022-05-09 08:11 UTC, emmasofiah2o commented on _posts/2022-02-17-journey-of-a-junior-software-engineer.md
> +I don’t know how it works in other degrees, but I didn’t write a single test for my programs till I enter the professional world.
```suggestion
I don’t know how it works in other degrees, but I didn’t write a single test for my programs until I enter the professional world.
```

2022-05-09 08:11 UTC, emmasofiah2o commented on _posts/2022-02-17-journey-of-a-junior-software-engineer.md
> +Since I’m working here, I’ve been using a JS testing framework, _[Jest](https://jestjs.io/)_ and a [*react testing library](https://testing-library.com/docs/react-testing-library/intro/).* Till recen
```suggestion
Since I’m working here, I’ve been using a JS testing framework, _[Jest](https://jestjs.io/)_ and a [*react testing library](https://testing-library.com/docs/react-testing-library/intro/).* Until recently, I have wondered: ‘My code is done, why am I wasting my time with this?’ - especially when a lot of times I was losing more time in writing tests than actual code. 😅 However, a few weeks ago, the moment came when I thanked myself for having tests. 💡 I have been working on a project since September so at this point it is getting pretty big.
```

2022-05-09 08:11 UTC, emmasofiah2o commented on _posts/2022-02-17-journey-of-a-junior-software-engineer.md
> +We are in the process of adding validations in user forms, and the tests are being like a bulletproof jacket 🛡️
```suggestion
We are in the process of adding validations in user forms, and the tests are functioning like a bulletproof jacket. 🛡️
```

2022-05-09 08:11 UTC, emmasofiah2o commented on _posts/2022-02-17-journey-of-a-junior-software-engineer.md
> +Multiple times I thought that my code was working good but then I ran the tests and I was breaking code of other features 🥲 My previous mentor once told me that he prefers to write the tests before h
```suggestion
Multiple times I thought that my code was working well but then I ran the tests and realized I was breaking the code of other features. 🥲 My previous mentor once told me that he prefers to write the tests before his code as a way of breaking down the steps of the problem and building confidence in his code.
```

2022-05-09 08:11 UTC, emmasofiah2o commented on _posts/2022-02-17-journey-of-a-junior-software-engineer.md
> +This style of programming is called TDD - test-driven development. In my head, it looked weird - “how can I write a test before having the code?”, but I’m starting to do it now:
```suggestion
This style of programming is called TDD - test-driven development. In my head it looked weird - “how can I write a test before having the code?”, but I have started to do it now:
```

2022-05-09 08:11 UTC, emmasofiah2o commented on _posts/2022-02-17-journey-of-a-junior-software-engineer.md
> +I needed to add a validation for an input, and I started with the code above, after, I would go to my validation function and change it till I make sure I was throwing an invalid response for null va
```suggestion
I needed to add a validation for an input and I started with the code above, after which I would go to my validation function and change it until I made sure I was throwing an invalid response for null values. 
```

2022-05-09 08:11 UTC, emmasofiah2o commented on _posts/2022-02-17-journey-of-a-junior-software-engineer.md
> +It’s still not my cup of tea, I want to invest more in learning about it and it will probably be more enjoyable once I get better at it, I will try to get my colleagues to pair program with me about
```suggestion
It’s still not my cup of tea. I want to invest more in learning about it and it will probably be more enjoyable once I get better at it, so I will try to get my colleagues to pair program with me about this.
```

2022-05-09 08:11 UTC, emmasofiah2o commented on _posts/2022-02-17-journey-of-a-junior-software-engineer.md
> +The way this goes depends on the environment of your company, unfortunately, I see a lot of juniors that tell me that they never did pair programming with any colleague or that they get judged by the
```suggestion
The way this goes depends on the environment within your company. Unfortunately, I see a lot of juniors that tell me that they never did pair programming with a colleague or that they get judged by the amount of time they need to accomplish their tasks.
```

2022-05-09 08:11 UTC, emmasofiah2o commented on _posts/2022-02-17-journey-of-a-junior-software-engineer.md
> +Till my first 3 months, I think I was pairing at least once a week sometimes more.
```suggestion
During my first 3 months at simplabs, I was probably pair programming at least once a week, sometimes more. 
```

2022-05-09 08:11 UTC, emmasofiah2o commented on _posts/2022-02-17-journey-of-a-junior-software-engineer.md
> +Right now I'm doing it less which is natural - as you progress the more independent you become.
```suggestion
Right now I'm doing it less often, which is natural - the more you progress the more independent you become.
```

2022-05-09 08:11 UTC, emmasofiah2o commented on _posts/2022-02-17-journey-of-a-junior-software-engineer.md
> +However, I want to go back to more regular pair programming sessions - not only is it a great way of learning, but it also makes you know better your colleagues thinking flow which makes it easier fo
```suggestion
However, I do want to go back to more regular pair programming sessions - not only is it a great way of learning, but it also makes you understand your colleagues' thinking flow better, which makes reviewing each other's code easier.
```

2022-05-09 08:11 UTC, emmasofiah2o commented on _posts/2022-02-17-journey-of-a-junior-software-engineer.md
> +-   I keep doing react, it has some tricky concepts that I’m still trying to fully understand, like dealing with the state of components.
```suggestion
-   I keep working with React: it has some tricky concepts that I’m still trying to fully understand, like dealing with the state of components.
```

2022-05-09 08:11 UTC, emmasofiah2o commented on _posts/2022-02-17-journey-of-a-junior-software-engineer.md
> +-   We have 1 day per week to work in open source/learning. I’m using mine to create a personal website in ember which has been a great way of learning while doing a project that I like.
```suggestion
-   We have 1 day per week to work on open source/learning. I’m using mine to create a personal website in Ember which has been a great way of learning while doing a project that I like.
```

2022-05-09 08:11 UTC, emmasofiah2o commented on _posts/2022-02-17-journey-of-a-junior-software-engineer.md
> +-   I’m part of the culture team - we discuss topics that aim for a continuous good team environment. I’m organizing the Lunch & Learn event once a month which was born from these meetings.
```suggestion
-   I’m part of the culture team - we discuss topics that aim for keeping a nice team environment. I’m organizing the Lunch & Learn event once a month which was born from these meetings.
```

2022-05-09 08:11 UTC, emmasofiah2o commented on _posts/2022-02-17-journey-of-a-junior-software-engineer.md
> +-   I’m having 🇫🇷 lessons, I’m very happy that Simplabs gives me the opportunity to grow in other fields too.
```suggestion
-   I’m having French 🇫🇷 lessons. I’m very happy that Simplabs gives me the opportunity to grow in other fields, too!
```

2022-05-09 08:11 UTC, emmasofiah2o commented on _posts/2022-02-17-journey-of-a-junior-software-engineer.md
> +As for my fellow, junior software engineers hope this helps in some way.
```suggestion
As for my fellow, junior software engineers, I hope this helped you in some way. 
```

2022-05-09 08:11 UTC, emmasofiah2o commented on _posts/2022-02-17-journey-of-a-junior-software-engineer.md
> +Don’t hesitate if you feel like sharing the challenges & your progress with me.
```suggestion
Feel free to share your challenges and progress with me. 
```

2022-05-09 08:11 UTC, emmasofiah2o commented on _posts/2022-02-17-journey-of-a-junior-software-engineer.md
> +Keep learning & being curious!
```suggestion
Keep learning & stay curious!
```

2022-05-09 08:26 UTC, marcoow reviewed
This is a really cool post – I think the tips certainly can help some other people, in particular I like the journal concept!

If you need some help to get the build to succeed, please reach out – once everything builds, there'll be a preview deployment which will allow everyone to preview the post on the real site.

2022-05-09 08:26 UTC, marcoow commented on _posts/2022-02-17-journey-of-a-junior-software-engineer.md
> +My journey in _Simplabs_ started in July of 2021, soon it will be 8 months that I’m here. This post has in mind all the future junior software-engineers. I will write how it has been like, how it is
```suggestion
My journey in simplabs started in July of 2021, soon it will be 8 months that I’m here. This post has in mind all the future junior software-engineers. I will write how it has been like, how it is now and try to give some tips on the way based on the challenges I faced 💪
```

always lowercase :)

2022-05-09 08:26 UTC, marcoow commented on _posts/2022-02-17-journey-of-a-junior-software-engineer.md
> +After the internship, I landed at _Simplabs_ for my 1st job 🙌
```suggestion
After the internship, I landed at simplabs for my 1st job 🙌
```

2022-05-09 08:26 UTC, marcoow commented on _posts/2022-02-17-journey-of-a-junior-software-engineer.md
> +Here, I started working in a website for an IT security company. The stack was - Next.js & Typescript.
```suggestion
Here, I started working in a web app for an IT security company. The stack was - Next.js & Typescript.
```

"website" would typically refer to a static webpage.

2022-05-09 08:26 UTC, marcoow commented on _posts/2022-02-17-journey-of-a-junior-software-engineer.md
> +-   I’m having 🇫🇷 lessons, I’m very happy that Simplabs gives me the opportunity to grow in other fields too.
```suggestion
-   I’m having 🇫🇷 lessons, I’m very happy that simplabs gives me the opportunity to grow in other fields too.
```

2022-05-10 09:00 UTC, inesilva commented on _posts/2022-02-17-journey-of-a-junior-software-engineer.md
> +I started looking for fullstack job positions - I wanted to get better at both things and discover the frontend world (that I had so little insight before).
you're right. Maybe I would change to - 'I wanted to continue to improve my backend knowledge and discover the frontend world (that I had so little insight into before)

2022-05-10 09:08 UTC, inesilva commented on _posts/2022-02-17-journey-of-a-junior-software-engineer.md
> +I can stop here for the **#1 tip** - **if you don’t know,** **start as fullstack.** So you can get better on both things and eventually find what fits you better, or just stay in both worlds.
So you can a better picture of the backend and frontend parts of a project, eventually, find what fits you better, or just stay in both worlds.

2022-05-10 09:12 UTC, emmasofiah2o commented on _posts/2022-02-17-journey-of-a-junior-software-engineer.md
> +I can stop here for the **#1 tip** - **if you don’t know,** **start as fullstack.** So you can get better on both things and eventually find what fits you better, or just stay in both worlds.
```suggestion
I can stop here for the **#1 tip** - **if you don’t know,** **start as full-stack.** This way, you can get a better picture of both frontend and backend parts of a project and then find what fits you better or just stay in both worlds.
```

2022-05-10 09:12 UTC, emmasofiah2o commented on _posts/2022-02-17-journey-of-a-junior-software-engineer.md
> +I started looking for fullstack job positions - I wanted to get better at both things and discover the frontend world (that I had so little insight before).
Sounds good :)

2022-05-10 09:14 UTC, inesilva commented on _posts/2022-02-17-journey-of-a-junior-software-engineer.md
> +-   I’m having 🇫🇷 lessons, I’m very happy that Simplabs gives me the opportunity to grow in other fields too.
Maybe I would shorten the other phrase too: 
I'm happy that Simplabs allows me to grow in other fields!

2022-05-10 09:37 UTC, emmasofiah2o commented on _posts/2022-02-17-journey-of-a-junior-software-engineer.md
> +-   I’m having 🇫🇷 lessons, I’m very happy that Simplabs gives me the opportunity to grow in other fields too.
Feel free to just write these down as suggestions, see what works best and then commit the suggestion. I'll do a second proof read once you are done if you'd like me to :)

2022-05-13 10:46 UTC, BobrImperator requested changes, later dismissed

2022-05-13 10:46 UTC, BobrImperator commented on _posts/2022-02-17-journey-of-a-junior-software-engineer.md
> +![](/assets/images/posts/2022-02-17-journey-of-a-junior-software-engineer/my-notion-notes-eg2.png)
The picture below features AIS client.
Did we have an NDA with them? @marcoow 

It could be a good idea to obfuscate the picture so we don't show AIS domain at all.
![Image](https://github.com/simplabs/simplabs.github.io/blob/journey-as-junior-dev/public/assets/images/posts/2022-02-17-journey-of-a-junior-software-engineer/my-notion-notes-eg2.png?raw=true)

2022-05-13 10:56 UTC, mansona commented on _posts/2022-02-17-journey-of-a-junior-software-engineer.md
> +
So the deploy preview on Netlify is failing because of an error: 

```
11:44:58 AM: Post "Journey of a Junior Software-Engineer" does not contain break marker! Add "<!--break-->" after the teaser.
```
I guess it makes sense to add it after this line?

```suggestion

<!--break-->

```

2022-05-13 13:43 UTC, inesoaresilva commented on _posts/2022-02-17-journey-of-a-junior-software-engineer.md
> +I started looking for fullstack job positions - I wanted to get better at both things and discover the frontend world (that I had so little insight before).
> 

```suggestion
I wanted to continue to improve my backend knowledge and discover the frontend world (that I had so little insight into before)
```

>

2022-05-13 13:43 UTC, inesoaresilva commented on _posts/2022-02-17-journey-of-a-junior-software-engineer.md
> +![](/assets/images/posts/2022-02-17-journey-of-a-junior-software-engineer/my-notion-notes-eg2.png)
I didn't think about these things. I can blur 'https://ais...' part

2022-05-16 06:52 UTC, marcoow commented on _posts/2022-02-17-journey-of-a-junior-software-engineer.md
> +![](/assets/images/posts/2022-02-17-journey-of-a-junior-software-engineer/my-notion-notes-eg2.png)
not sure what the image was but seems this was changed already?

2022-05-19 08:40 UTC, emmasofiah2o approved these changes

2022-05-19 09:20 UTC, merged