Blog post: Migrate Ember app to CSS modules
mainmatter/mainmatter.com pull request #1838
Opened 2022-08-08 13:13 UTC by BlueCutOfficial

TODO
- [ ] `og-image`

## Blog post: Migrate Ember app to CSS modules
This blog post proposal is a tutorial to start working with `ember-css-modules` in an existing Ember app. The purpose is to walk through the install process based on SuperRentals app and to help understanding `ember-css-module` doc out of a more practical perspective.

2022-08-08 14:27 UTC, lolmaus requested changes
Nice work!!

To maximize its value to developers, I think this article needs more structure:

* There should be a section explaining what CSS Modules are as a concept; what problems this technique aims to solve and how it is beneficial over global CSS; what alternatives are (e. g. `ember-component-css`) and why they are no good.
* Instead of installing the addon and exploring why the app broke and how to fix it, there should be a clear plan: describe how the addon is supposed to work *before* showing how it breaks an app. Maybe a section describing using the addon with a greenfield app might be helpful: it would set up a scene in the reader's head before frustrating them with broken CSS.

2022-08-08 14:27 UTC, lolmaus commented on _posts/2022-08-05-cookbook-ember-app-to-css-modules.md
> +addon that let developers easily integrate CSS modules to the implementation of
> addon that let developers easily integrate CSS modules

"CSS modules" isn't a standard term. It's not a standard, not a spec, not a library, not a @keyword.

So I believe it requires a brief introduction, something like: "...integrate CSS modules: a technique that lets you scope CSS classes by file, one per component or route".

2022-08-08 14:27 UTC, lolmaus commented on _posts/2022-08-05-cookbook-ember-app-to-css-modules.md
> +app triggers some breaking changes in the way the integrator should handle the
I found "integrator" confusing. "Developer" maybe?

2022-08-08 14:27 UTC, lolmaus commented on _posts/2022-08-05-cookbook-ember-app-to-css-modules.md
> +  existing app that already contains a global CSS.
I believe CSS is not countable, so instead of `a global CSS` it should be `global CSS` or `a global CSS setup`.

2022-08-08 14:27 UTC, lolmaus commented on _posts/2022-08-05-cookbook-ember-app-to-css-modules.md
> +example. SuperRentals is the great tutorial part of the Ember guides to
`is the great tutorial part` → `is a great tutorial part` maybe?

2022-08-08 14:27 UTC, lolmaus commented on _posts/2022-08-05-cookbook-ember-app-to-css-modules.md
> +was implemented as a migration test to Typescript). The file name is clickable
Should be capitalized as `TypeScript`. But is this relevant to the article?

2022-08-08 14:27 UTC, lolmaus commented on _posts/2022-08-05-cookbook-ember-app-to-css-modules.md
> +to apply globally. The isolation system applies on every CSS files, including
prevent `from`

2022-08-08 14:27 UTC, lolmaus commented on _posts/2022-08-05-cookbook-ember-app-to-css-modules.md
> +don't have a custom id. The `:global` directive indicates these classes are
Technically, `:global` is not a directive and more like a pseudoselector... But it may be OK to keep using the word `directive`.

2022-08-08 14:27 UTC, lolmaus commented on _posts/2022-08-05-cookbook-ember-app-to-css-modules.md
> +`ember-css-modules`. For instance, the `composes` feature is not about
The `composes` feature has not been mentioned before, so passage is hard to understand.

2022-08-08 16:14 UTC, BlueCutOfficial commented
@lolmaus thank you for all the feedbacks. I still need to work on my English so it's nice to have all these suggestions. Regarding the global comments:  

> There should be a section explaining what CSS Modules are as a concept; what problems this technique aims to solve and how it is beneficial over global CSS; what alternatives are (e. g. ember-component-css) and why they are no good.

The issue I have with this is that might be pretty long. I wanted this post to be a short tutorial to achieve something rather specific: set up `ember-css-modules` in an existing Ember app, so I believe such an intro would be a bit out of scope. That's why I put in the prerequisite: "You know a bit the theory about what CSS modules are but it might be the first time you actually try to work with them."

But in the other hand, I admit this prerequisite might sound like a closure for people who arrive randomly on this blog post without any knowledge on CSS modules. What I would prefer in this case is completing this bullet point with reference links to other contents explaining (better than I will) what CSS modules are, like this one: https://developer.adobe.com/commerce/pwa-studio/guides/general-concepts/css-modules/ but I am not sure what would be the best references on this topic. I'll dig into this, but don't hesitate if you have a good article in mind.

> Instead of installing the addon and exploring why the app broke and how to fix it, there should be a clear plan: describe how the addon is supposed to work before showing how it breaks an app. Maybe a section describing using the addon with a greenfield app might be helpful: it would set up a scene in the reader's head before frustrating them with broken CSS.

I am not convinced about this, because this plan wouldn't actually match the reality of what you experience as a developer. What happens to you as a developer is you install `ember-css-modules` => and your app breaks. I designed this article as a tutorial that creates the relief moment when you read black on white that oh! ok, my app should break, this is normal, and now I am going to read further to understand why. It is really on purpose that I put the practice before the theory here. Maybe I can improve a bit, maybe some short intro about `ember-css-modules` is missing, but I rather disagree to change completly the aprroach.

2022-08-08 16:18 UTC, BlueCutOfficial commented on _posts/2022-08-05-cookbook-ember-app-to-css-modules.md
> +`ember-css-modules`. For instance, the `composes` feature is not about
That's true. As the post focus on preparing the existing app for the migration, I thought maybe talking about `composes` would be out of scope. But in the other hand, that's actually quite interesting to understand what is the result of using this. So maybe it deserves a part too, or maybe I should remove that reference, even if it was tempting to mention it 🤔

2022-08-08 16:19 UTC, BlueCutOfficial commented on _posts/2022-08-05-cookbook-ember-app-to-css-modules.md
> +don't have a custom id. The `:global` directive indicates these classes are
I picked the word directive in the documentation, I'll read again to be sure it was the same context.

2022-08-08 16:20 UTC, BlueCutOfficial commented on _posts/2022-08-05-cookbook-ember-app-to-css-modules.md
> +example. SuperRentals is the great tutorial part of the Ember guides to
I meant "the" in the way I am talking about a very specific tutorial (the SuperRentals one), but there's certainly a way to turn the whole sentence better... -_-

2022-08-08 16:22 UTC, BlueCutOfficial commented on _posts/2022-08-05-cookbook-ember-app-to-css-modules.md
> +addon that let developers easily integrate CSS modules to the implementation of
Maybe the solution is to locate this after the prerequisite list and these references to docs about CSS modules I need to add (see general comment).

2022-08-08 16:36 UTC, marcoow reviewed
Nice post! I think it's a good topic and has a nice flow. I'd just consider explaining the core concept of CSS modules (that you don't have global styles and all styles are local within some boundary they cannot leak out of) and ember-css-modules (the CSS modules boundary is the component or route template) to make things a bit clearer. You can probably get away with only a few sentences about that.

I think there are some grammar mistakes left – consider using sth. like Grammarly maybe.

One thing I'd like to note is feel free to be a bit more colloquial (if you want – if not that's fine as well :) )

2022-08-08 16:37 UTC, marcoow commented on _posts/2022-08-05-cookbook-ember-app-to-css-modules.md
> +addon that let developers easily integrate CSS modules to the implementation of
see my comment – one paragraph introducing the concept would be helpful (even if most readers might know already)

2022-08-08 16:38 UTC, marcoow commented on _posts/2022-08-05-cookbook-ember-app-to-css-modules.md
> +`ember-css-modules`. For instance, the `composes` feature is not about
I think you could leave it out here – it's maybe more something for a follow-up post on more advanced CSS modules aspects?

2022-08-08 16:39 UTC, marcoow commented
> Instead of installing the addon and exploring why the app broke and how to fix it, there should be a clear plan: describe how the addon is supposed to work before showing how it breaks an app. Maybe a section describing using the addon with a greenfield app might be helpful: it would set up a scene in the reader's head before frustrating them with broken CSS.

I think the approach is fine and it's kind of a funny entry to the post's flow to say let's install this and break everything :)

2022-08-10 08:57 UTC, marcoow approved these changes
Nice post 🙌 

I left some comments mainly on minor languages aspects but will approve already to not block this.

2022-08-10 08:57 UTC, marcoow commented on _posts/2022-08-05-cookbook-ember-app-to-css-modules.md
> +using only one global CSS to CSS modules with
```suggestion
using global CSS to CSS modules with
```

I get what you want to say but I think it doesn't quite work like that since _"only one global CSS"_ kind of implies there could also be 2 or n global CSSs :)

2022-08-10 08:57 UTC, marcoow commented on _posts/2022-08-05-cookbook-ember-app-to-css-modules.md
> +  can be used in the Ember context.
```suggestion
  can be used in an Ember context.
```

?

2022-08-10 08:57 UTC, marcoow commented on _posts/2022-08-05-cookbook-ember-app-to-css-modules.md
> +CSS that applies globally on the whole page has some downsides in big and
```suggestion
on the page. Even when split into different files, having one 
CSS scope that applies globally on the whole page has some downsides in big and
```

I think scope is the keyword here?

2022-08-10 08:57 UTC, marcoow commented on _posts/2022-08-05-cookbook-ember-app-to-css-modules.md
> +complex applications. For instance, managing reusable components style is
```suggestion
complex applications. For instance, managing reusable component styles is
```

2022-08-10 08:57 UTC, marcoow commented on _posts/2022-08-05-cookbook-ember-app-to-css-modules.md
> +is not familiar with CSS modules in the first place, they might spend a hard
```suggestion
is not familiar with CSS modules in the first place, they might have a hard
```

2022-08-10 08:57 UTC, marcoow commented on _posts/2022-08-05-cookbook-ember-app-to-css-modules.md
> +[SuperRentals app](https://guides.emberjs.com/release/tutorial/part-1/) as an
```suggestion
the [SuperRentals app](https://guides.emberjs.com/release/tutorial/part-1/) as an
```

2022-08-10 08:57 UTC, marcoow commented on _posts/2022-08-05-cookbook-ember-app-to-css-modules.md
> +introduce the main Ember features. As the purpose of SuperRentals app is to
```suggestion
introduce the main Ember features. As the purpose of the SuperRentals app is to
```

2022-08-10 08:57 UTC, marcoow commented on _posts/2022-08-05-cookbook-ember-app-to-css-modules.md
> +learn Ember and writing CSS is irrelevant to the matter, the CSS to style the
```suggestion
teach Ember and writing CSS is irrelevant to the matter, the CSS to style the
```

:)

2022-08-10 08:57 UTC, marcoow commented on _posts/2022-08-05-cookbook-ember-app-to-css-modules.md
> +So let's make SuperRentals app ready for migration to CSS modules.
```suggestion
So let's make the SuperRentals app ready for migration to CSS modules.
```

2022-08-10 08:57 UTC, marcoow commented on _posts/2022-08-05-cookbook-ember-app-to-css-modules.md
> +Let's suppose we have finished implementing SuperRentals app. The following
```suggestion
Let's suppose we have finished implementing the SuperRentals app. The following
```

Alternatively you could also just say "SuperRentals" without "app" but I think adding "app" requires an article.

2022-08-10 08:57 UTC, marcoow commented on _posts/2022-08-05-cookbook-ember-app-to-css-modules.md
> +provided in SuperRentals tutorial:
```suggestion
provided in the tutorial:
```

2022-08-10 08:57 UTC, marcoow commented on _posts/2022-08-05-cookbook-ember-app-to-css-modules.md
> +Ouch, all the style is broken. What we see now in the browser is very similar to
```suggestion
Ouch, all the styles are broken. What we see now in the browser is very similar to
```

I think using plural to refer to an app's styles is more common.

2022-08-10 08:57 UTC, marcoow commented on _posts/2022-08-05-cookbook-ember-app-to-css-modules.md
> +`class="right tomster"`. As result, no CSS style is found for `.right` and
```suggestion
`class="right tomster"`. As a result, no CSS class is found for `.right` and
```

2022-08-10 08:57 UTC, marcoow commented on _posts/2022-08-05-cookbook-ember-app-to-css-modules.md
> +elements like `div` don't have any custom id added and keep applying.
```suggestion
elements like `div` match by the element itself and thus keep applying.
```

I think saying there's no custom ID added to these is a bit confusing as these are element selectors and thus different from class selectors anyway. An element selector like `div-340utgrheogf` would never work anyway as that element doesn't exist.

2022-08-10 08:57 UTC, marcoow commented on _posts/2022-08-05-cookbook-ember-app-to-css-modules.md
> +fix the style first and allow `app.css` to apply globally as it did before. To
```suggestion
fix the styles first and allow `app.css` to apply globally as it did before. To
```

2022-08-10 08:57 UTC, marcoow commented on _posts/2022-08-05-cookbook-ember-app-to-css-modules.md
> +global classes that should apply to the whole page. So we are back to a classic
```suggestion
global classes that should apply to the whole page. So we are back to classic
```

2022-08-10 08:57 UTC, marcoow commented on _posts/2022-08-05-cookbook-ember-app-to-css-modules.md
> +`class` attributes. By using `:global` pseudoselector on the whole existing CSS,
```suggestion
`class` attributes. By using the `:global` pseudoselector on the whole existing CSS,
```

2022-08-10 08:57 UTC, marcoow commented on _posts/2022-08-05-cookbook-ember-app-to-css-modules.md
> +In SuperRentals app, the Tomster `<div>` element is written in the `<Jumbo>`
```suggestion
In the SuperRentals app, the Tomster `<div>` element is written in the `<Jumbo>`
```

2022-08-10 08:57 UTC, marcoow commented on _posts/2022-08-05-cookbook-ember-app-to-css-modules.md
> +resulted to `<div class="right _tomster_1myv6d"></div>` in the browser so the
```suggestion
resulted in `<div class="right _tomster_1myv6d"></div>` in the browser so the
```

2022-08-10 08:57 UTC, marcoow commented on _posts/2022-08-05-cookbook-ember-app-to-css-modules.md
> +### One last note about `class` and `local-class`
I'm not quite sure about this paragraph. Without saying in which case this strategy could be useful (I'm not sure which ones that are tbh), it seems you're showing an anti-pattern?

2022-08-10 09:02 UTC, BlueCutOfficial commented on _posts/2022-08-05-cookbook-ember-app-to-css-modules.md
> +complex applications. For instance, managing reusable components style is
Just to be sure: I meant X reusable components, 1 style per reusable component.

2022-08-10 09:16 UTC, BlueCutOfficial commented on _posts/2022-08-05-cookbook-ember-app-to-css-modules.md
> +### One last note about `class` and `local-class`
I noticed it could be helpful when you start migrating a complex component, and you want to start using `local-class` in some part of the template, but another part keeps relying on global CSS as long as the component is not migrated entirely. This note is really included in the "migration in progress" idea as a way to move things at a fully controllable pace.

2022-08-10 10:20 UTC, marcoow commented on _posts/2022-08-05-cookbook-ember-app-to-css-modules.md
> +complex applications. For instance, managing reusable components style is
Hm, maybe

```suggestion
complex applications. For instance, managing the styles of reusable components is
```

then?

2022-08-10 10:22 UTC, marcoow commented on _posts/2022-08-05-cookbook-ember-app-to-css-modules.md
> +### One last note about `class` and `local-class`
Ah, I think I get it now. I'd explain that a bit though, otherwise it's not entirely clear maybe.

2022-08-10 14:06 UTC, BlueCutOfficial commented on _posts/2022-08-05-cookbook-ember-app-to-css-modules.md
> +### One last note about `class` and `local-class`
I tried something, let me know if it sounds better.

2022-08-10 14:20 UTC, marcoow commented on _posts/2022-08-05-cookbook-ember-app-to-css-modules.md
> +### One last note about `class` and `local-class`
I'm not sure I'm following that example tbh. In a migration like that, wouldn't you just move the entire `.rental` class over into the component and then use the local class within the component? I'm not sure why one would still want to also keep and apply the old, global class?

2022-08-10 14:51 UTC, BlueCutOfficial commented on _posts/2022-08-05-cookbook-ember-app-to-css-modules.md
> +### One last note about `class` and `local-class`
I found it useful when playing with the testing app I used, it was just a way to split the work when you have a lot of different rules applying on elements through different selectors. But if mentioning the idea is too confusing I prefer to remove this part, because I am not sure I can find a better example, and developing this case too much would be overkill. At the begining it was more a "little tip" rather than a doc section in my head.

2022-08-11 09:28 UTC, oscard0m approved these changes
Nice post @BlueCutOfficial!

I found it very useful and easy to follow. 

I like the flow you chose of installing the dependency, breaking the app, fixing it...

Congrats!

2022-08-11 09:28 UTC, oscard0m commented on _posts/2022-08-05-cookbook-ember-app-to-css-modules.md
> +### A word `ember-css-modules`
```suggestion
### A word about `ember-css-modules`
```

2022-08-11 09:28 UTC, oscard0m commented on _posts/2022-08-05-cookbook-ember-app-to-css-modules.md
> +### A word about less and sass
```suggestion
### A word about `less` and `sass`
```

2022-08-11 10:44 UTC, BlueCutOfficial commented on _posts/2022-08-05-cookbook-ember-app-to-css-modules.md
> +changes in the way the developer should handle the app style. If the developer
Do I have a missing "s" here?
```suggestion
changes in the way the developer should handle the app styles. If the developer
```

2022-08-11 10:44 UTC, BlueCutOfficial commented on _posts/2022-08-05-cookbook-ember-app-to-css-modules.md
> +![SuperRental style is broken](/assets/images/posts/2022-08-05-cookbook-ember-app-to-css-modules/screen-2.png)
?
```suggestion
![SuperRentals styles are broken](/assets/images/posts/2022-08-05-cookbook-ember-app-to-css-modules/screen-2.png)
```

2022-08-11 10:44 UTC, BlueCutOfficial commented on _posts/2022-08-05-cookbook-ember-app-to-css-modules.md
> +![SuperRental with global CSS](/assets/images/posts/2022-08-05-cookbook-ember-app-to-css-modules/screen-1.png)
```suggestion
![SuperRentals with global CSS](/assets/images/posts/2022-08-05-cookbook-ember-app-to-css-modules/screen-1.png)
```

2022-08-12 11:41 UTC, lolmaus approved these changes
Approved, with a few minor suggestions.

2022-08-12 11:41 UTC, lolmaus commented on _posts/2022-08-05-cookbook-ember-app-to-css-modules.md
> +classes locally, for instance to a single component. To read more about the
```suggestion
classes locally, for instance to individual components. To read more about the
```

2022-08-12 11:41 UTC, lolmaus commented on _posts/2022-08-05-cookbook-ember-app-to-css-modules.md
> +addon that lets developers easily integrate CSS modules to the implementation of
```suggestion
addon that lets developers easily integrate the CSS modules approach to the implementation of
```

This sounded as if a developer is supposed to download a few individual CSS modules and integrate them into their app.

2022-08-12 11:41 UTC, lolmaus commented on _posts/2022-08-05-cookbook-ember-app-to-css-modules.md
> +their Ember apps and addon.
```suggestion
their Ember apps and addons.
```

2022-08-15 14:30 UTC, emmasofiah2o submitted a review, later dismissed

2022-08-15 14:30 UTC, emmasofiah2o commented on _posts/2022-08-05-cookbook-ember-app-to-css-modules.md
> +This article is a perfect fit for you if:
Maybe "is exactly what you are looking for" instead of "is a perfect fit"? Idk if that is used to describe articles as well, I believe it's rather meant for people :)

2022-08-15 14:30 UTC, emmasofiah2o commented on _posts/2022-08-05-cookbook-ember-app-to-css-modules.md
> +- You know a bit of theory about what CSS modules are but you might have never
```suggestion
- You know a bit of theory about what CSS modules are but you have never
```

2022-08-15 14:30 UTC, emmasofiah2o commented on _posts/2022-08-05-cookbook-ember-app-to-css-modules.md
> +CSS modules aim at answering these challenges as a technique to scope CSS
You can't really answer a challenge. Maybe "aim to overcome"?

2022-08-15 14:30 UTC, emmasofiah2o commented on _posts/2022-08-05-cookbook-ember-app-to-css-modules.md
> +screen. Let's find in the DOM the element that should display Tomster. The image
Missing the object for "let's find" :)

2022-08-15 14:30 UTC, emmasofiah2o commented on _posts/2022-08-05-cookbook-ember-app-to-css-modules.md
> +screen. Let's find in the DOM the element that should display Tomster. The image
Or maybe you meant "let's look/search"

2022-08-15 14:30 UTC, emmasofiah2o commented on _posts/2022-08-05-cookbook-ember-app-to-css-modules.md
> +But this custom id is not present in our component's template, we still have
However, this custom id is not present in our component's template since we still have
```

2022-08-15 14:30 UTC, emmasofiah2o commented on _posts/2022-08-05-cookbook-ember-app-to-css-modules.md
> +fix the styles first and allow `app.css` to apply globally as it did before. To
```suggestion
fix the styles and allow `app.css` to apply globally as it did before. To
```

2022-08-15 14:30 UTC, emmasofiah2o commented on _posts/2022-08-05-cookbook-ember-app-to-css-modules.md
> +Before starting to actively use CSS modules across the app, we would prefer to
```suggestion
Before starting to actively use CSS modules across the app, we should
```

2022-08-15 14:30 UTC, emmasofiah2o commented on _posts/2022-08-05-cookbook-ember-app-to-css-modules.md
> +up to you to continue digging and deduce the best way to organize CSS in your
```suggestion
it is up to you to continue digging and deduce the best way to organize CSS in your
```

2022-08-16 08:23 UTC, BlueCutOfficial commented on _posts/2022-08-05-cookbook-ember-app-to-css-modules.md
> +screen. Let's find in the DOM the element that should display Tomster. The image
What do you mean by the "object" for let's find? If you mean the object to find, it's "the element that should display Tomster", so maybe the whole sentence is not clear enough?

2022-08-16 08:33 UTC, BlueCutOfficial commented on _posts/2022-08-05-cookbook-ember-app-to-css-modules.md
> +But this custom id is not present in our component's template, we still have
I am not 100% sure about the usage of "since" here. Just to clarify: there is not _really_ cause and effect link between  "this custom id is not present in our component's template" and "we still have `class="right tomster"`". It is more like two separated observations to reach the same conclusion. 
Considering this, do you think I should apply your suggestion or do you see a better way to say it?

2022-08-16 09:11 UTC, emmasofiah2o commented on _posts/2022-08-05-cookbook-ember-app-to-css-modules.md
> +screen. Let's find in the DOM the element that should display Tomster. The image
Try putting "in the DOM" at then end of the sentence then, I think it'd be clearer that way :)

2022-08-16 09:12 UTC, emmasofiah2o commented on _posts/2022-08-05-cookbook-ember-app-to-css-modules.md
> +But this custom id is not present in our component's template, we still have
Then "However, this custom id is not present in our component's template: we still have..."

2022-08-24 09:38 UTC, merged