Add "node_modules: How one character saved 50 GB of disk space" post
mainmatter/mainmatter.com pull request #1861
Opened 2022-08-18 12:49 UTC by Turbo87

2022-08-18 12:56 UTC, marcoow commented on _posts/2022-08-18-pnpm.md
> +title: 'node_modules: How one character saved 50 GB of disk space'
The art of headlines ™️ 

🤯

2022-08-18 12:57 UTC, marcoow commented on _posts/2022-08-18-pnpm.md
> +bio: 'Senior Software Engineer'
With that headline, should change this to

```suggestion
bio: 'Senior Software Engineer/Online Marketer'
```

;)

2022-08-18 13:06 UTC, Turbo87 commented on _posts/2022-08-18-pnpm.md
> +title: 'node_modules: How one character saved 50 GB of disk space'
you should read the rest of the post... 😂

2022-08-18 13:20 UTC, beerinho commented
Concise and an enjoyable read, very nice! The comments I made were just my preference on the reading flow so feel free to ignore them if you disagree

2022-08-18 13:21 UTC, beerinho approved these changes

2022-08-18 13:21 UTC, beerinho commented on _posts/2022-08-18-pnpm.md
> +need a particular, but different version of a package you're essentially
```suggestion
need a particular, but different, version of a package, you're essentially
```

2022-08-18 13:21 UTC, beerinho commented on _posts/2022-08-18-pnpm.md
> +need a particular, but different version of a package you're essentially
Commas galore! Maybe something like "That means, you're essentially screwed if you have two applications that both have the same package, but different versions." could work here to reduce the commas needed

2022-08-18 13:21 UTC, beerinho commented on _posts/2022-08-18-pnpm.md
> +works. These days there are ways to work around this and have an "environment"
```suggestion
Believe it or not, this is basically how everything in the Python and Ruby worlds
work. These days there are ways to work around this and have an "environment"
```

2022-08-18 13:21 UTC, beerinho commented on _posts/2022-08-18-pnpm.md
> +The beauty of this algorithm was that it allows us to have complicated
```suggestion
The beauty of this algorithm was that it allowed us to have complicated
```

2022-08-18 13:21 UTC, beerinho commented on _posts/2022-08-18-pnpm.md
> +have two versions of the same dependency in a project, then not be able to use
```suggestion
have two versions of the same dependency in a project, than not be able to use
```

2022-08-18 13:21 UTC, beerinho commented on _posts/2022-08-18-pnpm.md
> +character to find them, … No, wait that was something different.
😆 👍

2022-08-18 13:21 UTC, beerinho commented on _posts/2022-08-18-pnpm.md
> +finally came up with what they called "Plug'n'Play mode". This new mode promised
```suggestion
finally came up with what they called "Plug'n'Play mode" (or "PnP" for short). This new mode promised
```

2022-08-18 13:21 UTC, beerinho commented on _posts/2022-08-18-pnpm.md
> +momentum with quite a few high profile projects migrating to it.
```suggestion
While pnpm has been around for quite a while, it has lately started gaining more
momentum, with quite a few high profile projects migrating to it.
```

2022-08-18 13:21 UTC, beerinho commented on _posts/2022-08-18-pnpm.md
> +At simplabs we have started to convert a few of our own projects to it, and let
```suggestion
At Simplabs we have started to convert a few of our own projects to it, and let
```

2022-08-18 15:23 UTC, oscard0m approved these changes
Nice article Tobi! I plan to start usung `pnpm` in a couple of personal projects. I have more reasons now!

2022-08-18 15:52 UTC, marcoow commented on _posts/2022-08-18-pnpm.md
> +title: 'node_modules: How one character saved 50 GB of disk space'
I want to! Not sure I'll find the time before vacation though…

2022-08-18 17:05 UTC, BobrImperator approved these changes
LGTM.

The amount of sass though 😂 I love it

2022-09-01 08:44 UTC, Turbo87 commented on _posts/2022-08-18-pnpm.md
> +At simplabs we have started to convert a few of our own projects to it, and let
nope, it's lowercase ;)

2022-09-01 08:55 UTC, marcoow reviewed
👀 the diagram is nice but also huge – a PNG would likely only have 10% of the size of the JPG (which isn't a good format for sth. like this)

2022-09-01 08:59 UTC, beerinho approved these changes

2022-09-01 09:03 UTC, Turbo87 commented
> 👀 the diagram is nice but also huge – a PNG would likely only have 10% of the size of the JPG (which isn't a good format for sth. like this)

if I had the original source I would make it an SVG, but I only downloaded it from Twitter and didn't have any other options

2022-09-01 09:22 UTC, marcoow commented
I see - maybe we can still compress a bit or so@

2022-09-01 09:32 UTC, Turbo87 commented
I just ran it through ImageOptim, which saved 25% at least

2022-09-27 08:18 UTC, emmasofiah2o requested changes
Just a few suggestions :). Looks good tho. I have put together the social media post for it and will tag you on notion if you want to check it out @Turbo87. og:image is also coming asap

2022-09-27 08:18 UTC, emmasofiah2o commented on _posts/2022-08-18-pnpm.md
> +  'Tobias Bieniek describes a way to save many GB of disk space when working
```suggestion
  'Tobias Bieniek reveals his secret to saving many GB of disk space when working
```

2022-09-27 08:18 UTC, emmasofiah2o commented on _posts/2022-08-18-pnpm.md
> +  'Tobias Bieniek describes a way to save many GB of disk space when working
I think it sounds more catchy like this, but Idk if matches you writing style :)

2022-09-27 08:18 UTC, emmasofiah2o commented on _posts/2022-08-18-pnpm.md
> +the folder of each project. But also, each of the packages could also have other
```suggestion
the folder of each project. Each of the packages could also have other
```

2022-09-27 08:18 UTC, emmasofiah2o commented on _posts/2022-08-18-pnpm.md
> +`node_modules` folder: If you call `require('chesterton')` in a file, then it
```suggestion
`node_modules` folder: if you call `require('chesterton')` in a file, then it
```

2022-09-27 08:18 UTC, emmasofiah2o commented on _posts/2022-08-18-pnpm.md
> +found, will look for a `chesterton` folder inside it. If neither exists, it will
```suggestion
found, it will look for a `chesterton` folder inside it. If neither exists, it will
```

2022-09-27 08:18 UTC, emmasofiah2o commented on _posts/2022-08-18-pnpm.md
> +to the `bar` dependency of our project. But there is also a hidden `.pnpm`
```suggestion
to the `bar` dependency of our project. However, there is also a hidden `.pnpm`
```

Or perhaps "in addition to that" not sure "but" works here

2022-09-27 08:18 UTC, emmasofiah2o commented on _posts/2022-08-18-pnpm.md
> +At simplabs we have started to convert a few of our own projects to it, and let
```suggestion
At Mainmatter we have started to convert a few of our own projects to it, and let
```

2022-09-27 08:18 UTC, emmasofiah2o commented on _posts/2022-08-18-pnpm.md
> +it out and message us know if you hit any issues.
```suggestion
it out and message us if you hit any issues.
```

2022-09-29 09:16 UTC, emmasofiah2o approved these changes

2022-09-29 10:51 UTC, marcoow requested changes

2022-09-29 10:51 UTC, marcoow commented on src/posts/2022-09-29-pnpm.md
> +bio: "Tobias Bieniek"
This should be a bio – sth. like "Senior Engineering Consultant". Or you leave it out and it will use https://github.com/mainmatter/mainmatter.com/blob/master/src/authors/tobiasbieniek.md

2022-09-29 10:52 UTC, marcoow requested changes
@emmasofiah2o the `og:image`s should be JPGs now – PNG isn't a suitable format for images that contain photos.

2022-09-29 11:10 UTC, Turbo87 commented on src/posts/2022-09-29-pnpm.md
> +bio: "Tobias Bieniek"
hmm I was copying what I saw in the other previous blog posts. Guess those will need to be fixed too then?

2022-09-29 11:11 UTC, Turbo87 commented
@marcoow I did get it as a jpg too but it had significantly worse image quality. should we use webp instead to get best of both worlds?

2022-09-29 13:26 UTC, marcoow commented
@Turbo87 the others seem fine:

* https://mainmatter.com/blog/2020/12/31/xml-and-rust/
* https://mainmatter.com/blog/2019/04/24/dependency-updates-for-gitlab/
* https://mainmatter.com/blog/2019/07/15/sentry-and-ember/
* etc.

Can't use WebP for `og:image` as not all browsers support it yet. For images on the site, it will use WebP (using `<picture>` with a PNG or JPG fallback – but that doesn't work for `og:image`) This should work though?

![og-image](https://user-images.githubusercontent.com/1510/193043827-ac1f1645-7323-4e8a-8a94-8135462dd858.jpg)

We should definitely automate the `og:image` generation somehow…

2022-09-29 13:59 UTC, Turbo87 commented
according to https://caniuse.com/?search=webp only IE11 does not support it, which seems fine to ignore IMHO 😅 

> This should work though?

the text in the top left has quite a few artifacts. doesn't look great.

2022-09-29 14:03 UTC, marcoow commented
I think this is the main point:

<img width="203" alt="Bildschirmfoto 2022-09-29 um 16 02 22" src="https://user-images.githubusercontent.com/1510/193052855-baf64ebe-5979-4527-ab77-3c3a99d6336e.png">

I think in particular among our audience some people are quite cautious with their OS updates.

Also keep in mind you will typically see the `og:image` much smaller anyway

2022-09-29 14:29 UTC, marcoow approved these changes

2022-09-29 15:57 UTC, merged