Blog: Self-signed certificates for local HTTPS made easy
mainmatter/mainmatter.com pull request #1871
Opened 2022-09-02 17:23 UTC by pichfl

This made my life a lot easier. looking forward to feedback.

- [ ] Add proper og:image
- [ ] Add visuals?

2022-09-04 07:53 UTC, marcoow reviewed
Nice post 🙌 I didn't know about `mkcert` but would have been helpful recently when working on my chat roulette app…

2022-09-04 07:53 UTC, marcoow commented on _posts/2022-09-30-selfsigned-certificates-for-development.md
> +[letsencryp]: https://letsencrypt.org
```suggestion
[letsencrypt]: https://letsencrypt.org
```

2022-09-05 14:25 UTC, emmasofiah2o requested changes
Only a few minor changes! Looks good: not too long, straight to the point, and yet very well written :)

2022-09-05 14:25 UTC, emmasofiah2o commented on _posts/2022-09-30-selfsigned-certificates-for-development.md
> +Serving HTTPS locally is built into most web servers and frameworks, but the
```suggestion
Serving HTTPS locally is a function built into most web servers and frameworks, but the
```
I'd recommend defining the subject a bit better here :) not sure this can be called a function

2022-09-05 14:25 UTC, emmasofiah2o commented on _posts/2022-09-30-selfsigned-certificates-for-development.md
> +how you use it together with it's CLI.
```suggestion
how you use it together with its CLI.
```

2022-09-05 14:25 UTC, emmasofiah2o commented on _posts/2022-09-30-selfsigned-certificates-for-development.md
> +If you want to serve your project with SSL all the time, you can event put
```suggestion
If you want to serve your project with SSL all the time, you can even put
```

even?

2022-09-05 14:25 UTC, emmasofiah2o commented on _posts/2022-09-30-selfsigned-certificates-for-development.md
> +and in turn allowing to you replicate and debug real-world situations with ease.
```suggestion
and in turn, allowing you to replicate and debug real-world situations with ease.
```

2022-09-05 14:25 UTC, emmasofiah2o commented on _posts/2022-09-30-selfsigned-certificates-for-development.md
> +encryption and your local browsers will show a green checkmark as well!
```suggestion
encryption and your local browser will show a green checkmark as well!
```

2022-09-20 11:41 UTC, marcoow commented
the image seems to be extremely low quality?

<img width="1389" alt="Bildschirmfoto 2022-09-20 um 13 40 29" src="https://user-images.githubusercontent.com/1510/191248450-fe2dfce8-d073-4669-aa7c-97667e5fc47f.png">

2022-09-20 12:16 UTC, mansona approved these changes
A great post! really nicely self-contained and it will make a difference to anyone who needs a simple setup 🎉

2022-09-21 09:03 UTC, emmasofiah2o approved these changes

2022-09-22 09:28 UTC, merged