Added this-week-in-os 16
mainmatter/mainmatter.com pull request #1892
Opened 2022-09-27 12:11 UTC by emmasofiah2o

To-do:
Remove irrelevant links

2022-09-27 12:17 UTC, oscard0m commented on src/posts/2022-09-27-this-week-in-os-16.md
> +- [ezolenko/rollup-plugin-typescript2] [#420](https://github.com/ezolenko/rollup-plugin-typescript2/pull/420) fix(cache): default `clean: true` when necessary, add `extraCacheKeys` option ([@oscard0m
I would create a new category: Rollup

2022-09-27 12:17 UTC, oscard0m commented on src/posts/2022-09-27-this-week-in-os-16.md
> +- [oscard0m/octoherd-script-update-action-version-in-workflows] [#1](https://github.com/oscard0m/octoherd-script-update-action-version-in-workflows/pull/1) feat: Initial version ([@oscard0m])
Put them under `Octokit` category

2022-09-27 12:17 UTC, oscard0m commented on src/posts/2022-09-27-this-week-in-os-16.md
> +- [oscard0m/octokit-auth-oauth-user.js] [#13](https://github.com/oscard0m/octokit-auth-oauth-user.js/pull/13) add size limit workflow ([@oscard0m])
Ignore them

2022-09-27 12:17 UTC, oscard0m commented on src/posts/2022-09-27-this-week-in-os-16.md
> +- [oscard0m/remix-deploy-vercel] [#1](https://github.com/oscard0m/remix-deploy-vercel/pull/1) feat(preview): preview deployment ([@oscard0m])
Ignore them

2022-09-27 12:17 UTC, oscard0m commented on src/posts/2022-09-27-this-week-in-os-16.md
> +- [probot/twitter] [#27](https://github.com/probot/twitter/pull/27) chore(.github): remove unused Renovate configuration ([@oscard0m])
I would create a new category called `Probot`

2022-09-27 12:18 UTC, Turbo87 commented on src/posts/2022-09-27-this-week-in-os-16.md
> +- [XCSoar/xcsoar-data-content] [#294](https://github.com/XCSoar/xcsoar-data-content/pull/294) Add `united.fln` flarmnet option ([@Turbo87])
can probably just be removed

2022-09-27 12:18 UTC, Turbo87 commented on src/posts/2022-09-27-this-week-in-os-16.md
> +- [ember-cli/ember-cli-htmlbars] [#755](https://github.com/ember-cli/ember-cli-htmlbars/pull/755) Add a test that covers addon templates and fix ember-try to include correct ember-cli versions ([@man
this should be Ember.js

2022-09-27 12:19 UTC, Turbo87 commented on src/posts/2022-09-27-this-week-in-os-16.md
> +- [mainmatter/ember-test-selectors] [#1079](https://github.com/mainmatter/ember-test-selectors/pull/1079) rebrand simplabs to Mainmatter ([@marcoow])
I'd probably remove all the rebranding PRs from the list since they're just noise.

2022-09-27 12:20 UTC, Turbo87 commented on src/posts/2022-09-27-this-week-in-os-16.md
> +- [weglide/GliderList] [#42](https://github.com/weglide/GliderList/pull/42) Add 2023 handicaps ([@Turbo87])
can also be removed unless we want to add a "Gliding" category 😅

2022-09-27 12:21 UTC, BobrImperator commented on src/posts/2022-09-27-this-week-in-os-16.md
> +- [rrrene/credo] [#996](https://github.com/rrrene/credo/pull/996) feat: Add Ignore option for Credo.Check.Readability.ModuleNames ([@BobrImperator])
`rrrene/credo` is Elixir, so we'd need a new category for that

2022-09-27 12:24 UTC, BobrImperator commented on src/posts/2022-09-27-this-week-in-os-16.md
> +- [weglide/GliderList] [#42](https://github.com/weglide/GliderList/pull/42) Add 2023 handicaps ([@Turbo87])
Not a bad idea IMO :D

2022-09-27 13:37 UTC, mansona requested changes, later dismissed

2022-09-27 13:37 UTC, mansona commented on src/posts/2022-09-27-this-week-in-os-16.md
> +- [ember-learn/ember-release-bot] [#25](https://github.com/ember-learn/ember-release-bot/pull/25) Update postgres keyv dependencies ([@mansona])
I think this one can go into ember maybe? it's a simple little discord bot that we use to remind ourselves what needs to be released and when. what do we think?

2022-09-27 13:37 UTC, mansona commented on src/posts/2022-09-27-this-week-in-os-16.md
> +- [empress/bottled-ember] [#1](https://github.com/empress/bottled-ember/pull/1) Implement basic cach-folder version of bottled ember ([@mansona])
So these 3 (bottled-ember) could either go in EmberJS or Empress 🤔 any thoughts @Turbo87 ?

2022-09-27 13:37 UTC, mansona commented on src/posts/2022-09-27-this-week-in-os-16.md
> +- [mansona/chris.manson.ie] [#17](https://github.com/mansona/chris.manson.ie/pull/17) use bottled ember ([@mansona])
this is my personal blog so we can ignore this one 👍

2022-09-28 07:53 UTC, emmasofiah2o commented on src/posts/2022-09-27-this-week-in-os-16.md
> +- [ember-cli/ember-cli-htmlbars] [#755](https://github.com/ember-cli/ember-cli-htmlbars/pull/755) Add a test that covers addon templates and fix ember-try to include correct ember-cli versions ([@man
Only line 62/63 tho right?

2022-09-28 07:54 UTC, emmasofiah2o commented on src/posts/2022-09-27-this-week-in-os-16.md
> +- [mainmatter/ember-test-selectors] [#1079](https://github.com/mainmatter/ember-test-selectors/pull/1079) rebrand simplabs to Mainmatter ([@marcoow])
Yes! I think @BobrImperator said they might be relevant so I'll leave them out of the "exclude" group in the config, in case we have PRs there in the future

2022-09-28 07:58 UTC, Turbo87 commented on src/posts/2022-09-27-this-week-in-os-16.md
> +- [ember-cli/ember-cli-htmlbars] [#755](https://github.com/ember-cli/ember-cli-htmlbars/pull/755) Add a test that covers addon templates and fix ember-try to include correct ember-cli versions ([@man
yep 👍

2022-09-28 09:22 UTC, emmasofiah2o commented on src/posts/2022-09-27-this-week-in-os-16.md
> +- [weglide/GliderList] [#42](https://github.com/weglide/GliderList/pull/42) Add 2023 handicaps ([@Turbo87])
So should I? :D

2022-09-28 09:28 UTC, emmasofiah2o commented
How do I run format now? Also I need help with categorization from @locks

2022-09-28 09:59 UTC, BobrImperator commented
@emmasofiah2o `yarn lint:md:fix` to fix the markdown files, or `yarn lint:fix` to fix formatting for all files

2022-09-28 10:12 UTC, BobrImperator reviewed
~We most likely don't want the rebrand PRs in the post~
Removed the commit suggestions as they'll break once the file is formatted or changed in some way.

2022-09-28 10:12 UTC, BobrImperator commented on src/posts/2022-09-27-this-week-in-os-16.md
> +- [mainmatter/ember-test-selectors] [#1079](https://github.com/mainmatter/ember-test-selectors/pull/1079) rebrand simplabs to Mainmatter ([@marcoow])
```suggestion
```

2022-09-28 10:12 UTC, BobrImperator commented on src/posts/2022-09-27-this-week-in-os-16.md
> +- [ember-learn/ember-website] [#961](https://github.com/ember-learn/ember-website/pull/961) simplabs is rebranding to Mainmatter ([@marcoow])
```suggestion
```

2022-09-28 10:12 UTC, BobrImperator commented on src/posts/2022-09-27-this-week-in-os-16.md
> +- [mainmatter/qunit-dom] [#1695](https://github.com/mainmatter/qunit-dom/pull/1695) Rebrand simplabs to Mainmatter ([@BobrImperator])
```suggestion
```

2022-09-28 10:12 UTC, BobrImperator commented on src/posts/2022-09-27-this-week-in-os-16.md
> +- [erlef/website] [#417](https://github.com/erlef/website/pull/417) simplabs is rebranding to Mainmatter ([@marcoow])
```suggestion
```

2022-09-28 10:12 UTC, BobrImperator commented on src/posts/2022-09-27-this-week-in-os-16.md
> +- [mainmatter/renovate-config] [#11](https://github.com/mainmatter/renovate-config/pull/11) Rebrand simplabs to Mainmatter ([@BobrImperator])
```suggestion
```

2022-09-28 10:12 UTC, BobrImperator commented on src/posts/2022-09-27-this-week-in-os-16.md
> +[mainmatter/renovate-config]: https://github.com/mainmatter/renovate-config
```suggestion
```

2022-09-28 14:06 UTC, BobrImperator commented on src/posts/2022-09-27-this-week-in-os-16.md
> +- [weglide/GliderList] [#42](https://github.com/weglide/GliderList/pull/42) Add 2023 handicaps ([@Turbo87])
I made it official :D

2022-09-29 08:57 UTC, locks commented on src/posts/2022-09-27-this-week-in-os-16.md
> +
```suggestion
```

2022-10-03 13:18 UTC, oscard0m approved these changes

2022-10-03 13:52 UTC, merged