Added this-week-in-os-17
mainmatter/mainmatter.com pull request #1896
Opened 2022-10-14 14:43 UTC by emmasofiah2o

- Created file
- Added og

2022-10-14 16:39 UTC, Turbo87 commented on src/posts/2022-10-14-this-week-in-os-17.md
> +- [Swatinem/rust-cache] [#83](https://github.com/Swatinem/rust-cache/pull/83) Update `@actions/cors` to v1.10.0 ([@Turbo87])
This and the two above are "Rust"

2022-10-14 16:39 UTC, Turbo87 commented on src/posts/2022-10-14-this-week-in-os-17.md
> +- [jomjol/AI-on-the-edge-device] [#1158](https://github.com/jomjol/AI-on-the-edge-device/pull/1158) FlowPostProcessing::GetJSON: Add `pre` field to the `/json` response ([@Turbo87])
"Embedded" I guess

2022-10-14 16:44 UTC, oscard0m requested changes

2022-10-14 16:44 UTC, oscard0m commented on src/posts/2022-10-14-this-week-in-os-17.md
> +- [mainmatter/eurorust.eu] [#170](https://github.com/mainmatter/eurorust.eu/pull/170) feat(frontpage): add Grafbase as supporter ([@oscard0m])
Ignore `mainmatter/eurorust.eu`

```suggestion
```

2022-10-14 16:44 UTC, oscard0m commented on src/posts/2022-10-14-this-week-in-os-17.md
> +- [mainmatter/gravity] [#932](https://github.com/mainmatter/gravity/pull/932) Repositories screen ([@inesilva])
ignore `mainmatter/gravity`

```suggestion
```

2022-10-14 16:44 UTC, oscard0m commented on src/posts/2022-10-14-this-week-in-os-17.md
> +[mainmatter/gravity]: https://github.com/mainmatter/gravity
```suggestion
```

2022-10-14 16:44 UTC, oscard0m commented on src/posts/2022-10-14-this-week-in-os-17.md
> +- [huggingface/transformers] [#19280](https://github.com/huggingface/transformers/pull/19280) ci(stale.yml): update actions/checkout to v3 ([@oscard0m])
irrelevant PRs

2022-10-14 16:44 UTC, oscard0m commented on src/posts/2022-10-14-this-week-in-os-17.md
> +- [tldr-pages/tldr] [#8614](https://github.com/tldr-pages/tldr/pull/8614) ci: upgrade actions/setup-python to v4 ([@oscard0m])
irrelevant PRs
```suggestion
```

2022-10-14 16:44 UTC, oscard0m commented on src/posts/2022-10-14-this-week-in-os-17.md
> +- [withastro/docs] [#1662](https://github.com/withastro/docs/pull/1662) i18n(es): Update sharing-state.md translation ([@oscard0m])
category: Astro

2022-10-14 16:44 UTC, oscard0m commented on src/posts/2022-10-14-this-week-in-os-17.md
> +[ohmyzsh/ohmyzsh]: https://github.com/ohmyzsh/ohmyzsh
```suggestion
```

2022-10-14 16:44 UTC, oscard0m commented on src/posts/2022-10-14-this-week-in-os-17.md
> +[tldr-pages/tldr]: https://github.com/tldr-pages/tldr
```suggestion
```

2022-10-14 16:44 UTC, oscard0m commented on src/posts/2022-10-14-this-week-in-os-17.md
> +- [strapi/strapi] [#14516](https://github.com/strapi/strapi/pull/14516) ci(checks.yml): update actions/checkout to v3 ([@oscard0m])
```suggestion
```

2022-10-14 16:44 UTC, oscard0m commented on src/posts/2022-10-14-this-week-in-os-17.md
> +[chrislgarry/Apollo-11]: https://github.com/chrislgarry/Apollo-11
```suggestion
```

2022-10-14 16:44 UTC, oscard0m commented on src/posts/2022-10-14-this-week-in-os-17.md
> +[huggingface/transformers]: https://github.com/huggingface/transformers
```suggestion
```

2022-10-17 08:00 UTC, emmasofiah2o commented on src/posts/2022-10-14-this-week-in-os-17.md
> +- [jomjol/AI-on-the-edge-device] [#1158](https://github.com/jomjol/AI-on-the-edge-device/pull/1158) FlowPostProcessing::GetJSON: Add `pre` field to the `/json` response ([@Turbo87])
All of them?

2022-10-17 08:07 UTC, emmasofiah2o commented on src/posts/2022-10-14-this-week-in-os-17.md
> +- [withastro/docs] [#1662](https://github.com/withastro/docs/pull/1662) i18n(es): Update sharing-state.md translation ([@oscard0m])
Just line 109 right?

2022-10-17 08:56 UTC, Turbo87 commented on src/posts/2022-10-14-this-week-in-os-17.md
> +- [jomjol/AI-on-the-edge-device] [#1158](https://github.com/jomjol/AI-on-the-edge-device/pull/1158) FlowPostProcessing::GetJSON: Add `pre` field to the `/json` response ([@Turbo87])
no, sorry, just the one from `jomjol/AI-on-the-edge-device` :)

2022-10-18 08:28 UTC, oscard0m approved these changes

2022-10-19 07:04 UTC, merged