Add entry ember europe london
mainmatter/mainmatter.com pull request #1924
Opened 2022-10-28 11:57 UTC by emmasofiah2o

2022-10-31 07:38 UTC, marcoow requested changes
the SVG is slightly broken but I think we have a PNG as well

2022-10-31 09:10 UTC, emmasofiah2o commented
> the SVG is slightly broken but I think we have a PNG as well

Just changed, let me know if this works. I wasn't sure if I was supposed to use the logo with the big ben or the general one :).

2022-10-31 11:34 UTC, marcoow requested changes
I don't think this image works well tbh…

<img width="704" alt="Bildschirm­foto 2022-10-31 um 12 34 30" src="https://user-images.githubusercontent.com/1510/198998768-4ebb2296-823b-4be2-a75b-e3012f930be2.png">

2022-10-31 11:40 UTC, emmasofiah2o commented
> I don't think this image works well tbh…
> 
> <img alt="Bildschirm­foto 2022-10-31 um 12 34 30" width="704" src="https://user-images.githubusercontent.com/1510/198998768-4ebb2296-823b-4be2-a75b-e3012f930be2.png">

Is it because it misses the background? We only have transparent logos of Ember Europe, but I can create an extra one with a background if you like

2022-10-31 11:42 UTC, marcoow commented
I'd say it looks broken because it's apparently cut off and not meant for sth. like this? I don't think a background would make that much better. Maybe just the flags would work for example – be creative, I'm sure you'll find something that works well

2022-10-31 11:47 UTC, emmasofiah2o commented
> I'd say it looks broken because it's apparently cut off and not meant for sth. like this? I don't think a background would make that much better. Maybe just the flags would work for example – be creative, I'm sure you'll find something that works well

I thought it looked fine tbh :D. I'll see if I can come up with smth

2022-10-31 13:00 UTC, emmasofiah2o commented
Ok I figured out the problem. I thought the screenshot you sent was just weirdly cut - this one should work :) @marcoow

2022-10-31 13:01 UTC, marcoow commented
> I thought the screenshot you sent was just weirdly cut

always make sure to check out the changes on the preview system yourself before asking for review 🙏

2022-10-31 13:02 UTC, marcoow requested changes
I think it's fine but extremely blurry. Also it shouldn't be an SVG as it contains binary image data – use PNG instead but make sure to use a larger resolution

2022-10-31 13:27 UTC, emmasofiah2o commented
@marcoow I have tried changing it again, it is slightly bigger but still blurry. The problem is that I need to use Tomster's t-shirt to make the background cause I don't have an SVG of the background on its own. And my computer crashes if I try to make it bigger than how it is now...

2022-10-31 13:54 UTC, marcoow commented
please ask @davidhajba for help

2022-11-03 08:15 UTC, davidhajba commented
Hey Marco, 
Emma asked me to explain the situation from my perspective:
The picture both JPEG and PNG should work perfectly in this size that I sent to Emma. 
As it is distorted, it is not a visual design, but a development issue.
Maybe the website reduces file size significantly or there’s some error displaying the image.

2022-11-03 08:19 UTC, marcoow approved these changes

2022-11-03 08:22 UTC, marcoow requested changes
it's not a 1 day event but a regular evening meetup

2022-11-03 08:22 UTC, marcoow commented on src/calendar/2022-12-08-embereurope-london.md
> +event to allow people to join remotely as well.
```suggestion
Ember Europe series is back in Q4 with the last event for the year, this time hosted by CrowdStrike in London. The Ember Europe meetup series brings together the Ember community from all of Europe once a quarter. The meetup is organized by Mainmatter and Intercom as a hybrid event, hosted from a different city each time with the option for people to join remotely as well.
```

2022-11-03 08:23 UTC, marcoow commented
@emmasofiah2o for any PR that results in visual changes (which is essentially every PR to the website), it's always helpful to add a screenshot in the description to give people a quick glance at what's changing

2022-11-07 09:25 UTC, emmasofiah2o commented
@marcoow I have committed your suggestion. As for the background, it is still blurry (as David explained, this might be a different type of issue). Let me know if I can merge. I also added the screenshot in the description of the pr as you recommended.

2022-11-07 09:29 UTC, marcoow commented on src/calendar/2022-12-08-embereurope-london.md
> +Ember Europe series is back in Q4 with the last event for the year, this time
```suggestion
Ember Europe is back in Q4 with the last event for the year, this time
```

If using series I think it requires "The " as well but that's how the next sentence starts

2022-11-07 09:31 UTC, marcoow commented on src/calendar/2022-12-08-embereurope-london.md
> +title: "Ember Europe"
Let's also use a better title

```suggestion
title: "Ember Europe Q4 Meetup"
```

2022-11-07 10:13 UTC, emmasofiah2o commented on src/calendar/2022-12-08-embereurope-london.md
> +Ember Europe series is back in Q4 with the last event for the year, this time
You wrote the text, I just committed your suggestion :D. I'll change it

2022-11-10 07:16 UTC, marcoow approved these changes

2022-11-10 10:22 UTC, emmasofiah2o commented
Can I merge this @marcoow?

2022-11-10 11:23 UTC, marcoow commented
yes, it's approved – you can merge without asking again

2022-11-10 11:23 UTC, merged