Added entry for EuroRust 2023
mainmatter/mainmatter.com pull request #1937
Opened 2022-10-31 13:01 UTC by emmasofiah2o

- Copied file from last edition

2022-10-31 13:05 UTC, marcoow requested changes

2022-10-31 13:05 UTC, marcoow commented on src/calendar/2023-10-12-eurorust.md
> +location: tbd
```suggestion
location: "TBA & online"
```

2022-10-31 13:53 UTC, marcoow approved these changes

2022-11-02 15:57 UTC, emmasofiah2o commented
Can I merge this @marcoow?

2022-11-02 16:06 UTC, marcoow commented
yes, no need to ask again once approved :)

2022-11-03 17:42 UTC, merged