Add sveltekit super rentals blog post
mainmatter/mainmatter.com pull request #1952
Opened 2022-11-18 11:06 UTC by beerinho

This PR adds a new blog post that goes through building the Ember super rentals tutorial app with SvelteKit.

If there is a way to have both a title and subtitle, I'd like to change these around to be:
title - "SvelteKit super rentals"
subtitle - "A practical first look at the new Svelte framework"

Reviewers be warned, it's a long one!

Also, @emmasofiah2o, do you normally add the og images for these? Or how does that work?

2022-11-18 12:57 UTC, marcoow commented
> If there is a way to have both a title and subtitle, I'd like to change these around to be:

there isn't

2022-11-18 14:22 UTC, marcoow reviewed
This is a great post 🎉 and indeed very long :)

I left some comments on some details and I think there's some general points as well that would be worth addressing:

* you're using quotes in a few places where I think you just really want to use an italic or bold paragraph
* the tab with 8 spaces is a bit irritating – I'd suggest switching to 2 spaces and dropping the tabs
* some of the code examples seem to have broken formatting overall
* I'd always use `<Component>` when mentioning components in the text, I think that's a good way to separate them from e.g. class names etc. Also some mentions of components seem to be missing formatting as code completely – might be worth going over that again

2022-11-18 14:22 UTC, marcoow commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +authorHandle: mainmatter
@beerinho this should be you :)

2022-11-18 14:22 UTC, marcoow commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +title: "A practical first look at the new Svelte framework"
I'm not sure about _"new"_ tbh :)

2022-11-18 14:22 UTC, marcoow commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +[github repo](https://github.com/beerinho/sveltekit-super-rentals/tags).
Can we move this to the mainmatter GH org?

2022-11-18 14:22 UTC, marcoow commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +> [GitHub Discussions tab](https://github.com/sveltejs/kit/discussions?discussions_q=sort%3Atop).
I don't think this is intended to be a quote?

<img width="1083" alt="Bildschirm­foto 2022-11-18 um 14 16 45" src="https://user-images.githubusercontent.com/1510/202713875-49d71bdb-c64e-479c-a5d7-a683eacccd8a.png">

2022-11-18 14:22 UTC, marcoow commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +
Might be a good idea to add a screenshot of the super rentals demo app here since not everyone will be familiar with it and a screenshot would give a good first impression of what the app actually is?

2022-11-18 14:22 UTC, marcoow commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +you want to see if it, feel free to check out the repo on GitHub.
```suggestion
you want to see it, feel free to check out the repo on GitHub.
```

👀

2022-11-18 14:22 UTC, marcoow commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +And when we serve the app we are greeted by the friendly face of Tomster but it
Might be good saying where to put the image and to copy/paste the styles into whatever SvelteKit's CSS file is? I was slightly confused why we would already see the Tomster when running the app at this point.

2022-11-18 14:22 UTC, marcoow commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +> will most likely just bounce back to you.
Don't think this should actually be a quote?

2022-11-18 14:22 UTC, marcoow commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +what happens when we run this tests:
```suggestion
what happens when we run this test:
```

👀

2022-11-18 14:22 UTC, marcoow commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +no longer have.
```suggestion
no longer have since we replaced the default content of the file with the HTML for the Super Rentals app.
```

or something like that might be clearer?

2022-11-18 14:22 UTC, marcoow commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +      {" "}
Might be good to explain what these are?

2022-11-18 14:22 UTC, marcoow commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +```
Formatting of this code block seems messed up?

2022-11-18 14:22 UTC, marcoow commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +```
Formatting of this code block seems messed up?

2022-11-18 14:22 UTC, marcoow commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +```
Formatting of this code block seems messed up?

2022-11-18 14:22 UTC, marcoow commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +As you can see, another different between SvelteKit and Ember is that Ember has
```suggestion
As you can see, another difference between SvelteKit and Ember is that Ember has
```

2022-11-18 14:22 UTC, marcoow commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +opted for the single file approach.
Single File components are coming in Ember as well – I think would be good to mention that.

2022-11-18 14:22 UTC, marcoow commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +name of the component when you import it - i.e.
This is actually a shortcoming in Ember and template imports are coming in Ember as well (and will fix a number of things)

2022-11-18 14:22 UTC, marcoow commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +```
Formatting of this code block seems messed up?

2022-11-18 14:22 UTC, marcoow commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +immediately obvious which component is which.
I'm not sure – you could choose named exports to prevent that or address it with linting.

2022-11-18 14:22 UTC, marcoow commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +portal to render the route content through.
What's a portal?

2022-11-18 14:22 UTC, marcoow commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +[localhost:3000](http://localhost:3000) directly (referencing localhost:3000
```suggestion
http://localhost:3000 directly (referencing localhost:3000
```

Not sure there's value in actually linking this?

2022-11-18 14:22 UTC, marcoow commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +is external or internal, whereas the `@/this` syntax used in Ember gives a
```suggestion
is external or internal, whereas the `@`/`this` syntax used in Ember gives a
```

2022-11-18 14:22 UTC, marcoow commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +```js
```suggestion
```diff
```

might make this easier to read?

2022-11-18 14:22 UTC, marcoow commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +(this is ignored by git so isn’t shown in the repo), it is also important to
Not sure what

> (this is ignored by git so isn’t shown in the repo)

means?

2022-11-18 14:22 UTC, marcoow commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +```
Are you sure about this one? The `src` property isn't the actual tracked property but a regular property that **depends** on the args of the component (`this.args`) which are auto-tracked?

2022-11-18 14:22 UTC, marcoow commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +sticking with the Ember-super-rentals tutorial and store it inside our app, you
```suggestion
sticking with the Ember-super-rentals tutorial and store it inside our app as JSON files, you
```

might make this clearer since there are many options to do this in theory

2022-11-18 14:22 UTC, marcoow commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +We can then update the Rental/Index component to receive the rental and use it’s
```suggestion
We can then update the Rental/Index component to receive the rental and use its
```

2022-11-18 14:22 UTC, marcoow commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +And now we have a lovely looking index page that shows us the data for each of
I'd recommend adding a screenshot – most users won't be following this by actually making the same changes locally and thus having sth. visual in their own browsers.

2022-11-18 14:22 UTC, marcoow commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +```js
```suggestion
```diff
```

2022-11-18 14:22 UTC, marcoow commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +Let’s start off by replacing that placeholder “Share to Twitter” button we
more like

```suggestion
Let’s continue by replacing that placeholder “Share to Twitter” button we
```

?

2022-11-18 14:22 UTC, marcoow commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +```js
```suggestion
```diff
```

2022-11-18 14:22 UTC, marcoow commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +And there we have it, SvelteKit Super Rentals!
Would be cool to link to a deployment of the actual app on Netlify or sth.

2022-11-18 14:22 UTC, marcoow commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +very close to native javascript, which makes me think I think it would be a
```suggestion
very close to native javascript, which makes me think it would be a
```

2022-11-18 14:56 UTC, beerinho commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +authorHandle: mainmatter
I know but I don't have twitter, should I just leave it out?

2022-11-18 14:56 UTC, beerinho commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +title: "A practical first look at the new Svelte framework"
👍

2022-11-18 14:57 UTC, beerinho commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +[github repo](https://github.com/beerinho/sveltekit-super-rentals/tags).
Done

2022-11-18 15:01 UTC, beerinho commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +> [GitHub Discussions tab](https://github.com/sveltejs/kit/discussions?discussions_q=sort%3Atop).
You're right, this shouldn't be a quote, I was using the quote block in Notion and couldn't see anything that helps to emphasise a section. Do you have any suggestions?

2022-11-18 15:14 UTC, beerinho commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +is external or internal, whereas the `@/this` syntax used in Ember gives a
This is supposed to mean the `@` or `this`, so I have updated it to hopefully be a little clearer

2022-11-18 15:27 UTC, beerinho commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +
Am I okay to use the screenshot from the ember site here? Or should I save it and add it myself?

2022-11-18 15:31 UTC, marcoow commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +authorHandle: mainmatter
This references your author file (see https://github.com/mainmatter/mainmatter.com/tree/master/src/authors) – I guess you can leave out Twitter there

2022-11-18 15:32 UTC, marcoow commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +> [GitHub Discussions tab](https://github.com/sveltejs/kit/discussions?discussions_q=sort%3Atop).
See my comment above – I think the only things we have that work here are italic or bold paragraphs. Using quotes is confusing – I was asking myself who you're quoting here until I realized it's actually the author speaking here still :)

2022-11-18 15:33 UTC, marcoow commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +
I guess you can use the one from the Ember site

2022-11-18 15:34 UTC, marcoow commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +is external or internal, whereas the `@/this` syntax used in Ember gives a
ah, right – `@this` doesn't exist anyway :)

2022-11-18 15:46 UTC, beerinho commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +And when we serve the app we are greeted by the friendly face of Tomster but it
Nice idea, added ✅

2022-11-18 15:51 UTC, beerinho commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +      {" "}
These must have just come from copying from Notion, I've removed them now

2022-11-18 15:55 UTC, beerinho commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +> [GitHub Discussions tab](https://github.com/sveltejs/kit/discussions?discussions_q=sort%3Atop).
I've replaced this with `hr`s above and below to make it stand out more

2022-11-18 16:22 UTC, beerinho commented
Hey @marcoow, thank you very much for your detailed feedback, looking at some of the spelling/grammar mistakes, I'm starting to rethink some of my placements on the skills matrix 🙈.

I changed some of the codeblocks to use `diff` and it looked much better in the preview in the IDE but it doesn't seem to be styled properly on the actual site. I don't know if the styling for `diff` blocks is missing?

2022-11-18 16:26 UTC, beerinho commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +And there we have it, SvelteKit Super Rentals!
I was thinking of creating some follow-up posts integrating firebase hosting, authentication, CRUD, and cloud functions so would add it then, I could do this one separately though?

2022-11-18 16:34 UTC, beerinho commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +And now we have a lovely looking index page that shows us the data for each of
✅

2022-11-18 16:38 UTC, beerinho commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +```
I mention afterwards that this isn't actually a very good pattern for this as the attributes don't change after the component is rendered, but I just wanted to replicate what is in the Ember tutorial. I'm fine with removing it if you think it's confusing

2022-11-18 16:41 UTC, beerinho commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +(this is ignored by git so isn’t shown in the repo), it is also important to
I've changed the wording here so hopefully it's a bit clearer what I mean here

2022-11-18 16:44 UTC, beerinho commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +portal to render the route content through.
I'm not sure of the best way to phrase this, but it is how the `{{outlet}}` and `{{yield}}` blocks work. I've updated it to hopefully be a bit clearer

2022-11-18 16:50 UTC, beerinho commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +opted for the single file approach.
https://github.com/emberjs/rfcs/blob/master/text/0779-first-class-component-templates.md is this the RFC you're referring to?

2022-11-18 16:50 UTC, beerinho commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +
Ignore this, I took a screenshot anyway and will use that

2022-11-18 16:51 UTC, beerinho commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +name of the component when you import it - i.e.
https://github.com/emberjs/rfcs/blob/master/text/0779-first-class-component-templates.md is this the RFC for this?

2022-11-18 16:55 UTC, beerinho commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +immediately obvious which component is which.
I don't think named exports could work here, but the components can certainly be imported as whatever you like. I've added a note about that and the lint rule 👍

2022-11-21 07:05 UTC, marcoow commented
> Hey @marcoow, thank you very much for your detailed feedback, looking at some of the spelling/grammar mistakes, I'm starting to rethink some of my placements on the skills matrix 🙈.

I think it's written well overall – this is a huge post so no surprise there are some spelling mistakes :)

> I changed some of the codeblocks to use diff and it looked much better in the preview in the IDE but it doesn't seem to be styled properly on the actual site. I don't know if the styling for diff blocks is missing?

This is the relevant documentation: https://www.11ty.dev/docs/plugins/syntaxhighlight/#show-changes-using-diff-syntax If the CSS is missing, could you add it in a separate PR?

2022-11-21 07:07 UTC, marcoow commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +And there we have it, SvelteKit Super Rentals!
I meant just link to a deployment of the app in the state it would be in at this point in the tutorial. I think you could simply set up Netlify deployment for [this repo](https://github.com/mainmatter/sveltekit-super-rentals) and that should just work?

2022-11-21 07:08 UTC, marcoow commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +```
ok, if this is in the Ember guides I guess it's fine

2022-11-21 07:09 UTC, marcoow commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +(this is ignored by git so isn’t shown in the repo), it is also important to
Easiest fix might be to just include it in the repo? The token ends up being published as part of the site anyway so doesn't need to be kept a secret?

2022-11-21 07:11 UTC, marcoow commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +(this is ignored by git so isn’t shown in the repo), it is also important to
> required and is similar to the `{{outlet}}` in Ember, which allows the parent to render content to a specific area of the child component.

I think it's the other way round:

> required and is similar to the `{{outlet}}` in Ember, which allows child routes to render content into a specific area of the parent route.

2022-11-21 07:12 UTC, marcoow commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +name of the component when you import it - i.e.
I'm not entirely sure and there might be multiple relevant RFCs but I guess that's one of them, yes.

2022-11-25 08:44 UTC, beerinho commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +authorHandle: mainmatter
👍

2022-11-25 09:24 UTC, beerinho commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +(this is ignored by git so isn’t shown in the repo), it is also important to
🤦

2022-11-25 11:29 UTC, beerinho commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +And there we have it, SvelteKit Super Rentals!
Done, I also added a link to it at the top of the post.

2022-11-25 12:24 UTC, beerinho commented
The `diff` code-block styles will be added in this [PR](https://github.com/mainmatter/mainmatter.com/pull/1955)

2022-11-28 08:52 UTC, marcoow reviewed
Nice post 🙌 

I left some comments, mainly regarding stylistic points. I think for syntax highlighting Svelte components, HTML will likely give better results or you could consider adding Svelte as it's own language of course – I'd imagine the highlighter supports that.

2022-11-28 08:52 UTC, marcoow commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +tags: [svelte, sveltekit]
```suggestion
tags: [svelte]
```

I'd only use one – we don't have so many posts and if we have too many and specific tags, we end up with only one post per tag anyway.

2022-11-28 08:52 UTC, marcoow commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +We’re going to skip typescript because, to quote Sweet Brown “Ain’t nobody got
```suggestion
We’re going to skip TypeScript because, to quote Sweet Brown “Ain’t nobody got
```

2022-11-28 08:52 UTC, marcoow commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +
I'd consider adding a screenshot here to give an impression of what you'd have at this point.

2022-11-28 08:52 UTC, marcoow commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +likely just bounce back to you.
:)

2022-11-28 08:52 UTC, marcoow commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +```js
```suggestion
```bash
```

2022-11-28 08:52 UTC, marcoow commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +```js
```suggestion
```html
```

2022-11-28 08:52 UTC, marcoow commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +```js
```suggestion
```html
```

2022-11-28 08:52 UTC, marcoow commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +```js
```suggestion
```html
```

2022-11-28 08:52 UTC, marcoow commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +```js
```suggestion
```bash
```

2022-11-28 08:52 UTC, marcoow commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +```js
```suggestion
```bash
```

2022-11-28 08:52 UTC, marcoow commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +```js
```suggestion
```bash
```

2022-11-28 08:52 UTC, marcoow commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +```js
```suggestion
```bash
```

2022-11-28 08:52 UTC, marcoow commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +```js
```suggestion
```html
```

2022-11-28 08:52 UTC, marcoow commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +```js
```suggestion
```html
```

2022-11-28 08:52 UTC, marcoow commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +```js
```suggestion
```html
```

2022-11-28 08:52 UTC, marcoow commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +```js
```suggestion
```html
```

2022-11-28 08:52 UTC, marcoow commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +```js
```suggestion
```html
```

2022-11-28 08:52 UTC, marcoow commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +```js
```suggestion
```html
```

2022-11-28 08:52 UTC, marcoow commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +```js
```suggestion
```html
```

2022-11-28 08:52 UTC, marcoow commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +```js
```suggestion
```bash
```

2022-11-28 08:52 UTC, marcoow commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +```js
```suggestion
```html
```

2022-11-28 08:52 UTC, marcoow commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +```js
```suggestion
```html
```

2022-11-28 08:52 UTC, marcoow commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +```diff-js
```suggestion
```diff-html
```

2022-11-28 08:52 UTC, marcoow commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +```js
```suggestion
```html
```

2022-11-28 08:52 UTC, marcoow commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +```js
```suggestion
```html
```

2022-11-28 08:52 UTC, marcoow commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +```js
```suggestion
```html
```

2022-11-28 08:52 UTC, marcoow commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +```xml
```suggestion
```bash
```

2022-11-28 08:52 UTC, marcoow commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +```xml
```suggestion
```js
```

2022-11-28 08:52 UTC, marcoow commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +```js
```suggestion
```html
```

2022-11-28 08:52 UTC, marcoow commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +```diff-js
```suggestion
```diff-html
```

2022-11-28 08:52 UTC, marcoow commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +```diff-js
```suggestion
```diff-html
```

2022-11-28 08:52 UTC, marcoow commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +```diff-js
```suggestion
```diff-html
```

2022-11-28 08:52 UTC, marcoow commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +
```suggestion
```

2022-11-28 08:52 UTC, marcoow commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +```diff-js
```suggestion
```diff-html
```

2022-11-28 08:52 UTC, marcoow commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +to be added to Ember).
The RFC has been accepted and merged already and I think the feature even has been implemented and this should actually be released soon.

2022-11-28 08:52 UTC, marcoow commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +using HBS, while Svelte goes for pure HTML that can take pure JS expressions.
> goes for pure HTML

I'm not sure that's true? It's a template language as well but one that allows JS expressions (essentially like JSX)?

2022-11-28 08:52 UTC, marcoow commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +_Note: There is currently an open
See above, the RFC isn't open – it has been accepted and merged and even implemented already.

2022-11-28 08:52 UTC, marcoow commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +way of have the `this.args.` object that can be of any shape, though this can
```suggestion
way of have the `this.args` object that can be of any shape, though this can
```

2022-11-28 08:52 UTC, marcoow commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +attribute you are setting has the same name as the parameter, you can omit the
```suggestion
attribute you are setting has the same name as the variable, you can omit the
```

2022-11-28 08:52 UTC, marcoow commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +called `api` alongside or `images` folder. (You can call this folder whatever
```suggestion
called `api` alongside our `images` folder. (You can call this folder whatever
```

or I guess

```suggestion
called `api` alongside the `images` folder. (You can call this folder whatever
```

2022-11-28 08:52 UTC, marcoow commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +The `load` function is a reserved word and is used to load the relevant data for
```suggestion
The `load` function is used to load the relevant data for
```

"reserved word" is a bit confusing – reserved keywords in languages are words that have meaning and you cannot use to name e.g. your variables, for example `function` or `async` in JS. This is just Svelte's API.

2022-11-28 08:52 UTC, marcoow commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +The `onMount` function here is very similar to Glimmer’s `constructor`, this is
I think this makes it sound like the constructor is somehow a concept of Glimmer. I'd consider changing to sth. like

```suggestion
The `onMount` function here is very similar to Glimmer components' constructors, this is
```

2022-11-29 09:59 UTC, emmasofiah2o commented
> Also, @emmasofiah2o, do you normally add the og images for these? Or how does that work?

Yes, I do! I will do a quick read for review and then get your og-image ready. When would you like this to go out? Your rotation's post isn't due until August next year so I am assuming this is an in-between thing?

2022-11-29 19:08 UTC, emmasofiah2o requested changes
There are many comments, but mainly because this was VERY long lol. Just a few general tips:
1) its = possessive adjective :).
2) Any ";" can become a "." and make your text more readable.
3) Short sentences are easier to understand, especially when dealing with topics this complicated. I recommend using MAX 3 verbs per sentence - although one or two would be ideal.
4) Don't be afraid of using ":" when explaining stuff. This basically allows you to add an extra sentence to your thought without sacrificing readability.

2022-11-29 19:08 UTC, emmasofiah2o commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +  <p>As SvelteKit edges ever closer to it's 1.0 release, let's take a look at what makes it special and how it compares to EmberJS by recreating the Ember Super Rentals with SvelteKit.</p>
```suggestion
  <p>As SvelteKit edges ever closer to its 1.0 release, let's take a look at what makes it unique and how it compares to EmberJS by recreating the Ember Super Rentals with SvelteKit.</p>
```

2022-11-29 19:08 UTC, emmasofiah2o commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +understand the concepts behind the library, but because it is focused on the
```suggestion
understand the concepts behind the library. However, because it is focused on the
```

2022-11-29 19:08 UTC, emmasofiah2o commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +component side of Svelte (as opposed to the framework, SvelteKit) there isn’t
```suggestion
component side of Svelte (as opposed to the framework, SvelteKit), there isn’t
```

2022-11-29 19:08 UTC, emmasofiah2o commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +for introducing the principles of the framework. So we will be cross-pollinating
```suggestion
for introducing the principles of the framework. 
We will be cross-pollinating
```

2022-11-29 19:08 UTC, emmasofiah2o commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +applications.** SvelteKit is still pre version 1.0 and so is constantly changing
```suggestion
applications.** SvelteKit is still pre version 1.0 and therefore constantly changing
```

2022-11-29 19:08 UTC, emmasofiah2o commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +We’re going to skip typescript because, to quote Sweet Brown “Ain’t nobody got
```suggestion
We’re going to skip typescript because, to quote Sweet Brown, “Ain’t nobody got
```

2022-11-29 19:08 UTC, emmasofiah2o commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +SvelteKit has an interesting naming convention for routes, we can still have
```suggestion
SvelteKit has an interesting naming convention for routes: we can still have
```

2022-11-29 19:08 UTC, emmasofiah2o commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +slightly differing syntax, both have opted for more native looking HTML - Ember
```suggestion
slightly differing syntax. Both have opted for more native-looking HTML - Ember
```

2022-11-29 19:08 UTC, emmasofiah2o commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +But it can be argued that Svelte’s approach could lead to more confusion as the
```suggestion
It can be argued that Svelte’s approach could lead to more confusion as the
```

2022-11-29 19:08 UTC, emmasofiah2o commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +immediately obvious which component is which; although this isn't the strongest
```suggestion
immediately obvious which component is which: this isn't the strongest
```

2022-11-29 19:08 UTC, emmasofiah2o commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +did opt to include Playwright when setting up the project, so I initially wanted
```suggestion
did opt to include Playwright when setting up the project. I initially wanted
```

2022-11-29 19:08 UTC, emmasofiah2o commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +to implement Playwright’s experimental Component Testing library but as of the
```suggestion
to implement Playwright’s experimental Component Testing library, but as of the
```

2022-11-29 19:08 UTC, emmasofiah2o commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +to use it in this project. (there are other options for unit testing including
```suggestion
to use it in this project (there are other options for unit testing including
```

2022-11-29 19:08 UTC, emmasofiah2o commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +to e2e testing using Playwright for this example)
```suggestion
to e2e testing using Playwright for this example).
```

2022-11-29 19:08 UTC, emmasofiah2o commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +to use the UI to test the things that I wanted assure was actually working in
```suggestion
to use the UI to test the things that I wanted assure were actually working in
```

2022-11-29 19:08 UTC, emmasofiah2o commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +was visible, to get around this it required clicking on a non-interactive
```suggestion
was visible: to get around this it required clicking on a non-interactive
```

2022-11-29 19:08 UTC, emmasofiah2o commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +this way, but in general I prefer having to define the parameters over glimmers
```suggestion
this way, but in general I prefer having to define the parameters over glimmers'
```

2022-11-29 19:08 UTC, emmasofiah2o commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +way of have the `this.args.` object that can be of any shape, though this can
```suggestion
way of have the `this.args` object that can be of any shape. Though this can
```

2022-11-29 19:08 UTC, emmasofiah2o commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +`<img {src} {alt} />` is making use of Svelte’s shorthand mechanism, if the
```suggestion
`<img {src} {alt} />` is making use of Svelte’s shorthand mechanism: if the
```

2022-11-29 19:08 UTC, emmasofiah2o commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +This syntax will look very similar to that of Ember, with a few minor changes,
```suggestion
This syntax will look very similar to that of Ember, with a few minor changes:
```

2022-11-29 19:08 UTC, emmasofiah2o commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +instead of relying on Glimmer’s `{{on}}` modifier, we user Svelte’s `on:`
Is it Glimmer or Glimmers? Also, capitalized or not? I have corrected one a few paragraphs above, but I recommend double-checking that you wrote this the same way everywhere.

2022-11-29 19:08 UTC, emmasofiah2o commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +Now let’s add an external API, for this we will need a Mapbox account and to
```suggestion
Now, let’s add an external API: for this we will need a Mapbox account and to
```

2022-11-29 19:08 UTC, emmasofiah2o commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +this example, we will use the suggested route, we will create a `.env` file in
```suggestion
this example, we will use the suggested rout. We will create a `.env` file in
```

2022-11-29 19:08 UTC, emmasofiah2o commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +the root of our project and add `PUBLIC_MAPBOX_TOKEN = 'your_access_token’`, it
```suggestion
the root of our project and add `PUBLIC_MAPBOX_TOKEN = 'your_access_token’`. It
```

2022-11-29 19:08 UTC, emmasofiah2o commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +There are a couple of things to unwrap in this component, the first is that we
```suggestion
There are a couple of things to unwrap in this component. The first is that we
```

2022-11-29 19:08 UTC, emmasofiah2o commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +have two `script` tags, the first script tag has `context="module"` which means
```suggestion
have two `script` tags: one has `context="module"`, which means
```

2022-11-29 19:08 UTC, emmasofiah2o commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +The second `script` is not a module which means the properties within it can
```suggestion
The other `script` is not a module, which means the properties within it can
```

2022-11-29 19:08 UTC, emmasofiah2o commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +change between instances, this is important as we will be using this component
```suggestion
change between instances. This is important as we will be using this component
```

2022-11-29 19:08 UTC, emmasofiah2o commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +component but to keep this tutorial in line with the Ember Super Rentals
```suggestion
component, but to keep this tutorial in line with the Ember Super Rentals
```

2022-11-29 19:08 UTC, emmasofiah2o commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +Now we have some nice looking components but they’re not very interesting, the
```suggestion
Now we have some nice-looking components but they’re not very interesting yet. The
```

2022-11-29 19:08 UTC, emmasofiah2o commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +page source which means it is search engine bots are able to crawl it easier,
```suggestion
page source which means its search engine bots are able to crawl it easier,
```

?

2022-11-29 19:08 UTC, emmasofiah2o commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +increasing it’s SEO score.
```suggestion
increasing its SEO score.
```

2022-11-29 19:08 UTC, emmasofiah2o commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +the page, the load function should return an object of the data but can also
```suggestion
the page. The load function should return an object of the data but can also
```

2022-11-29 19:08 UTC, emmasofiah2o commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +Next stop, individual rental pages.
```suggestion
Next stop: individual rental pages.
```

2022-11-29 19:08 UTC, emmasofiah2o commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +expanding the `data` object and assigning `data.rental` to it’s own property to
```suggestion
expanding the `data` object and assigning `data.rental` to its own property to
```

2022-11-29 19:08 UTC, emmasofiah2o commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +based on a text search
```suggestion
based on a text search.
```

2022-11-29 19:08 UTC, emmasofiah2o commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +appeal of it, it’s a very lightweight framework and in a lot of ways it stays
```suggestion
appeal of it. It’s a very lightweight framework and in a lot of ways it stays
```

2022-11-29 19:08 UTC, emmasofiah2o commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +very close to native javascript, which makes me think it would be a really great
```suggestion
very close to native JavaScript, which makes me think it would be a really great
```

2022-11-29 19:08 UTC, emmasofiah2o commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +which will only help when trying out other frameworks in the future. Which I
```suggestion
which will only help when trying out other frameworks in the future. I feel this
```

2022-11-29 19:08 UTC, emmasofiah2o commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +feel is almost the opposite of Ember, there are a lot of areas of the framework
```suggestion
is almost the opposite of Ember: there are a lot of areas of the framework
```

2022-11-29 19:08 UTC, emmasofiah2o commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +light on SvelteKit’s test suite as a whole, Ember’s qunit integration allows for
```suggestion
light on SvelteKit’s test suite as a whole. Ember’s qunit integration allows for
```

2022-11-30 16:10 UTC, emmasofiah2o commented
![og-image blog post sveltekit](https://user-images.githubusercontent.com/83696750/204849379-8ad20b72-71ce-4412-bde3-0010586c243f.jpg)

@beerinho here is the og-image. I am not sure if we can change the logo's colors like this, but it didn't look good with the red. Let me know if you want me to adjust something.

2022-11-30 16:24 UTC, davidhajba commented
OG image updated, 
we cannot use purple instead of red, we can use only black to white if we don't use the original colors.

2022-12-02 10:29 UTC, beerinho commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +```diff-js
This has a similar issue to the js, the diff styling can be added, but the HTML styling is missing

2022-12-02 10:45 UTC, beerinho commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +for introducing the principles of the framework. So we will be cross-pollinating
I think these sentences need to be combined into one as it's still talking about the same thing

2022-12-02 10:58 UTC, beerinho commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +immediately obvious which component is which; although this isn't the strongest
I'm not sure about this one, it doesn't feel like the second clause here needs any extra emphasis as it's more of a side note

2022-12-02 11:09 UTC, beerinho commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +The second `script` is not a module which means the properties within it can
I want it to be clear here that there is an order, so I've added the punctuation but kept the "first" and "second"

2022-12-02 11:23 UTC, beerinho commented
Hey @davidhajba, where is the updated OG image? Or were you saying that the one from Emma has been updated?

2022-12-02 11:25 UTC, beerinho commented
Hey @emmasofiah2o, thank you very much for your feedback, I'd never really used a colon to add emphasis before, I like it! There were a couple of suggested places that I didn't think it was suitable though. And also, I can't believe I've gone this long in life using a possessive apostrophe for "its" - yet another failure of the English education system 😆

2022-12-02 13:16 UTC, beerinho commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +```diff-js
This has a similar issue to the js, the diff styling can be added, but the HTML styling is missing

2022-12-02 13:17 UTC, beerinho commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +```diff-js
This has a similar issue to the js, the diff styling can be added, but the HTML styling is missing

2022-12-02 13:17 UTC, beerinho commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +```diff-js
This has a similar issue to the js, the diff styling can be added, but the HTML styling is missing

2022-12-02 13:17 UTC, beerinho commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +```diff-js
This has a similar issue to the js, the diff styling can be added, but the HTML styling is missing

2022-12-02 14:10 UTC, beerinho commented on src/posts/2022-11-18-sveltekit-super-rentals.md
> +using HBS, while Svelte goes for pure HTML that can take pure JS expressions.
I've updated this but still not sure of the best way to have a succinct explanation of it. Essentially you can write native HTML and add JS to it. Not quite like JSX though as that is more HTML through JS, whereas with Svelte you can have HTML without the JS

2022-12-02 14:41 UTC, emmasofiah2o commented
> Hey @emmasofiah2o, thank you very much for your feedback, I'd never really used a colon to add emphasis before, I like it! There were a couple of suggested places that I didn't think it was suitable though. And also, I can't believe I've gone this long in life using a possessive apostrophe for "its" - yet another failure of the English education system 😆.
> 
> In regards to when I've like it to go out, I'm happy to get it out as soon as it's ready, I don't see any need to wait with it

Feel free to ignore suggestions that you don't like! :). I guess since you have gotten a few reviews already this can be released next week?

2022-12-07 11:53 UTC, emmasofiah2o approved these changes

2022-12-07 11:54 UTC, emmasofiah2o commented
I have approved the changes and added the new og-image. As far as I understood, you will be getting the illustration from David. Let me know when this is ready so I can change the date and release it. We have it scheduled for tomorrow so it would be ideal if you could make it by tonight :D

2022-12-07 12:13 UTC, davidhajba commented
The OG image is updated in it's original Place in Sketch, @emmasofiah2o can you proceed based on this ?

2022-12-07 12:43 UTC, emmasofiah2o commented
> The OG image is updated in it's original Place in Sketch, @emmasofiah2o can you proceed based on this ?

I have updated it already. Is it not the final version?

2022-12-14 09:48 UTC, emmasofiah2o commented
@beerinho is this ready now? Or is there still something left to fix?

2022-12-14 10:54 UTC, beerinho commented
@emmasofiah2o unfortunately there is still ongoing discussion about the `diff` highlighting in this [PR](https://github.com/mainmatter/mainmatter.com/pull/1955) so I don't think the highlighting is quite right yet

2022-12-14 11:55 UTC, emmasofiah2o commented
> @emmasofiah2o unfortunately there is still ongoing discussion about the `diff` highlighting in this [PR](https://github.com/mainmatter/mainmatter.com/pull/1955) so I don't think the highlighting is quite right yet

How can I help you move forward with this?

2022-12-14 14:26 UTC, beerinho commented
> How can I help you move forward with this?
Unfortunately there isn't a whole lot you can do to help, unless you know how to fix the highlighting?

2022-12-15 09:13 UTC, emmasofiah2o commented
> > How can I help you move forward with this?
> > Unfortunately there isn't a whole lot you can do to help, unless you know how to fix the highlighting?

Mmh I don't think I know, but maybe we can ask on Slack for someone to have a look.

2022-12-19 08:53 UTC, beerinho commented
Hey @emmasofiah2o, this is ready for release now 😊

2022-12-19 08:58 UTC, emmasofiah2o commented
@beerinho is it normal that a lot of checks aren't passing tho?

2022-12-19 09:10 UTC, beerinho commented
According to @marcoow some of the failures are caused by someone impersonating simplabs. But some of them look like genuine build errors. I've not seen those before but I don't know if they are normal for this repo?

2022-12-19 09:25 UTC, emmasofiah2o commented
> According to @marcoow some of the failures are caused by someone impersonating simplabs. But some of them look like genuine build errors. I don't think they are good but I don't know if they are normal for this repo?

Have you run "lint fix" after correcting the diff thing?

2022-12-19 09:35 UTC, beerinho commented
I did indeed. And from looking at the CI, the linting was the only one that was successful

2022-12-19 09:51 UTC, emmasofiah2o commented
> I did indeed. And from looking at the CI, the linting was the only one that was successful

I think re-running the tests also isn't helping. Let's wait for @marcoow's reply then and aim to get it released tomorrow.

2022-12-19 10:50 UTC, beerinho commented
Sveltekit hit 1.0 over the weekend, so if this post can wait until Friday I can update it to use the 1.0 release version which could mean a more relevant post

2022-12-19 11:26 UTC, marcoow commented
The build for this is broken so that needs to be fixed. And yes, please also update to take the release of SvelteKit 1.0 into account – we shouldn't release as is as some of this is just not correct anymore.

2022-12-23 16:20 UTC, beerinho commented
Okay this is really weird, I've been wrestling with this all day and I have no idea why, but the `html-minifier` library has an issue with the `diff` blocks.

This one builds fine but doesn't render the `diff` block as a diff block, it just shows it as standard text (possibly because the `diff` expects the `+` or `-` to be the very first character on the line).
<img width="688" alt="Screenshot 2022-12-23 at 17 15 07" src="https://user-images.githubusercontent.com/38084194/209366162-40a68d73-b727-40c4-ba38-630b35cb5335.png">

This doesn't build, but running it locally (skipping the minify step) works and renders the `diff` block correctly.
<img width="666" alt="Screenshot 2022-12-23 at 17 15 54" src="https://user-images.githubusercontent.com/38084194/209366170-3a26f1cc-3009-48d8-b6b2-7c3ec3a54cf8.png">

Note: the only difference between these two is the tabbing.

2022-12-23 16:31 UTC, beerinho commented
Maybe the `ignoreCustomFragments` setting will help us? https://github.com/kangax/html-minifier

2022-12-23 16:43 UTC, marcoow commented
ugh, strange… I think it'd be totally fine to ignore `<code>` blocks – minifying HTML isn't too relevant at all really.

Btw, you should never use ` ```diff` but always the language-specific diff variants, e.g. ` ```diff-js` etc., see https://github.com/mainmatter/mainmatter.com/pull/1955#issuecomment-1354883218

2023-01-18 19:00 UTC, BobrImperator approved these changes

2023-01-18 19:01 UTC, BobrImperator commented
Crazy research and good comparisons with links to RFCs too 🙏

2023-01-20 07:48 UTC, marcoow commented
@beerinho this fixes the build problem: https://github.com/mainmatter/mainmatter.com/pull/1978 (don't ask me why 🤷 )

2023-01-20 09:05 UTC, beerinho commented
@emmasofiah2o this is ready to go now 😄 🎉

2023-01-22 17:49 UTC, emmasofiah2o commented
> @emmasofiah2o this is ready to go now 😄 🎉

Awesome, thanks for the heads up :). I'll get it out tomorrow or Tuesday: the post is ready :).

2023-01-23 07:46 UTC, marcoow commented
@emmasofiah2o it's still missing a header image – let's please add one

2023-01-23 09:31 UTC, emmasofiah2o commented
> @emmasofiah2o it's still missing a header image – let's please add one

David said we don't have illustrations yet. The ones that we did with the patterns (like for your Rust email post for example), are not really meant to be used for all posts - is that what you meant?

2023-01-23 09:45 UTC, emmasofiah2o commented
> > @emmasofiah2o it's still missing a header image – let's please add one
> 
> David said we don't have illustrations yet. The ones that we did with the patterns (like for your Rust email post for example), are not really meant to be used for all posts - is that what you meant?

Just connected with David. I'll add one of the pictures we use on the website.

2023-01-23 10:03 UTC, marcoow commented
We should generally have visuals for posts. In this case I guess an obvious possibility would be to use the [Ember Super Rentals app](https://ember-super-rentals.netlify.app) and the Svelte logo somehow?

2023-01-23 10:04 UTC, emmasofiah2o commented
> We should generally have visuals for posts. In this case I guess an obvious possibility would be to use the [Ember Super Rentals app](https://ember-super-rentals.netlify.app) and the Svelte logo somehow?

There was a discussion between you and David on this topic here: https://www.notion.so/mainmatter/832aecb85d3747a2adab6a5fce452f5e?v=999496eec6c24b06818ad82a363a8d45&p=e66f4b6878a74e099950a6cd25dd346d&pm=s.

2023-01-23 10:13 UTC, marcoow commented
ok, sure – just in this case, the Svelte logo **must** be in there somehow

2023-01-23 12:13 UTC, emmasofiah2o commented
@marcoow David provided the header image. I have added it to the post, updated the og-image, and updated the dates. Please let me know if this is approved so I can merge and post tomorrow :)

2023-01-23 12:43 UTC, marcoow approved these changes

2023-01-23 12:44 UTC, marcoow commented
It's fine but overall I'm not sure the purple tint works well for photos we use on a purple background, e.g. https://deploy-preview-1952--objective-northcutt-37494c.netlify.app/blog/

2023-01-23 14:18 UTC, emmasofiah2o commented
> It's fine but overall I'm not sure the purple tint works well for photos we use on a purple background, e.g. https://deploy-preview-1952--objective-northcutt-37494c.netlify.app/blog/

I'll let David know :)

2023-01-24 09:31 UTC, merged