Add "actix – an actor framework for the Rust programming language" blog post
mainmatter/mainmatter.com pull request #198
Opened 2018-05-28 13:16 UTC by Turbo87

Resolve #197

2018-05-28 17:39 UTC, oliverbarnes requested changes
👏 great post, really well written. Rust syntax still seems alien to me, but this was an interesting first read about it, for me. Just the small comments below

2018-05-28 17:39 UTC, oliverbarnes commented on blog/_posts/2018-05-28-actix.md
> +scripting languages like JavaScript or Ruby and a low-level high-performance
I'd remove the `scripting`, seems to imply they're not full-fledged languages. some people might get stung by it ;)

2018-05-28 17:39 UTC, oliverbarnes commented on blog/_posts/2018-05-28-actix.md
> +similar to `npm` in JavaScript or `pip` in Python, with the main difference
maybe mention javascript and ruby (`bundler`) first and mention python and pip as an aside, given we work with the first two?

2018-05-28 17:39 UTC, oliverbarnes commented on blog/_posts/2018-05-28-actix.md
> +that `cargo` is also used to build and test your applications and libraries.
like `mix`, in Elixir

2018-05-28 17:39 UTC, oliverbarnes commented on blog/_posts/2018-05-28-actix.md
> +The main advantage over all the other languages is Safety. The Rust compiler is
*safety*, lowercase

2018-05-28 17:39 UTC, oliverbarnes commented on blog/_posts/2018-05-28-actix.md
> +An actor is a thing, that can only be interacted with using "messages". A
no need for the comma

2018-05-28 17:39 UTC, oliverbarnes commented on blog/_posts/2018-05-28-actix.md
> +
this summary about the actor model is great. but one thing I got confused about when first reading about the actor model is how it sounds like the object model, given it also involves message passing between things with behavior and state. maybe I don't understand it in full, still - the only distinction I make, based on Elixir, is that this "thing" has its own process within the VM. is this it? have no idea how it works with Rust. In any case, would be great to distinguish between the two, here

2018-05-28 17:39 UTC, oliverbarnes commented on blog/_posts/2018-05-28-actix.md
> +While [actix-web] is interesting and worth another blog post we will focus on
*...and worth another blog post, we will...` (adding the comma)

2018-05-28 17:39 UTC, oliverbarnes commented on blog/_posts/2018-05-28-actix.md
> +The first thing to do when using actix actors is to set up a [`System`], that
what do the square brackets mean here? is it a syntax thing in Rust?

2018-05-28 17:39 UTC, oliverbarnes commented on blog/_posts/2018-05-28-actix.md
> +The first thing to do when using actix actors is to set up a [`System`], that
just noticed the link on the rendered page, but don't understand how it's linking ;) Anyway, `[Arbiter]` below isn't linked (yet?)

2018-05-28 17:39 UTC, oliverbarnes commented on blog/_posts/2018-05-28-actix.md
> +
Now that I've finished the post, seems that would mean threads in Rust

2018-05-29 07:42 UTC, niklaslong reviewed
I really enjoyed this post (looking forward to the next one as well)! 🎉 
+1 on what @oliverbarnes mentioned and I made some small wording suggestions.

2018-05-29 07:42 UTC, niklaslong commented on blog/_posts/2018-05-28-actix.md
> +While building the actor was relatively okay, running it is unfortunately still
Small suggestion: _easy_ instead of _okay_

2018-05-29 07:42 UTC, niklaslong commented on blog/_posts/2018-05-28-actix.md
> +similar to `npm` in JavaScript or `pip` in Python, with the main difference
like hex in Elixir? (used by mix)

2018-05-29 08:30 UTC, Turbo87 commented on blog/_posts/2018-05-28-actix.md
> +
yeah, with OOP you call things on the class instances directly. with the actor model you have this indirection through the actor framework that abstracts away the communication between the actors so that you can distribute them to different threads, processes or even entirely different machines. actix currently only supports different threads, but the rest is on the roadmap too.

2018-05-29 08:32 UTC, Turbo87 commented on blog/_posts/2018-05-28-actix.md
> +The first thing to do when using actix actors is to set up a [`System`], that
it was missing the following line below the section:

```
[`Arbiter`]: https://actix.rs/actix/actix/struct.Arbiter.html
```

added now, good catch 👍

2018-05-29 13:30 UTC, oliverbarnes approved these changes

2018-05-29 15:10 UTC, chriskrycho commented on blog/_posts/2018-05-28-actix.md
> +back in 2010. You can think about it as an interesting mix of high-level
Actually started all the way back in 2006! See [this FAQ entry](https://www.rust-lang.org/en-US/faq.html#is-this-project-controlled-by-mozilla).

2018-05-29 15:19 UTC, Turbo87 commented on blog/_posts/2018-05-28-actix.md
> +back in 2010. You can think about it as an interesting mix of high-level
whoops... don't believe everything Wikipedia tells you 😜

2018-06-04 18:46 UTC, marcoow reviewed
This is a very good post 👍 I left some comments on wording where changes could make the text easier to understand, in particular for people not already familiar with the matter.

I'd release this one next week and the 2nd part in 2 weeks then.

2018-06-04 18:46 UTC, marcoow commented on blog/_posts/2018-05-28-actix.md
> +we will have a closer look at now.
I think this sentence is unnecessary hard to understand as it initially refers to the actor from the example but then makes a general point regarding actors which is not actually true for the actor in the example (as that's just a base JS class). So basically what I'm saying is, this gets simpler if you change it to _"The complexity of actors is relatively low…"_.

2018-06-04 18:46 UTC, marcoow commented on blog/_posts/2018-05-28-actix.md
> +explicitly declare that. That leaves us with an empty `PlusOne` message,
I think it might be worth explaining this a bit more, e.g. by saying that we need the `type` property on the message in JS so we can identify what kind of message we're receiving while in Rust we can declare the handler to handle messages of type `PlusOne` as that type exists and has meaning in Rust. I think it might not be 100% clear to everyone what you're trying to say here otherwise.

2018-06-04 18:46 UTC, marcoow commented on blog/_posts/2018-05-28-actix.md
> +The `Arbiter::start()` call returns us an `Addr`, that we can use to talk to
Does _"returns us"_ work in english? I think the _"us"_ should be removed?

2018-06-04 18:46 UTC, marcoow commented on blog/_posts/2018-05-28-actix.md
> +`clone()` and use that one instead.
This doesn't actually explicitly get mentioned earlier. I'd add just one sentence saying explicitly that Rust checks who owns which data and thus might modify data and that the concept of _"borrowing"_ exists etc. (I'm not really familiar with the details - you'll know much better) to https://github.com/simplabs/simplabs.github.io/pull/198/files#diff-129064ba4cecc35f3701f92524e29ea2R44 so that this gets clearer.

2018-06-04 18:48 UTC, marcoow commented
> I'd release this one next week and the 2nd part in 2 weeks then.

Not sure why I was thinking there was a second part of this already :)

2018-06-11 10:39 UTC, merged