Add magdeburger developer days
mainmatter/mainmatter.com pull request #2005
Opened 2023-03-09 17:33 UTC by emmasofiah2o

Add event,
Add logo,
Add Marco's talk.

2023-03-09 17:39 UTC, emmasofiah2o commented
Hi @marcoow. I have added the event you tagged me to the calendar. I will add it to the appearances section when/if a video is released.

2023-03-10 07:01 UTC, marcoow requested changes
all of our website should remain in english

2023-03-13 10:17 UTC, emmasofiah2o commented
@marcoow updated

2023-03-13 10:57 UTC, marcoow commented on src/calendar/2023-05-08-magdeburger-developer-days.md
> +Magdeburger Developer Days is a 3-day developer & community conference in
```suggestion
Magdeburger Developer Days is a 3-day software engineering conference in
```

2023-03-13 10:57 UTC, marcoow commented on src/calendar/2023-05-08-magdeburger-developer-days.md
> +challenges and strategies to overcome them.
```suggestion
Magdeburg. Mainmatter Founder Marco Otte-Witte will talk about
Continuous Deployment Workflows. He will present main advantages
compared to classical processes, explain the essential components of such a
process (especially with ryegard to testing and automation), and discuss typical
challenges and strategies to overcome them.
```

2023-03-14 14:42 UTC, emmasofiah2o commented on src/calendar/2023-05-08-magdeburger-developer-days.md
> +ryegard to testing and automation), and discuss typical challenges and
```suggestion
regard to testing and automation), and discuss typical challenges and
```

2023-03-15 08:23 UTC, marcoow commented
@emmasofiah2o linting fails

2023-03-16 09:32 UTC, emmasofiah2o commented
Can I merge @marcoow?

2023-03-16 10:55 UTC, marcoow approved these changes

2023-03-16 10:55 UTC, merged