Add This week in os #22
mainmatter/mainmatter.com pull request #2022
Opened 2023-04-12 14:28 UTC by emmasofiah2o

- Add file 

To-do:
- Categorize Unknown links

2023-04-17 13:29 UTC, oscard0m requested changes

2023-04-17 13:29 UTC, oscard0m commented on src/twios/2023-04-18.md
> +  Next ([@oscard0m])
```suggestion
```

2023-04-17 13:32 UTC, emmasofiah2o commented on src/twios/2023-04-18.md
> +  Next ([@oscard0m])
Why the double dash? :)

2023-04-17 13:36 UTC, oscard0m commented on src/twios/2023-04-18.md
> +  Next ([@oscard0m])
I'm suggesting removing these 2 lines.

The way this view works (it's called `diff`) is by adding `-` in front of each line of code removed and adding `+` in front of each line of code added.

See this example:

```diff
+ line 1 added
+ line 2 added
- line 3 removed
- line 4 removed
```

In this case, the double dash is because the line deleted (`-`) starts with a dash:

```diff
- - line deleted starting with a dash
```

2023-04-17 13:49 UTC, emmasofiah2o commented on src/twios/2023-04-18.md
> +  Next ([@oscard0m])
Ah I see. Is this repo to be excluded from all posts? In that case I would update the config

2023-04-17 13:53 UTC, oscard0m commented on src/twios/2023-04-18.md
> +  Next ([@oscard0m])
No, only this PR

2023-04-18 08:29 UTC, emmasofiah2o commented
@oscard0m could you reapprove Gravity if the changes are fine to you?

2023-04-18 08:30 UTC, oscard0m approved these changes

2023-04-18 08:40 UTC, merged