Add Marco's talk from Rust Munich 2 2023
mainmatter/mainmatter.com pull request #2032
Opened 2023-04-26 11:22 UTC by emmasofiah2o

- Add talk
- Add channel
- Add visual and logo

<img width="1325" alt="Screenshot 2023-04-26 at 13 28 29" src="https://user-images.githubusercontent.com/83696750/234561639-74c125ce-6d76-4926-a51c-b34c8278c2a1.png">

2023-04-26 11:29 UTC, emmasofiah2o commented
@marcoow ready for review. I used pretty much the same description that I used for the post.

2023-04-26 11:29 UTC, emmasofiah2o commented
I think the background image doesn't really work, but if we change that we should probably change them all since they all are similar (picture + title)

2023-04-26 11:43 UTC, marcoow requested changes

2023-04-26 11:43 UTC, marcoow commented on src/appearances/2023-04-20-sending-emails-from-the-edge.md
> +Meetup.
```suggestion
Marco Otte-Witte explained how to run Rust code on edge functions in his talk at the Rust Munich
Meetup. He showed how Rust, compiled to WASM, running on Cloudflare Workers handles submissions of [Mainmatter's contact form](/contact).
```

2023-05-03 11:31 UTC, emmasofiah2o commented
<img width="1311" alt="Screenshot 2023-05-03 at 13 28 03" src="https://user-images.githubusercontent.com/83696750/235903582-f71e4fad-f208-48c2-8ed4-fbaa46dc747d.png">
@marcoow I have updated the visual - can this be merged?

2023-05-03 11:45 UTC, marcoow approved these changes

2023-05-03 11:53 UTC, merged