Add Ember Europe Q2 2023
mainmatter/mainmatter.com pull request #2039
Opened 2023-05-16 08:49 UTC by emmasofiah2o

- Add event
- Add description
- Add image

2023-05-16 10:14 UTC, emmasofiah2o commented
<img width="661" alt="Screenshot 2023-05-16 at 12 14 08" src="https://github.com/mainmatter/mainmatter.com/assets/83696750/6bbd6b50-f384-4e8f-b864-8cba0d6d32f6">

2023-05-16 10:27 UTC, marcoow requested changes
one typo

2023-05-16 10:27 UTC, marcoow commented on src/calendar/2023-06-15-embereurope-dublin.md
> +by Intercom at their Dublin's office. The Ember Europe meetup series brings
```suggestion
by Intercom at their Dublin office. The Ember Europe meetup series brings
```

2023-06-01 07:21 UTC, marcoow commented
@emmasofiah2o please ping reviewers when change requests have been adressed – this went unnoticed for 2 weeks now…

2023-06-01 07:37 UTC, merged

2023-06-01 12:24 UTC, emmasofiah2o commented
> @emmasofiah2o please ping reviewers when change requests have been adressed – this went unnoticed for 2 weeks now…

I thought you would be automatically notified since I committed your suggestion. I'll tag you next time.