Add new startups page
mainmatter/mainmatter.com pull request #2049
Opened 2023-05-22 15:45 UTC by inesilva

### Context
#2047

2023-05-23 14:24 UTC, davidhajba commented
hey @inesilva 
could you please add a preview link?
under the 'Deploy Preview ready!' I see the Mainmatter homepage

2023-05-23 14:32 UTC, inesoaresilva commented
> hey @inesilva could you please add a preview link? under the 'Deploy Preview ready!' I see the Mainmatter homepage

Yup, I just updated the description

2023-05-23 15:13 UTC, oscard0m requested changes
The page looks good!

Check Percy. The header has a duplicated link to 'Blog':
![image](https://github.com/mainmatter/mainmatter.com/assets/2574275/7e1c0f1b-f2c7-4f86-9ebd-b45176d5397f)

2023-05-24 06:49 UTC, marcoow reviewed
Nice! Just some comments on minor aspects

2023-05-24 06:49 UTC, marcoow commented on src/startups.njk
> +  description: "Find out how can we help you grow your business.",
I'm not sure this works as a description – can you help @SaeLLo? See [this](https://ahrefs.com/blog/open-graph-meta-tags/) for reference

2023-05-24 06:49 UTC, marcoow commented on src/startups.njk
> +  "alt": "A massive vessel packed with cargo containers navigating in a water channel",
This is the Ever Given in the Suez Canal: https://en.wikipedia.org/wiki/Ever_Given#2021_Suez_Canal_grounding

2023-05-24 06:49 UTC, marcoow commented on src/startups.njk
> +{% set logoCompanies = ['Qonto', 'Trainline', 'Cardstack', 'Timify', 'Experteer', 'Robin Hood', 'Dim3' ] %}
```suggestion
{% set logoCompanies = ['Qonto', 'Trainline', 'Cardstack', 'Timify', 'Experteer', 'Rail Europe', 'Sage' ] %}
```

2023-05-24 06:49 UTC, marcoow commented on src/startups.njk
> +  "text": "We will begin by setting up a web server for our web application using the Axum framework, which is built on top of Tokio and Hyper. We will learn about the FromRequest and IntoResponse tr
wrong text

2023-05-24 06:49 UTC, marcoow commented on src/startups.njk
> +  {{ navPagination(pagination.href.previous, pagination.href.next, nextLabel) }}
```suggestion
```

no pagination here

2023-05-24 08:15 UTC, SaeLLo requested changes

2023-05-24 08:15 UTC, SaeLLo commented on src/startups.njk
> +  "text": "We will begin by setting up a web server for our web application using the Axum framework, which is built on top of Tokio and Hyper. We will learn about the FromRequest and IntoResponse tr
-> "We’ve got a proven track record as digital product developers. We collaborate with our clients from the strategy phases to validation to MVP and beyond.  Our experienced team will get you to market."

2023-05-24 09:32 UTC, inesilva commented on src/startups.njk
> +{% set logoCompanies = ['Qonto', 'Trainline', 'Cardstack', 'Timify', 'Experteer', 'Robin Hood', 'Dim3' ] %}
@davidhajba do you have rail europe logo in monochrome version?

2023-05-26 12:47 UTC, SaeLLo approved these changes

2023-05-26 12:51 UTC, oscard0m requested changes
I see in Percy there are some pages generated which I think we don't want to:
- /startups/9/index.html
- /startups/8/index.html
- /startups/7/index.html
- ...

I guess is related to pagination?

Also, CI failing now.

2023-05-26 13:08 UTC, davidhajba commented
It looks great, 

* Background images 'Instantly add years of expertise' & 'Grow your business with us' 
looks bad quality on my side.

* I'm not sure about the extra black transparent overlay animation on the top, I didn't suggest anything like this, the pictures are colored as a final result, and no further overlay is needed.

2023-05-26 15:13 UTC, inesilva commented
> It looks great,
> 
> * Background images 'Instantly add years of expertise' & 'Grow your business with us'
>   looks bad quality on my side.
> * I'm not sure about the extra black transparent overlay animation on the top, I didn't suggest anything like this, the pictures are colored as a final result, and no further overlay is needed.

I removed the black overlay, and the photos are looking better now, I should be exporting the images with 2x the size, instead of the standard 1x (otherwise, they don't get enough pixel density to look good on retina screens)

2023-05-29 13:22 UTC, inesilva commented on src/startups.njk
> +  description: "Find out how can we help you grow your business.",
@SaeLLo do you have any updates on this?

2023-05-30 08:26 UTC, davidhajba commented
thank you  @inesilva 
* looks much better now
* yes, retina screens always need 2x size when importing pictures from Sketch to achieve the same resolution you see
* this double size picture should work on bigger screens too (big enough to look good) but on the website it still looks too low quality
* as I know there's some automatic tool 'optimizes' picture size, but imo it doesn't work well, if the UX impression is low quality images, is it possible to improve this?

2023-05-31 07:43 UTC, oscard0m commented on src/startups.njk
> +  },
I suspect this is copy-paste and is generating the undesired pagination in Percy, could be? @inesilva

2023-05-31 07:44 UTC, oscard0m requested changes

2023-05-31 07:44 UTC, oscard0m commented on src/startups.njk
> +  },
```suggestion
```

I suspect this is copy-paste and is generating the undesired pagination in Percy, could be? @inesilva

2023-06-01 10:12 UTC, inesilva commented on src/startups.njk
> +  },
This is required to display the posts at the end of the page:
<img width="1677" alt="image" src="https://github.com/mainmatter/mainmatter.com/assets/15367376/cae5cd3b-eabf-4cdb-80f8-51a7d268fa14">

2023-06-01 10:26 UTC, oscard0m commented on src/startups.njk
> +  },
> This is required to display the posts at the end of the page: <img alt="image" width="1677" src="https://user-images.githubusercontent.com/15367376/242563880-cae5cd3b-eabf-4cdb-80f8-51a7d268fa14.png">

Oh! I see. 

Then the question here is: What should we do here?
a) We only show the first three blog posts, and the link points to `/blog/page/2/#posts`
b) What we have right now is correct.

2023-06-01 10:37 UTC, davidhajba commented on src/startups.njk
> +  },
I think we're missing the 'Explore more articles' button from the bottom, 
Imo if you could add it, the current version would be good

<img width="1024" alt="Screenshot 2023-06-01 at 12 35 45" src="https://github.com/mainmatter/mainmatter.com/assets/78347340/8a3992e8-bd25-4fb6-a663-9dc52154dd7a">

2023-06-01 11:07 UTC, inesilva commented on src/startups.njk
> +  },
which link @oscard0m ?

2023-06-01 11:15 UTC, inesilva commented on src/startups.njk
> +  },
the one of explore more articles?

2023-06-01 11:16 UTC, oscard0m commented on src/startups.njk
> +  },
> which link @oscard0m ?

I thought we would have this on the homepage:
![image](https://github.com/mainmatter/mainmatter.com/assets/2574275/f04a6b85-1432-42ae-b402-0d3880d12217)

So... forget about the link part a)/b). We need to find a way to render the first 3 blog posts but to not have pagination.

2023-06-01 11:51 UTC, inesilva commented on src/startups.njk
> +  },
pagination removed ✅

2023-06-01 11:52 UTC, inesilva commented on src/startups.njk
> +  description: "Find out how can we help you grow your business.",
@marcoow @SaeLLo I updated the text. Let me know if it looks good or if you have other suggestions

2023-06-01 12:06 UTC, oscard0m requested changes
Check Percy's comments. I see a padding/margin issue at the end of some pages.

2023-06-01 14:05 UTC, SaeLLo approved these changes

2023-06-01 14:05 UTC, SaeLLo commented on src/startups.njk
> +  description: "Find out how can we help you grow your business.",
@inesilva Where is this description?

2023-06-01 14:05 UTC, SaeLLo commented on src/startups.njk
> +  description: "Find out how can we help you grow your business.",
Let's use: 
Burst through your scale-up bottleneck. We'll be your expert guides.

2023-06-01 16:32 UTC, inesilva commented
@SaeLLo the description it is here - https://github.com/mainmatter/mainmatter.com/pull/2049/commits/91df17f9d234ad04f93c8531c1d29e294cc8aa0d

2023-06-16 14:31 UTC, oscard0m approved these changes

2023-07-17 12:28 UTC, SaeLLo commented
@inesilva and @oscard0m This is ready, right?

2023-07-17 12:57 UTC, oscard0m commented
> @inesilva and @oscard0m This is ready, right?

@inesilva is on top of this. On my side, LGTM

2023-07-19 10:42 UTC, SaeLLo commented
@inesilva Can we please get this done? What is missing?

2023-07-19 11:13 UTC, merged

2023-07-19 11:13 UTC, inesilva commented
> @inesilva Can we please get this done? What is missing?

All done, I just merged it