Update info in rust workshop page
mainmatter/mainmatter.com pull request #2052
Opened 2023-05-24 14:47 UTC by inesilva

It closes #2050

2023-05-24 14:52 UTC, davidhajba approved these changes

2023-05-24 15:03 UTC, SaeLLo requested changes

2023-05-24 15:03 UTC, SaeLLo commented on src/web-based-services-in-rust-workshop.njk
> +          <p>Each session will include practical examples, and in addition, we will provide optional homework for you to work on.</p>
Can we do it without an extra paragraph?

2023-05-24 15:37 UTC, marcoow approved these changes

2023-05-24 15:37 UTC, marcoow commented on src/web-based-services-in-rust-workshop.njk
> +            <div class="color-hero__text color-hero__text--small"> Remote </div>
```suggestion
            <div class="color-hero__text color-hero__text--small">11.-13. (14:00 - 18:00 CEST) July 2023</div>
            <div class="color-hero__text color-hero__text--small">Remote</div>
```

2023-05-25 11:37 UTC, davidhajba approved these changes

2023-05-25 13:54 UTC, SaeLLo approved these changes

2023-05-31 07:40 UTC, oscard0m commented
Is this ready to merge?

2023-05-31 07:45 UTC, SaeLLo approved these changes

2023-06-01 07:20 UTC, merged