feat(blog): open-source Experimental Branding Templates
mainmatter/mainmatter.com pull request #2053
Opened 2023-05-25 14:17 UTC by oscard0m

2023-05-30 10:59 UTC, marcoow reviewed
Nice post 👍 

I think the intro is not straight forward to follow for someone who doesn't know we have 20% time though.

Also, it'd need to be reviewed for grammar and typography before release

2023-05-30 10:59 UTC, marcoow commented on src/posts/2023-05-24-open-source-experimental-branding-templates.md
> +image: "/assets/images/posts/2023-05-24-open-source-experimental-branding-templates/header-illustration.jpg"
let's not mix Mainmatter and any personal/private brands

2023-05-30 10:59 UTC, marcoow commented on src/posts/2023-05-24-open-source-experimental-branding-templates.md
> +  <p>For the first hearing, it was surprising and challenging how a visual designer can start open-source projects. As an applied art service provider ~ ex freelancer, everything started with a clien
I think you need to provide some context here, explaining that Mainmatter has 20% time which also applies to a designer, etc.

**Update:** I see that comes at the end – I think it'd make sense to reverse the order

2023-05-30 10:59 UTC, marcoow commented on src/posts/2023-05-24-open-source-experimental-branding-templates.md
> +  <p>For the first hearing, it was surprising and challenging how a visual designer can start open-source projects. As an applied art service provider ~ ex freelancer, everything started with a clien
```suggestion
  <p>For the first hearing, it was surprising and challenging how a visual designer can start open-source projects. As an applied art service provider/ex freelancer, everything started with a client or project requirements and the number of projects that I did for myself just for fun was significantly shrinking, especially as a beginner father. At Mainmatter everyone spends 20% of their time as an active member of the open-source community, so I had to find a solution.</p>
```

2023-05-30 10:59 UTC, marcoow commented on src/posts/2023-05-24-open-source-experimental-branding-templates.md
> +solution for’. Instead of this, I thought what if turn the whole process upside
```suggestion
I assume - "Let’s imagine a fictional client or project that I have to find a
solution for". Instead of this, I thought what if turn the whole process upside
```

2023-05-30 10:59 UTC, marcoow commented on src/posts/2023-05-24-open-source-experimental-branding-templates.md
> +strange but well-designed font I've ever seen called ‘Nabla’. I knew I have to
```suggestion
strange but well-designed font I've ever seen called "Nabla". I knew I have to
```

2023-05-30 10:59 UTC, marcoow commented on src/posts/2023-05-24-open-source-experimental-branding-templates.md
> +offer these as open-source projects.
might make sense to put these in a GitHub repo…

2023-05-30 15:01 UTC, davidhajba commented on src/posts/2023-05-24-open-source-experimental-branding-templates.md
> +  <p>For the first hearing, it was surprising and challenging how a visual designer can start open-source projects. As an applied art service provider ~ ex freelancer, everything started with a clien
@oscard0m 

could you pls update this paragraph;

At Mainmatter everyone spends 20% of their time as an active member of the open-source community. For the first hearing, it was surprising and challenging how a visual designer can start these kinds of projects. As an applied art service provider ~ ex freelancer, everything started with client or project requirements and the number of projects that I did for myself just for fun was significantly shrinking, especially as a beginner father.

2023-05-30 15:16 UTC, marcoow commented on src/posts/2023-05-24-open-source-experimental-branding-templates.md
> +  <p>For the first hearing, it was surprising and challenging how a visual designer can start open-source projects. As an applied art service provider ~ ex freelancer, everything started with a clien
I think this is a great opportunity for @davidhajba to learn how to do this himself using https://desktop.github.com

2023-05-31 08:07 UTC, davidhajba commented on src/posts/2023-05-24-open-source-experimental-branding-templates.md
> +image: "/assets/images/posts/2023-05-24-open-source-experimental-branding-templates/header-illustration.jpg"
sure, I understand
can you please confirm [THIS](https://www.sketch.com/s/066e539c-c206-4261-aafb-9634ab577579/a/3onxgLd#Version) cover image idea?

2023-05-31 08:27 UTC, davidhajba commented on src/posts/2023-05-24-open-source-experimental-branding-templates.md
> +  <p>For the first hearing, it was surprising and challenging how a visual designer can start open-source projects. As an applied art service provider ~ ex freelancer, everything started with a clien
I'm happy to learn all new things and improve myself 👌

Please make a hierarchy between animation and desktop.github.com and I will start with it in my 20% time.
I'm super busy in my regular days and these all requires full attention, my private time is absolutely full with family.

Please consider that, I feel physical pain and suffering when I have to code something, that's why I became a visual designer. Despite it would be a terrible torture, I'm not against to learn anything new. Probably it would have negative effect to all my other design works.

2023-05-31 09:34 UTC, davidhajba commented on src/posts/2023-05-24-open-source-experimental-branding-templates.md
> +  <p>For the first hearing, it was surprising and challenging how a visual designer can start open-source projects. As an applied art service provider ~ ex freelancer, everything started with a clien
I understand for you it can seem an easy task to write a blogpost in desktop.github.com and you want people to work independently. 
Please understand that, for me to start to work with a tool which is code based is terrifying / out of my interest .

We discussed with @oscard0m the current blogpost procedure is not for non dev people,
if there would be some template where I have to replace titles, body text, images I can absolutely do this.

2023-05-31 09:46 UTC, marcoow commented on src/posts/2023-05-24-open-source-experimental-branding-templates.md
> +image: "/assets/images/posts/2023-05-24-open-source-experimental-branding-templates/header-illustration.jpg"
sure, that seems fine 👍

2023-05-31 09:47 UTC, marcoow commented on src/posts/2023-05-24-open-source-experimental-branding-templates.md
> +  <p>For the first hearing, it was surprising and challenging how a visual designer can start open-source projects. As an applied art service provider ~ ex freelancer, everything started with a clien
I'm sure you can work with that – the template is previous blog posts

2023-05-31 10:24 UTC, davidhajba commented on src/posts/2023-05-24-open-source-experimental-branding-templates.md
> +  <p>For the first hearing, it was surprising and challenging how a visual designer can start open-source projects. As an applied art service provider ~ ex freelancer, everything started with a clien
I saw on screen sharing how Oscar did it and it was way too complex to do it without dev experience.
@oscard0m could you please share your experience too?

I'm happy to start learning animation, although it was not in a focus of my interest, but it's not far from my profession and if you need it of course, let's do it.

Web development is exactly the opposite of my interest and I never said I will take any steps to this direction.

I really hope I can be appreciated for what can I do, which is quite a lot and I do it on high level.
I'm also happy of course to improve myself around my profession.

2023-06-01 12:30 UTC, emmasofiah2o commented on src/posts/2023-05-24-open-source-experimental-branding-templates.md
> +  <p>For the first hearing, it was surprising and challenging how a visual designer can start open-source projects. As an applied art service provider ~ ex freelancer, everything started with a clien
@davidhajba I'll show you on Monday as we discussed, but just so you know, you won't really need any coding knowledge to work on your blog post. It's just like editing a text file really :)

2023-06-01 12:30 UTC, emmasofiah2o commented on src/posts/2023-05-24-open-source-experimental-branding-templates.md
> +  <p>For the first hearing, it was surprising and challenging how a visual designer can start open-source projects. As an applied art service provider ~ ex freelancer, everything started with a clien
Also, I'll review your blog post for grammar and typos this week so that we can post it soon

2023-06-02 10:00 UTC, emmasofiah2o requested changes
Hi @davidhajba. I have just finished reviewing your post. It was very interesting and I think you explained your ideas well, but I had to re-write a lot of sentences to make them more readable :). The structure is good also so I would only "commit the suggestion" (I'll explain what this does on our call Monday) and then further modify if you need to.

2023-06-02 10:00 UTC, emmasofiah2o commented on src/posts/2023-05-24-open-source-experimental-branding-templates.md
> +  <p>For the first hearing, it was surprising and challenging how a visual designer can start open-source projects. As an applied art service provider/ex freelancer, everything started with a client
I'm not sure what "for the first hearing" means in this context. Can you pls explain so I can formulate this better?

2023-06-02 10:00 UTC, emmasofiah2o commented on src/posts/2023-05-24-open-source-experimental-branding-templates.md
> +After getting used to rules and requirements everywhere at first it was kind of
```suggestion
After getting used to rules and requirements, at first it felt kind of
```

2023-06-02 10:00 UTC, emmasofiah2o commented on src/posts/2023-05-24-open-source-experimental-branding-templates.md
> +strange to have all the freedom of the world - I can do anything I want until
```suggestion
strange to have all the freedom of the world - I can do anything I want as long as
```

2023-06-02 10:00 UTC, emmasofiah2o commented on src/posts/2023-05-24-open-source-experimental-branding-templates.md
> +Among my expertise Branding and Ui/Ux seemed the best direction to start
```suggestion
Among the fields I have experience in, Branding and UI/UX seemed the best choice for starting a new open-source project. 
```

2023-06-02 10:00 UTC, emmasofiah2o commented on src/posts/2023-05-24-open-source-experimental-branding-templates.md
> +solution for". Instead of this, I thought what if turn the whole process upside
```suggestion
solution for". Instead of this, I thought: "What if I turn the whole process upside
```

2023-06-02 10:00 UTC, emmasofiah2o commented on src/posts/2023-05-24-open-source-experimental-branding-templates.md
> +down and create something based on my gut feelings, combine surprising elements
```suggestion
down and create something based on my gut feelings, combining surprise elements
```

2023-06-02 10:00 UTC, emmasofiah2o commented on src/posts/2023-05-24-open-source-experimental-branding-templates.md
> +together as a montage, that is functional meanwhile, and see what comes out of
```suggestion
together and see what comes out? "
```

2023-06-02 10:00 UTC, emmasofiah2o commented on src/posts/2023-05-24-open-source-experimental-branding-templates.md
> +it? Why not?
```suggestion

```

2023-06-02 10:00 UTC, emmasofiah2o commented on src/posts/2023-05-24-open-source-experimental-branding-templates.md
> +The first concept became boring (I won't show it to anybody) I became a bit
```suggestion
The first concept quickly turned boring and I started feeling a bit
```

2023-06-02 10:00 UTC, emmasofiah2o commented on src/posts/2023-05-24-open-source-experimental-branding-templates.md
> +skeptical about my idea. But instead of giving up, I realized what I want.
```suggestion
skeptical about my idea. But instead of giving up, that brought me closer to what I really wanted.
```

2023-06-02 10:00 UTC, emmasofiah2o commented on src/posts/2023-05-24-open-source-experimental-branding-templates.md
> +I was searching between Google fonts when I found the most ridiculous and
```suggestion
I was searching among Google fonts when I found the most ridiculous but
```

2023-06-02 10:00 UTC, emmasofiah2o commented on src/posts/2023-05-24-open-source-experimental-branding-templates.md
> +strange but well-designed font I've ever seen called "Nabla". I knew I have to
```suggestion
well-designed font I've ever seen, called "Nabla". I knew I had to
```

2023-06-02 10:00 UTC, emmasofiah2o commented on src/posts/2023-05-24-open-source-experimental-branding-templates.md
> +start something with this, let's see if it is even usable for anything or if it
```suggestion
start something with it.
```

2023-06-02 10:00 UTC, emmasofiah2o commented on src/posts/2023-05-24-open-source-experimental-branding-templates.md
> +is only a joke. I don’t think I've ever would suggest this to a client in a real
```suggestion
I don’t think I would ever suggest using a similar font to a client in a real-world
```

2023-06-02 10:00 UTC, emmasofiah2o commented on src/posts/2023-05-24-open-source-experimental-branding-templates.md
> +situation, so here is the time to find out if it is good for something. This was
```suggestion
situation, so this project was the perfect opportunity to experiment with it.
```

2023-06-02 10:00 UTC, emmasofiah2o commented on src/posts/2023-05-24-open-source-experimental-branding-templates.md
> +the point when things became interesting. I started to combine the font with
```suggestion

Here things became interesting: I started to combine the font with
```

2023-06-02 10:00 UTC, emmasofiah2o commented on src/posts/2023-05-24-open-source-experimental-branding-templates.md
> +beautiful cloud illustrations, and soft and warm color tones and kept the
```suggestion
captivating cloud illustrations, focusing on using soft and warm color tones while maintaining the
```

2023-06-02 10:00 UTC, emmasofiah2o commented on src/posts/2023-05-24-open-source-experimental-branding-templates.md
> +balance with Circular Std font which is a wonderful quality font with strong
```suggestion
balance with the Circular Std font, which has a strong
```

2023-06-02 10:00 UTC, emmasofiah2o commented on src/posts/2023-05-24-open-source-experimental-branding-templates.md
> +geometric types.
```suggestion
geometric typeface.
```

2023-06-02 10:00 UTC, emmasofiah2o commented on src/posts/2023-05-24-open-source-experimental-branding-templates.md
> +Based on the overall impression I decided to use some professional Chinese
```suggestion
Based on the overall impression I was getting from the design, I decided to use some professional Chinese
```

2023-06-02 10:00 UTC, emmasofiah2o commented on src/posts/2023-05-24-open-source-experimental-branding-templates.md
> +street photography which was super hard to find, but after hours of searching
```suggestion
street photography. It was hard to find exactly what I was looking for, but after hours of searching through seas of stock photos, I finally came across the perfect pictures for this project.
```

2023-06-02 10:00 UTC, emmasofiah2o commented on src/posts/2023-05-24-open-source-experimental-branding-templates.md
> +stock photography, I found what I was looking for. After this it was obvious to
```suggestion
These naturally led me into
```

2023-06-02 10:00 UTC, emmasofiah2o commented on src/posts/2023-05-24-open-source-experimental-branding-templates.md
> +try some traditional Chinese typography (what I never did before), it was very
```suggestion
trying some traditional Chinese typography (which I never did before). It was very
```

2023-06-02 10:00 UTC, emmasofiah2o commented on src/posts/2023-05-24-open-source-experimental-branding-templates.md
> +satisfying and mega fun. I'm quite happy with the overall result, can be ideal
```suggestion
satisfying and lots of fun. 

I'm quite happy with the overall result and I believe it would look great
```

2023-06-02 10:00 UTC, emmasofiah2o commented on src/posts/2023-05-24-open-source-experimental-branding-templates.md
> +for a fashion brand with a young target group for the Chinese market, or any
```suggestion
for a fashion brand with a young target group within the Chinese market, or any
```

2023-06-02 10:00 UTC, emmasofiah2o commented on src/posts/2023-05-24-open-source-experimental-branding-templates.md
> +other market with some strong connection to China.
```suggestion
other market with a strong connection to China.
```

2023-06-02 10:00 UTC, emmasofiah2o commented on src/posts/2023-05-24-open-source-experimental-branding-templates.md
> +Berlin is an amazing inspiration for creative people even a poster on the street
```suggestion
Berlin is a costant inspiration for creative people. Even a poster on the street
```

2023-06-02 10:00 UTC, emmasofiah2o commented on src/posts/2023-05-24-open-source-experimental-branding-templates.md
> +can be a good start of something great, this is how Concept 2 was born. I
```suggestion
can turn into something great: this is how Concept 2 was born. 
I
```

2023-06-02 10:00 UTC, emmasofiah2o commented on src/posts/2023-05-24-open-source-experimental-branding-templates.md
> +​The Larken font immediately seemed a good combination here, I remembered for if
```suggestion
​The Larken font immediately seemed a good fit here. I remembered this font
```

2023-06-02 10:00 UTC, emmasofiah2o commented on src/posts/2023-05-24-open-source-experimental-branding-templates.md
> +from the past, it is a very special bohemian, font between modern and classical,
```suggestion
from the past work: it is a very special bohemian font, between modern and classic,
```

2023-06-02 10:00 UTC, emmasofiah2o commented on src/posts/2023-05-24-open-source-experimental-branding-templates.md
> +elegant and crazy. Fits just perfectly. The brutal geometric shapes required
```suggestion
elegant and crazy. 
The brutal geometric shapes required
```

2023-06-02 10:00 UTC, emmasofiah2o commented on src/posts/2023-05-24-open-source-experimental-branding-templates.md
> +some smaller details for balance, I found a package with interesting bug
```suggestion
some smaller details for balance so I found a package with some interesting bugs
```

2023-06-02 10:00 UTC, emmasofiah2o commented on src/posts/2023-05-24-open-source-experimental-branding-templates.md
> +illustrations which I modified to make all the bugs symmetrical to fit better in
```suggestion
illustrations which I modified to make them symmetrical and complement
```

2023-06-02 10:00 UTC, emmasofiah2o commented on src/posts/2023-05-24-open-source-experimental-branding-templates.md
> +the concept. This idea has quite versatile usage of course the illustration
```suggestion
the concept better. 

This idea has a quite versatile usage and of course the illustration
```

2023-06-02 10:00 UTC, emmasofiah2o commented on src/posts/2023-05-24-open-source-experimental-branding-templates.md
> +package can be changed to match specific cases.
```suggestion
package can be changed to match specific contexts.
```

2023-06-02 10:00 UTC, emmasofiah2o commented on src/posts/2023-05-24-open-source-experimental-branding-templates.md
> +never had a chance to do, so Concept 4 seemed just the perfect time for it.
```suggestion
never had the chance to. Concept 4 seemed just the perfect time to experiment with them.
```

2023-06-02 10:00 UTC, emmasofiah2o commented on src/posts/2023-05-24-open-source-experimental-branding-templates.md
> +After finding the ‘Rama Gothic C’ font which I considered the most well-designed
```suggestion
After finding the ‘Rama Gothic C’ font which I considered the best designed
```

2023-06-02 10:00 UTC, emmasofiah2o commented on src/posts/2023-05-24-open-source-experimental-branding-templates.md
> +in this category, started to test different concepts and how can I make the best
```suggestion
in this category, I started to test different concepts.
```

2023-06-02 10:00 UTC, emmasofiah2o commented on src/posts/2023-05-24-open-source-experimental-branding-templates.md
> +out of it. It turned out a slideshow-style website combines colorful surfaces
```suggestion
My idea quickly turned into a slideshow-style website combining colorful surfaces
```

2023-06-02 10:00 UTC, emmasofiah2o commented on src/posts/2023-05-24-open-source-experimental-branding-templates.md
> +with typography playfulness and amazing monochrome photography with
```suggestion
with typography playfulness, and wonderful monochrome photography with
```

2023-06-02 10:00 UTC, emmasofiah2o commented on src/posts/2023-05-24-open-source-experimental-branding-templates.md
> +center-aligned overlay color circles, highlighting some important parts of the
```suggestion
center-aligned overlay color circles, highlighting important parts of the
```

2023-06-02 10:00 UTC, emmasofiah2o commented on src/posts/2023-05-24-open-source-experimental-branding-templates.md
> +image. I will be curious to try further different concepts with the ‘Rama Gothic
```suggestion
image. 
```

2023-06-02 10:00 UTC, emmasofiah2o commented on src/posts/2023-05-24-open-source-experimental-branding-templates.md
> +C’ font.
```suggestion
```

2023-06-02 10:00 UTC, emmasofiah2o commented on src/posts/2023-05-24-open-source-experimental-branding-templates.md
> +It was very useful for me to experience the freedom of the creation of ‘Branding
```suggestion
It was very valuable for me to experience the freedom of creating Branding
```

2023-06-02 10:00 UTC, emmasofiah2o commented on src/posts/2023-05-24-open-source-experimental-branding-templates.md
> +templates’ without any rules or requirements and it’s strongly motivating to
```suggestion
templates without any rules or requirements and it has surely motivated me to
```

2023-06-02 10:00 UTC, emmasofiah2o commented on src/posts/2023-05-24-open-source-experimental-branding-templates.md
> +suggest braver and more outstanding elements in real-life projects as well. I
```suggestion
suggest braver and more outstanding elements in real-life projects as well. 
I
```

2023-06-02 10:00 UTC, emmasofiah2o commented on src/posts/2023-05-24-open-source-experimental-branding-templates.md
> +hope these templates will be just as much useful and fun to work with - or
```suggestion
hope these templates will be just as useful and fun to work with - or
```

2023-06-02 10:00 UTC, emmasofiah2o commented on src/posts/2023-05-24-open-source-experimental-branding-templates.md
> +implement further - for the designer community, as it was for me. I’d gladly
```suggestion
implement further - for the designer community, as it was for me to create them. 
```

2023-06-02 10:00 UTC, emmasofiah2o commented on src/posts/2023-05-24-open-source-experimental-branding-templates.md
> +offer these as open-source projects.
```suggestion
```

2023-06-02 10:00 UTC, emmasofiah2o commented on src/posts/2023-05-24-open-source-experimental-branding-templates.md
> +something with and the idea came quickly, I can be useful for the designer
```suggestion
The idea came quickly: I decided to create Branding and UI/UX Templates for fellow designers. In the past months, I have dedicated one day of my work week, my "20% time", to the conception and realization of this project and I will be showcasing the results in this post.
```

2023-06-02 10:00 UTC, emmasofiah2o commented on src/posts/2023-05-24-open-source-experimental-branding-templates.md
> +community using my 20% time for creating inspiration, and free to use Branding -
```suggestion
```

2023-06-02 10:00 UTC, emmasofiah2o commented on src/posts/2023-05-24-open-source-experimental-branding-templates.md
> +Ui/Ux Template projects that can be also developed further.
```suggestion
```

2023-06-02 10:01 UTC, emmasofiah2o requested changes
Hi @davidhajba. I have just finished reviewing your post. It was very interesting and I think you explained your ideas well, but I had to re-write a lot of sentences to make them more readable :). The structure is good also so I would only "commit the suggestion" (I'll explain what this does on our call Monday) and then further modify if you need to.

2023-06-05 12:28 UTC, emmasofiah2o commented on src/posts/2023-05-24-open-source-experimental-branding-templates.md
> +offer these as open-source projects.
The files are already in a shared Google Drive folder, I am not sure if we can create a repository with sketch files, but I am also not familiar with what type of files are accepted there :D

2023-06-05 13:28 UTC, davidhajba commented on src/posts/2023-05-24-open-source-experimental-branding-templates.md
> +  <p>For the first hearing, it was surprising and challenging how a visual designer can start open-source projects. As an applied art service provider/ex freelancer, everything started with a client
I meant 'when I first heard about this' in Hungary we say 'for the first hearing' maybe it's not a proper translation, what do you think, how would you translate?

2023-06-13 09:50 UTC, emmasofiah2o commented on src/posts/2023-05-24-open-source-experimental-branding-templates.md
> +  <p>For the first hearing, it was surprising and challenging how a visual designer can start open-source projects. As an applied art service provider/ex freelancer, everything started with a client
```suggestion
  <p>How can a visual designer work and collaborate on open-source projects? As an applied art service provider/ex-freelancer, my projects always started with a client and project requirements. The number of projects I did for myself just for fun was significantly shrinking, especially since becoming a first-time father. At Mainmatter everyone spends 20% of their time as an active member of the open-source community, so I had to find a way.</p>
```

2023-06-14 06:58 UTC, davidhajba commented
hey @emmasofiah2o 
I can see the old cover -Marco asked to change- is it only on my side ?
[THIS](https://www.sketch.com/s/066e539c-c206-4261-aafb-9634ab577579/a/3onxgLd) should be the new one, could you please check ?

2023-06-15 08:21 UTC, emmasofiah2o commented
@marcoow can I merge this? I see you have a few open comments that came before my review

2023-06-15 08:23 UTC, emmasofiah2o commented
> hey @emmasofiah2o I can see the old cover -Marco asked to change- is it only on my side ? [THIS](https://www.sketch.com/s/066e539c-c206-4261-aafb-9634ab577579/a/3onxgLd) should be the new one, could you please check ?

You can see the cover image if you scroll down on files changes. It is updated :)

2023-06-15 08:26 UTC, davidhajba commented
@emmasofiah2o 

yes, I see, thank you 🎉

2023-06-15 11:08 UTC, marcoow approved these changes
just some grammar things in the description

2023-06-15 11:08 UTC, marcoow commented on src/posts/2023-06-15-open-source-experimental-branding-templates.md
> +  the journey & experience"
```suggestion
  "David Hajba, senior visual/product designer at Mainmatter created
  open source experimental branding templates. In this blog post, he talks about
  the journey & experience"
```

2023-06-15 11:08 UTC, marcoow commented on src/posts/2023-06-15-open-source-experimental-branding-templates.md
> +  purple/salmon color geometrical abstract background"
```suggestion
  "a large white geometrical shape of a bug on a purple/salmon color geometrical abstract background"
```

2023-06-16 07:44 UTC, emmasofiah2o approved these changes

2023-06-16 08:52 UTC, merged