Blog post: From React to Ember - Building a Personal Website/Blog
mainmatter/mainmatter.com pull request #2057
Opened 2023-06-02 14:02 UTC by inesilva

A blog post about the website I built with Ember, with the guidance of Chris.
I explain the process with some of the challenges and how I overcame them. I compare some development differences I found between Ember and React. In the end, I also leave my opinion on having a personal website/blog and tips for someone that might want to create their blog.

2023-06-05 09:00 UTC, marcoow reviewed
Nice post - well written!

Some things aren't quite correct I think but overall pretty cool :raised_hands:

2023-06-05 09:00 UTC, marcoow commented on src/posts/2023-05-28-from-react-to-ember-building-a-blog.md
> +my working in my working colleague, Chris. From that day forward, we began
```suggestion
my working colleague, Chris. From that day forward, we began
```

2023-06-05 09:00 UTC, marcoow commented on src/posts/2023-05-28-from-react-to-ember-building-a-blog.md
> +who hadn't experienced working with Ember. This sparked my curiosity to know at
```suggestion
who didn't have experience working with Ember. This sparked my curiosity to know at
```

2023-06-05 09:00 UTC, marcoow commented on src/posts/2023-05-28-from-react-to-ember-building-a-blog.md
> +    - **Component** is a class from the Glimmer library (DOM rendering engine
```suggestion
    - `Component` is a class from the Glimmer library (DOM rendering engine
```

?

2023-06-05 09:00 UTC, marcoow commented on src/posts/2023-05-28-from-react-to-ember-building-a-blog.md
> +      developer can extend to create their own reusable components.
Typically now, you're using functional components in React now so there is no `Component` base class anymore

2023-06-05 09:00 UTC, marcoow commented on src/posts/2023-05-28-from-react-to-ember-building-a-blog.md
> +    - `{action}` is a method coming from @ember/object module. It is Ember's own
```suggestion
    - `{action}` is a method coming from the `@ember/object` module. It is Ember's own
```

2023-06-05 09:00 UTC, marcoow commented on src/posts/2023-05-28-from-react-to-ember-building-a-blog.md
> +      ?`dropdown()` function that gets trigger when the user clicks on the
```suggestion
      `dropdown()` function that gets trigger when the user clicks on the
```

2023-06-05 09:00 UTC, marcoow commented on src/posts/2023-05-28-from-react-to-ember-building-a-blog.md
> +      normally plain js objects.
The reason isn't object but the fact that you can use regular functions as event handlers directly.

2023-06-05 09:00 UTC, marcoow commented on src/posts/2023-05-28-from-react-to-ember-building-a-blog.md
> +      @glimmer/tracking. This is a module provided by glimmer framework that
```suggestion
      `@glimmer/tracking`. This is a module provided by glimmer framework that
```

2023-06-05 09:00 UTC, marcoow commented on src/posts/2023-05-28-from-react-to-ember-building-a-blog.md
> +      useState hook. In my website this translates to - whenever a user clicks
```suggestion
      `useState` hook. In my website this translates to - whenever a user clicks
```

2023-06-05 09:00 UTC, marcoow commented on src/posts/2023-05-28-from-react-to-ember-building-a-blog.md
> +   [**Broccoli-Static-Site-Json.**](**https://www.npmjs.com/package/broccoli-static-site-json**)
```suggestion
   [**Broccoli-Static-Site-Json.**](https://www.npmjs.com/package/broccoli-static-site-json)
```

2023-06-05 09:00 UTC, marcoow commented on src/posts/2023-05-28-from-react-to-ember-building-a-blog.md
> +   Why? The browser was adding a hash to my photo sources, e.g - from
It's not the browser adding the fingerprints – it's Ember

2023-06-05 09:00 UTC, marcoow commented on src/posts/2023-05-28-from-react-to-ember-building-a-blog.md
> +there, but if I would write down a specific URL, it won't know how to handle it.
What's happening is when you're requesting a path like `/blog/post` from the webserver, the server won't find a file at the specified path and responds with a 404. I think it could help to be a bit more explicit about this here.

2023-06-05 09:00 UTC, marcoow commented on src/posts/2023-05-28-from-react-to-ember-building-a-blog.md
> +2. If we want to keep this a SPA - we tell Netlify to give us the index.html
> If we want to keep this a SPA

It's an SPA either way – this is just about the initial route that gets loaded when you make the first request to the app. All subsequent requests are handled in the browser SPA-style either way.

2023-06-05 10:48 UTC, emmasofiah2o commented
@inesilva could you please ping me once you have gone through Marco's suggestions? That way I don't double-review things he might have already corrected :D

2023-06-06 15:51 UTC, inesilva commented on src/posts/2023-05-28-from-react-to-ember-building-a-blog.md
> +2. If we want to keep this a SPA - we tell Netlify to give us the index.html
here I meant compared to the 1st solution (that doesn't follow a SPA approach). If we want to keep SPA logic, we opt for the second way. I will drop it, it is not important and I guess it is not clear.

2023-06-06 16:04 UTC, inesoaresilva commented on src/posts/2023-05-28-from-react-to-ember-building-a-blog.md
> +    - **Component** is a class from the Glimmer library (DOM rendering engine
This question mark is about my definition of Component from Glimmer? Is it wrong?

2023-06-06 16:05 UTC, inesilva commented
> @inesilva could you please ping me once you have gone through Marco's suggestions? That way I don't double-review things he might have already corrected :D

Hey Emma, I just applied Marco's feedback

2023-06-07 07:34 UTC, marcoow approved these changes

2023-06-07 09:59 UTC, emmasofiah2o commented
> > @inesilva could you please ping me once you have gone through Marco's suggestions? That way I don't double-review things he might have already corrected :D
> 
> Hey Emma, I just applied Marco's feedback

Thank you, I'll go through it as well this week :)

2023-06-07 11:53 UTC, mansona approved these changes
Amazing 😍 I love it! I've added a few comments, at least one of them is just an opinion so don't feel the need to accept them all 👍

2023-06-07 11:53 UTC, mansona commented on src/posts/2023-05-28-from-react-to-ember-building-a-blog.md
> +rendering efficently my photos was my big issue._
```suggestion
rendering my photos efficiently was my big issue._
```

2023-06-07 11:53 UTC, mansona commented on src/posts/2023-05-28-from-react-to-ember-building-a-blog.md
> +  was a new keyword for me as well. This was a new keyword for me as well. The
```suggestion
- Then I have a `<div>` that will receive {% raw %}`{{yield}}`{% endraw %}. This was a new keyword for me as well. The
```
Just a duplicate sentence 👍

2023-06-07 11:53 UTC, mansona commented on src/posts/2023-05-28-from-react-to-ember-building-a-blog.md
> +      button. In React, we can use regular functions as event handlers directly.
So this is a bit of a tricky one. You use regular functions in ember too without any issue, the only reason we need to use `@action` in this context is because we are using `this` in the function and it needs to bind the Glimmer Template context to the context of the class. Nowadays you can think of `@action` in the same way you would use `bind` in Javascript but I don't know if that is a helpful analogy 😂

2023-06-07 11:53 UTC, mansona commented on src/posts/2023-05-28-from-react-to-ember-building-a-blog.md
> +    - `{action}` is a method coming from the `@ember/object` module. It is Ember's own
this is a decorator so I think it might be good to call it a decorator instead of a method 🤔 

```suggestion
    - `{action}` is a decorator coming from the `@ember/object` module. It is Ember's own
```

2023-06-07 11:53 UTC, mansona commented on src/posts/2023-05-28-from-react-to-ember-building-a-blog.md
> +   This addon converts my markdown into readable HTLM objects, so I don’t need
```suggestion
   This addon converts my markdown into HTML, so I don’t need
```

2023-06-07 11:53 UTC, mansona commented on src/posts/2023-05-28-from-react-to-ember-building-a-blog.md
> +   Now that I have them defined, I need to tell broccoli addon what attributes
```suggestion
   Now that I have them defined, I need to tell the broccoli addon what attributes
```

2023-06-07 11:53 UTC, mansona commented on src/posts/2023-05-28-from-react-to-ember-building-a-blog.md
> +   adds it to your project):
```suggestion
   Let’s add that in `/lib/content-generator/index.js` (an in-repo Ember addon that you can use to add broccoli-static-site-json to your project):
```
I kinda feel bad suggesting this 🙈 it's a bit more correct but probably a bit too much detail

2023-06-07 11:53 UTC, mansona commented on src/posts/2023-05-28-from-react-to-ember-building-a-blog.md
> +   Additionally, I utilize the last configuration variable, which allows me to
```suggestion
   Additionally, I utilize the last configuration variable, `collate`, which allows me to
```

2023-06-07 11:53 UTC, mansona commented on src/posts/2023-05-28-from-react-to-ember-building-a-blog.md
> +If you want to check my internet corner you can access
```suggestion
If you want to check my internet corner you can access it 
```

2023-06-07 16:03 UTC, inesoaresilva commented on src/posts/2023-05-28-from-react-to-ember-building-a-blog.md
> +      button. In React, we can use regular functions as event handlers directly.
which class  - 'context of the class' ?

2023-06-07 16:08 UTC, inesoaresilva commented on src/posts/2023-05-28-from-react-to-ember-building-a-blog.md
> +   adds it to your project):
but it is still a file coming from the addon, right? Would this sentence be correct? a file coming from the in-repo Ember addon that you can use to add broccoli-static-site-json to your project

2023-06-07 16:33 UTC, mansona commented on src/posts/2023-05-28-from-react-to-ember-building-a-blog.md
> +      button. In React, we can use regular functions as event handlers directly.
the Dropdown class in `dropdown.js` essentially the underlying code needs to have some hint that it needs to bind `this` to the instance of the `Dropdown` class so the function has the right `this` when being called from a template.

I'm sure someone else could do a better job of explaining this 🙈 maybe we could call about it?

2023-06-07 16:35 UTC, mansona commented on src/posts/2023-05-28-from-react-to-ember-building-a-blog.md
> +   adds it to your project):
yes that's correct 👍

2023-06-09 08:58 UTC, emmasofiah2o commented
@inesilva sorry about the delay on the review - I see Chris has left comments as well so I'd say I'll wait until you have worked through them to avoid double corrections or conflicting suggestions :)

2023-06-16 13:14 UTC, inesilva commented on src/posts/2023-05-28-from-react-to-ember-building-a-blog.md
> +      button. In React, we can use regular functions as event handlers directly.
Ok, I added more detail to this explanation. Can you tell me if you think this new explanation is correct?

2023-06-16 14:15 UTC, inesilva commented
> @inesilva sorry about the delay on the review - I see Chris has left comments as well so I'd say I'll wait until you have worked through them to avoid double corrections or conflicting suggestions :)

Hey Emma, I applied them

2023-06-19 11:16 UTC, emmasofiah2o requested changes
I left a few comments. This was well-written and easy to understand. I would re-formulate a couple of sentences in the conclusion to make it clearer.

2023-06-19 11:16 UTC, emmasofiah2o commented on src/posts/2023-05-28-from-react-to-ember-building-a-blog.md
> +  features, the challenges she faced and she how overcame them. At the same
```suggestion
  features, the challenges she faced, and how she overcame them. At the same
```

2023-06-19 11:16 UTC, emmasofiah2o commented on src/posts/2023-05-28-from-react-to-ember-building-a-blog.md
> +  <p>Having a personal website/blog has been on my to-do list for quite some time, but I always found myself stuck when answering the question, 'How do I start?' With countless frameworks and differe
```suggestion
  <p>Having a personal website/blog has been on my to-do list for quite some time, but I always found myself stuck when answering the question: "How do I start?". With countless frameworks and different tech stacks to choose from, the options seemed overwhelming. I've been working with React since I joined the company, but most of my colleagues are experts in Ember, so I wanted to learn more about it. I decided to use this project as an opportunity to do that.
```

2023-06-19 11:16 UTC, emmasofiah2o commented on src/posts/2023-05-28-from-react-to-ember-building-a-blog.md
> +  I will share my journey, detailing the challenges I encountered and how I overcame them while comparing the development process between Ember and React.</p>
```suggestion
  I will share my journey, including the challenges I encountered and how I overcame them, and compare the development process between Ember and React.</p>
```

2023-06-19 11:16 UTC, emmasofiah2o commented on src/posts/2023-05-28-from-react-to-ember-building-a-blog.md
> +- You would like to create your website/blog (if you decide to use Ember.js
```suggestion
- You would like to create your own website/blog (if you decide to use Ember.js
```

2023-06-19 11:16 UTC, emmasofiah2o commented on src/posts/2023-05-28-from-react-to-ember-building-a-blog.md
> +However, the amount of different tools for creating a website and the fact that
```suggestion
The amount of different tools for creating a website and the fact that
```

2023-06-19 11:16 UTC, emmasofiah2o commented on src/posts/2023-05-28-from-react-to-ember-building-a-blog.md
> +I never have done one on my own was overwhelming me. I shared these dramas with
```suggestion
I had never done one on my own before, felt overwhelming. I shared my issues with
```

2023-06-19 11:16 UTC, emmasofiah2o commented on src/posts/2023-05-28-from-react-to-ember-building-a-blog.md
> +work together on a client project. However, I believe it's fantastic to have the
```suggestion
work together on a client project. I really enjoyed having the
```

2023-06-19 11:16 UTC, emmasofiah2o commented on src/posts/2023-05-28-from-react-to-ember-building-a-blog.md
> +chance to collaborate with someone outside of your usual circle. As the least
```suggestion
chance to collaborate with someone outside of my usual circle. 
As a junior
```

2023-06-19 11:16 UTC, emmasofiah2o commented on src/posts/2023-05-28-from-react-to-ember-building-a-blog.md
> +experienced member of the company, these sessions have proven to be incredibly
```suggestion
developer, these sessions have proven to be incredibly
```

2023-06-19 11:16 UTC, emmasofiah2o commented on src/posts/2023-05-28-from-react-to-ember-building-a-blog.md
> +rendering efficiently my photos was my big issue._
```suggestion
efficiently rendering my photos was my big issue._
```

2023-06-19 11:16 UTC, emmasofiah2o commented on src/posts/2023-05-28-from-react-to-ember-building-a-blog.md
> +who didn't have experience working with Ember. This sparked my curiosity to know
```suggestion
who didn't have experience working with Ember. This sparked my curiosity to learn
```

2023-06-19 11:16 UTC, emmasofiah2o commented on src/posts/2023-05-28-from-react-to-ember-building-a-blog.md
> +Chris has been working with this framework for 10 years, starting those pair
```suggestion
Chris has been working with this framework for 10 years, so starting those pair
```

2023-06-19 11:16 UTC, emmasofiah2o commented on src/posts/2023-05-28-from-react-to-ember-building-a-blog.md
> +programming sessions with him seemed the good moment to start learning Ember.
```suggestion
programming sessions with him seemed like the perfect way to start learning Ember.
```

2023-06-19 11:16 UTC, emmasofiah2o commented on src/posts/2023-05-28-from-react-to-ember-building-a-blog.md
> +To me, this was an important step to kick off the project. It helped me
```suggestion
To me, designing a mockup of the website was an important step to kick off the project. It helped me
```

2023-06-19 11:16 UTC, emmasofiah2o commented on src/posts/2023-05-28-from-react-to-ember-building-a-blog.md
> +would answer _There is no such thing as in Ember. This is just javascript._ 😆)
```suggestion
would answer _There is no such thing as "in Ember". This is just javascript._ 😆)
```

2023-06-19 11:16 UTC, emmasofiah2o commented on src/posts/2023-05-28-from-react-to-ember-building-a-blog.md
> +I mean, from someone coming from React, there was a lot of new stuff going on in
```suggestion
I mean, for someone coming from React, there was a lot of new stuff going on in
```

2023-06-19 11:16 UTC, emmasofiah2o commented on src/posts/2023-05-28-from-react-to-ember-building-a-blog.md
> +how understanding it was the boss level of object-oriented programming. 😂
```suggestion
how it was understanding the boss level of object-oriented programming. 😂
```

2023-06-19 11:16 UTC, emmasofiah2o commented on src/posts/2023-05-28-from-react-to-ember-building-a-blog.md
> +_On a side note, I want to say that this is probably not the most helpful
```suggestion
_Note that this is probably not the most helpful
```

2023-06-19 11:16 UTC, emmasofiah2o commented on src/posts/2023-05-28-from-react-to-ember-building-a-blog.md
> +dropdown component since I can only customize its title. In my case, I ended up
```suggestion
dropdown component since only its title is customizable. In my case, I ended up
```

2023-06-19 11:16 UTC, emmasofiah2o commented on src/posts/2023-05-28-from-react-to-ember-building-a-blog.md
> +  saying to my component that when someone clicks it, run the
```suggestion
  saying to my component to run the
```

2023-06-19 11:16 UTC, emmasofiah2o commented on src/posts/2023-05-28-from-react-to-ember-building-a-blog.md
> +  `dropdown()`function - defined in the _dropdown.js_ file.
```suggestion
  `dropdown()`function - defined in the _dropdown.js_ file on click.
```

2023-06-19 11:16 UTC, emmasofiah2o commented on src/posts/2023-05-28-from-react-to-ember-building-a-blog.md
> +      when I use `this.open` inside of my Dropdown class at the dropdown.js
```suggestion
      when I use `this.open` inside of my Dropdown class in the dropdown.js
```

2023-06-19 11:16 UTC, emmasofiah2o commented on src/posts/2023-05-28-from-react-to-ember-building-a-blog.md
> +      template the right context (`this`) gets passed to it. files React doesn't
I think a piece is missing here after the "."

2023-06-19 11:16 UTC, emmasofiah2o commented on src/posts/2023-05-28-from-react-to-ember-building-a-blog.md
> +    allows me to create a link to a route, the `@model` argument I use, allows
```suggestion
    allows me to create a link to a route, while the `@model` argument, allows
```

2023-06-19 11:16 UTC, emmasofiah2o commented on src/posts/2023-05-28-from-react-to-ember-building-a-blog.md
> +   After giving the shape I wanted for my website, the question for one of the
```suggestion
   After giving the shape I wanted to my website, the question for one of the
```

2023-06-19 11:16 UTC, emmasofiah2o commented on src/posts/2023-05-28-from-react-to-ember-building-a-blog.md
> +   key features was - ‘How do I create a not-so-complicated system that allows
```suggestion
   key features was: "How do I create a not-so-complicated system that allows
```

2023-06-19 11:16 UTC, emmasofiah2o commented on src/posts/2023-05-28-from-react-to-ember-building-a-blog.md
> +   me to publish blog posts?’ ‘Am I going to create HTML pages every time?´
```suggestion
   me to publish blog posts? Am I going to create HTML pages every time?"
```

2023-06-19 11:16 UTC, emmasofiah2o commented on src/posts/2023-05-28-from-react-to-ember-building-a-blog.md
> +   Chris proposed an approach - ‘Let’s create posts using markdown files.’ He
```suggestion
   Chris proposed an approach: "Let’s create posts using markdown files." He
```

2023-06-19 11:16 UTC, emmasofiah2o commented on src/posts/2023-05-28-from-react-to-ember-building-a-blog.md
> +   said we could use this tool - `ember-cli-showdown`.
```suggestion
   said we could use `ember-cli-showdown`.
```

2023-06-19 11:16 UTC, emmasofiah2o commented on src/posts/2023-05-28-from-react-to-ember-building-a-blog.md
> +   This addon converts my markdown into HTLM, so I don’t need to have that
```suggestion
   This addon converts my markdown into HTLM, so I don’t need to do
```

2023-06-19 11:16 UTC, emmasofiah2o commented on src/posts/2023-05-28-from-react-to-ember-building-a-blog.md
> +2. **Combining my posts information with my tool**
```suggestion
2. **Combining my posts information with the tool**
```

2023-06-19 11:16 UTC, emmasofiah2o commented on src/posts/2023-05-28-from-react-to-ember-building-a-blog.md
> +   - I need to define what data will populate my JSON API, to do it, I define a
```suggestion
   - I need to define what data will populate my JSON API and to do it, I define a
```

2023-06-19 11:16 UTC, emmasofiah2o commented on src/posts/2023-05-28-from-react-to-ember-building-a-blog.md
> +   Now that I have them defined, I need to tell the broccoli addon what
```suggestion
   Now that I have that defined, I need to tell the broccoli addon what
```

2023-06-19 11:16 UTC, emmasofiah2o commented on src/posts/2023-05-28-from-react-to-ember-building-a-blog.md
> +   particularly useful when I need to retrieve all posts. Now, let's move on to
```suggestion
   particularly useful when I need to retrieve all posts. 
   Now, let's move on to
```

2023-06-19 11:16 UTC, emmasofiah2o commented on src/posts/2023-05-28-from-react-to-ember-building-a-blog.md
> +because when my markdown is being converted into static JSON each of my
```suggestion
because when my markdown is being converted into static JSON, each of my
```

2023-06-19 11:16 UTC, emmasofiah2o commented on src/posts/2023-05-28-from-react-to-ember-building-a-blog.md
> +told me ‘Write down the minimum features you need to make it functional till you
```suggestion
told me: "Write down the minimum features you need to make it functional till you
```

2023-06-19 11:16 UTC, emmasofiah2o commented on src/posts/2023-05-28-from-react-to-ember-building-a-blog.md
> +deploy it”, this help me prioritise what I really needed, and keep my focus.
```suggestion
deploy it". This help me prioritize what I really needed and keep my focus.
```

2023-06-19 11:16 UTC, emmasofiah2o commented on src/posts/2023-05-28-from-react-to-ember-building-a-blog.md
> +1. Image fingerprinting The photos were not loading on the deployed website.
```suggestion
1. Image fingerprinting 

The photos were not loading on the deployed website.
```

2023-06-19 11:16 UTC, emmasofiah2o commented on src/posts/2023-05-28-from-react-to-ember-building-a-blog.md
> +To handle direct URLs requested to the web server, there are two approaches:
```suggestion
To handle direct URLs requests to the web server, there are two approaches:
```

2023-06-19 11:16 UTC, emmasofiah2o commented on src/posts/2023-05-28-from-react-to-ember-building-a-blog.md
> +Seven months have passed since I released it.
```suggestion
Seven months have passed since I released my new blog.
```

2023-06-19 11:16 UTC, emmasofiah2o commented on src/posts/2023-05-28-from-react-to-ember-building-a-blog.md
> +performance. After running Lighthouse, I saw that my biggest issue was not being
```suggestion
performance. By running Lighthouse, I saw that my biggest issue was not being
```

2023-06-19 11:16 UTC, emmasofiah2o commented on src/posts/2023-05-28-from-react-to-ember-building-a-blog.md
> +efficient when loading my images. I recently added a little reaction button at
```suggestion
efficient when loading my images. 
I recently added a little reaction button at
```

2023-06-19 11:16 UTC, emmasofiah2o commented on src/posts/2023-05-28-from-react-to-ember-building-a-blog.md
> +to ember it wasn't the smoothest transition. I found Ember a bit harder. I guess
```suggestion
to ember wasn't the smoothest transition as I found Ember a bit harder. I guess
```

2023-06-19 11:16 UTC, emmasofiah2o commented on src/posts/2023-05-28-from-react-to-ember-building-a-blog.md
> +every framework has its pros and cons. In React, dealing with component states
```suggestion
every framework has its pros and cons. 
In React, dealing with component states
```

2023-06-19 11:16 UTC, emmasofiah2o commented on src/posts/2023-05-28-from-react-to-ember-building-a-blog.md
> +all these separate files that target the same page can confuse me - controllers,
```suggestion
all these separate files that target the same page can create confusion - controllers,
```

2023-06-19 11:16 UTC, emmasofiah2o commented on src/posts/2023-05-28-from-react-to-ember-building-a-blog.md
> +.js, .hbs. However, some people prefer it. In the end, there is also a
```suggestion
.js, .hbs. However, some people prefer this approach. In the end, choices like these are very subjective.
```

2023-06-19 11:16 UTC, emmasofiah2o commented on src/posts/2023-05-28-from-react-to-ember-building-a-blog.md
> +preference matter.
```suggestion
```

2023-06-19 11:16 UTC, emmasofiah2o commented on src/posts/2023-05-28-from-react-to-ember-building-a-blog.md
> +Regarding the type of project I built - a personal website/blog. I might be If
I am not sure what you mean with this conclusion

2023-06-19 11:16 UTC, emmasofiah2o commented on src/posts/2023-05-28-from-react-to-ember-building-a-blog.md
> +My pieces of advice are: to choose a publishing tool that is easy enough - the
```suggestion
My pieces of advice are: choose a publishing tool that is easy enough - the
```

2023-06-19 11:16 UTC, emmasofiah2o commented on src/posts/2023-05-28-from-react-to-ember-building-a-blog.md
> +keep in mind short posts as well.
```suggestion
keep short posts in mind as well.
```

2023-06-19 11:16 UTC, emmasofiah2o commented on src/posts/2023-05-28-from-react-to-ember-building-a-blog.md
> +website where you can share your work and interests - you can end up meeting
```suggestion
own website where you can share your work and interests - you can end up meeting
```

2023-06-19 11:16 UTC, emmasofiah2o commented on src/posts/2023-05-28-from-react-to-ember-building-a-blog.md
> +more people with the same interests as you and possibly cool work
```suggestion
more people with the same interests as you and possibly initiate cool work
```

2023-06-19 11:18 UTC, emmasofiah2o requested changes
I left a few comments. This was well-written and easy to understand. I would re-formulate a couple of sentences in the conclusion to make it clearer.

2023-06-23 12:57 UTC, inesilva commented on src/posts/2023-05-28-from-react-to-ember-building-a-blog.md
> +how understanding it was the boss level of object-oriented programming. 😂
This will change what I want to express in this sentence. I mean that understanding the 'this' keyword was the boss level. Is it confusing?  I can rephrase it a bit to get more clear.             
"Also, going back to using `this.` keyword brought memories from my university days and
how understanding this concept was the boss level of object-oriented programming." 😂

2023-06-23 13:11 UTC, inesilva commented on src/posts/2023-05-28-from-react-to-ember-building-a-blog.md
> +  saying to my component that when someone clicks it, run the
I would like to keep the mention of the click event. 
If I rephrase to this:
Next, we have {% raw %}`{{on 'click' this.dropdown}}`{% endraw %}, this instructs my app to run the
  `dropdown()`function (defined in the _dropdown.js_ file) after the user clicks on the button.
  how does it sound?

2023-06-23 13:12 UTC, inesilva commented on src/posts/2023-05-28-from-react-to-ember-building-a-blog.md
> +  `dropdown()`function - defined in the _dropdown.js_ file.
I don't think this makes sense

2023-06-23 13:27 UTC, inesilva commented on src/posts/2023-05-28-from-react-to-ember-building-a-blog.md
> +Regarding the type of project I built - a personal website/blog. I might be If
I think some information got lost here 🙈 I will rephrase it.

2023-06-23 13:48 UTC, inesilva commented
> I left a few comments. This was well-written and easy to understand. I would re-formulate a couple of sentences in the conclusion to make it clearer.

I decided to add a new paragraph that makes a recap of the process. I thought it was missing that in the conclusion. Let me know what you think.

"
It was rewarding to learn and use my current knowledge to make a website live
with my personality on it. It felt like decorating a house. 😆

I started by collecting inspiration from other websites. After that, I began sketching how the pages would look on Figma, and only then did I start coding. Having the sketches in the first place helped me in this process, but
keep in mind that it will probably not be pixel-perfect. I also realized that some design choices were harder to implement than I thought, so I kept embracing some improvisation here. 😅"

2023-06-26 13:35 UTC, emmasofiah2o commented
How about: 
"It was rewarding to learn and use my current knowledge to create a website that would match my personality: it felt like decorating a house. 😆

I started by collecting inspiration from other websites, then I sketched how I wanted the pages to look in Figma, and finally, I started coding. Having the sketches in the first place helped me a lot throughout the process although they were not pixel-perfect. I also realized that some design choices were harder to implement than I thought, so I kept embracing some improvisation. 😅"

2023-06-26 15:58 UTC, emmasofiah2o commented on src/posts/2023-05-28-from-react-to-ember-building-a-blog.md
> +title: "From React To Ember: Building a Personal Website/Blog"
```suggestion
title: "From React To Ember: Building a Personal Website"
```

2023-06-30 13:53 UTC, emmasofiah2o approved these changes
Looks good to me. I planned release for next week Monday :)

2023-07-03 08:22 UTC, emmasofiah2o commented
@inesilva final check: can I merge this? :) I have updated the dates. Made a bit of confusion with a commit, but I think I restored everything

2023-07-03 15:19 UTC, merged