Twios 25
mainmatter/mainmatter.com pull request #2066
Opened 2023-06-16 14:23 UTC by emmasofiah2o

Adds This-week-in-os #25.

To-do:
- Sort unknown links

2023-06-16 14:45 UTC, oscard0m commented on src/twios/2023-05-29.md
> +- [oscard0m/openapi] [#1](https://github.com/oscard0m/openapi/pull/1) git diff
We can remove this one

2023-06-16 14:45 UTC, oscard0m commented on src/twios/2023-05-29.md
> +[oscard0m/openapi]: https://github.com/oscard0m/openapi
we can remove this

2023-06-16 14:47 UTC, emmasofiah2o commented on src/twios/2023-05-29.md
> +- [oscard0m/openapi] [#1](https://github.com/oscard0m/openapi/pull/1) git diff
Forever or just for this post?

2023-06-16 16:23 UTC, oscard0m commented on src/twios/2023-05-29.md
> +- [oscard0m/openapi] [#1](https://github.com/oscard0m/openapi/pull/1) git diff
For all the upcoming posts

2023-06-19 08:19 UTC, oscard0m requested changes

2023-06-19 08:19 UTC, oscard0m commented on config/this-week-in-open-source.config.json
> +        "oscard0m/openapi"
```suggestion
```

2023-06-19 10:00 UTC, emmasofiah2o commented
@oscard0m I have committed your suggestion, but I thought you wanted your repo removed?

2023-06-19 10:05 UTC, oscard0m commented
> @oscard0m I have committed your suggestion, but I thought you wanted your repo removed?

Yes. My suggestion removed the repo, right?

2023-06-19 10:11 UTC, emmasofiah2o commented
> > @oscard0m I have committed your suggestion, but I thought you wanted your repo removed?
> 
> Yes. My suggestion removed the repo, right?

No, you removed it from the config file where it was under "exclude". Meaning it is now included :D

2023-06-19 10:47 UTC, oscard0m commented
> > > @oscard0m I have committed your suggestion, but I thought you wanted your repo removed?
> > 
> > 
> > Yes. My suggestion removed the repo, right?
> 
> No, you removed it from the config file where it was under "exclude". Meaning it is now included :D

Ahhh sorry, I did not notice that was the list of exclusions 🤦🏽. So sorry. Yes, it has to be excluded so keep it in the list of exclusions 🙏🏽

2023-06-19 11:19 UTC, emmasofiah2o commented
> > > > @oscard0m I have committed your suggestion, but I thought you wanted your repo removed?
> > > 
> > > 
> > > Yes. My suggestion removed the repo, right?
> > 
> > 
> > No, you removed it from the config file where it was under "exclude". Meaning it is now included :D
> 
> Ahhh sorry, I did not notice that was the list of exclusions 🤦🏽. So sorry. Yes, it has to be excluded so keep it in the list of exclusions 🙏🏽

Oki, I'll change it back later!

2023-06-20 11:14 UTC, oscard0m approved these changes

2023-06-20 13:20 UTC, merged