Add Rust interview with Luca Palmieri
mainmatter/mainmatter.com pull request #2069
Opened 2023-06-28 07:49 UTC by emmasofiah2o

- Add as blog post
- Embed video
- Add og-image

To-do: add visual

2023-06-29 08:04 UTC, emmasofiah2o commented
The youtube link appears broken in the preview but works from the code. Not sure how to fix that

2023-06-29 09:43 UTC, marcoow requested changes

2023-06-29 09:43 UTC, marcoow commented on src/posts/2023-06-28-present-and-future-of-rust-with-luca-palmieri.md
> +  <p>Rust has become more popular among web developers in recent years. In this interview, Luca Palmieri, Senior Software Engineer at Mainmatter and Rust author, and Marco Otte-Witte, Founder of Maim
```suggestion
  <p>Rust has become more popular among web developers in recent years. In this interview, Luca Palmieri, Principal Engineering Consultant at Mainmatter and Rust author, and Marco Otte-Witte, Founder of Maimatter, delved into the world of backend development with Rust, examining the state of the ecosystem, the challenges it faces, and the success stories it generated.</p>
```

2023-06-29 09:43 UTC, marcoow commented on src/posts/2023-06-28-present-and-future-of-rust-with-luca-palmieri.md
> +<iframe width="560" height="315" src="https://youtu.be/Xb7NokhAVKI" title="Embedded video of Luca's interview" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyrosc
This doesn'T seem to work – check the preview

2023-06-29 09:43 UTC, marcoow commented on src/posts/2023-06-28-present-and-future-of-rust-with-luca-palmieri.md
> +backend development in Rust" with which he aimed to bridge the gap between
```suggestion
Luca then talked about his book "Zero To Production In Rust: An Introduction To
Backend Development" with which he aimed to bridge the gap between
```

see https://www.zero2prod.com/index.html

2023-06-29 09:43 UTC, marcoow commented on src/posts/2023-06-28-present-and-future-of-rust-with-luca-palmieri.md
> +<iframe width="560" height="315" src="https://youtu.be/Xb7NokhAVKI" title="Embedded video of Luca's interview" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyrosc
```suggestion
<iframe width="560" height="315" src="https://youtu.be/Xb7NokhAVKI" title="Embedded video of Luca's interview" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

If you're looking to adopt Rust to develop web backends and need guidance along the way, [get in touch](/contact/) We offer [team augmentation, mentoring, as well as development with Rust](/rust-consulting/).
```

2023-06-30 10:01 UTC, emmasofiah2o commented on src/posts/2023-06-28-present-and-future-of-rust-with-luca-palmieri.md
> +<iframe width="560" height="315" src="https://youtu.be/Xb7NokhAVKI" title="Embedded video of Luca's interview" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyrosc
Yeah, I've commented above. The link is correct, just the iframe doesn't work, but I copied it from Chris and not sure how to fix it

2023-07-04 08:58 UTC, BobrImperator commented on src/posts/2023-06-28-present-and-future-of-rust-with-luca-palmieri.md
> +<iframe width="560" height="315" src="https://youtu.be/Xb7NokhAVKI" title="Embedded video of Luca's interview" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyrosc
```suggestion
<iframe width="560" height="315" src="https://www.youtube-nocookie.com/embed/Xb7NokhAVKI?rel=0" title="Embedded video of Luca's interview" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
```

2023-07-04 10:11 UTC, marcoow requested changes
All looks good but let's use a visual that has Luca's photo instead of the generic Rust logo

2023-07-04 10:16 UTC, emmasofiah2o commented
@davidhajba what should we use?

2023-07-10 08:50 UTC, davidhajba commented
[HERE](https://www.sketch.com/s/066e539c-c206-4261-aafb-9634ab577579/a/y9QYmWz) is the blog post cover with Luca's photo instead of the generic Rust logo

2023-07-17 09:04 UTC, emmasofiah2o commented
@marcoow can I merge?

2023-07-17 09:14 UTC, marcoow approved these changes

2023-07-17 09:14 UTC, merged