Blog post: Setting up OAuth with Auth.js in a SvelteKit project for local development
mainmatter/mainmatter.com pull request #2088
Opened 2023-07-28 12:41 UTC by lolmaus

[Rendered](https://github.com/mainmatter/mainmatter.com/blob/84aea1cc9421f67126be3e82ae8fefc2f92af8c3/src/posts/2099-01-01-setting-up-oauth-with-auth-js-and-sveltekit.md).

2023-07-31 07:46 UTC, marcoow reviewed
I'd consider instead of making this focused on gotchas, making the outline a step-by-step guide for building auth with Auth.js and Svelte and then mentioning the gotchas along the way. I think that way this would be much more helpful for much more people. Reading further, it seems the big theme for the post is we're building auth for GitHub and Google with Auth.js and Svelte – I'd make that clear from the beginning and make that the outline for the post.

I'd also recommend going over it again and try to make the tone a bit more positive. It seems in particular the intro is a bit negative ("everything around OAuth sucks, particular errors are bad" does not make me want to read an article :) ).

2023-07-31 07:46 UTC, marcoow commented on src/posts/2099-01-01-setting-up-oauth-with-auth-js-and-sveltekit.md
> +I will not into more details about how OAuth works beyond and absolute minimum.
```suggestion
I will not go into more details about how OAuth works beyond the absolute minimum.
```

2023-07-31 07:46 UTC, marcoow commented on src/posts/2099-01-01-setting-up-oauth-with-auth-js-and-sveltekit.md
> +“authorization”. Offices behind security checkpoints are API endpoints.
I'm not sure it's clear what the difference is. In my experience, the best way to explain is the say authentication is checking a user is who they claim to be and authorization is checking they are allowed what they want to do. I know that's what you're trying to say with the example above – maybe it can be made a bit clearer how presenting the pass is different in the 2 above cases and what the purpose of presenting the pass is in the 2 situations.

2023-07-31 07:46 UTC, marcoow commented on src/posts/2099-01-01-setting-up-oauth-with-auth-js-and-sveltekit.md
> +interchangeably, without a second thought.
```suggestion
“authentication” and “authorization” that much. You can find these terms used
interchangeably.
```

makes it sound less like you're accusing people of deliberately misleading other or so

2023-07-31 07:46 UTC, marcoow commented on src/posts/2099-01-01-setting-up-oauth-with-auth-js-and-sveltekit.md
> +For this reason, your frontend app must delegate the actual authentication to
I'd say the actual authentication is still delegated to the external service? What you're delegating to the backend is verifying the authentication?

2023-07-31 07:46 UTC, marcoow commented on src/posts/2099-01-01-setting-up-oauth-with-auth-js-and-sveltekit.md
> +3. **Your frontend makes a POST request to your backend** to
What's this post request for?

2023-07-31 07:46 UTC, marcoow commented on src/posts/2099-01-01-setting-up-oauth-with-auth-js-and-sveltekit.md
> +7. **GitHub makes a 302 redirect to your backend** to
This might be specific to Auth.js but there's no reason this has to go to the backend – you can totally get the auth code in the frontend and use a `fetch` to post it to the backend and exchange for a cookie

2023-07-31 07:46 UTC, marcoow commented on src/posts/2099-01-01-setting-up-oauth-with-auth-js-and-sveltekit.md
> +You will end up with three or more sets of app ids and secret tokens.
This isn't necessarily true. Many providers let you define multiple redirect URLs so that you can reuse the same app in different environments

2023-07-31 07:46 UTC, marcoow commented on src/posts/2099-01-01-setting-up-oauth-with-auth-js-and-sveltekit.md
> +```julia
```suggestion
```
```

2023-07-31 07:46 UTC, marcoow commented on src/posts/2099-01-01-setting-up-oauth-with-auth-js-and-sveltekit.md
> +## How to create a subdomain on example.com
```suggestion
### How to create a subdomain on example.com
```

2023-07-31 07:46 UTC, marcoow commented on src/posts/2099-01-01-setting-up-oauth-with-auth-js-and-sveltekit.md
> +## What’s Auth.js
This seems to pop up a bit randomly among the list of gotchas?

2023-07-31 07:46 UTC, marcoow commented on src/posts/2099-01-01-setting-up-oauth-with-auth-js-and-sveltekit.md
> +define them.
You didn't say to install `@auth/sveltekit` or run any `npx` or anything? See my general recommendation: if you change the outline from being focused on gotchas to being centered around a step-by-step guide, I think it gets much easier to follow.

2023-07-31 07:46 UTC, marcoow commented on src/posts/2099-01-01-setting-up-oauth-with-auth-js-and-sveltekit.md
> +define them.
I now see you're mentioning that below – I think the order is wrong here.

2023-07-31 07:46 UTC, marcoow commented on src/posts/2099-01-01-setting-up-oauth-with-auth-js-and-sveltekit.md
> +- `AUTH_SECRET` should be a random string. It’s used to encrypt tokens exchanged
`AUTH_SECRET` isn't among the env vars in the list above? Honestly, I don't understand what this is and I implemented plenty of OAuth :)

2023-07-31 07:46 UTC, marcoow commented on src/posts/2099-01-01-setting-up-oauth-with-auth-js-and-sveltekit.md
> +{#if $page.data.session} {#if $page.data.session.user?.image}
```suggestion
{#if $page.data.session && $page.data.session.user?.image}
```

I guess?

2023-07-31 07:46 UTC, marcoow commented on src/posts/2099-01-01-setting-up-oauth-with-auth-js-and-sveltekit.md
> +Alternatively, you can redirect from a `+layout.server.js`, which arguably
I assume this would not work when the app has rehydrated and routing happens client side?

2023-07-31 07:46 UTC, marcoow commented on src/posts/2099-01-01-setting-up-oauth-with-auth-js-and-sveltekit.md
> +### 8. ???
???

2023-08-05 16:19 UTC, lolmaus commented
> I'd consider instead of making this focused on gotchas, making the outline a step-by-step guide for building auth with Auth.js and Svelte and then mentioning the gotchas along the way.

That was my plan in the first place. It's just that the actual step by step guide is rather small. This article does not focus on providing extensive instructions on coding in SvelteKit.

It's about the gotchas — each of them has been a blocker on my path of implementing OAuth. Each of them I had to figure out myself: though all the information was available on the internet, it took time, effort and trial-and-error to figure out each item.

I made a lot of effort to make the narration order natural to a newbie. You may not recognize it to be natural because you have [the curse of knowledge](https://en.wikipedia.org/wiki/Curse_of_knowledge) with all your OAuth experience. But @BlueCutOfficial personally told me she found the the article easy to follow and succeeded implementing a test app on the first try.

2023-08-05 16:20 UTC, lolmaus commented
> the intro is a bit negative ("everything around OAuth sucks, particular errors are bad" does not make me want to read an article :) )

I have entirely rephrased the intro to be more positive and better expalin the goal of the article.

2023-08-05 16:20 UTC, lolmaus commented on src/posts/2099-01-01-setting-up-oauth-with-auth-js-and-sveltekit.md
> +“authorization”. Offices behind security checkpoints are API endpoints.
I have added the clarifications that you suggested.

2023-08-05 16:21 UTC, lolmaus commented on src/posts/2099-01-01-setting-up-oauth-with-auth-js-and-sveltekit.md
> +For this reason, your frontend app must delegate the actual authentication to
No, I meant it's the backend and not the frontend who should be authenticating with and OAuth provider.

I have updated the phrasing.

2023-08-05 16:23 UTC, lolmaus commented on src/posts/2099-01-01-setting-up-oauth-with-auth-js-and-sveltekit.md
> +3. **Your frontend makes a POST request to your backend** to
I believe Auth.js performs it in order to pass the control flow to your backend.

I hesitate to add this statement to the article because it's my guess and not a fact.

2023-08-05 16:24 UTC, lolmaus commented on src/posts/2099-01-01-setting-up-oauth-with-auth-js-and-sveltekit.md
> +7. **GitHub makes a 302 redirect to your backend** to
Yes, it's specific to Auth.js.

In fact, this article took me more time to write because initially I had described a flow based on the articles I read. But then I investigated the *actual* flow with loggers and Dev Tools Network — and found it to be very different from what I imagined from the articles.

This flow should precisely describe what Auth.js is actually doing.

2023-08-05 16:25 UTC, lolmaus commented on src/posts/2099-01-01-setting-up-oauth-with-auth-js-and-sveltekit.md
> +You will end up with three or more sets of app ids and secret tokens.
Good point, I have updated the paragraph.

2023-08-05 16:26 UTC, lolmaus commented on src/posts/2099-01-01-setting-up-oauth-with-auth-js-and-sveltekit.md
> +## How to create a subdomain on example.com
I'd rather keep it as is.

The structure of the article is flat, except for the part "## Configuring SvelteKit" which has steps.

2023-08-05 16:28 UTC, lolmaus commented on src/posts/2099-01-01-setting-up-oauth-with-auth-js-and-sveltekit.md
> +## What’s Auth.js
Uhm, you're right. 

I moved it to the very top, after "What is OAuth"

2023-08-05 16:30 UTC, lolmaus commented on src/posts/2099-01-01-setting-up-oauth-with-auth-js-and-sveltekit.md
> +define them.
Moved this gotcha ot the bottom, together with the "Auth.js is evolving" gotcha.

2023-08-05 16:31 UTC, lolmaus commented on src/posts/2099-01-01-setting-up-oauth-with-auth-js-and-sveltekit.md
> +- `AUTH_SECRET` should be a random string. It’s used to encrypt tokens exchanged
> AUTH_SECRET isn't among the env vars in the list above?

It is, though?

2023-08-05 16:31 UTC, lolmaus commented on src/posts/2099-01-01-setting-up-oauth-with-auth-js-and-sveltekit.md
> +- `AUTH_SECRET` should be a random string. It’s used to encrypt tokens exchanged
And I did explain what it is. =) It's specific to Auth.js.

2023-08-05 16:31 UTC, lolmaus commented on src/posts/2099-01-01-setting-up-oauth-with-auth-js-and-sveltekit.md
> +{#if $page.data.session} {#if $page.data.session.user?.image}
Nope.

I have fixed the indentation instead.

2023-08-05 16:33 UTC, lolmaus commented on src/posts/2099-01-01-setting-up-oauth-with-auth-js-and-sveltekit.md
> +Alternatively, you can redirect from a `+layout.server.js`, which arguably
Oh, very good catch! 👀 💎

I have replaced `+layout.server.js` with `+layout.js` that runs both on server-side and client-side. I am not familiar with it, though, to be honest.

2023-08-05 16:33 UTC, lolmaus commented on src/posts/2099-01-01-setting-up-oauth-with-auth-js-and-sveltekit.md
> +### 8. ???
Removed.

2023-08-05 16:35 UTC, lolmaus commented
@marcoow The CI is failing. Fails locally for me too.

I tried to figure it out by comparing with other blog post PRs but failed. What am I missing?

2023-08-07 07:51 UTC, marcoow commented
it looks like there's some broken links: https://github.com/mainmatter/mainmatter.com/actions/runs/5771725705/job/15645973055?pr=2088

2023-08-07 07:53 UTC, marcoow commented on src/posts/2099-01-01-setting-up-oauth-with-auth-js-and-sveltekit.md
> +3. **Your frontend makes a POST request to your backend** to
might be worth to find out?

2023-10-27 13:05 UTC, lolmaus commented on src/posts/2099-01-01-setting-up-oauth-with-auth-js-and-sveltekit.md
> +3. **Your frontend makes a POST request to your backend** to
Added this clarification:

> This passes the control flow to the backend, which computes sign-in options for the OAuth provider: callback URL, scopes, etc.

2023-10-27 13:34 UTC, BlueCutOfficial approved these changes
I had read the first iteration of the doc on Notion, the steps make sense to me and I was able to set up OAuth in a sandbox app by just following this doc, without any extra-search aside.

2023-10-30 13:35 UTC, marcoow reviewed
Nice post! I'd just fix a few smaller things and change the title as that's a bit misleading currently

2023-10-30 13:35 UTC, marcoow commented on src/posts/2023-10-26-setting-up-oauth-with-auth-js-and-sveltekit.md
> +  "Setting up OAuth with Auth.js in a SvelteKit project for local development"
```suggestion
  "Setting up OAuth with Auth.js in a SvelteKit project"
```

otherwise it sounds like this is about how to set up things for local development **only** which most people would not be interested in probably…

2023-10-30 13:35 UTC, marcoow commented on src/posts/2023-10-26-setting-up-oauth-with-auth-js-and-sveltekit.md
> +and “authorization” is verifying if the identified user is permitted to access
```suggestion
and “authorization” is verifying if the identified user is permitted to access or do
```

2023-10-30 13:35 UTC, marcoow commented on src/posts/2023-10-26-setting-up-oauth-with-auth-js-and-sveltekit.md
> +- \***\*Device authorization\*\*** flow — uses a separate device for user
```suggestion
- **Device authorization** flow — uses a separate device for user
```

I guess this wasn't intended formatting?

2023-10-30 13:35 UTC, marcoow commented on src/posts/2023-10-26-setting-up-oauth-with-auth-js-and-sveltekit.md
> +[prose/gatekeeper](https://pikabu.ru/story/myerilin_monro_10493776) (that you
I don't think this is the correct link?

2023-10-30 13:35 UTC, marcoow commented on src/posts/2023-10-26-setting-up-oauth-with-auth-js-and-sveltekit.md
> +Tools or JS scripts. This substantially improves security.
I'm not sure this is part of OAuth 2? I think you'd be able to issue e.g. a bearer token with OAuth 2.0? Also, you could have a JWT in the cookie?

2023-10-30 13:35 UTC, marcoow commented on src/posts/2023-10-26-setting-up-oauth-with-auth-js-and-sveltekit.md
> +`http://my-app.[example.com](http://example.com)`, as the `example.com` domain
```suggestion
`http://my-app.example.com`, as the `example.com` domain
```

this doesn't render correctly otherwise

2023-10-30 13:35 UTC, marcoow commented on src/posts/2023-10-26-setting-up-oauth-with-auth-js-and-sveltekit.md
> +1. Visit https://github.com/settings/developers and click `New OAuth app`.
```suggestion
1. Visit [https://github.com/settings/developers](https://github.com/settings/developers) and click `New OAuth app`.
```

2023-10-30 13:35 UTC, marcoow commented on src/posts/2023-10-26-setting-up-oauth-with-auth-js-and-sveltekit.md
> +https://authjs.dev/reference/core/providers_github
```suggestion
[https://authjs.dev/reference/core/providers_github](https://authjs.dev/reference/core/providers_github)
```

2023-10-30 13:35 UTC, marcoow commented on src/posts/2023-10-26-setting-up-oauth-with-auth-js-and-sveltekit.md
> +1. Visit https://console.cloud.google.com/ .
```suggestion
1. Visit [https://console.cloud.google.com/](https://console.cloud.google.com/).
```

2023-10-30 13:35 UTC, marcoow commented on src/posts/2023-10-26-setting-up-oauth-with-auth-js-and-sveltekit.md
> +   https://console.cloud.google.com/apis/credentials/consent and change the
```suggestion
   [https://console.cloud.google.com/apis/credentials/consent](https://console.cloud.google.com/apis/credentials/consent) and change the
```

2023-10-30 13:35 UTC, marcoow commented on src/posts/2023-10-26-setting-up-oauth-with-auth-js-and-sveltekit.md
> +   https://console.cloud.google.com/apis/credentials
```suggestion
   [https://console.cloud.google.com/apis/credentials](https://console.cloud.google.com/apis/credentials)
```

2023-10-30 13:35 UTC, marcoow commented on src/posts/2023-10-26-setting-up-oauth-with-auth-js-and-sveltekit.md
> +   http://my-app.example.com:5173/auth/callback/google
```suggestion
   [http://my-app.example.com:5173/auth/callback/google](http://my-app.example.com:5173/auth/callback/google)
```

2023-10-30 13:35 UTC, marcoow commented on src/posts/2023-10-26-setting-up-oauth-with-auth-js-and-sveltekit.md
> +https://authjs.dev/reference/core/providers_github
```suggestion
[https://authjs.dev/reference/core/providers_github](https://authjs.dev/reference/core/providers_github)
```

2023-10-30 13:35 UTC, marcoow commented on src/posts/2023-10-26-setting-up-oauth-with-auth-js-and-sveltekit.md
> +- Source: https://github.com/nextauthjs/sveltekit-auth-example
```suggestion
- Source: [https://github.com/nextauthjs/sveltekit-auth-example](https://github.com/nextauthjs/sveltekit-auth-example)
```

2023-11-08 11:37 UTC, lolmaus commented on src/posts/2023-10-26-setting-up-oauth-with-auth-js-and-sveltekit.md
> +[prose/gatekeeper](https://pikabu.ru/story/myerilin_monro_10493776) (that you
Fixed.

2023-11-08 11:38 UTC, lolmaus commented on src/posts/2023-10-26-setting-up-oauth-with-auth-js-and-sveltekit.md
> +Tools or JS scripts. This substantially improves security.
You're right.

Auth.js uses the term "session token", which I believe is a synonym for "bearer token". I was not able to figure out if their token is opaque or JWT.

I have removed mentions of JWT from this paragraph.

2023-11-08 13:24 UTC, lolmaus commented
> it looks like there's some broken links: https://github.com/mainmatter/mainmatter.com/actions/runs/5771725705/job/15645973055?pr=2088

It took me a lot of time to figure out that this was due to the fact that my blog post was set to a future date. 🙈

2023-11-08 13:55 UTC, marcoow approved these changes

2023-11-09 12:33 UTC, emmasofiah2o requested changes
This was very well written! 🙌 
I made comments for some minor typos/mistakes and capitalized your titles. 

Just one note: "insecure" is usually for people (as in "lacking confidence"). When you talk about tech it's usually "unsafe". I know it is called "IT Security", but "insecure" doesn't sound right in those contexts :).

2023-11-09 12:33 UTC, emmasofiah2o commented on src/posts/2023-10-26-setting-up-oauth-with-auth-js-and-sveltekit.md
> +  number of pifalls that may be a source of frustration even to experienced
```suggestion
  number of pitfalls that may be a source of frustration even to experienced
```

2023-11-09 12:33 UTC, emmasofiah2o commented on src/posts/2023-10-26-setting-up-oauth-with-auth-js-and-sveltekit.md
> +  <p>There are numerous articles and libraries around OAuth available, and yet setting it up may appear challenging — not due any particular code complexity, but rather due to small details missing o
```suggestion
  <p>There are numerous OAuth articles and libraries available, and yet setting it up may appear challenging — not due to any particular code complexity, but rather to small details missing or incorrectly configured. This article provides a step-by-step guide for setting up OAuth using a specific combination of technologies, SvelteKit + Auth.js, along with explanations of all the pitfalls.</p>
```

2023-11-09 12:33 UTC, emmasofiah2o commented on src/posts/2023-10-26-setting-up-oauth-with-auth-js-and-sveltekit.md
> +  <p>This article describes configuration of Google and GitHub OAuth providers, since they are among the most popular ones with developers. You're not limited with those two, though: set it up with a
```suggestion
  <p>This article focuses on the configuration of Google and GitHub OAuth providers since they are among the most popular ones with developers. You're not limited with those two, though: set it up with any other OAuth provider of choice.</p>
```

2023-11-09 12:33 UTC, emmasofiah2o commented on src/posts/2023-10-26-setting-up-oauth-with-auth-js-and-sveltekit.md
> +In simplest words, OAuth is an approach for letting users log into your app
```suggestion
In simple words, OAuth is an approach for letting users log into your app
```

2023-11-09 12:33 UTC, emmasofiah2o commented on src/posts/2023-10-26-setting-up-oauth-with-auth-js-and-sveltekit.md
> +authentication there, and the provider redirects back into the app, which ends
```suggestion
authentication there, and the provider redirects back to the app, where the user is now
```

2023-11-09 12:33 UTC, emmasofiah2o commented on src/posts/2023-10-26-setting-up-oauth-with-auth-js-and-sveltekit.md
> +up authenticated.
```suggestion
authenticated.
```

2023-11-09 12:33 UTC, emmasofiah2o commented on src/posts/2023-10-26-setting-up-oauth-with-auth-js-and-sveltekit.md
> +I will not go into more details about how OAuth works beyond the absolute
```suggestion
```

2023-11-09 12:33 UTC, emmasofiah2o commented on src/posts/2023-10-26-setting-up-oauth-with-auth-js-and-sveltekit.md
> +minimum. There are plenty of articles on the internet that let you understand
```suggestion
If you need to, you can look up more information on OAuth online, where you will find plenty of articles
```

2023-11-09 12:33 UTC, emmasofiah2o commented on src/posts/2023-10-26-setting-up-oauth-with-auth-js-and-sveltekit.md
> +this topic with a desired level of depth.
```suggestion
for your desired level of depth.
```

2023-11-09 12:33 UTC, emmasofiah2o commented on src/posts/2023-10-26-setting-up-oauth-with-auth-js-and-sveltekit.md
> +(full-stack, React-based), but later was converted into a universal library.
```suggestion
(full-stack, React-based), but was later converted into a universal library.
```

2023-11-09 12:33 UTC, emmasofiah2o commented on src/posts/2023-10-26-setting-up-oauth-with-auth-js-and-sveltekit.md
> +There’s a lot of confusion around these terms.
```suggestion
There’s a lot of confusion around the terms "authentication" and "authorization".
```

2023-11-09 12:33 UTC, emmasofiah2o commented on src/posts/2023-10-26-setting-up-oauth-with-auth-js-and-sveltekit.md
> +and “authorization” is verifying if the identified user is permitted to access
```suggestion
and “authorization” is verifying if the identified user has permission to access
```

2023-11-09 12:33 UTC, emmasofiah2o commented on src/posts/2023-10-26-setting-up-oauth-with-auth-js-and-sveltekit.md
> +The security guard would make sure that the pass is still valid and they might
```suggestion
The security guard would then make sure that the pass is still valid and might
```

2023-11-09 12:33 UTC, emmasofiah2o commented on src/posts/2023-10-26-setting-up-oauth-with-auth-js-and-sveltekit.md
> +checkpoints represent API endpoints.
Loved this analogy! It made it super easy to understand the concept! 🔥

2023-11-09 12:33 UTC, emmasofiah2o commented on src/posts/2023-10-26-setting-up-oauth-with-auth-js-and-sveltekit.md
> +title: "Setting up OAuth with Auth.js in a SvelteKit project"
```suggestion
title: "Setting up OAuth with Auth.js in a SvelteKit Project"
```

2023-11-09 12:33 UTC, emmasofiah2o commented on src/posts/2023-10-26-setting-up-oauth-with-auth-js-and-sveltekit.md
> +## Gotcha 0: authentication vs authorization
```suggestion
## Gotcha 0: Authentication vs Authorization
```

2023-11-09 12:33 UTC, emmasofiah2o commented on src/posts/2023-10-26-setting-up-oauth-with-auth-js-and-sveltekit.md
> +OAuth 2. This article does too.
```suggestion
OAuth 2. This article does this, too.
```

2023-11-09 12:33 UTC, emmasofiah2o commented on src/posts/2023-10-26-setting-up-oauth-with-auth-js-and-sveltekit.md
> +## Gotcha 2: OAuth authentication flow types
```suggestion
## Gotcha 2: OAuth Authentication Flow Types
```

2023-11-09 12:33 UTC, emmasofiah2o commented on src/posts/2023-10-26-setting-up-oauth-with-auth-js-and-sveltekit.md
> +We’re gonna be doing the **authorization code** flow.
```suggestion
We will be using the **authorization code** flow.
```

2023-11-09 12:33 UTC, emmasofiah2o commented on src/posts/2023-10-26-setting-up-oauth-with-auth-js-and-sveltekit.md
> +## Gotcha 3: you need a backend!
```suggestion
## Gotcha 3: You Need a Backend!
```

2023-11-09 12:33 UTC, emmasofiah2o commented on src/posts/2023-10-26-setting-up-oauth-with-auth-js-and-sveltekit.md
> +OAuth authentication cannot be implemented in a frontend-only app, such as an
```suggestion
OAuth authentication cannot be implemented in a frontend-only app without any backend, such as an
```

2023-11-09 12:33 UTC, emmasofiah2o commented on src/posts/2023-10-26-setting-up-oauth-with-auth-js-and-sveltekit.md
> +SPA deployed to GitHub Pages and not having any backend.
```suggestion
SPA deployed to GitHub Pages.
```

2023-11-09 12:33 UTC, emmasofiah2o commented on src/posts/2023-10-26-setting-up-oauth-with-auth-js-and-sveltekit.md
> +provider directly, but rather should this job to your backend. It’s your backend
```suggestion
provider directly, but rather leave this job to your backend. It’s your backend
```

2023-11-09 12:33 UTC, emmasofiah2o commented on src/posts/2023-10-26-setting-up-oauth-with-auth-js-and-sveltekit.md
> +Luckily, SvelteKit can work as a full-stack app, with a frontend and a backend!
```suggestion
Luckily, SvelteKit can work as a full-stack app, with a frontend **and** a backend!
```

2023-11-09 12:33 UTC, emmasofiah2o commented on src/posts/2023-10-26-setting-up-oauth-with-auth-js-and-sveltekit.md
> +## Gotcha 4: the authorization code flow can be implemented in different ways
```suggestion
## Gotcha 4: The Authorization Code Flow Can Be Implemented in Different Ways
```

2023-11-09 12:33 UTC, emmasofiah2o commented on src/posts/2023-10-26-setting-up-oauth-with-auth-js-and-sveltekit.md
> +Many apps and libraries store tokens in localStorage. Some developers and
```suggestion
Many apps and libraries store tokens in localStorage, but some developers and
```

2023-11-09 12:33 UTC, emmasofiah2o commented on src/posts/2023-10-26-setting-up-oauth-with-auth-js-and-sveltekit.md
> +security professionals believe this to be insecure.
```suggestion
security professionals believe this to be unsafe.
```

2023-11-09 12:33 UTC, emmasofiah2o commented on src/posts/2023-10-26-setting-up-oauth-with-auth-js-and-sveltekit.md
> +such as GitHub or Google) on the backend side and uses a Secure, HttpOnly cookie
```suggestion
such as GitHub or Google) on the backend side and uses a secure, HttpOnly cookie
```

2023-11-09 12:33 UTC, emmasofiah2o commented on src/posts/2023-10-26-setting-up-oauth-with-auth-js-and-sveltekit.md
> +be accessed or copied from browser Dev Tools or JS scripts. This substantially
```suggestion
be accessed or copied from browsers' Dev Tools or JS scripts. This substantially
```

2023-11-09 12:33 UTC, emmasofiah2o commented on src/posts/2023-10-26-setting-up-oauth-with-auth-js-and-sveltekit.md
> +## **OAuth Authorization Code Flow with Auth.js**
```suggestion
## OAuth Authorization Code Flow with Auth.js
```

2023-11-09 12:33 UTC, emmasofiah2o commented on src/posts/2023-10-26-setting-up-oauth-with-auth-js-and-sveltekit.md
> +   `https://github.com/login/oauth/authorize`, passing a number of query params,
```suggestion
   `https://github.com/login/oauth/authorize`, passing a number of query parameters,
```

2023-11-09 12:33 UTC, emmasofiah2o commented on src/posts/2023-10-26-setting-up-oauth-with-auth-js-and-sveltekit.md
> +   - `client_id`: the id of your app at GitHub;
```suggestion
   - `client_id` – the id of your app at GitHub;
```

2023-11-09 12:33 UTC, emmasofiah2o commented on src/posts/2023-10-26-setting-up-oauth-with-auth-js-and-sveltekit.md
> +   - `redirect_uri=http://my-app.example.com:5173/auth/callback/github`: your
```suggestion
   - `redirect_uri=http://my-app.example.com:5173/auth/callback/github` – your
```

2023-11-09 12:33 UTC, emmasofiah2o commented on src/posts/2023-10-26-setting-up-oauth-with-auth-js-and-sveltekit.md
> +6. **The user authorizes your app to authenticate with GitHub,** if they haven't
```suggestion
6. **The user authorizes your app to authenticate with GitHub**, if they haven't
```

2023-11-09 12:33 UTC, emmasofiah2o commented on src/posts/2023-10-26-setting-up-oauth-with-auth-js-and-sveltekit.md
> +    Here the backend sets a secure HttpOnly cookie containing a session token
```suggestion
    Here, the backend sets a secure HttpOnly cookie containing a session token
```

2023-11-09 12:33 UTC, emmasofiah2o commented on src/posts/2023-10-26-setting-up-oauth-with-auth-js-and-sveltekit.md
> +the fronted, only to the backend. This means that steps 7 and 8 could
```suggestion
the frontend, only to the backend. This means that steps 7 and 8 could
```

2023-11-09 12:33 UTC, emmasofiah2o commented on src/posts/2023-10-26-setting-up-oauth-with-auth-js-and-sveltekit.md
> +insecure and only offer the Authorization code flow, so that’s what Auth.js is
```suggestion
unsafe and only offer the Authorization code flow, so that’s what Auth.js is
```

2023-11-09 12:33 UTC, emmasofiah2o commented on src/posts/2023-10-26-setting-up-oauth-with-auth-js-and-sveltekit.md
> +## Gotcha 5: you should “create” a separate “app” with each OAuth provider for every deployment environment
```suggestion
## Gotcha 5: You Should “Create” a Separate “App” with each OAuth Provider for Every Deployment Environment
```

2023-11-09 12:33 UTC, emmasofiah2o commented on src/posts/2023-10-26-setting-up-oauth-with-auth-js-and-sveltekit.md
> +with the provider for each deployment environment, e. g. local development,
```suggestion
with the provider for each deployment environment, e.g., local development,
```

2023-11-09 12:33 UTC, emmasofiah2o commented on src/posts/2023-10-26-setting-up-oauth-with-auth-js-and-sveltekit.md
> +staging and production. You will end up with three or more sets of app ids and
```suggestion
staging, and production. You will end up with three or more sets of app ids and
```

2023-11-09 12:33 UTC, emmasofiah2o commented on src/posts/2023-10-26-setting-up-oauth-with-auth-js-and-sveltekit.md
> +## Gotcha 6: you need a domain for local development
```suggestion
## Gotcha 6: You Need a Domain for Local Development
```

2023-11-09 12:33 UTC, emmasofiah2o commented on src/posts/2023-10-26-setting-up-oauth-with-auth-js-and-sveltekit.md
> +`http://localhost:5173``.
```suggestion
`http://localhost:5173`.
```

2023-11-09 12:33 UTC, emmasofiah2o commented on src/posts/2023-10-26-setting-up-oauth-with-auth-js-and-sveltekit.md
> +The problem with it is the `localhost` domain is not unique and some OAuth
```suggestion
The problem with it is that the `localhost` domain is not unique, and some OAuth
```

2023-11-09 12:33 UTC, emmasofiah2o commented on src/posts/2023-10-26-setting-up-oauth-with-auth-js-and-sveltekit.md
> +providers would refuse to work with it.
```suggestion
providers will refuse to work with it.
```

2023-11-09 12:33 UTC, emmasofiah2o commented on src/posts/2023-10-26-setting-up-oauth-with-auth-js-and-sveltekit.md
> +but there’s another problem with it.
```suggestion
but there’s another problem with this.
```

2023-11-09 12:33 UTC, emmasofiah2o commented on src/posts/2023-10-26-setting-up-oauth-with-auth-js-and-sveltekit.md
> +## Gotcha 7: some OAuth providers refuse to work with unencrypted http
```suggestion
## Gotcha 7: Some OAuth Providers Refuse to Work with Unencrypted http
```

2023-11-09 12:33 UTC, emmasofiah2o commented on src/posts/2023-10-26-setting-up-oauth-with-auth-js-and-sveltekit.md
> +The `http` protocol is inherently insecure and some OAuth providers would refuse
```suggestion
The `http` protocol is inherently unsafe and some OAuth providers refuse
```

2023-11-09 12:33 UTC, emmasofiah2o commented on src/posts/2023-10-26-setting-up-oauth-with-auth-js-and-sveltekit.md
> +Google would also reject URLs on made-up top-level domains.
```suggestion
Google, however, also rejects URLs on made-up top-level domains.
```

2023-11-09 12:33 UTC, emmasofiah2o commented on src/posts/2023-10-26-setting-up-oauth-with-auth-js-and-sveltekit.md
> +## How to create a subdomain on example.com
```suggestion
## How to Create a Subdomain on Example.com
```

2023-11-09 12:33 UTC, emmasofiah2o commented on src/posts/2023-10-26-setting-up-oauth-with-auth-js-and-sveltekit.md
> +2. In the top-left corner of the pae, expand the list of projects and click
```suggestion
2. In the top-left corner of the page, expand the list of projects and click
```

2023-11-09 12:33 UTC, emmasofiah2o commented on src/posts/2023-10-26-setting-up-oauth-with-auth-js-and-sveltekit.md
> +### 0. Set up a SvelteKit codebase
```suggestion
### 0. Set Up a SvelteKit Codebase
```

2023-11-09 12:33 UTC, emmasofiah2o commented on src/posts/2023-10-26-setting-up-oauth-with-auth-js-and-sveltekit.md
> +### 2. Set up environment variables
```suggestion
### 2. Set Up the Environment Variables
```

2023-11-09 12:33 UTC, emmasofiah2o commented on src/posts/2023-10-26-setting-up-oauth-with-auth-js-and-sveltekit.md
> +  [here](https://generate-secret.vercel.app/32). That’s theoretically insecure,
```suggestion
  [here](https://generate-secret.vercel.app/32). That’s theoretically unsafe,
```

2023-11-09 12:33 UTC, emmasofiah2o commented on src/posts/2023-10-26-setting-up-oauth-with-auth-js-and-sveltekit.md
> +  will only show it once! Don’t lose it or you’ll have to rejenerate it.
```suggestion
  will only show it once! Don’t lose it, or you’ll have to regenerate it.
```

2023-11-09 12:33 UTC, emmasofiah2o commented on src/posts/2023-10-26-setting-up-oauth-with-auth-js-and-sveltekit.md
> +### 3. Create a server hook to initialize AuthJS
```suggestion
### 3. Create a Server Hook to Initialize AuthJS
```

2023-11-09 12:33 UTC, emmasofiah2o commented on src/posts/2023-10-26-setting-up-oauth-with-auth-js-and-sveltekit.md
> +### 4. Load the session from your backend
```suggestion
### 4. Load the Session from Your Backend
```

2023-11-09 12:33 UTC, emmasofiah2o commented on src/posts/2023-10-26-setting-up-oauth-with-auth-js-and-sveltekit.md
> +### 5. Use the session in your frontend
```suggestion
### 5. Use the Session in Your Frontend
```

2023-11-09 12:33 UTC, emmasofiah2o commented on src/posts/2023-10-26-setting-up-oauth-with-auth-js-and-sveltekit.md
> +In `src/routes/+layout.svelte` or whateve layout or page you need it in:
```suggestion
In `src/routes/+layout.svelte` or whatever layout or page you need it in:
```

2023-11-09 12:33 UTC, emmasofiah2o commented on src/posts/2023-10-26-setting-up-oauth-with-auth-js-and-sveltekit.md
> +### 6. Add a sign-in button
```suggestion
### 6. Add a Sign-in Button
```

2023-11-09 12:33 UTC, emmasofiah2o commented on src/posts/2023-10-26-setting-up-oauth-with-auth-js-and-sveltekit.md
> +### 7. Protect a route from anonymous access
```suggestion
### 7. Protect a Route from Anonymous Access
```

2023-11-09 12:33 UTC, emmasofiah2o commented on src/posts/2023-10-26-setting-up-oauth-with-auth-js-and-sveltekit.md
> +  This is a protected content. You can access this content because you are
```suggestion
  This is protected content. You can access this content because you are
```

2023-11-09 12:33 UTC, emmasofiah2o commented on src/posts/2023-10-26-setting-up-oauth-with-auth-js-and-sveltekit.md
> +### 9. You’re breathtaking!
```suggestion
### 9. You Rock!
```

2023-11-09 12:33 UTC, emmasofiah2o commented on src/posts/2023-10-26-setting-up-oauth-with-auth-js-and-sveltekit.md
> +## Gotcha 8: automatically generated routes
```suggestion
## Gotcha 8: Automatically Generated Routes
```

2023-11-09 12:33 UTC, emmasofiah2o commented on src/posts/2023-10-26-setting-up-oauth-with-auth-js-and-sveltekit.md
> +## Gotcha 9: Auth.js is evolving
```suggestion
## Gotcha 9: Auth.js Is Evolving
```

2023-11-09 12:33 UTC, emmasofiah2o commented on src/posts/2023-10-26-setting-up-oauth-with-auth-js-and-sveltekit.md
> +As of 2023, the library is relatively new. It’s core is more or less stable, but
```suggestion
As of 2023, the library is relatively new. Its core is more or less stable, but
```

2023-11-09 12:33 UTC, emmasofiah2o commented on src/posts/2023-10-26-setting-up-oauth-with-auth-js-and-sveltekit.md
> +## Demo app
```suggestion
## Demo App
```

2023-11-09 12:33 UTC, emmasofiah2o commented on src/posts/2023-10-26-setting-up-oauth-with-auth-js-and-sveltekit.md
> +## Next steps
```suggestion
## Next Steps
```

2023-11-13 09:10 UTC, lolmaus commented on src/posts/2023-10-26-setting-up-oauth-with-auth-js-and-sveltekit.md
> +I will not go into more details about how OAuth works beyond the absolute
Is this correct?

2023-11-13 09:11 UTC, lolmaus commented on src/posts/2023-10-26-setting-up-oauth-with-auth-js-and-sveltekit.md
> +I will not go into more details about how OAuth works beyond the absolute
Ah, it's paired with the following edit. OK!

2023-11-13 09:21 UTC, lolmaus commented on src/posts/2023-10-26-setting-up-oauth-with-auth-js-and-sveltekit.md
> +and “authorization” is verifying if the identified user is permitted to access
I believe this one should stay as is.

2023-11-13 09:53 UTC, lolmaus commented on src/posts/2023-10-26-setting-up-oauth-with-auth-js-and-sveltekit.md
> +such as GitHub or Google) on the backend side and uses a Secure, HttpOnly cookie
"Secure" is a property.

2023-11-13 09:59 UTC, lolmaus commented on src/posts/2023-10-26-setting-up-oauth-with-auth-js-and-sveltekit.md
> +   `https://github.com/login/oauth/authorize`, passing a number of query params,
"Query params" is an established term.

2023-11-13 10:41 UTC, lolmaus commented on src/posts/2023-10-26-setting-up-oauth-with-auth-js-and-sveltekit.md
> +and “authorization” is verifying if the identified user is permitted to access
Nevermind! I misread the suggestion as `has permitted`. Committed your suggestion.

2023-11-13 14:56 UTC, marcoow approved these changes

2023-11-13 15:27 UTC, emmasofiah2o requested changes
Just a small mistake in the description. I'll prep the visuals :)

2023-11-13 15:27 UTC, emmasofiah2o commented on src/posts/2023-10-26-setting-up-oauth-with-auth-js-and-sveltekit.md
> +  authentication using the Auth.js libry in a SvelteKit project. He describes a
```suggestion
  authentication using the Auth.js library in a SvelteKit project. He describes a
```

2023-11-13 15:50 UTC, lolmaus commented
The crawl links job is failing because the blog post is set to a future date.

2023-11-14 11:41 UTC, emmasofiah2o commented on src/posts/2023-10-26-setting-up-oauth-with-auth-js-and-sveltekit.md
> +  authentication using the Auth.js libry in a SvelteKit project. He describes a
@lolmaus can you commit this pls?

2023-11-14 11:42 UTC, emmasofiah2o commented on src/posts/2023-10-26-setting-up-oauth-with-auth-js-and-sveltekit.md
> +  authentication using the Auth.js libry in a SvelteKit project. He describes a
Oh wait, it's outdated. I'll just change it before release

2023-11-14 11:49 UTC, emmasofiah2o approved these changes

2023-11-15 08:22 UTC, paoloricciuti reviewed
Very good article @lolmaus i've added some small nitpicks in comments but feel free to ignore them. I especially liked the hack to have it work with localhost (even tho i actually never experienced those problems)

2023-11-15 08:22 UTC, paoloricciuti commented on src/posts/2023-11-16-setting-up-oauth-with-auth-js-and-sveltekit.md
> +
I don't know if it's worth saying to allow preview deploys to work sometimes you can specify a more generic redirect uri.

For example if you are deploying on vercel every preview gets a different URL in the shape of `https://somename.vercel.app`. GitHub only allow you to specify one redirect URL but if you specify `https://vercel.app` per Oauth2 specification if you try to redirect to `https://somename.vercel.app` or `https://someothername.vercel.app` both will be valid redirect uri.

Also if you have multiple domains (for example `https://my-app.dev` and `https://my-app.com` one way to use the same GithubApp can be to always redirect to `https://my-app.dev` and reroute there to `https://my-app.com` if they are coming from `https://my-app.dev` after the code exchange.

2023-11-15 08:22 UTC, paoloricciuti commented on src/posts/2023-11-16-setting-up-oauth-with-auth-js-and-sveltekit.md
> +{#if $page.data.session} {#if $page.data.session.user?.image}
Personally i found this double if a bit hard to read but that's really a nitpick

2023-11-15 08:22 UTC, paoloricciuti commented on src/posts/2023-11-16-setting-up-oauth-with-auth-js-and-sveltekit.md
> +…are routes automatically generated by `@auth/sveltekit`. You don’t need to
I imagine those are handled in the `hooks.server.ts`. If that's the case rather than saying that the routes are generated i would say that are handled in the hooks file because this could become confusing if someone is following along and don't see the file literally being generated.

2023-11-15 08:22 UTC, paoloricciuti commented on src/posts/2023-11-16-setting-up-oauth-with-auth-js-and-sveltekit.md
> +VS Code with the official Svelte
I don't think the VS Code extension is needed to get intellisense on `$env/static/private` they are just typescript `.d.ts` files generated by the dev server.

2023-11-15 13:58 UTC, closed without merging