add breethe post part 1
mainmatter/mainmatter.com pull request #209
Opened 2018-07-05 12:01 UTC by niklaslong

This is the first draft of the breethe-server post. A big chunk of the post is giving context and explaining the application structure, and although necessary it might be a little long-winded.
Let me know what you think.

2018-07-05 12:59 UTC, marcoow reviewed
This is a really good post! I think you're right though that this might contain a bit too much detail on some of the things. It might be possible to shorten the explanations for some of the individual modules and methods a bit and e.g. just say things along the lines of _"this gets data from openaq"_, _"this gets cached data from the db"_ etc. Also, I think it'd be important to explain a bit how the `Breethe` module in `breethe.ex` is kind of the public API of the app that the webserver app will use as that is a very important point about umbrella apps - the fact that the apps are clearly separated and communicate via a well defined interface.

2018-07-05 12:59 UTC, marcoow commented on blog/_posts/2018-06-25-breethe-elixir.md
> +title: "Elixir/Phoenix Breethe.app part 1: Data"
I think we should look for a catchier title :) Maybe something like _"Building an Umbrella API app with Elixir and Phoenix"_ or so…

2018-07-05 12:59 UTC, marcoow commented on blog/_posts/2018-06-25-breethe-elixir.md
> +Breethe.app is an air quality app. This means our back end interacts with with a number of external APIs to aggregate the data:
I think this should be _"Breethe"_.

2018-07-05 12:59 UTC, marcoow commented on blog/_posts/2018-06-25-breethe-elixir.md
> +Over the last couple of months, we have been building an Elixir umbrella app to serve as our back end for breethe.app, which provides instant access to up to date air quality data for locations acros
I think we should always say just _"Breethe"_ and also have a link to https://breethe.app when mentioning it first.

2018-07-05 12:59 UTC, marcoow commented on blog/_posts/2018-06-25-breethe-elixir.md
> +The breethe.app project is intirely open-source. Please take a look at the code for the [client](https://github.com/simplabs/breethe-client) and the [back end](https://github.com/simplabs/breethe-ser
_"~i~entirely"_?

2018-07-05 12:59 UTC, marcoow commented on blog/_posts/2018-06-25-breethe-elixir.md
> +Over the last couple of months, we have been building an Elixir umbrella app to serve as our back end for breethe.app, which provides instant access to up to date air quality data for locations acros
_"to serve as ~our~the back end"_?

2018-07-05 12:59 UTC, marcoow commented on blog/_posts/2018-06-25-breethe-elixir.md
> +The breethe.app project is intirely open-source. Please take a look at the code for the [client](https://github.com/simplabs/breethe-client) and the [back end](https://github.com/simplabs/breethe-ser
I'd generally say _"server"_ instead of _"back end"_

2018-07-05 12:59 UTC, marcoow commented on blog/_posts/2018-06-25-breethe-elixir.md
> +- `:bc` - _black carbon_, a component of fine particulate matter - causes human morbidity and premature mortality
I'm not sure we need this level of detailed info for context :)

2018-07-05 12:59 UTC, marcoow commented on blog/_posts/2018-06-25-breethe-elixir.md
> +- `:ppm` - parts per million (ppm) (needs to be removed as it is unused troughout the app)
see above

2018-07-05 12:59 UTC, marcoow commented on blog/_posts/2018-06-25-breethe-elixir.md
> +The `google` directory contains a single file called `geocoding.ex`. In that file we have written code which will request data from [Google's geocoding API](https://developers.google.com/maps/documen
> _"In that file we have written code which will request data from [Google's geocoding API](https://developers.google.com/maps/documentation/geocoding/intro) and allows us to convert between coordinates and addresses."_

Maybe be a bit more specific here, e.g.

_"That module uses [Google's geocoding API](https://developers.google.com/maps/documentation/geocoding/intro) to translate addresses as put in by the user when searching for a location into precise coordinates."_

?

2018-07-05 12:59 UTC, marcoow commented on blog/_posts/2018-06-25-breethe-elixir.md
> +Firstly, let me give you a little context concerning the function parameters. We want to be able to search `locations` both by `search_term` (e.g.: `"Münich"`) or `lat, lon` (e.g.: `51.1789,-1.8261`)
> `"Münich"`

It's either _"Munich"_ or _"München"_ :)

2018-07-12 11:27 UTC, oliverbarnes requested changes
Aside from my previous comment, I feel like this post touches on a few different things, I had a little trouble figuring out the common thread. Either this could be broken down (and each piece elaborate on the specific points it's making/showing), or slimmed down to focus on the umbrella-ness of this approach - so the intention (why it's a good/useful thing), then what's different in terms of building and how it executes. 

What do you think?

2018-07-12 11:27 UTC, oliverbarnes commented on blog/_posts/2018-06-25-breethe-elixir.md
> +* a mix application named `breethe` which handles our _data_
I'd be curious to know more of why it's a good idea to separate the data concerns into its own app. something quick perhaps linking to a discussion of this

2018-08-03 08:29 UTC, niklaslong commented
@oliverbarnes Agreed, it's been quite difficult for me to find the balance between giving context about the app and focusing on the more interesting aspects of the code. I'll spend some time editing and reworking the post - hopefully it'll have more focus on the right things.

2018-08-03 08:32 UTC, niklaslong commented on blog/_posts/2018-06-25-breethe-elixir.md
> +- `:bc` - _black carbon_, a component of fine particulate matter - causes human morbidity and premature mortality
It felt a little weird to just leave the atoms without explanation, I'll do the rewrite and see if it still makes sense to keep them in.

2018-08-03 08:36 UTC, niklaslong commented
@marcoow My plan was to go through `breethe.ex` in the second post (as well as the async stuff), although it might make more sense to include it here, or at least introduce it 🤔

2018-08-03 08:38 UTC, marcoow commented
Yeah, I think the fact that all of what you're describing is abstracted away behind the app's public interface that is `breethe.ex` is really a key point.

2018-08-03 08:39 UTC, marcoow commented on blog/_posts/2018-06-25-breethe-elixir.md
> +- `:bc` - _black carbon_, a component of fine particulate matter - causes human morbidity and premature mortality
Yeah but I think just saying `:o3` is Ozone is probably enough :)

2018-08-13 06:37 UTC, niklaslong commented on blog/_posts/2018-06-25-breethe-elixir.md
> +Breethe.app is an air quality app. This means our back end interacts with with a number of external APIs to aggregate the data:
fixed

2018-08-13 06:37 UTC, niklaslong commented on blog/_posts/2018-06-25-breethe-elixir.md
> +Over the last couple of months, we have been building an Elixir umbrella app to serve as our back end for breethe.app, which provides instant access to up to date air quality data for locations acros
fixed

2018-08-13 06:37 UTC, niklaslong commented on blog/_posts/2018-06-25-breethe-elixir.md
> +The breethe.app project is intirely open-source. Please take a look at the code for the [client](https://github.com/simplabs/breethe-client) and the [back end](https://github.com/simplabs/breethe-ser
fixed

2018-08-13 06:37 UTC, niklaslong commented on blog/_posts/2018-06-25-breethe-elixir.md
> +- `:bc` - _black carbon_, a component of fine particulate matter - causes human morbidity and premature mortality
fixed

2018-08-13 06:38 UTC, niklaslong commented on blog/_posts/2018-06-25-breethe-elixir.md
> +- `:ppm` - parts per million (ppm) (needs to be removed as it is unused troughout the app)
fixed

2018-08-13 06:38 UTC, niklaslong commented on blog/_posts/2018-06-25-breethe-elixir.md
> +The `google` directory contains a single file called `geocoding.ex`. In that file we have written code which will request data from [Google's geocoding API](https://developers.google.com/maps/documen
fixed

2018-08-13 06:38 UTC, niklaslong commented on blog/_posts/2018-06-25-breethe-elixir.md
> +Firstly, let me give you a little context concerning the function parameters. We want to be able to search `locations` both by `search_term` (e.g.: `"Münich"`) or `lat, lon` (e.g.: `51.1789,-1.8261`)
fixed

2018-08-14 14:27 UTC, niklaslong commented
I've slimmed this down a little. I think adding a section about the Breethe module and the async optimisations would make this one too long, hence why I didn't add it here. I think this is an improvement over the last version - let me know what you think.

2018-08-20 12:27 UTC, marcoow reviewed
I think this can evolve into a good post but currently it's not necessarily one on umbrella apps but more on about the specific data model and related logic of Breethe (which I'm afraid is not particularly interesting to our readers 😞). I think I'd focus on the Umbrella aspect and ignore most of the rest.

In general, I think we should make all Breethe related posts more about particular topics that are relevant by themselves (in this case the concept of Umbrella apps), using Breethe as an example only rather than writing about Breethe and focussing on particular aspects. When writing about particular products people usually feel like you're trying to sell that product and in this case it's even something that nobody knows. Also, we're in fact not trying to sell Breethe to anyone but the whole point why we built it is so we could use it as an example later on :) I'd make that clearer in particular in the beginning though - focussing less on Breethe but rather the main topic of the post which is Umbrella apps.

I'm happy to sit down together and come up with an outline for this!

2018-08-20 13:45 UTC, niklaslong commented
@marcoow Thanks for the feedback! I'll bring it back to the drawing board and give it a thorough think.

2019-02-19 16:48 UTC, niklaslong commented
Closed in favour of #281

2019-02-19 16:48 UTC, closed without merging