[WIP] From SPA to PWA
mainmatter/mainmatter.com pull request #212
Opened 2018-08-02 20:52 UTC by marcoow

This is the second part in the blog post serices on Breethe, covering PWAs and offline functionality (Web Manifest, Service Workers, offline data with `IndexedDB` and Orbit, testing).

2018-08-07 15:22 UTC, jayjayjpg reviewed
This is a really detailed and insightful post :sparkles: I left a few comments and questions, feel free to let me know what you think

2018-08-07 15:22 UTC, jayjayjpg commented on css/app.scss
> +    margin: 0 auto 20px auto;
I think there's also the possibility to only pass 3 values to `margin` and `padding` to define this here, along the form of 

```
margin: <top> <left-and-right> <bottom>;
```

So this could also be

```css
  margin: 0 auto 20px;
```

See also [here](https://developer.mozilla.org/de/docs/Web/CSS/margin#Beispiele) for more context.

2018-08-07 15:22 UTC, jayjayjpg commented on blog/_posts/2018-07-24-from-spa-to-pwa.md
> +Single Page Apps (SPAs) already meant a giant leap forward for web apps, PWAs
I think you might have already explored that idea in the first blog post, but while reading the introduction here in this separate blog post I think as a reader I'd also find it useful to hear about one or two properties of SPAs which verify the statement that

```
Single Page Apps (SPAs) already meant a giant leap forward for web apps [...]
```
another time, as in "Why have SPAs advanced the way web apps are built today?". I think it's then also easier to understand from the next part of the text why `PWAs are taking things even one step further`, by comparing what PWAs do in contrast to common web apps directly and solidifies the motivation of the following blog post imho. What do you think?

2018-08-07 15:22 UTC, jayjayjpg commented on blog/_posts/2018-07-24-from-spa-to-pwa.md
> +but all generally applicable to all frontend stacks.
I think it would be 

```
[...] but are applicable to all frontend stacks.
```

2018-08-07 15:22 UTC, jayjayjpg commented on blog/_posts/2018-07-24-from-spa-to-pwa.md
> +In short, Progressive Web Apps are websites that look and behave like native
Would it be useful to also add one or two benefits of web apps compared to native apps here? I could imagine something along the lines of

```
In short, Progressive Web Apps are websites which offer a user experience which can barely be distinguished from native apps. On top of that PWAs also offer benefits in terms of reach and cost efficiency - an app which has been built once can be run on almost any device regardless of the OS operating it making it extremely easy to reach users and saving development costs for porting. 
```

What do you think?

2018-08-07 15:22 UTC, jayjayjpg commented on blog/_posts/2018-07-24-from-spa-to-pwa.md
> +and web apps are now capable of offering equal if not better user experiences
:+1:

2018-08-07 15:22 UTC, jayjayjpg commented on blog/_posts/2018-07-24-from-spa-to-pwa.md
> +In short, Progressive Web Apps are websites that look and behave like native
I just see that you mention several characteristics already further down below. Might it make sense to just state that there are several benefits to PWAs that are further explained below here already? What do you think?

2018-08-07 15:22 UTC, jayjayjpg commented on blog/_posts/2018-07-24-from-spa-to-pwa.md
> +* App-likeliness: they offer the rich user experience that users know and love
I'm not sure about the term `App-likeliness` - do you have a British / American source which is using this term as well?

2018-08-07 15:22 UTC, jayjayjpg commented on blog/_posts/2018-07-24-from-spa-to-pwa.md
> +browser. The App Manifest is a simple JSON file with key/value pairs that
I think it would be 

```
[...] is a simple JSON file [...] that configures the main [....]
```

2018-08-07 15:22 UTC, jayjayjpg commented on blog/_posts/2018-07-24-from-spa-to-pwa.md
> +* `orientation`: the orientation to launch the app with if only one orientation
I'm unsure what `or makes sense for the app` means yet. Do you say here that if the app developer would like to offer their app only in one specific orientation they can set this preferred orientation via this key?

2018-08-07 15:22 UTC, jayjayjpg commented on blog/_posts/2018-07-24-from-spa-to-pwa.md
> +gets installed into the users browser and are subsequently able to intercept
I think it would be 

```
They are standalone pieces [...] that get installed [...] the user's browser [...]
```

2018-08-07 15:22 UTC, jayjayjpg commented on blog/_posts/2018-07-24-from-spa-to-pwa.md
> +that rejects if the service worker could not successfully be registered.
I think it would be 

```
could not be registered successfully.
```

2018-08-07 15:22 UTC, jessica-jordan commented on blog/_posts/2018-07-24-from-spa-to-pwa.md
> +does not even have 100 lines of code. Of course being able to start up the app
This is a pretty neat lead into the next sub section :+1:

2018-08-07 15:22 UTC, jessica-jordan commented on blog/_posts/2018-07-24-from-spa-to-pwa.md
> +  request.onsuccess = function(event) {
If I see correctly, the `event` parameter doesn't seem to be needed in the following function. Does it make sense to just remove it then or should something be replaced below?

2018-08-07 15:22 UTC, jessica-jordan commented on blog/_posts/2018-07-24-from-spa-to-pwa.md
> +Orbit.js works based on a schema definition that defines the models, their
Might it make sense to link to Orbit.js here? I can imagine quite a few readers of that blog post might want to read more about it. What do you think?

2018-08-07 15:22 UTC, jessica-jordan commented on blog/_posts/2018-07-24-from-spa-to-pwa.md
> +import Store from '@orbit/store';
I assume the `schema` would also have to be imported here to be used in the instantiation of the `Store`, correct?

2018-08-07 15:22 UTC, jessica-jordan commented on blog/_posts/2018-07-24-from-spa-to-pwa.md
> +(and I'm sure this is true for anyone reading this as well) would never ship
I really like the part that affirms that we at our company value testing and that we believe that it is an `essential part of modern software engineering`. I'm not entirely sure about

```
[you] would never ship code that is not fully tested
```

I feel that there are still  a good number of developers out there who don't substantially test their projects due to all kinds of reasons that might be more or less outside of their control. Might it make sense to rephrase to sound either more neutral or more empowering? To me it feels that stating that nobody would ever ship untested code is a bit shaming. What do you think about it?

2018-08-07 15:22 UTC, jessica-jordan commented on blog/_posts/2018-07-24-from-spa-to-pwa.md
> +      await page.setOfflineMode(true);
How does `page.setOfflineMode` work?

2018-08-07 15:22 UTC, jessica-jordan commented on blog/_posts/2018-07-24-from-spa-to-pwa.md
> +advantages of classic server rendered websites. In the next post in this
I think it would be `the next post of this series`

2018-08-08 09:55 UTC, marcoow commented on css/app.scss
> +    margin: 0 auto 20px auto;
I never remember that :) fixed

2018-08-08 09:56 UTC, marcoow commented on blog/_posts/2018-07-24-from-spa-to-pwa.md
> +browser. The App Manifest is a simple JSON file with key/value pairs that
Hm, I think _"configure"_ refers to the key value pairs here, not the JSON file?

2018-08-08 09:57 UTC, marcoow commented on blog/_posts/2018-07-24-from-spa-to-pwa.md
> +* `orientation`: the orientation to launch the app with if only one orientation
Yes, that's the idea - I think I'll just leave _"or makes sense for the app"_ out

2018-08-08 09:58 UTC, marcoow commented on blog/_posts/2018-07-24-from-spa-to-pwa.md
> +  request.onsuccess = function(event) {
Yes, good catch 👍

2018-08-08 09:59 UTC, marcoow commented on blog/_posts/2018-07-24-from-spa-to-pwa.md
> +import Store from '@orbit/store';
yep 👍

2018-08-08 10:00 UTC, marcoow commented on blog/_posts/2018-07-24-from-spa-to-pwa.md
> +      await page.setOfflineMode(true);
I don't know - that's part of the puppeteer API but I guess it would lead to far away from the main topic to explore that in more detail?

2018-08-13 07:00 UTC, jorgelainfiesta commented
Really good entry! I like how it introduces general concepts and then dives into specifics to provide a very insightful perspective on PWAs.

2018-08-13 08:36 UTC, niklaslong reviewed
This is a really great post! The flow is nice between sections and the explanations/examples are really clear. I especially liked the context and detailed introduction you gave about PWAs at the beginning of the post.  🎉

2018-08-14 07:58 UTC, jessica-jordan commented on blog/_posts/2018-07-24-from-spa-to-pwa.md
> +      await page.setOfflineMode(true);
Yes sure, that makes sense - I  just wasn't aware of that when reading it for the first time but maybe other readers would pick that up differently

2018-08-14 08:02 UTC, marcoow commented on blog/_posts/2018-07-24-from-spa-to-pwa.md
> +      await page.setOfflineMode(true);
We could add a code comment saying this simulates the browser being offline (I believe this is the same functionality that you're using when you put the network to offline in the _"Network"_ tab in Developer Tools)

2018-08-14 14:43 UTC, oliverbarnes requested changes
awesome post 👏 very well written, enjoyed reading it and learned a lot. just the small comments I made, else this is good to go for me

2018-08-14 14:43 UTC, oliverbarnes commented on blog/_posts/2018-07-24-from-spa-to-pwa.md
> +better choice than native apps in a large number of scenarios now.
eloquently put. but would be great to see some examples here to back this claim

2018-08-14 14:43 UTC, oliverbarnes commented on blog/_posts/2018-07-24-from-spa-to-pwa.md
> +* **Installability**: they can be installed on the user's home screen without
How about *Ease of installation* instead? better if we can avoid yet another "*ability" neologism

2018-08-14 14:43 UTC, oliverbarnes commented on blog/_posts/2018-07-24-from-spa-to-pwa.md
> +* **Connectivity Independence**: they work on low quality networks or without
Wouldn't *Autonomy* be more accurate than *Indepencence*?

2018-08-14 14:43 UTC, oliverbarnes commented on blog/_posts/2018-07-24-from-spa-to-pwa.md
> +Many of the orignal ideas behind Gears found their way into the HTML5 spec
missing *i* in *original*

2018-08-14 14:43 UTC, oliverbarnes commented on blog/_posts/2018-07-24-from-spa-to-pwa.md
> +
And for online mode, I assume these tests would have to be complemented by tests hitting mirage-like api stubs?

2018-08-16 18:55 UTC, marcoow commented on blog/_posts/2018-07-24-from-spa-to-pwa.md
> +better choice than native apps in a large number of scenarios now.
added a link to https://appsco.pe

2018-08-16 18:56 UTC, marcoow commented on blog/_posts/2018-07-24-from-spa-to-pwa.md
> +* **Installability**: they can be installed on the user's home screen without
this is from the Wikipedia article and I think sort of an official term

2018-08-16 18:56 UTC, marcoow commented on blog/_posts/2018-07-24-from-spa-to-pwa.md
> +* **Connectivity Independence**: they work on low quality networks or without
same as above

2018-08-16 18:58 UTC, marcoow commented on blog/_posts/2018-07-24-from-spa-to-pwa.md
> +
we are actually running the tests against an express server that re-uses the Ember CLI mock server endpoints: https://github.com/simplabs/breethe-client/blob/master/integration-tests/helpers/api-server.js - I think going into a lot of detail here would be beyond the scope of the article?

2018-08-21 10:22 UTC, oliverbarnes commented on blog/_posts/2018-07-24-from-spa-to-pwa.md
> +
Agreed, wouldn't go into a lot of detail. would just a add a note, but it's not a big deal if nothing is said

2018-08-21 10:24 UTC, oliverbarnes approved these changes

2018-08-22 08:48 UTC, mansona approved these changes
This is a **great** post 🎉 I know I have a lot of comments but most of them are just style-related and I don't think any of them are blockers (hence this being an approval)

2018-08-22 08:48 UTC, mansona commented on blog/_posts/2018-07-24-from-spa-to-pwa.md
> +Single Page Apps (SPAs) already meant a giant leap forward, PWAs are taking
I would say "have already meant a giant leap forward" or "have already been a giant leap forward"

2018-08-22 08:48 UTC, mansona commented on blog/_posts/2018-07-24-from-spa-to-pwa.md
> +the situation actually is, is the first step for everyone to question their
this comma seems a bit out of place 🤔 I know it seems necessary because of the double "is" but we might be able to get around it with a restructure?

"having data that shows the depth of the situation is the first step" 
"having data on the current situation is the first step" 

I don't actually know what's best here 😖

2018-08-22 08:48 UTC, mansona commented on blog/_posts/2018-07-24-from-spa-to-pwa.md
> +([not always to the benefit of everyone](https://en.wikipedia.org/wiki/Mobile_phone_overuse)
I would probably just remove this subclause 🤔 I don't think it actually adds much to the paragraph and it doesn't necessarily help the premise of the piece. If we have people using PWAs they can still overuse their phones 😂

2018-08-22 08:48 UTC, mansona commented on blog/_posts/2018-07-24-from-spa-to-pwa.md
> +  leading to long download times which are particularly painful on often spotty
I don't know if we need the word "often" here 🤔 maybe something like "painful on less reliable mobile connections"

2018-08-22 08:48 UTC, mansona commented on blog/_posts/2018-07-24-from-spa-to-pwa.md
> +instantaneously - if done right, even on spotty mobile connections.
if you make the above change ☝️  I would recommend changing "spotty mobile connections" to "unreliable mobile connections" just for consistency.

that being said I'm not sure you should accept the above change 😂

2018-08-22 08:48 UTC, mansona commented on blog/_posts/2018-07-24-from-spa-to-pwa.md
> +load times and superior discoverability, Progressive Web Apps are clearly the
I feel like "superior discoverability" might need backing up with an explanation before it's used here to justify the use of PWAs 🤔 **I** know as a developer that you mean in terms of linkability (with URLs etc.) but one of the things that is often referenced as a **negative** for PWAs is the fact that they are **less** discoverable because they are not in App Stores

2018-08-22 08:48 UTC, mansona commented on blog/_posts/2018-07-24-from-spa-to-pwa.md
> +load times and superior discoverability, Progressive Web Apps are clearly the
Although I know there is some movement on this subject recently, I was at a conference where I think it was a bit of talk about getting PWAs into app stores 🤔 here is the link if anyone is interested: https://skillsmatter.com/skillscasts/10583-keynote-the-survival-kit-of-the-web-and-pwas

2018-08-22 08:48 UTC, mansona commented on blog/_posts/2018-07-24-from-spa-to-pwa.md
> +businesses with ca. 84% of the global user base on browsers and OSes capable of
I know ca. stands for circa but I would have thought it's not a very common word to use 🤔 and even less common to abbreviate

is there any reason we're not just using the word "approximately" here?

2018-08-22 08:48 UTC, mansona commented on blog/_posts/2018-07-24-from-spa-to-pwa.md
> +![The Breethe PWA starting up standalone](/images/posts/2018-07-24-from-spa-to-pwa/breethe-startup-standalone.gif)
This is more of a "think about this for the future" kind of comment so ignore for now if it's not important. 

We may want to think about not using animated gifs but instead using autoplay highly compressed video. I recently hosted a meetup that talked about this exact topic: https://youtu.be/jHu2V0xsm4E?t=27m13s

2018-08-22 08:48 UTC, mansona commented on blog/_posts/2018-07-24-from-spa-to-pwa.md
> +that is essentially made for loading anything that it requires remotely, that
It might be possible to improve the readability of this sentence 🤔 

"For a browser-based application designed to load required assets remotely, that is no easy task" ¯\_(ツ)_/¯

2018-08-22 08:48 UTC, mansona commented on blog/_posts/2018-07-24-from-spa-to-pwa.md
> +is no easy task. One of the first approaches for achieving just this was
I would remove "just"

2018-08-22 08:48 UTC, mansona commented on blog/_posts/2018-07-24-from-spa-to-pwa.md
> +ecosystem though and was discontinued in 2010.
I would remove this "though" to remove duplication with the next sentence

2018-08-22 08:48 UTC, mansona commented on blog/_posts/2018-07-24-from-spa-to-pwa.md
> +be used for tracking users or keeping their sessions alive when the browser is
I think the use of `cannot` here is implying that they *can't* be used for something 🤔 I would phrase this as "Cookies have been around for quite some time, and not only can they be used for tracking users...."

2018-08-22 08:48 UTC, mansona commented on blog/_posts/2018-07-24-from-spa-to-pwa.md
> +With this setup, all data that ever gets loaded by the app while the device is
i would remove "ever" here

2018-08-22 08:48 UTC, mansona commented on blog/_posts/2018-07-24-from-spa-to-pwa.md
> +online is available for later offline use where it will be read from
I think we need a comma here 🤔 "for later offline use, where it will be read..."

2018-08-22 08:48 UTC, mansona commented on blog/_posts/2018-07-24-from-spa-to-pwa.md
> +the device comes back online - refer to the
I think this sentence may need a comma 🤔 

"This mechanism works the other way round as well of course, such that the app..." 

And I would add a `then` in later too:  "while offline and then sync these changes"

2018-08-22 08:48 UTC, mansona commented on blog/_posts/2018-07-24-from-spa-to-pwa.md
> +of these for Breethe).
what do you mean by "quite some" in this context? do you mean "quite a lot"? 🤔 or is it more so talking how cool the tests are?

2018-08-22 08:48 UTC, mansona commented on blog/_posts/2018-07-24-from-spa-to-pwa.md
> +      await page.setOfflineMode(true);
We might want to update this code to include @jorgelainfiesta's work on "waiting for the service worker to be ready before going offline" https://github.com/simplabs/breethe-client/blob/master/integration-tests/offline-test.js#L4

2018-08-23 13:11 UTC, marcoow commented on blog/_posts/2018-07-24-from-spa-to-pwa.md
> +
I'd rather say nothing than get people excited about the topic but then not really providing much detail. mirage etc. is worth a post of its own really.

2018-08-23 13:13 UTC, marcoow commented on blog/_posts/2018-07-24-from-spa-to-pwa.md
> +      await page.setOfflineMode(true);
added a comment

2018-08-23 13:14 UTC, marcoow commented on blog/_posts/2018-07-24-from-spa-to-pwa.md
> +Single Page Apps (SPAs) already meant a giant leap forward, PWAs are taking
fixed

2018-08-23 13:15 UTC, marcoow commented on blog/_posts/2018-07-24-from-spa-to-pwa.md
> +the situation actually is, is the first step for everyone to question their
changed to _"…shows the depth of the situation…"_

2018-08-23 13:16 UTC, marcoow commented on blog/_posts/2018-07-24-from-spa-to-pwa.md
> +([not always to the benefit of everyone](https://en.wikipedia.org/wiki/Mobile_phone_overuse)
yeah, good point - I'll remove it

2018-08-23 13:17 UTC, marcoow commented on blog/_posts/2018-07-24-from-spa-to-pwa.md
> +  leading to long download times which are particularly painful on often spotty
👍

2018-08-23 13:17 UTC, marcoow commented on blog/_posts/2018-07-24-from-spa-to-pwa.md
> +instantaneously - if done right, even on spotty mobile connections.
I think this is good

2018-08-23 13:20 UTC, marcoow commented on blog/_posts/2018-07-24-from-spa-to-pwa.md
> +load times and superior discoverability, Progressive Web Apps are clearly the
I think we could just change this to _"…load times and superior discoverability (allowing direct access via the browser and search engines), Progressive Web Apps are clearly the…"_?

2018-08-23 13:21 UTC, marcoow commented on blog/_posts/2018-07-24-from-spa-to-pwa.md
> +businesses with ca. 84% of the global user base on browsers and OSes capable of
In german it's super common actually - but maybe not in english or course. I'll change that.

2018-08-23 13:21 UTC, marcoow commented on blog/_posts/2018-07-24-from-spa-to-pwa.md
> +![The Breethe PWA starting up standalone](/images/posts/2018-07-24-from-spa-to-pwa/breethe-startup-standalone.gif)
👍

2018-08-23 13:22 UTC, marcoow commented on blog/_posts/2018-07-24-from-spa-to-pwa.md
> +that is essentially made for loading anything that it requires remotely, that
👍

2018-08-23 13:23 UTC, marcoow commented on blog/_posts/2018-07-24-from-spa-to-pwa.md
> +is no easy task. One of the first approaches for achieving just this was
👍

2018-08-23 13:23 UTC, marcoow commented on blog/_posts/2018-07-24-from-spa-to-pwa.md
> +ecosystem though and was discontinued in 2010.
👍

2018-08-23 13:24 UTC, marcoow commented on blog/_posts/2018-07-24-from-spa-to-pwa.md
> +be used for tracking users or keeping their sessions alive when the browser is
👍

2018-08-23 13:24 UTC, marcoow commented on blog/_posts/2018-07-24-from-spa-to-pwa.md
> +With this setup, all data that ever gets loaded by the app while the device is
👍

2018-08-23 13:24 UTC, marcoow commented on blog/_posts/2018-07-24-from-spa-to-pwa.md
> +online is available for later offline use where it will be read from
👍

2018-08-23 13:25 UTC, marcoow commented on blog/_posts/2018-07-24-from-spa-to-pwa.md
> +the device comes back online - refer to the
👍

2018-08-23 13:26 UTC, marcoow commented on blog/_posts/2018-07-24-from-spa-to-pwa.md
> +of these for Breethe).
I meant _"quite a lot"_, yes - will change

2018-08-23 13:27 UTC, marcoow commented on blog/_posts/2018-07-24-from-spa-to-pwa.md
> +      await page.setOfflineMode(true);
I think that's way too much detail tbh. Almost all of the code examples are missing stuff as they would otherwise be much harder to understand. They are mainly used for getting the general idea across and not really meant as copy/pastable code blocks.

2018-08-23 13:28 UTC, marcoow commented
thanks @mansona - this kind of comments that makes the text more fluent is super useful!

2018-08-24 08:45 UTC, merged