add designer job posting
mainmatter/mainmatter.com pull request #217
Opened 2018-08-13 19:47 UTC by marcoow

This adds a job posting for a UI/UX designer

2018-08-14 12:47 UTC, oliverbarnes requested changes

2018-08-14 12:47 UTC, oliverbarnes commented on jobs/index.html
> +                    We expect you to be able to<strong>create appealing visual designs</strong> and user experiences as well as <strong>implementing these designs in HTML and CSS/Sass</strong>.
missing space between `to` and `strong` tag

2018-08-14 12:47 UTC, oliverbarnes commented on jobs/index.html
> +                    We expect you to be able to<strong>create appealing visual designs</strong> and user experiences as well as <strong>implementing these designs in HTML and CSS/Sass</strong>.
"We expect you to create... as well as *implement*" (without the `ing`)

2018-08-14 12:47 UTC, oliverbarnes commented on jobs/index.html
> +                    We expect you to be able to<strong>create appealing visual designs</strong> and user experiences as well as <strong>implementing these designs in HTML and CSS/Sass</strong>.
shouldn't the designer also have basic programming/javascript skills and be experienced in designing SPAs? Basic git and github skills desirable, as well - for pushing html mockups to github/gitlab and getting them reviewed, for instance

2018-08-14 12:47 UTC, oliverbarnes commented on jobs/index.html
> +                  <p>simplabs is a small and growing Engineering Consultancy based in Munich.
*engineering consultancy*, lowercased

2018-08-14 12:47 UTC, oliverbarnes commented on jobs/index.html
> +                    We <strong>develop custom solutions using modern technologies for our clients, help clients in developing their products and also mentoring and workshops</strong>.
We develop custom solutions using modern technologies, help clients develop their products, and offer mentoring and workshops for both client employees and the tech community at large

2018-08-14 12:47 UTC, oliverbarnes commented on jobs/index.html
> +                  <p>We focus on Web Engineering with <strong>Ember.js, Elixir/Phoenix and Ruby on Rails</strong> and are consistently involved in these open-source communities.
*web engineering*, lowercase

2018-08-14 12:47 UTC, oliverbarnes commented on jobs/index.html
> +                  <p>We support team members to attend and participate in conferences and other IT events and we mentor and encourage interested engineers to present at events themselves.
How about:

"We encourage team members to attend and present at conferences and other IT events, providing support and mentoring for presentations."

Tighter, and good to remove *engineers* since the person we're trying to attract isn't one ;) more inclusive

2018-08-14 12:47 UTC, oliverbarnes commented on jobs/index.html
> +                  <p>We strongly believe that diversity of experience contributes to a wider outlook of our team that not only improves our working atmosphere but also increases our productivity as a
I'd remove the *that*s - "We strongly believe diversity of experience...", "and not only improves our working atmosphere..."

2018-08-14 12:47 UTC, oliverbarnes commented on jobs/index.html
> +                    <li>you're sensitive to clients' needs <strong>and you're creating trusting work relationships</strong> by reviewing the work of others or discussing UI/UX options in a collaborat
"and building trust, reviewing the work of others and discussing UI/UX options in a friendly collaborative fashion"

2018-08-14 12:47 UTC, oliverbarnes commented on jobs/index.html
> +                    <li>you will help clients with their projects as well as support our <strong>open source projects</strong></li>
I'd remove the *you* from these statements. so this one would start with "helping clients with their projects...". Adding the *you* makes it a bit too forceful, that always put me off in job descriptions

2018-08-14 12:47 UTC, oliverbarnes commented on jobs/index.html
> +                    <li>we're committed to our participation in the open source and general tech community and <strong>give talks, attend conferences, host meetups</strong> etc. If you enjoy doing th
"participating in open source projects and community. Big plus if you like giving talks or would like to start doing it, we'll give you all necessary support..."

2018-08-14 12:47 UTC, oliverbarnes commented on jobs/index.html
> +                    <li>we're committed to our participation in the open source and general tech community and <strong>give talks, attend conferences, host meetups</strong> etc. If you enjoy doing th
(no need to the "we're committed" part, we already do enough of that elsewhere, and here we're talking about the designer's responsibilities, not our commitments)

2018-08-14 12:47 UTC, oliverbarnes commented on jobs/index.html
> +                    <li>showing attention to detail</li>
no need for *showing*, the skill is just *attention to detail*

2018-08-14 12:47 UTC, oliverbarnes commented on jobs/index.html
> +                    <li>Your are up-to-date with best practices in UI/UX as well as HTML/CSS</li>
fluency in best practices

2018-08-14 12:47 UTC, oliverbarnes commented on jobs/index.html
> +                    we enable you to <strong>take part in modern projects for clients ranging from small startups to big enterprises, national as well as international</strong>.
This initial chunk of text before *We work* should really go in the **Who we are** section

2018-08-14 12:47 UTC, oliverbarnes commented on jobs/index.html
> +                  <p>We also offer the <strong>opportunity to travel internationally</strong> - either to visit clients on-site for a limited time or to attend tech conferences (if you enjoy speaking
"We travel from time to client offices and conferences". The part about speaking at events and support for it has already been well explained before, it's redundant and sounding a little over-eager heheh

2018-08-14 12:47 UTC, oliverbarnes commented on jobs/index.html
> +                  <p>We start the <strong>day with our standup meeting</strong> in which everyone gives an update on what they worked on the previous day and what they plan to do on the current day.
maybe the feature branch part is irrelevant for a designer?

2018-08-14 12:47 UTC, oliverbarnes commented on jobs/index.html
> +                  <p>Apart from working on client projects we also maintain a bunch of open source libraries and tools on which you're invited to work on as well.</p>
I'd replace *bunch* with a *varied* or something like it

2018-08-14 12:47 UTC, oliverbarnes commented on jobs/index.html
> +                  <p>Apart from working on client projects we also maintain a bunch of open source libraries and tools on which you're invited to work on as well.</p>
Perhaps we could link to the playbook here?

2018-08-14 12:47 UTC, oliverbarnes commented on jobs/index.html
> +                    <li>a <strong>flextime schedule</strong> to accommodate the needs of caretakers</li>
not just needs of caretakers, but also any quality of life needs (sports, hobbies, etc), right? I think it's important to mention caretakers, but also assert valuing people's time and personal activities in general

2018-08-14 12:54 UTC, oliverbarnes commented on jobs/index.html
> +                    We expect you to be able to<strong>create appealing visual designs</strong> and user experiences as well as <strong>implementing these designs in HTML and CSS/Sass</strong>.
(and experience with PWAs desired)

2018-08-16 16:20 UTC, marcoow commented on jobs/index.html
> +                    We expect you to be able to<strong>create appealing visual designs</strong> and user experiences as well as <strong>implementing these designs in HTML and CSS/Sass</strong>.
added something on github; with respect to SPAs/PWAs, I wouldn't make it too specific? We're saying they should have design experience for the web and know HTML/CSS already - I wouldn't want to exclude potentially good candidates only because they haven't worked on a PWA before (not many people have anyway).

2018-08-16 16:21 UTC, marcoow commented on jobs/index.html
> +                  <p>simplabs is a small and growing Engineering Consultancy based in Munich.
fixed

2018-08-16 16:21 UTC, marcoow commented on jobs/index.html
> +                    We <strong>develop custom solutions using modern technologies for our clients, help clients in developing their products and also mentoring and workshops</strong>.
fixed

2018-08-16 16:22 UTC, marcoow commented on jobs/index.html
> +                  <p>We focus on Web Engineering with <strong>Ember.js, Elixir/Phoenix and Ruby on Rails</strong> and are consistently involved in these open-source communities.
fixed

2018-08-16 16:23 UTC, marcoow commented on jobs/index.html
> +                  <p>We support team members to attend and participate in conferences and other IT events and we mentor and encourage interested engineers to present at events themselves.
fixed

2018-08-16 16:24 UTC, marcoow commented on jobs/index.html
> +                  <p>We also offer the <strong>opportunity to travel internationally</strong> - either to visit clients on-site for a limited time or to attend tech conferences (if you enjoy speaking
removed

2018-08-16 16:25 UTC, marcoow commented on jobs/index.html
> +                  <p>We start the <strong>day with our standup meeting</strong> in which everyone gives an update on what they worked on the previous day and what they plan to do on the current day.
no, as we expect them to do HTML/CSS we want them to understand the PR workflow

2018-08-16 16:25 UTC, marcoow commented on jobs/index.html
> +                  <p>Apart from working on client projects we also maintain a bunch of open source libraries and tools on which you're invited to work on as well.</p>
fixed

2018-08-16 16:25 UTC, marcoow commented on jobs/index.html
> +                  <p>Apart from working on client projects we also maintain a bunch of open source libraries and tools on which you're invited to work on as well.</p>
for sure in the future but it's not public yet

2018-08-16 16:27 UTC, marcoow commented on jobs/index.html
> +                    <li>a <strong>flextime schedule</strong> to accommodate the needs of caretakers</li>
Hm, I wouldn't promise too much here…

2018-08-20 12:27 UTC, marcoow commented
@oliverbarnes: can you update/resolve the review? We should release this.

2018-08-21 08:12 UTC, Turbo87 approved these changes

2018-08-21 08:12 UTC, Turbo87 commented on jobs/index.html
> +                    <li>basic familiarity with version control systems such as git</li>
this conflicts somewhat with the above point. I'd suggest to merge them into one point.

2018-08-21 08:12 UTC, Turbo87 commented on jobs/index.html
> +                    Beyond a supportive team culture and a relaxed work atmosphere in our office in the city center (we're actually right next to the Isar!) for on-site engineers,
> city center **of Munich**

2018-08-21 08:12 UTC, Turbo87 commented on jobs/index.html
> +                    <li>chance and suuport to <strong>attend and speak at international conferences</strong></li>
typo: support

2018-08-21 08:12 UTC, Turbo87 commented on jobs/index.html
> +                    We're looking forward to <strong>a link to your Github account if you have one or any other samples of your previous work</strong>.
"Github account" seems unusual for designers 🤔

2018-08-21 08:12 UTC, marcoow commented on jobs/index.html
> +                    <li>basic familiarity with version control systems such as git</li>
🤦‍♂️

2018-08-21 08:14 UTC, marcoow commented on jobs/index.html
> +                    Beyond a supportive team culture and a relaxed work atmosphere in our office in the city center (we're actually right next to the Isar!) for on-site engineers,
👍

2018-08-21 08:14 UTC, marcoow commented on jobs/index.html
> +                    <li>chance and suuport to <strong>attend and speak at international conferences</strong></li>
👍

2018-08-21 08:15 UTC, marcoow commented on jobs/index.html
> +                    We're looking forward to <strong>a link to your Github account if you have one or any other samples of your previous work</strong>.
👍

2018-08-21 08:31 UTC, niklaslong approved these changes

2018-08-21 09:45 UTC, marcoow commented on jobs/index.html
> +                    <li>you're sensitive to clients' needs <strong>and you're creating trusting work relationships</strong> by reviewing the work of others or discussing UI/UX options in a collaborat
fixed

2018-08-21 09:49 UTC, marcoow commented on jobs/index.html
> +                    <li>you will help clients with their projects as well as support our <strong>open source projects</strong></li>
fixed

2018-08-21 09:50 UTC, marcoow commented on jobs/index.html
> +                    <li>we're committed to our participation in the open source and general tech community and <strong>give talks, attend conferences, host meetups</strong> etc. If you enjoy doing th
fixed

2018-08-21 09:51 UTC, marcoow commented on jobs/index.html
> +                    <li>showing attention to detail</li>
fixed

2018-08-21 09:52 UTC, marcoow commented on jobs/index.html
> +                    <li>Your are up-to-date with best practices in UI/UX as well as HTML/CSS</li>
fixed

2018-08-21 09:53 UTC, oliverbarnes commented on jobs/index.html
> +                    <li>a <strong>flextime schedule</strong> to accommodate the needs of caretakers</li>
I don't see the difference between stepping out to take care of a child and stepping out to take care of oneself doing yoga, paragliding or a course, flextime is flextime, for quality of life in all its different aspects.

Besides being fair, it's also smart from a recruiting perspective - this will be attractive to designers who are not parents. Quite a few of them out there

2018-08-21 09:55 UTC, oliverbarnes commented on jobs/index.html
> +                    We expect you to be able to<strong>create appealing visual designs</strong> and user experiences as well as <strong>implementing these designs in HTML and CSS/Sass</strong>.
I wouldn't make it a requirement, just as a big nice plus if she happens to have experience or just familiarity with SPAs/PWAs

2018-08-21 10:00 UTC, marcoow commented on jobs/index.html
> +                    <li>a <strong>flextime schedule</strong> to accommodate the needs of caretakers</li>
But we are looking for a full time designer who works 5 days a week roughly at the same time as the rest of the team. Of course we're all flexible but _"Tuesday afternoon"_ is paragliding, _"Friday is my yoga-day"_ won't work…

2018-08-21 10:02 UTC, marcoow commented on jobs/index.html
> +                    <li>a <strong>flextime schedule</strong> to accommodate the needs of caretakers</li>
So I'd be worried to add something here that gives people a wrong impression in terms of what flexibility means…

2018-08-21 10:19 UTC, oliverbarnes commented on jobs/index.html
> +                    <li>a <strong>flextime schedule</strong> to accommodate the needs of caretakers</li>
I'm talking about stepping out for 2h for yoga or whatever (not a whole day or even afternoon), and starting later/earlier or ending later/earlier around other commitments. A full-time designer who's a parent will have had their parental leave etc, so their flextime besides that is the same as any quality of life flextime, in my opinion. 

The same goes for parents and people with other activities besides work: time is flexible but people need to be sensible with overlap time with coworkers, and with overall productivity. This doesn't need to be stated in the job ad, of course - just needs to be clarified during the interview. Like it would be for a parent.

We don't need to be afraid of wrong impressions with flextime any more than with wrong impressions about the ability of working fully remote.

Companies that prioritize quality of life are very attractive, specially with high quality professionals. Top notch people will take pay cuts to get out of big bad corporations and get more quality of life.

Just my opinion :) your call, of course

2018-08-21 10:24 UTC, marcoow commented on jobs/index.html
> +                    <li>a <strong>flextime schedule</strong> to accommodate the needs of caretakers</li>
I think we're talking about two different things here - I was under the impression flextime was referring to working non-fulltime. I changed this to be more general.

2018-08-21 10:36 UTC, marcoow commented
@oliverbarnes: can you make a proposal?

2018-08-21 10:37 UTC, oliverbarnes commented on jobs/index.html
> +                    <li>a <strong>flextime schedule</strong> to accommodate the needs of caretakers</li>
I see, yeah I mean in general terms. if you're talking about a specific benefit for fulltime employees who are parents (with tax breaks for the employer, etc), I'd probably mention both the specific and the general

2018-08-21 10:48 UTC, oliverbarnes reviewed
sure, added the proposal inline

2018-08-21 10:48 UTC, oliverbarnes commented on jobs/index.html
> +                    We are committed to increase the diversity of our team wherever we can and we encourage everyone to consider becoming a part of it.</p>
after the diversity line I'd add the part about flexible time and quality of life

"We value quality of life, and keep working times flexible to accommodate personal commitments like parenting, sports, hobbies and personal projects."

2018-08-23 13:08 UTC, marcoow commented on jobs/index.html
> +                    We are committed to increase the diversity of our team wherever we can and we encourage everyone to consider becoming a part of it.</p>
ok, added

2018-08-27 07:21 UTC, mansona approved these changes
Just another few comments on style. I'm approving because I don't think any of them on their own should stop us from releasing this 👍

2018-08-27 07:21 UTC, mansona commented on jobs/index.html
> +                  <p>We're currently <strong>looking for a UI/UX Designer</strong> to join our team. You'll work in a small, international team with <strong>responsibility early on</strong> and can h
I have a small feeling that the sentence "can have a large impact on client as well as open source projects"  doesn't quite work 🤔 

My first thought was that you need to change it to "can have a large impact on clients as well as ..." but I know you're trying to go for something that says "client projects and open source projects". I think that if you're implying that you might need to shorten the sentence "can have a large impact on client and open source projects" but I would prefer to be explicit: "can have a large impact on client projects, as well as open source projects."

2018-08-27 07:21 UTC, mansona commented on jobs/index.html
> +                    Events we're organizing include Rails Girls Munich, the Elixir User Group Munich among others.
So I don't know what it means to add a group to the "events we're organizing" but I run EmberJS Dublin and DublinJS 😂 #justathought

2018-08-27 07:21 UTC, mansona commented on jobs/index.html
> +                    by providing diversity sponsorships for people who are yet underrepresented in tech.</p>
I would just remove the "yet" in "people who are yet underrepresented in tech."

2018-08-27 07:21 UTC, mansona commented on jobs/index.html
> +                    paid time to work on open source projects, attend trainings and participate in mentorships and more.</p>
I think you've doubled the "final clause" in this list 🤔 

I would make it: "paid time to work on open source projects, attend trainings, participate in mentorships and more." or if our style is to use the "Oxford comma" then it would be "paid time to work on open source projects, attend trainings, participate in mentorships, and more."

2018-08-27 07:21 UTC, mansona commented on jobs/index.html
> +                  <p>We strongly believe that diversity of experience contributes to a wider outlook of our team that not only improves our working atmosphere but also increases our productivity as a
This feels like it might need a comma 🤔 

"wider outlook of our team, that not only improves our working..."

2018-08-27 07:21 UTC, mansona commented on jobs/index.html
> +                    We are committed to increase the diversity of our team wherever we can and we encourage everyone to consider becoming a part of it. We value quality of life, and keep working time
Maybe we don't need the comma here 😂 

"We value quality of life and keep working times flexible"

2018-08-27 07:21 UTC, mansona commented on jobs/index.html
> +                    <li><strong>30 days of paid vacation</strong></li>
eh... I could have this wrong because I'm new 😂 but isn't this 30 days **on top** of national holidays? It's just that this is a great quota if it includes national holidays but it's **amazing** if it's on top of them. Might as well make our strengths clear 💪

2018-08-27 07:21 UTC, mansona commented on jobs/index.html
> +                    We're looking forward to <strong> samples of your previous work</strong>.
shouldn't this be "we're looking forward to seeing samples of your previous work"? 🤔

2018-08-27 13:56 UTC, oliverbarnes approved these changes

2018-08-27 15:33 UTC, wadie approved these changes

2018-08-27 15:40 UTC, marcoow commented on jobs/index.html
> +                  <p>We're currently <strong>looking for a UI/UX Designer</strong> to join our team. You'll work in a small, international team with <strong>responsibility early on</strong> and can h
👍

2018-08-27 15:40 UTC, marcoow commented on jobs/index.html
> +                    Events we're organizing include Rails Girls Munich, the Elixir User Group Munich among others.
sure, I'll add those :)

2018-08-27 15:41 UTC, marcoow commented on jobs/index.html
> +                    by providing diversity sponsorships for people who are yet underrepresented in tech.</p>
👍

2018-08-27 15:42 UTC, marcoow commented on jobs/index.html
> +                    paid time to work on open source projects, attend trainings and participate in mentorships and more.</p>
👍

2018-08-27 15:43 UTC, marcoow commented on jobs/index.html
> +                  <p>We strongly believe that diversity of experience contributes to a wider outlook of our team that not only improves our working atmosphere but also increases our productivity as a
👍

2018-08-27 15:43 UTC, marcoow commented on jobs/index.html
> +                    We are committed to increase the diversity of our team wherever we can and we encourage everyone to consider becoming a part of it. We value quality of life, and keep working time
👍

2018-08-27 15:44 UTC, marcoow commented on jobs/index.html
> +                    <li><strong>30 days of paid vacation</strong></li>
I don't know how that relates to other countries actually - I think France might have more even ;)

2018-08-27 15:49 UTC, merged