Add Paolo's talk to Svelte Summit
mainmatter/mainmatter.com pull request #2174
Opened 2023-10-30 15:15 UTC by emmasofiah2o

Add talk to event description

2023-10-30 16:59 UTC, marcoow requested changes

2023-10-30 16:59 UTC, marcoow commented on src/calendar/2023-11-11-svelte-summit.md
> +happening in the community. Mainmatter's Senior Frontend Engineer Paolo Ricciuti
```suggestion
happening in the community. Mainmatter's Svelte expert Paolo Ricciuti
```

2023-10-30 16:59 UTC, marcoow commented on src/calendar/2023-11-11-svelte-summit.md
> +and we are supporting the event as a Gold Sponsor.
```suggestion
and we are supporting the event as a Gold Sponsor as well.
```

2023-10-31 11:58 UTC, marcoow commented on src/workshops/telemetry-for-rust-apis.md
> +      logged?).
this should not be in this PR

2023-10-31 12:37 UTC, emmasofiah2o commented on src/workshops/telemetry-for-rust-apis.md
> +      logged?).
Yes. There are problems with linting. I tried rebasing but it didn't work

2023-10-31 13:02 UTC, marcoow approved these changes

2023-10-31 13:18 UTC, merged