Redesign
mainmatter/mainmatter.com pull request #219
Opened 2018-09-06 19:26 UTC by wadie

Everything should be good, there were a lot of links to edit as well so let me know if I missed anything. the pages, head, foot and layout are all already and everything should be ready to go.

One thing's left and I'm not sure what's the problem, the text styling in the blog posts in `/article/index.html` doesn't appear as intended in the redesign. maybe we need to edit the CSS differently ? or is there a way to access `#### Header` from the md files, like with `post.head` ?

Waiting for your input! 👍

2018-09-07 08:07 UTC, marcoow commented
Looks good already 👍 Here's a few things I found (without having looked at the code yet):

* the contact form isn't functional yet
* the navigation menu doesn't work on all pages - this needs to be an include actually
* the links on the open source projects don't work - I think best is to just grep for `href="#"` in the codebase and replace **all** occurrences of it with the correct link
* the embedded videos on the ember page are not the correct ones (the designers used fake ones - the correct ones are on http://relaxed-agnesi-cb3d83.netlify.com/services/ember/)
* the favicon is missing
* the blog posts on the ember page don't seem to be dynamic (Tobias is not actually the author of all of them, that was just something that the designers did as a placeholder)
* footer links to github etc. don't work
* most of the blog posts are missing the category
* formatting of the blog posts is off and images are broken (e.g. http://localhost:4000/blog/2018/07/24/from-spa-to-pwa.html)

2018-09-07 08:08 UTC, marcoow commented
@wadie: please ask all @simplabs/devs for review once this is closer to its final state 👍

2018-09-13 10:30 UTC, marcoow reviewed
- [X] the contact form needs to be validated with HTML5 attributes like on the current website

- [X] there are JS errors on the page (at least on `/contact-us`)

- [X] the contact form does not work (it seems to send the message but then never enters the success screen)

- [X] the blog posts are not styled correctly (code snippets much too big, no spacing between paragraphs, headings, font also seems generally bigger than on the other pages, syntax highlighting is not correct - compare http://localhost:4000/blog/2018/07/24/from-spa-to-pwa.html with https://simplabs.com/blog/2018/07/24/from-spa-to-pwa.html, author info does not seem to be styled correctly: 
<img width="389" alt="bildschirmfoto 2018-09-13 um 12 14 26" src="https://user-images.githubusercontent.com/1510/45482516-9b8f6c00-b74e-11e8-97b5-440ff1c739dc.png">

- [X] let's make sure we always indent new levels everywhere with 2 spaces - this gets super hard to read and maintain otherwise; there are lots of tools that integrate with editors and do that automatically

- [X] we should only show the last 3 blog posts for the respective category on the ember and elixir pages

- [X] I'm not sure the Google Analytics snippet is included in **every** page?

- [X] Text flows when hovering over in blog page

2018-09-13 10:30 UTC, marcoow commented on Gemfile
> +end
missing newline 👀

2018-09-13 10:30 UTC, marcoow commented on _config.yml
> +width: 144
this is missing a newline and seems wrongly indented

2018-09-13 10:30 UTC, marcoow commented on _includes/contact_banner.html
> +  </div>
wrong indentation

2018-09-13 10:30 UTC, marcoow commented on _includes/head.html
> +    <link href="https://fonts.googleapis.com/css?family=Nunito+Sans:300,300i,400,400i,600,600i,700,700i,900,900i" rel="stylesheet">
We should not actually include all of the font weights here - that was only for testing really. The font bundle gets really big that way - can you check again and make sure we're only using 3-4 weights?

2018-09-13 10:30 UTC, marcoow commented on _config.yml
>  navigation:
is this still used?

2018-09-13 10:30 UTC, marcoow commented on _layouts/article.html
> +        document.querySelectorAll('code').forEach(tag => tag.classList.add('article-text-code'));
We should not do this, mainly as it makes things unnecessarily complex. Instead, style the tags as such but scoped to an element that wraps the post, e.g. 

```html
<article class="blog-post">
  …
</article>
```

```sass
.blog-post {
  h4 {
  }
  …
}
```

2018-09-13 10:30 UTC, marcoow commented on contact/index.html
> +  </script>
We should not use things like `const` and `Promise` as those are not necessarily supported by all of our user's browsers 😞

2018-09-13 10:30 UTC, marcoow commented on elixir/index.html
> +    </script>
This is repeated several times and should be in an include.

2018-09-13 11:18 UTC, wadie commented on _includes/head.html
> +    <link href="https://fonts.googleapis.com/css?family=Nunito+Sans:300,300i,400,400i,600,600i,700,700i,900,900i" rel="stylesheet">
600 is the only one we're not using..

2018-09-13 12:10 UTC, marcoow commented on _includes/head.html
> +    <link href="https://fonts.googleapis.com/css?family=Nunito+Sans:300,300i,400,400i,600,600i,700,700i,900,900i" rel="stylesheet">
we need to reduce the number of weights we're using then; can you make a list of which ones we're using and where?

2018-09-16 14:54 UTC, wadie commented on contact/index.html
> +  </script>
I think `const` shouldn't be a problem, based on [caniuse](https://caniuse.com/#feat=const)

2018-09-16 15:11 UTC, wadie commented on _includes/head.html
> +    <link href="https://fonts.googleapis.com/css?family=Nunito+Sans:300,300i,400,400i,600,600i,700,700i,900,900i" rel="stylesheet">
Font weight | Usage
------------ | -------------
900 | Headers & Subheaders (H1,H2...) and feature text
300 | .card-text
300 | .blog-post-text
300 | .swiper-slide-news-body-text
400 | links, cookie banner, dropdown-item, .navbar-collapse, .btn-work-with-us, .article-info
700 | footer .nav-header
700 | .contact-us
700 | .quote-text
700 | .service-description

I think we can remove 700 and use 900 instead which is already being used for headers and larger text.
We can also use 300 only instead of 400 since we already use it for blog-post-text and it looks nice, so 400 isn't really necessary.

2018-09-17 09:04 UTC, oliverbarnes submitted a review, later dismissed
Hey @wadie, everything looks good to me, both viewing on desktop and mobile. I just miss the logo being accompanied at the top by `simplabs`, like already pointed out by @Turbo87 on slack. But I'm not going to block the MR for this, sounds like it's an ongoing discussion

2018-09-17 15:05 UTC, wadie commented on contact/index.html
> +  </script>
Based on [caniuse](https://caniuse.com/#feat=const), `const` shouldn't really be a problem.
We can avoid using [Promise](https://caniuse.com/#feat=promises) though.

2018-11-23 16:12 UTC, marcoow commented
The OSS project logos are broken in Safari: 
<img width="762" alt="bildschirmfoto 2018-11-23 um 17 11 46" src="https://user-images.githubusercontent.com/1510/48952562-e98cd100-ef42-11e8-8aa1-adc90142941e.png">

2018-11-23 16:27 UTC, ghislaineguerin commented
@marcoow got it, will fix.

2018-11-23 16:52 UTC, marcoow commented
@wadie: I added the missing blog post categories - we have these now (and I suggest we use the following colors for them):

* ember (#dd4025)
* ruby (#cc342d)
* misc (#007df7)
* js (#f7df1e)
* elixir (#0d182f)
* rust (#000000)

2018-11-23 16:53 UTC, marcoow commented
I just realized the list of blog post is slightly mis-formatted - I believe the 2 lines of text should be vertically centered towards the image:

<img width="705" alt="bildschirmfoto 2018-11-23 um 17 52 26" src="https://user-images.githubusercontent.com/1510/48954172-b1888c80-ef48-11e8-936f-33aecc86d461.png">

2018-11-29 11:06 UTC, ghislaineguerin commented
@marcoow I've added highlight styles. I think we are ready for another review round.

2018-11-29 13:41 UTC, oliverbarnes commented
I don't see a way to add a github review per se, already had one approved. tried dismissing it, but the option to add another one doesn't show up. so I'll give my feedback over a regular comment. by the way, take any design comments on my part with a huge grain of salt:

Homepage:

- really think we need the word simplabs next to the logo, at least on the homepage. personally I'd prefer it on all pages too - so that if someone shares an internal page, the opener of said page will know which company it's about, and not have to dig

- the line next to the first paragraph on the homepage looks, to me, like an illustration image that didn't finish loading. Is it meant as a separator? using Chrome 70.0.3538.110 

<img width="1168" alt="screenshot 2018-11-29 at 11 09 49" src="https://user-images.githubusercontent.com/21290/49224031-83330300-f3c7-11e8-893d-856ded8fbbb7.png">

- distance from that paragraph to *services* seems to big to me. And I find myself wanting those arrow to scroll down that single-page sites have

- I like the weird visual effect around the icons for Full-Stack Engineering, Team Augmentation and Tutoring. 

- But alignment for these titles below the icons seems a little odd, perhaps centering them could compensate for the difference in title lengths? or not, not sure. 

- Case studies show up right under *services*, kind of unexpectedly to me - maybe a *case studies* header could keep things consistent?

- the boxes with image backgrounds are nice, but feel conflicting with the new design direction. just the client logos with the text blurb would probably already work nicely.

- the Our Work button feels too close to the logos above it

- obviously, I miss Ruby being included our *Expertise* menu at the end.

Internal pages

- I like the inclusion of related blog posts like it's done on the Elixir page

- On full-stack engineeering page, again the case-study box doesn't fit in, and specially conflicts with the _work with us box_

- I like the Trainline case study page, super clear what value we brought to the project, nicely laid-out

- ...but the ember box with the background also feels odd here

- the ember page is very nicely laid-out and clear, and I like the logos for the open source projects. the trainline case study box actually fits here, not sure what does it - perhaps it spanning the width of the page (on a 13" screen), or the whitespace around it

- on the menu below, would be nice to add Experteer eventually

That's it for now :)

2018-11-29 13:53 UTC, Turbo87 commented
<img width="317" alt="bildschirmfoto 2018-11-29 um 14 39 03" src="https://user-images.githubusercontent.com/141300/49225509-8c7e9880-f3e4-11e8-87d8-75c9207da7df.png">

I have mentioned this before, on the frontpage there is only a single mention of "simplabs", which is all the way at the bottom of the page. If we want people to remember simplabs we should use it more often, which would also have SEO advantages.

---

<img width="560" alt="bildschirmfoto 2018-11-29 um 14 38 35" src="https://user-images.githubusercontent.com/141300/49225508-8be60200-f3e4-11e8-8637-952588e94333.png">

the same as above is true for the mobile view

---
![zoom-effect](https://user-images.githubusercontent.com/141300/49225329-0bbf9c80-f3e4-11e8-9f51-d9ea90532332.gif)

the background zoom effect on these tiles seems to have a fixed right side for some reason. I would suggest to zoom into the center instead to make it look better when multiple tiles are displayed side-by-side.

---

<img width="1307" alt="bildschirmfoto 2018-11-29 um 14 14 37" src="https://user-images.githubusercontent.com/141300/49225301-fe0a1700-f3e3-11e8-818d-2d27e9825946.png">

frontpage: the line on the left looks a little out of place. at first I thought it might be an underline of the section above it with broken rendering in firefox, but apparently this was intended.

---

![wrapping](https://user-images.githubusercontent.com/141300/49225328-0bbf9c80-f3e4-11e8-9a76-89dd590dac59.gif)

the hover effect on the blog post previews is causing the text to wrap which makes the page jump

---

<img width="1168" alt="bildschirmfoto 2018-11-29 um 14 14 42" src="https://user-images.githubusercontent.com/141300/49225302-fe0a1700-f3e3-11e8-8c40-aeabaade5a6d.png">

the blue/red effect on the icons literally make my eyes hurt... 😕

---

<img width="379" alt="bildschirmfoto 2018-11-29 um 14 17 16" src="https://user-images.githubusercontent.com/141300/49225304-fea2ad80-f3e3-11e8-83e5-f9a772f0e8b8.png">

what does "on" mean?

---

<img width="245" alt="bildschirmfoto 2018-11-29 um 14 18 14" src="https://user-images.githubusercontent.com/141300/49225305-fea2ad80-f3e3-11e8-82df-8e032e202ca8.png">

the left-side arrow on the "Learn more" links is not vertically centered with the text

---

<img width="1386" alt="bildschirmfoto 2018-11-29 um 14 18 50" src="https://user-images.githubusercontent.com/141300/49225306-fea2ad80-f3e3-11e8-99b2-c228273a3fe9.png">

the "blue boxes" on some pages are inconsistently placed. sometimes they appear left-aligned, sometimes centered.

---

<img width="544" alt="bildschirmfoto 2018-11-29 um 14 19 45" src="https://user-images.githubusercontent.com/141300/49225307-fea2ad80-f3e3-11e8-855b-49e12d78f282.png">

the click targets on some images are larger than the images for no obvious reason, which makes the hover effect trigger earlier than expected in some cases

---

<img width="1193" alt="bildschirmfoto 2018-11-29 um 14 21 22" src="https://user-images.githubusercontent.com/141300/49225308-ff3b4400-f3e3-11e8-8fc3-6294e62577ac.png">

the section about our Ember addons should mention their names to make people recognize them better

---

<img width="517" alt="bildschirmfoto 2018-11-29 um 14 25 24" src="https://user-images.githubusercontent.com/141300/49225310-ff3b4400-f3e3-11e8-91fb-c27983fe6f29.png">

I think this should be "bootstrapped", without the hyphen.

---

<img width="1136" alt="bildschirmfoto 2018-11-29 um 14 29 21" src="https://user-images.githubusercontent.com/141300/49225312-ffd3da80-f3e3-11e8-81f6-0ac922bdc446.png">
<img width="764" alt="bildschirmfoto 2018-11-29 um 14 30 51" src="https://user-images.githubusercontent.com/141300/49225314-ffd3da80-f3e3-11e8-98b8-3a10245dcfdf.png">
<img width="816" alt="bildschirmfoto 2018-11-29 um 14 32 28" src="https://user-images.githubusercontent.com/141300/49225316-006c7100-f3e4-11e8-9945-46eacd21a8ad.png">

highlightjs doesn't seem to recognize the correct languages sometimes and generally doesn't seem good at highlighting Handlebars and Rust.


---

<img width="775" alt="bildschirmfoto 2018-11-29 um 14 30 17" src="https://user-images.githubusercontent.com/141300/49225313-ffd3da80-f3e3-11e8-9e0b-b32a458f61f0.png">

the subheadings in the blog posts could use a bit more `margin-bottom`

---

<img width="787" alt="bildschirmfoto 2018-11-29 um 14 31 33" src="https://user-images.githubusercontent.com/141300/49225315-006c7100-f3e4-11e8-9536-7ad7c445db4e.png">

the `<pre>` elements blend too much into the regular text for my taste. my suggestion would be to unify the font-size across both, but then use some slight color highlights to emphasize the monospace parts

---

<img width="840" alt="bildschirmfoto 2018-11-29 um 14 33 53" src="https://user-images.githubusercontent.com/141300/49225318-006c7100-f3e4-11e8-95fc-d4e133bc5eb5.png">

blog post preview texts don't render line breaks, paragraphs, links or code blocks

---

- work: no mention of Cardstack?
- expertise: no mention of Ruby?
- contact: the map does not seem to point to the correct address
- imprint: the address is missing line breaks

2018-11-30 09:07 UTC, marcoow reviewed
### About Page

<img width="1116" alt="bildschirmfoto 2018-11-30 um 09 50 22" src="https://user-images.githubusercontent.com/1510/49278533-66f59b80-f485-11e8-8449-847d5f1b9844.png">

maybe one of these is better?

![simplabs3](https://user-images.githubusercontent.com/1510/49278600-8d1b3b80-f485-11e8-8fad-6e543e8c5e55.jpg)
![simplabs4](https://user-images.githubusercontent.com/1510/49278601-8db3d200-f485-11e8-9ca3-18d55f5c398b.jpg)
![simplabs10](https://user-images.githubusercontent.com/1510/49278602-8db3d200-f485-11e8-99a8-1b2313262079.jpg)

also this one is really bad 😞 

<img width="1243" alt="bildschirmfoto 2018-11-30 um 09 52 05" src="https://user-images.githubusercontent.com/1510/49278625-a1f7cf00-f485-11e8-8f5b-aa940e5fd662.png">

We don't have a single good photo of the office though - I'm not sure what to do about that. Can we just remove this photo?

### Ember Page

clickable area is tiny for these icons and there is no hover effect: 
<img width="745" alt="bildschirmfoto 2018-11-30 um 09 54 44" src="https://user-images.githubusercontent.com/1510/49278772-0adf4700-f486-11e8-97db-2726d4d27b57.png">

### Home Page

I'd make this button black: 
<img width="268" alt="bildschirmfoto 2018-11-30 um 09 59 42" src="https://user-images.githubusercontent.com/1510/49279040-b2f51000-f486-11e8-83d7-5af31d4e7bfd.png">

Not sure there is more grey text that should be made black as well?

### Trainline Page

This looks a bit strange on mobile - I think we should drop that line and let the text flow over the full page width:

<img width="584" alt="bildschirmfoto 2018-11-30 um 10 03 39" src="https://user-images.githubusercontent.com/1510/49279233-37e02980-f487-11e8-86fe-234dff95114a.png">

(same for the other case studies)

### About Page

text is too narrow: 
<img width="584" alt="bildschirmfoto 2018-11-30 um 10 05 31" src="https://user-images.githubusercontent.com/1510/49279323-7b3a9800-f487-11e8-9ddd-bc92567ee482.png">

### Blog

I think we should center all images - currently they all look a bit misplaced

2018-11-30 09:07 UTC, marcoow commented on index.html
> +            Whether you're looking get your project going, boost your productivity, or make better technology decisions, our team of experts has the necessary skills to ensure long-term success.
```suggestion
            We turn ideas into products and help tech teams move faster with confidence, enabling the long-term success of our clients' businesses.
```

2018-11-30 09:07 UTC, marcoow commented on index.html
> +            <p class="pr-3 mb-3 text-dark" aria-hidden="true">We take the lead and turn our clients' ideas into successful products, working closely with them in short iterations.</p>
```suggestion
            <p class="pr-3 mb-3 text-dark" aria-hidden="true">We turn our clients' ideas into successful products, working closely with them in short iterations.</p>
```

2018-11-30 09:07 UTC, marcoow commented on index.html
> +            <p class="pr-3 mb-3 text-dark" aria-hidden="true">Our technology experts step in and merge with our clients' in-house engineering teams, spearhead development initiatives, and establish b
```suggestion
            <p class="pr-3 mb-3 text-dark" aria-hidden="true">Our technology experts merge with our clients' in-house engineering teams, spearhead development initiatives and establish best practices.</p>
```

2018-11-30 09:07 UTC, marcoow commented on index.html
> +          <p>Trainline is Europe’s leading independent rail and coach platform. We worked with Trainline to deliver a scalable, high-performance mobile web app, along with an improved engineer proces
```suggestion
          <p>Trainline is Europe’s leading independent rail and coach platform. We worked with them to deliver a high-performance mobile web app, along with an improved engineering process, enabling Trainline to achieve their business goals for years to come.</p>
```

2018-11-30 09:07 UTC, marcoow commented on index.html
> +          <p>When Timify decided it was time to re-engineer their existing product, they trusted us to bring them into the future. We added engineering capacity to Timify's team and helped to build a
```suggestion
          <p>When Timify decided it was time to re-engineer their existing product, they trusted us to bring them into the future. We added engineering capacity and technology expertise to Timify's internal team and helped to build a solid foundation that enabled them to iterate fast and launch on-schedule, without sacrificing quality.</p>
```

2018-11-30 09:07 UTC, marcoow commented on index.html
> +          image_url="/images/news-1.png"
these news images need to be replaced with something meaningful

2018-11-30 09:07 UTC, marcoow commented on services/index.html
> +          <p class="lead pr-3 mb-3 text-dark" aria-hidden="true">We take the lead and turn our clients' ideas into successful products, working closely with them in short iterations. Our solutions ar
```suggestion
          <p class="lead pr-3 mb-3 text-dark" aria-hidden="true">We turn ideas into successful products, working closely with our clients in short iterations. Our solutions are well architected and easy to maintain and extend by our clients once they are ready to take over themselves.</p>
```

2018-11-30 09:07 UTC, marcoow commented on services/index.html
> +              <p class="lead pr-3 mb-3 text-dark" aria-hidden="true">Not all engineering teams have the experience or confidence to make big decisions and complete large scale projects on time and bu
```suggestion
              <p class="lead pr-3 mb-3 text-dark" aria-hidden="true">Not all engineering teams have the experience or confidence to make big decisions and complete large scale projects on time and budget. Our technology experts step in and merge with our clients' in-house engineering teams, spearhead development initiatives, establish best practices and install a smooth engineering process to get their projects across the finish line.</p>
```

2018-11-30 09:07 UTC, marcoow commented on full-stack-engineering/index.html
> +    <p>Instead, focussing on their core strengths while getting software engineering help from an experienced partner can make software an enabler for success rather than a liability.</p>
```suggestion
    <p>Instead, focussing on their own core strengths while getting software engineering help from an experienced partner can make software an enabler for success rather than a liability.</p>
```

2018-11-30 09:07 UTC, marcoow commented on team-augmentation/index.html
> +        <p class="lead mb-4">We are experts in Ember.js and Elixir & Phoenix frameworks.</p>
```suggestion
        <p class="lead mb-4">We value conventions-based frameworks that result in maintainable and well-defined projects which are easy to take over by our clients once we've left.</p>
```

2018-11-30 09:07 UTC, marcoow commented on team-augmentation/index.html
> +        <p class="lead mb-4">It allows us to build solid projects and our clients can easily maintain them after we finish our work.</p>
```suggestion
        <p class="lead mb-4">Our engineers are technology experts and actively contribute to the tools and frameworks we build projects on.</p>
```

2018-11-30 09:07 UTC, marcoow commented on team-augmentation/index.html
> +        <p class="lead mb-4">It allows us to build solid projects and our clients can easily maintain them after we finish our work.</p>
The above 2 apply to all other occurences of the same text as well of course.

2018-11-30 09:07 UTC, marcoow commented on trainline/index.html
> +              <h4 class="py-4 text-dark">Faster Load Time</h4>
```suggestion
              <h4 class="py-4 text-dark">Faster Load Times</h4>
```

2018-11-30 09:07 UTC, marcoow commented on trainline/index.html
> +              <h4 class="py-4 text-dark">Better Server Rendering</h4>
```suggestion
              <h4 class="py-4 text-dark">Server-Side Pre-Rendering</h4>
```

2018-11-30 09:07 UTC, marcoow commented on dd-wrt/index.html
> +          <p>We are Europe's leading Ember experts withe people involved in Ember.js core teams like Ember CLI and Ember Learning.</p><p>We have been hosting and supporting several Ember.js meetups a
```suggestion
          <p>We are Europe's leading Ember experts with people actively involved in Ember.js core teams.</p><p>We have been an active part of the community from the early days and co-organize EmberFest, the European Ember Community Conference.</p>
```

2018-11-30 09:07 UTC, marcoow commented on trainline/index.html
> +        <p class="lead mb-4">We develop deep expertise in the tools that we specialize in and take an active role in the communities.</p>
Should we use the same text that we use [here](https://github.com/simplabs/simplabs.github.io/pull/219/files#diff-87950fc1cda37694465bf56c1af74d8fR78)? Otherwise this is essentially the same thing that we also say in the ember box itself.

2018-11-30 09:07 UTC, marcoow commented on timify/index.html
> +              Leveraging modern web technologies like SVG for the main calendar view, we were able to achieve decent runtime performance even for large data sets. The JSON API based server API allowe
```suggestion
              Leveraging modern web technologies like SVG for the main calendar view, we were able to achieve decent runtime performance even for large data sets. The json:api based server API allowed us to implement the client and server side of a feature concurrently.
```

2018-11-30 09:07 UTC, marcoow commented on about/index.html
> +                      We have reviewed applications for various clients in the past, covering technology stacks from Ruby
```suggestion
                      We have written and reviewed applications for various international clients in the past, covering technology stacks from Ruby
```

2018-11-30 09:07 UTC, marcoow commented on about/index.html
> +                <p class="lead">We Open Source and take an active role in the projects that we leverage for our clients, contributing code and supporting the communities.</p>
```suggestion
                <p class="lead">We ❤️ Open Source and take an active role in the projects that we leverage for our clients, contributing code and supporting the communities.</p>
```

2018-11-30 09:07 UTC, marcoow commented on about/index.html
> +                <p class="lead">Being a remote culture doesn't mean everyone needs to be remote at all times though. We have regular company events to connect offline and spend some time together - w
```suggestion
                <p class="lead">Being a remote company doesn't mean everyone needs to be remote at all times though. We have regular company events to connect offline and spend some time together - we even invite our clients to join us!</p>
```

2018-11-30 09:07 UTC, marcoow commented on ember/index.html
> +        </p>
Do we need this paragraph? Seems a bit repetitive.

2018-11-30 09:07 UTC, marcoow commented on elixir/index.html
> +            <p class="lead mb-4">Elixir and Phoenix are open community projects and <strong>we are an active member of the community</strong>. We support theElixir Munich meetup and have been sponsor
```suggestion
            <p class="lead mb-4">Elixir and Phoenix are open community projects and <strong>we are an active member of the community</strong>. We support the Elixir Munich meetup and have been sponsors of ElixirConf and ElixirConf EU for years.</p>
```

2018-11-30 10:14 UTC, jorgelainfiesta commented
### Homepage

<img width="194" alt="screen shot 2018-11-30 at 10 48 55 am" src="https://user-images.githubusercontent.com/4451393/49281723-93151a80-f48d-11e8-9ee7-00cf78cca40e.png">
The weird color derfagmentation of the icons are quite disturbing, and they don't seem to fit with any other style in the site? 

---

<img width="1132" alt="screen shot 2018-11-30 at 10 53 35 am" src="https://user-images.githubusercontent.com/4451393/49282000-50077700-f48e-11e8-8b79-38b2f7f6fe8d.png">
Can we add actual relevant thumbnails to the news section? Perhaps we can rename that "News" section as it's not really news. Actually, I would say that none of the blocks there are news nor they have links to news articles.

### Train line case study

There's a small typo on the ember banner. Also the HTML in that banner is not semantic, we have a block element inside a link.
<img width="574" alt="screen shot 2018-11-30 at 11 01 19 am" src="https://user-images.githubusercontent.com/4451393/49282369-4cc0bb00-f48f-11e8-9eb9-ecc871bebff1.png">

### Blog
<img width="417" alt="screen shot 2018-11-30 at 11 05 17 am" src="https://user-images.githubusercontent.com/4451393/49282659-fdc75580-f48f-11e8-8b88-38931f81d882.png">

Maybe we shouldn't use all caps for the author's names in the blog entries. Far from using caps, the rest of the design is about no-caps in the titles and such. If caps are desired for the author for some reason, I think we should use small caps.

### About page

I think this page is way too impersonal. These days people want to be able to conect with people, not institutions, even at professional levels. I'd argue that faceless companies are not very charming. We could work on this page in a future iteration and just leave it as it is for this week's release.

2018-11-30 10:47 UTC, marcoow reviewed
added some suggestions for the news on the front page

2018-11-30 10:47 UTC, marcoow commented on index.html
> +          content="We are part of the organisational committee behind EmberFest. This year, we also sponsored the video recordings of all talks which are now available on YouTube. We hope everyone en
I think this should contain the link as well like on the current https://simplabs.com

2018-11-30 10:47 UTC, marcoow commented on index.html
> +          title="JSConf.eu"
```suggestion
          title="Meet us at EmberConf"
```

2018-11-30 10:47 UTC, marcoow commented on index.html
> +          url="https://2018.jsconf.eu/"
```suggestion
          url="https://emberconf.com"
```

2018-11-30 10:47 UTC, marcoow commented on index.html
> +          content="We will be at JSConf EU in Berlin, June 2nd and 3rd, 2018 and we will have @locks from the Ember.js core team join us at our booth!"
```suggestion
          content="We are happy to be sponsoring EmberConf again in 2019. If you're going to be in Portland, make sure to connect with our team!"
```

2018-11-30 10:47 UTC, marcoow commented on index.html
> +          title="CodeBot supports ES2017"
```suggestion
          title="Launching Breethe"
```

2018-11-30 10:47 UTC, marcoow commented on index.html
> +          content="Our Slack Bot CodeBot, that takes any JavaScript code you send it, runs it and returns with the result and captured log output is now running Node 9 and thus supports all the lates
```suggestion
          content="We are happy to launch Breethe, a Progressive Web App for accessing air quality data for locations around the world. We built Breethe with Glimmer.js so that it would be blazing fast and lightweight. It is server side rendered, works offline and even with JavaScript disabled!"
```

2018-11-30 10:47 UTC, marcoow commented on index.html
> +          url="http://codebot.chat/"
```suggestion
          url="https://breethe.app"
```

2018-11-30 15:56 UTC, marcoow requested changes
I just realized that there's a bug that causes the page to be scrollable horizontally while all content actually shrinks correctly:

![hori](https://user-images.githubusercontent.com/1510/49299772-d76dde00-f4c0-11e8-8f2c-6af196a4a57d.gif)

2018-12-02 20:46 UTC, geekygrappler approved these changes

2018-12-02 20:47 UTC, geekygrappler commented
Most of the stuff I picked  up, already mentioned by others. The only question/comment I have is:

<img width="1580" alt="screenshot 2018-12-02 at 21 41 20" src="https://user-images.githubusercontent.com/3627301/49344757-ccab7880-f67b-11e8-9bd3-f4de5264e58d.png">

Personally think the circle with examples should be larger than they are.

2018-12-03 08:31 UTC, marcoow commented
@geekygrappler: all of the visual design will be reviewed again post-release.

2018-12-04 16:35 UTC, Turbo87 commented
<img width="820" alt="bildschirmfoto 2018-12-04 um 17 34 49" src="https://user-images.githubusercontent.com/141300/49457319-eddea700-f7ea-11e8-9cd1-7fe14108fdbf.png">

this should be multiline

2018-12-04 16:38 UTC, jayjayjpg reviewed
First off, the website looks :sparkles: 

One thing I noticed while browsing the site was that I wasn't able to enter anything into the textarea to describe the project. Can you take another look?

![contact](https://user-images.githubusercontent.com/8811742/49457612-680f2b80-f7eb-11e8-9631-e791664ecbda.gif)

2018-12-04 16:51 UTC, marcoow commented
@Turbo87: not sure what the intention of this was? 021fd5d1e10f845bc59434ac4ec022f59a58406e Everything looks correct after removing that though.

2018-12-04 16:56 UTC, marcoow commented
@jessica-jordan: should be fixed

2018-12-04 16:59 UTC, Turbo87 commented
@marcoow the intention was that inline codeblocks should not be wrapped, and on https://simplabs.com/blog/2018/11/27/open-source-maintenance.html this seems to have worked fine

2018-12-04 17:01 UTC, Turbo87 commented
<img width="765" alt="bildschirmfoto 2018-12-04 um 18 00 41" src="https://user-images.githubusercontent.com/141300/49459101-8c203c00-f7ee-11e8-9d92-0cac61b434b9.png">

specifically this wrapping is what I wanted to avoid

2018-12-04 17:04 UTC, marcoow commented
@Turbo87: restored that in a less global way :)

2018-12-05 11:15 UTC, ghislaineguerin approved these changes

2018-12-05 12:42 UTC, marcoow approved these changes

2018-12-05 12:51 UTC, merged