[WIP] Embroider update
mainmatter/mainmatter.com pull request #2215
Opened 2023-11-15 15:00 UTC by mansona

I'm working with @KevinBongart and @lolmaus to get this done, It's not ready for review yet

Note: This takes over from https://github.com/mainmatter/mainmatter.com/pull/2211 after the master snafu 🙈

2023-11-15 23:20 UTC, mansona reviewed
I just did a quick review like this before I saw @KevinBongart's slack message, so consider these comments things that I will look at first thing in the morning 👍 

One thing I would like to know: is there a way for us to turn off the general "Get in touch about Ember" CTA on this post? It just seems odd that we have a specific CTA about the initiative at the very end and then a general CTA directly after it 🤔

2023-11-15 23:20 UTC, mansona commented on src/posts/2023-11-06-embroider-initiative-progress.md
> +To reach these goals and keep up the momentum, the project needs your financial support. Please [get in touch] to learn how to directly benefit from this investment.
I don't know what this link is supposed to point to but I'm assuming it should be a link 😂

2023-11-15 23:20 UTC, mansona commented on src/posts/2023-11-06-embroider-initiative-progress.md
> +Let's see some success stories in details:
```suggestion
Let's see some success stories in detail:
```

2023-11-15 23:20 UTC, mansona commented on src/posts/2023-11-06-embroider-initiative-progress.md
> +Chris work improving the ergonomics of the v2 addon blueprint in the early weeks of the Embroider Initiative, proved very useful during the process of converting Ticketsolve's internal addon.
```suggestion
Chris' work improving the ergonomics of the v2 addon blueprint in the early weeks of the Embroider Initiative, proved very useful during the process of converting Ticketsolve's internal addon.
```

2023-11-15 23:20 UTC, mansona commented on src/posts/2023-11-06-embroider-initiative-progress.md
> +While this work was going on, Intercom Engineer [Aaron Chambers](https://github.com/achambers) had setup a CI build step that would keep track if the main Intercom app could build with Embroider and
```suggestion
While this work was going on, Intercom Engineer [Aaron Chambers](https://github.com/achambers) had setup a CI build step that would keep track if the main Intercom app could build with Embroider and if any tests were passing. Because of this CI job, Aaron identified a 10x slowdown in build times between Embroider v3.1 and v3.2. Chris used a number of pairing sessions to dive into the issue and produce a number of flamecharts for their Embroider builds to get an insight into what was causing their specific slowdown. Those flamecharts were pointing at a particular part of Embroider Package Cache not working exactly as we intended it to. Ed Faulkner managed to pinpoint the problem (while he and Chris were discussing it in the "hallway track" of [EmberFest](https://emberfest.eu)) and [opened a pull-request with the fix](https://github.com/embroider-build/embroider/pull/1609). This completely fixed the performance regression for Intercom.
```

2023-11-15 23:20 UTC, mansona commented on src/posts/2023-11-06-embroider-initiative-progress.md
> +Because of the overall complexity of project and the rapid iteration of the internal architecture, it hasn't been practical to create any documentation that could communicate what is going on under t
```suggestion
Because of the overall complexity of project and the rapid iteration of the internal architecture, it hasn't been practical to create any documentation that could communicate what is going on under the hood. This is illustrated by the fact that [Aaron Chambers](https://github.com/achambers) and [Peter Meehan](https://github.com/22a) put together a [document trying to explain the full architecture of the project](https://github.com/embroider-build/embroider/pull/1459), only to have it be completely outdated less than a month later when Ed Falkner merged [the first of many internal refactors](https://github.com/embroider-build/embroider/pull/1435).
```

2023-11-15 23:20 UTC, mansona commented on src/posts/2023-11-06-embroider-initiative-progress.md
> +[Scenario tester](https://github.com/embroider-build/scenario-tester) is a testing tool that the team makes use of a lot when testing Embroider and `ember-auto-import`. It allows us to generate many
```suggestion
[Scenario tester](https://github.com/embroider-build/scenario-tester) is a testing tool that the team makes use of a lot when testing Embroider and `ember-auto-import`. It allows us to generate many scenarios with different combinations of dependencies. We tried using it outside of Embroider, or more specifically outside of a Typescript project, and saw it doesn't work in a CJS environment. [Chris started the effort to move the Typescript build to output an ESM-compatible build](https://github.com/embroider-build/scenario-tester/pull/18) so it can be consumed directly in ESM without a build step. This change has been tested against the Embroider CI and was recently released in [v3.0.0](https://github.com/embroider-build/scenario-tester/releases/tag/v3.0.0).
```

2023-11-15 23:20 UTC, mansona commented on src/posts/2023-11-06-embroider-initiative-progress.md
> +[`scenario-tester`](https://github.com/ef4/scenario-tester/) is to Embroider what `ember-try` is to Ember CLI: it's a tool that lets us perform automated tests with various combinations of dependenci
We should add  a concluding line here that says something like "this means it's quite a complex project and can be challenging to use. As we are making Embroider more mainstream we want people to be able to contribute failing tests for bugs that the discover so it's very important to have the system that we rely on for testing be more easily accessible by the community"

2023-11-15 23:20 UTC, mansona commented on src/posts/2023-11-06-embroider-initiative-progress.md
> +We are hoping we can extend the initiative's budget and timeline to keep up the momentum in 2024. Please [get in touch] to learn how to financially support the Embroider Initiative and directly benef
again we need the get in touch to be a link of some sort 😂

2023-11-16 08:24 UTC, marcoow approved these changes
This is good 🙌 Just the right level of detail while making the value that's being added clear.

2023-11-16 10:47 UTC, marcoow requested changes
@yaigrie I think it'd be good to use the sponsor logos collage (the one from http://mainmatter.com/embroider-initiative/) for the header image and `og:image` instead of the rather generic one with the stock photo – can we change that?

2023-11-16 10:50 UTC, marcoow commented
@yaigrie I also change the title to be more concise – will need to be reflected in the `og:image` as well

2023-11-16 11:18 UTC, yaigrie commented
@marcoow I changed the images - I hope I understood you correctly?

2023-11-16 11:21 UTC, marcoow commented
yes, thanks

2023-11-16 11:23 UTC, marcoow approved these changes

2023-11-16 11:27 UTC, merged