feat: new storybook and sveltekit blog post
mainmatter/mainmatter.com pull request #2244
Opened 2023-11-27 12:36 UTC by paoloricciuti

This is still missing the OG image, is there a template i can use quickly?

2023-11-27 12:40 UTC, marcoow commented on src/posts/2023-11-27-sveltekit-storybook.md
> +tagline: |
This is the first paragraph of the post actually – e.g. _"There are numerous OAuth articles…"_ on [this one](https://mainmatter.com/blog/2023/11/23/setting-up-oauth-with-auth-js-and-sveltekit/).

2023-11-27 12:40 UTC, marcoow commented on src/posts/2023-11-27-sveltekit-storybook.md
> +tags: [svelte, sveltekit, storybook]
```suggestion
tags: [svelte, storybook]
```

I'd say let's collect all Svelte posts under the `svelte` tag – otherwise we have too many tags with too few posts each

2023-11-27 12:41 UTC, marcoow commented
@emmasofiah2o can you create a header visual and `og:image`?

2023-11-27 12:43 UTC, paoloricciuti commented on src/posts/2023-11-27-sveltekit-storybook.md
> +tagline: |
Oh ok fixing it now

2023-11-27 12:59 UTC, paoloricciuti commented
Deploying seems to be failing because it can't find an import from sentry...Is this somehow caused by a bad formatting on my post?

2023-11-27 13:00 UTC, emmasofiah2o commented
> Deploying seems to be failing because it can't find an import from sentry...Is this somehow caused by a bad formatting on my post?

We had this problem with Andrey's post, too. I think we fixed it by rebasing.

2023-11-27 13:05 UTC, BobrImperator commented
This was the fix https://github.com/mainmatter/mainmatter.com/pull/2230
This is what probably breaks it again https://github.com/mainmatter/mainmatter.com/pull/2243

@emmasofiah2o @paoloricciuti @marcoow

2023-11-27 13:06 UTC, paoloricciuti commented
> This was the fix #2230 This is what probably breaks it again #2243
> 
> @emmasofiah2o @paoloricciuti @marcoow 

My usual fix for locks problems is delete the old and reinstall lol... should I go ahead?

2023-11-27 13:09 UTC, BobrImperator commented
@paoloricciuti I doubt it'll work since Renovate already did an update and that's why it breaks.

I suspect that Netlify has some weird cache problems most likely - especially since the project actually builds for the "Crawl" step.

2023-11-27 14:18 UTC, paoloricciuti commented
> @paoloricciuti I doubt it'll work since Renovate already did an update and that's why it breaks.
> 
> I suspect that Netlify has some weird cache problems most likely - especially since the project actually builds for the "Crawl" step. It might not be checking the cache version against a lockfile.

So should we revert that back again? This post should be up by tomorrow so that storybook can link to it in their release post if possible

2023-11-27 15:39 UTC, BobrImperator commented
@paoloricciuti see #2245 it reverts the lockfile change and should fix netlify.
Feel free to approve that and rebase after. The revert is set to auto-merge.

2023-11-28 09:08 UTC, emmasofiah2o requested changes
Just a few form suggestions and some commas :)

2023-11-28 09:08 UTC, emmasofiah2o commented on src/posts/2023-11-27-sveltekit-storybook.md
> +make the onboarding for new devs to be seamless and also to allow all project
```suggestion
make the onboarding for new devs seamless and allow all project
```

2023-11-28 09:08 UTC, emmasofiah2o commented on src/posts/2023-11-27-sveltekit-storybook.md
> +just a slight problem...
```suggestion
just a small problem...
```

2023-11-28 09:08 UTC, emmasofiah2o commented on src/posts/2023-11-27-sveltekit-storybook.md
> +projects with the teams we work with, and Storybook was an obvious choice to
```suggestion
projects with the teams we work with. Storybook was the obvious choice to
```

2023-11-28 09:08 UTC, emmasofiah2o commented on src/posts/2023-11-27-sveltekit-storybook.md
> +Storybook has a wonderful Story (pun intended) with Svelte but the integration
```suggestion
Storybook has a wonderful Story (pun intended) with Svelte, but the integration
```

2023-11-28 09:08 UTC, emmasofiah2o commented on src/posts/2023-11-27-sveltekit-storybook.md
> +considered a bad practice (you could just pass the store value as a prop)
```suggestion
considered a bad practice (you could just pass the store value as a prop),
```

2023-11-28 09:08 UTC, emmasofiah2o commented on src/posts/2023-11-27-sveltekit-storybook.md
> +sometimes is just tedious to have to pass a prop every time. For example, if you
```suggestion
sometimes it is just tedious having to pass a prop every time. For example, if you
```

2023-11-28 09:08 UTC, emmasofiah2o commented on src/posts/2023-11-27-sveltekit-storybook.md
> +## The problem
```suggestion
## The Problem
```

2023-11-28 09:08 UTC, emmasofiah2o commented on src/posts/2023-11-27-sveltekit-storybook.md
> +## The solution
```suggestion
## The Solution
```

2023-11-28 09:08 UTC, emmasofiah2o commented on src/posts/2023-11-27-sveltekit-storybook.md
> +Vite plugins to the defaults ones, writing a Vite is not that complex, and to
```suggestion
Vite plugins to the default ones. Writing a Vite is not that complex, and to
```

2023-11-28 09:08 UTC, emmasofiah2o commented on src/posts/2023-11-27-sveltekit-storybook.md
> +Luckily for us, SvelteKit is just a Vite plugin. Storybook allows you to add any
```suggestion
Luckily for us, SvelteKit is just a Vite plugin and Storybook allows you to add any
```

2023-11-28 09:08 UTC, emmasofiah2o commented on src/posts/2023-11-27-sveltekit-storybook.md
> +week to work on open source. So I got in touch with
```suggestion
week to work on open source projects. So I got in touch with
```

2023-11-28 09:08 UTC, emmasofiah2o commented on src/posts/2023-11-27-sveltekit-storybook.md
> +So as of Storybook v7.6 if you are using the SvelteKit integration, you can now
```suggestion
As of Storybook v7.6, if you are using the SvelteKit integration, you can now
```

2023-11-28 09:08 UTC, emmasofiah2o commented on src/posts/2023-11-27-sveltekit-storybook.md
> +### How to use it
```suggestion
### How to Use It
```

2023-11-28 09:08 UTC, emmasofiah2o commented on src/posts/2023-11-27-sveltekit-storybook.md
> +the `page` store exported from `$app/stores` you can set
```suggestion
the `page` store exported from `$app/stores`, you can set
```

2023-11-28 09:08 UTC, emmasofiah2o commented on src/posts/2023-11-27-sveltekit-storybook.md
> +`sveltekit_experimental.stores.page` or to customize the behavior of the `goto`
```suggestion
`sveltekit_experimental.stores.page`, or to customize the behavior of the `goto`
```

2023-11-28 09:08 UTC, emmasofiah2o commented on src/posts/2023-11-27-sveltekit-storybook.md
> +function exported from `$app/navigation` you can set
```suggestion
function exported from `$app/navigation`, you can set
```

2023-11-28 09:08 UTC, emmasofiah2o commented on src/posts/2023-11-27-sveltekit-storybook.md
> +store. You are free to assign only a partial (what you need in the story)
```suggestion
store. You are free to assign only a partial (what you need in the story).
```

2023-11-28 09:08 UTC, emmasofiah2o commented on src/posts/2023-11-27-sveltekit-storybook.md
> +`goto` function by the component. If you don't pass any function to this
```suggestion
`goto` function by the component. If you don't pass any function to this,
```

2023-11-28 09:08 UTC, emmasofiah2o commented on src/posts/2023-11-27-sveltekit-storybook.md
> +this Storybook will log an action in the actions panel.
```suggestion
this, Storybook will log an action in the actions panel.
```

2023-11-28 09:08 UTC, emmasofiah2o commented on src/posts/2023-11-27-sveltekit-storybook.md
> +are rendering calls `invalidateAll`. If you don't pass any function to this
```suggestion
are rendering calls `invalidateAll`. If you don't pass any function to this,
```

2023-11-28 09:08 UTC, emmasofiah2o commented on src/posts/2023-11-27-sveltekit-storybook.md
> +argument using `navigation.afterNavigate` (you can pass a partial)
```suggestion
argument using `navigation.afterNavigate` (you may also pass a partial).
```

2023-11-28 09:08 UTC, emmasofiah2o commented on src/posts/2023-11-27-sveltekit-storybook.md
> +If you are using the `enhance` action on a form when inside Storybook the form
```suggestion
If you are using the `enhance` action on a form when inside Storybook, the form
```

2023-11-28 09:08 UTC, emmasofiah2o commented on src/posts/2023-11-27-sveltekit-storybook.md
> +By default every link will log an action to the Actions panel but if you want
```suggestion
By default, every link will log an action to the Actions panel, but if you want
```

2023-11-28 09:08 UTC, emmasofiah2o commented on src/posts/2023-11-27-sveltekit-storybook.md
> +has an `href` equal to the key. If you specified `asRegex` as true the function
```suggestion
has a `href` equal to the key. If you specified `asRegex` as true, the function
```

2023-11-28 09:08 UTC, emmasofiah2o commented on src/posts/2023-11-27-sveltekit-storybook.md
> +And that was it: this was a brief introduction to those new features and I'm
```suggestion
And that was it: this was a brief introduction to the new features, and I'm
```

2023-11-28 09:08 UTC, emmasofiah2o commented on src/posts/2023-11-27-sveltekit-storybook.md
> +been able to contribute to such a pivotal project (also i want to thank Jeppe
```suggestion
been able to contribute to such a pivotal project, and more so to be able to use those features myself! Also, I want to thank Jeppe
```

2023-11-28 09:08 UTC, emmasofiah2o commented on src/posts/2023-11-27-sveltekit-storybook.md
> +for helping me become familiar with this huge codebase) but i'm more than happy
```suggestion
for helping me become familiar with this huge codebase.
```

2023-11-28 09:08 UTC, emmasofiah2o commented on src/posts/2023-11-27-sveltekit-storybook.md
> +that i will soon be able to use those features myself!
```suggestion
```

2023-11-28 11:20 UTC, marcoow requested changes
there are some obvious problems

2023-11-28 11:20 UTC, marcoow commented on src/posts/2023-11-28-sveltekit-storybook.md
> +
```suggestion
```

This is in https://github.com/mainmatter/mainmatter.com/pull/2244/files#diff-29694489b8fe5b2a28cd0f8c3c6d1e2a4bfa6db70b9f273793e62918dd405e77R11 already – like this, it'll render twice

2023-11-28 11:20 UTC, marcoow commented on src/posts/2023-11-28-sveltekit-storybook.md
> +bio: "Paolo Ricciuti (paoloricciuti)"
```suggestion
bio: "Paolo Ricciuti, Senior Software Engineer"
```

or something similar, the Twitter handle isn't a bio :)

2023-11-28 11:20 UTC, marcoow commented on src/posts/2023-11-28-sveltekit-storybook.md
> +
```suggestion
```

This is the title of the post already – see https://github.com/mainmatter/mainmatter.com/pull/2244/files#diff-29694489b8fe5b2a28cd0f8c3c6d1e2a4bfa6db70b9f273793e62918dd405e77R2

2023-11-28 11:27 UTC, paoloricciuti commented on src/posts/2023-11-28-sveltekit-storybook.md
> +bio: "Paolo Ricciuti (paoloricciuti)"
I was using the last post as reference...fixing

2023-11-28 11:44 UTC, marcoow commented on src/posts/2023-11-28-sveltekit-storybook.md
> +
This is still the title of the post already? Have a look at the preview and you'll see it's duplicated

2023-11-28 11:46 UTC, paoloricciuti commented on src/posts/2023-11-28-sveltekit-storybook.md
> +
Mmm i see but i don't see it as a problem since they are so far away one from the other...do you prefer i remove this?

2023-11-28 12:39 UTC, marcoow commented on src/posts/2023-11-28-sveltekit-storybook.md
> +
ok, if it's intentional I'm fine keeping it

2023-11-28 12:39 UTC, marcoow approved these changes

2023-11-28 13:15 UTC, emmasofiah2o approved these changes

2023-11-28 13:15 UTC, merged