Aleph Alpha's case study.
mainmatter/mainmatter.com pull request #2253
Opened 2023-12-05 12:14 UTC by LukeMathWalker

2023-12-05 12:42 UTC, marcoow reviewed
I think it's good. The only general comment I'd have is it might be a bit long and detailed and there's maybe potential for shortening a bit – I wouldn't overestimate people's willingness to read long success stories :)

I'd also have the copywriter we're working with for the service pages look over it – can't hurt. @SaeLLo should be able to make a connection

2023-12-05 12:42 UTC, marcoow commented on src/cases/aleph-alpha.md
> +The entire data pipeline was built in Rust. That's the reason Aleph Alpha reached out to Mainmatter in the first place:
I'd mention Rust at the top where you talk about the need for performance?

2023-12-05 13:19 UTC, LukeMathWalker commented on src/cases/aleph-alpha.md
> +The entire data pipeline was built in Rust. That's the reason Aleph Alpha reached out to Mainmatter in the first place:
Where are you referring to? The architecture section?

2023-12-05 13:21 UTC, LukeMathWalker commented
> The only general comment I'd have is it might be a bit long and detailed and there's maybe potential for shortening a bit – I wouldn't overestimate people's willingness to read long success stories

The way I think about it: to a certain audience, the content doesn't a matter at all—the only thing that matters is that we worked with company XYZ.  
To another audience (smaller, more tech savvy, perhaps in the very same AI field), adding a bit more detail helps to qualify us as experts.

2023-12-05 13:31 UTC, marcoow commented on src/cases/aleph-alpha.md
> +The entire data pipeline was built in Rust. That's the reason Aleph Alpha reached out to Mainmatter in the first place:
The challenge I think

2023-12-11 08:04 UTC, sabine-devins commented on src/cases/aleph-alpha.md
>    ideally as efficiently as possible to save time and money. When Aleph Alpha
I think this should be reframed with Rust at the beginning. It sounds like Aleph Alpha was training a new model for the first time and MM suggested a solution in Rust but I *think* it was that Aleph Alpha wanted support in training the new model using Rust. 

Suggested rewrite: 
When Aleph Alpha set out to leverage Rust to train a new model, they reached out to Main Matter for support in architecting and implementing a capable and efficient data pipeline.

2023-12-11 08:05 UTC, sabine-devins commented on src/cases/aleph-alpha.md
> +Aleph Alpha is a German AI startup, a leader in the field of explainable and trustworthy sovereign AI.
not sure what is meant by explainable? Maybe better word would be "accessible" or "understandable"

2023-12-11 08:46 UTC, LukeMathWalker commented on src/cases/aleph-alpha.md
> +Aleph Alpha is a German AI startup, a leader in the field of explainable and trustworthy sovereign AI.
This is straight from their press release/company brand content, I ported it verbatim 🤷🏻‍♂️

2023-12-11 14:23 UTC, sabine-devins commented on src/cases/aleph-alpha.md
> +They're one of the few major players in the AI space to be based (and funded) entirely in Europe.
remove "to be"

2023-12-11 14:23 UTC, sabine-devins commented on src/cases/aleph-alpha.md
> +The name of the game in the world of AI is data: you want to train using a **large high-quality dataset** to
capitalise You: 

AI is data: You want to train

2023-12-11 14:23 UTC, sabine-devins commented on src/cases/aleph-alpha.md
> +
We have a lot of sentences that rely on the : here so a suggested rewrite. 

Processing a lot of data is a challenge in itself. When you are dealing with **petabytes** of text, you can't just spin up a single large server to process it all. That would take **forever** and **forever** is not an option when you're working in the AI space. You have to be able to iterate quickly to improve your models and ensure that you as well as your customers are always building with the latest and greatest. Aleph Alpha had booked a GPY cluster to train their models a few months in advance. This means the dataset had to be processed and ready to go by the time cluster was available. The clock was ticking! The plan: Build a **distributed data pipeline in Rust** in order to process the data in a reasonable amount of time.

2023-12-11 14:23 UTC, sabine-devins commented on src/cases/aleph-alpha.md
> +Their Engineering team must ensure that the existing product platform is running smoothly: they won't neglect
engineering team (small e) 

Capitalize They - 

running smoothly: They won't neglect

2023-12-11 14:23 UTC, sabine-devins commented on src/cases/aleph-alpha.md
> +
We partnered with Aleph Alpha in September 2023 to help them design and implement the data pipeline they needed. We followed a **team augmentation** approach and our Principal Engineering Consultant, Luca Palmieri, embedded into Aleph Alpha's team for three months to ensure they could deliver the project. 

We took responsibility in four key areas: Architecture,  infrastructure, Rust and mentoring.

2023-12-11 14:23 UTC, sabine-devins commented on src/cases/aleph-alpha.md
> +
cloud computing: Going from zero to **thousands of CPUs** for a few hours and then back to zero.

2023-12-11 14:23 UTC, sabine-devins commented on src/cases/aleph-alpha.md
> +
Capitalize the first letter after the :

2023-12-11 14:23 UTC, sabine-devins commented on src/cases/aleph-alpha.md
> +
We worked closely with Aleph Alpha's team to design a system that would satisfy these constraints as well as be **simple to operate** and ... 
--> I'm not sure what is meant by "easy to reason about"

2023-12-11 14:23 UTC, sabine-devins commented on src/cases/aleph-alpha.md
> +
You can't architect a system in a vacuum: You need to take into the **infrastructure** it will run on. The underlying provider determines the capabilities and constraints you have to work with, such as the maximum download / upload throughput you can expect from a single data bucket or the cost of moving a GB of data from one geographic (??) region to another, etc.

2023-12-11 14:23 UTC, sabine-devins commented on src/cases/aleph-alpha.md
> +
We chose to rely on managed versions of Open Source software. We were able to transfer knowledge built over years of experience with these tools to Aleph Alpha's team, while still benefiting from the ease of use of a managed service.  At the same time, it reduced the overall infrastructure risk for the project. If we were to run into an unsolvable issue with StackIt's managed offering, we could always fall back to the Open Source version or switch to another provider.

-- changed the : to periods.

2023-12-11 14:23 UTC, sabine-devins commented on src/cases/aleph-alpha.md
> +
Capitalize the first letter after a :

2023-12-11 14:23 UTC, sabine-devins commented on src/cases/aleph-alpha.md
> +
Capititalize They

2023-12-11 14:23 UTC, sabine-devins commented on src/cases/aleph-alpha.md
> +
Rust is a great fit for this kind of project as it delivers high and predictable performance, while giving you 
precise control over the memory layout of your data. That efficiency is critical when dealing with 
such a large dataset and you want to make sure you are not wasting CPU cycles or RAM.  

-- I suggest a rewrite of this sentence as it doesn't fit in with the rest of the paragraph that focusses on the advantages of Rust for this kind of project and this sentence just tells us they already know Rust? 

Furthermore, Aleph Alpha's team was already familiar with it: they've been using Rust to power their core product
offering for years.

--> Rewrite: 
But the Aleph Alpha team already knows all this: They've been using Rust to power their core product offering for years.

2023-12-11 14:23 UTC, sabine-devins commented on src/cases/aleph-alpha.md
> +  port the Python code over to Rust.
Aleph Alpha's AI researchers were working very closely with us on the project to tune parameters, test filters, check data quality, etc. Using Rust's excellent Python interop capabilities, we empowered them to prototype in Python (the language they were familiar with): we would then plug the Python code into the Rust pipeline
--> rewrote to reduce the number of sentences using a : 
--> This contradicts the sentence above where we say AA has been using Rust for years? I think we need make clearer that we were supplementing the AI research team, who were more familiar with Python than they were with Rust?

2023-12-11 14:23 UTC, sabine-devins commented on src/cases/aleph-alpha.md
> +Mainmatter's Principal Engineering Consultant, Luca Palmieri, spent several hours a week pairing with Aleph Alpha's
Luca spent several hours a week pairing with Aleph Alpha's team, working together on the project, discussing design decisions, reviewing code and sharing knowledge. 

( we already introduce Luca and his role - and we switch perspectives halfway thru the sentence).

2023-12-11 14:23 UTC, sabine-devins commented on src/cases/aleph-alpha.md
> +
capitalize Having (after the :)

2023-12-11 14:23 UTC, sabine-devins commented on src/cases/aleph-alpha.md
> +We look forward to working together again in the future!
We successfully assembled a high-quality multilingual dataset with more than **X trillion tokens**.  The data pipeline was also designed, developed and ran on time and on budget – Alelph Alpha didn't have to delay their training schedule by a single day. The data was ready to go by the time the GPU cluster was available.

2023-12-11 14:23 UTC, sabine-devins commented on src/cases/aleph-alpha.md
> +We look forward to working together again in the future!
And delete the "we look forward to working together again in teh future!

It's too bloggy - not case study.

2023-12-12 09:29 UTC, LukeMathWalker commented on src/cases/aleph-alpha.md
> +
It's an engineering way of saying to refer to the quality/clarity of a chunk code/system—see https://softwareengineering.stackexchange.com/questions/351244/easy-to-reason-about-what-does-that-mean

2023-12-12 09:53 UTC, LukeMathWalker commented
Thanks a lot for the review @sabine-devins!
I think I've addressed all your comments (mostly accepted them as they are and clarified a few parts that you highlighted as confusing).

2024-01-31 18:00 UTC, LukeMathWalker commented
This is ready to go!

I can't seem to find the page in the preview though cc @yaigrie—could it have something to do with "Aleph Alpha" being two separate words?

2024-02-01 07:05 UTC, marcoow commented
This needs to be linked manually from the work page etc. @LukeMathWalker. There's a number of TODOs still – I think @yaigrie can take over:

- [ ] add `og:image`
- [ ] add some kind of visual also in the main content (maybe we can just use some of Aleph Alpha's press materials or so)
- [ ] add a large teaser for this on the `/work` page

Later we can also add this to the Rust landing page maybe and we should also add the quote we got (or will get?) from the to the Rust landing page.

2024-02-01 09:28 UTC, LukeMathWalker commented
The quote is already in the case study, so we can copy if from there and replace MVB's with it @marcoow

2024-02-01 09:41 UTC, yaigrie commented
@marcoow do you know where I can find those press images? Do we have a contact we can ask for such images?

2024-02-01 09:48 UTC, marcoow commented
@yaigrie ideally there's sth. on their website – we have contacts but they are super slow to respond so if we can go without them, that's eaiser

2024-02-01 10:18 UTC, yaigrie commented
@marcoow sadly there is no section on their website with images provided for press usage, I tried to google image search their images to see if they're using free stock, but got no results :(

We could try to use our own images, but it's a difficult topic to find images for
https://unsplash.com/photos/blue-and-white-water-wave-nbW-kaz2BlE
https://unsplash.com/photos/a-close-up-of-a-water-droplet-with-a-blue-background-kCrrUx7US04
https://unsplash.com/photos/a-very-tall-building-with-lots-of-windows-v0aq2kqDr7M (closeup?)
https://unsplash.com/photos/a-photo-taken-from-the-ground-looking-up-at-the-sky-bVO_LiMSVgw

2024-02-01 10:27 UTC, marcoow commented
Hm, too bad – maybe just a notebook with their website or sth.? Or maybe @LukeMathWalker has sth. – some code or graph showing the imported data or sth. (without revealing anything we can't reveal of course)…

2024-02-01 11:01 UTC, LukeMathWalker commented
Everything I have is in the aleph-alpha channel on Slack (mostly screenshots).

2024-02-01 11:28 UTC, yaigrie commented
@marcoow @LukeMathWalker I added a notebook showing some of the screenshots

2024-02-01 11:34 UTC, marcoow requested changes
Let's remove the images we're not actually using. Also I think their logo is missing:

![Bildschirmfoto 2024-02-01 um 12 32 06](https://github.com/mainmatter/mainmatter.com/assets/1510/24545057-3d2e-4ae1-965c-cfcedb84289c)

Can we also feature the case study on the Rust landing page?

2024-02-01 11:40 UTC, LukeMathWalker commented on src/cases/aleph-alpha.md
> +        <p>We successfully assembled a high-quality multilingual dataset with more than <strong>4.5 trillion tokens</strong>.
```suggestion
        <p>We successfully preprocessed <strong>4.5 trillion tokens</strong> to assemble a high-quality multilingual dataset. 
```

2024-02-01 11:42 UTC, LukeMathWalker commented on src/cases/aleph-alpha.md
> +title: A large-scale data pipeline to feed AI models | Work
A few alternatives I considered:
- "Preprocessing trillions of tokens with Rust"
- "Large models need large datasets: preprocessing trillions of tokens with Rust"

2024-02-01 11:43 UTC, LukeMathWalker commented
The graphs in the notebook image must be redacted @yaigrie—no numbers on either axis, no titles.

2024-02-01 11:43 UTC, marcoow commented on src/cases/aleph-alpha.md
> +title: A large-scale data pipeline to feed AI models | Work
I think the first one is good – bit more catchy than the latter :)

2024-02-01 11:47 UTC, LukeMathWalker commented on src/cases/aleph-alpha.md
> +title: A large-scale data pipeline to feed AI models | Work
Yup, that's my favourite as well.

2024-02-01 12:20 UTC, yaigrie commented
@marcoow if we soon merge both case studies, this one and rail europe, which one should be at the top of the work page?
I think I resolved all issues now :)

2024-02-01 13:45 UTC, marcoow commented
let's put this one at the top

2024-02-02 16:54 UTC, marcoow approved these changes
🙌

2024-02-02 16:55 UTC, merged