Blog post/ Automating maintenance of the Ember Guides FR
mainmatter/mainmatter.com pull request #2295
Opened 2024-01-11 08:19 UTC by BlueCutOfficial

- Is the size of the blog post ok or do you think it is worth splitting? So far the only one that big is the Super Rental app with SvelteKit.
- I am not 100% sure about the mix between the tuto-like approach and the fact it's not a proper tuto you can do on your side. But if it's not pedagogic I am not sure it's relevant at all.

2024-01-12 16:20 UTC, emmasofiah2o requested changes
Review until line 334 ✅

2024-01-12 16:20 UTC, emmasofiah2o commented on src/posts/2024-01-10-ember-guides-fr-git-automation.md
> +    One of the main blockers to translation projects is the overwhelming question: how to maintain it? The tool you're building is already something big, and the English docs for this tool are genera
```suggestion
    One of the main blockers to translation projects is the overwhelming question: how do you maintain it? The tool you're building is already big, and the English docs for this tool are generally a complete website that you must keep up to date. What's the best approach to setting up translations? The answer's probably unique to each project. But how to make maintenance a realistic task? The answer contains a tiny bit of genericity: automation saves time. What I built for the Ember Guides might give you some ideas. It's going to be about Node.js, git, and GitHub API.
```

2024-01-12 16:20 UTC, emmasofiah2o commented on src/posts/2024-01-10-ember-guides-fr-git-automation.md
> +When I am writing these lines,
```suggestion
As I am writing this blog post,
```

2024-01-12 16:20 UTC, emmasofiah2o commented on src/posts/2024-01-10-ember-guides-fr-git-automation.md
> +website accordingly. Let's say we must _"catch up"_ with English.
```suggestion
website accordingly. Let's say we must _"catch up"_ with the English version.
```

2024-01-12 16:20 UTC, emmasofiah2o commented on src/posts/2024-01-10-ember-guides-fr-git-automation.md
> +[the manual process to catch up with English](https://www.youtube.com/watch?v=hTc_vH-AQdk&t=282s)
```suggestion
[the manual process of catching up with English](https://www.youtube.com/watch?v=hTc_vH-AQdk&t=282s)
```

2024-01-12 16:20 UTC, emmasofiah2o commented on src/posts/2024-01-10-ember-guides-fr-git-automation.md
> +when a new version of the docs is released. However, such a manual process is
```suggestion
when a new version of the docs is released. However, such process is
```

2024-01-12 16:20 UTC, emmasofiah2o commented on src/posts/2024-01-10-ember-guides-fr-git-automation.md
> +not a realistic way to maintain the website in the long term.
```suggestion
not a realistic way to maintain the website in the long run.
```

2024-01-12 16:20 UTC, emmasofiah2o commented on src/posts/2024-01-10-ember-guides-fr-git-automation.md
> +API requests. However, it's not a "tutorial" so to speak, because we create the
```suggestion
API requests. However, it's not a "tutorial", because we create the
```

2024-01-12 16:20 UTC, emmasofiah2o commented on src/posts/2024-01-10-ember-guides-fr-git-automation.md
> +script in an existing app, we don't start from a blank page nor expect you to
```suggestion
script in an existing app. We don't start from a blank page nor expect you to
```

2024-01-12 16:20 UTC, emmasofiah2o commented on src/posts/2024-01-10-ember-guides-fr-git-automation.md
> +At the moment I am writing these lines, the latest version is v21.5.0. It lets
```suggestion
At the moment I am writing this, the latest version is v21.5.0. It lets
```

2024-01-12 16:20 UTC, emmasofiah2o commented on src/posts/2024-01-10-ember-guides-fr-git-automation.md
> +The output “I love Ember” shows up in the terminal 🎉
```suggestion
The output “I love Ember” shows up in the terminal. 🎉
```

2024-01-12 16:20 UTC, emmasofiah2o commented on src/posts/2024-01-10-ember-guides-fr-git-automation.md
> +read options by index or using
```suggestion
read options by index or using the
```

2024-01-12 16:20 UTC, emmasofiah2o commented on src/posts/2024-01-10-ember-guides-fr-git-automation.md
> +Now we have the expected format, let's store the arguments into variables that
```suggestion
Now that we have the expected format, let's store the arguments into variables that
```

2024-01-12 16:20 UTC, emmasofiah2o commented on src/posts/2024-01-10-ember-guides-fr-git-automation.md
> +header contains an `Authorization` field that must be filed with
```suggestion
header contains an `Authorization` field that must be filled with
```

2024-01-12 16:20 UTC, emmasofiah2o commented on src/posts/2024-01-10-ember-guides-fr-git-automation.md
> +It’s fine, but not good enough. We don’t want to copy manually the `token` from
```suggestion
It’s fine, but not good enough. We don’t want to copy the `token` manually from
```

2024-01-15 15:06 UTC, BlueCutOfficial commented on src/posts/2024-01-10-ember-guides-fr-git-automation.md
> +when a new version of the docs is released. However, such a manual process is
@emmasofiah2o With the suggestion, do you think it's clear that I mean "such process" in the way "such process when I run the steps manually"?

2024-01-15 15:50 UTC, emmasofiah2o requested changes
Reviewed up to line 882 ✅. Will finish up the rest later or tomorrow :)

2024-01-15 15:50 UTC, emmasofiah2o commented on src/posts/2024-01-10-ember-guides-fr-git-automation.md
> +committed to GitHub inadvertently. Along with this file, an `.env_example` which
```suggestion
committed to GitHub inadvertently. Along with this file, an `.env_example`, which
```

2024-01-15 15:50 UTC, emmasofiah2o commented on src/posts/2024-01-10-ember-guides-fr-git-automation.md
> +contains fake values is committed to GitHub and describes what secret variables
```suggestion
contains fake values, is committed to GitHub and describes what secret variables
```

2024-01-15 15:50 UTC, emmasofiah2o commented on src/posts/2024-01-10-ember-guides-fr-git-automation.md
> +Let's remove that `console.log` now the check is done. Once the `token` variable
```suggestion
Let's remove that `console.log` and now the check is done. Once the `token` variable
```

2024-01-15 15:50 UTC, emmasofiah2o commented on src/posts/2024-01-10-ember-guides-fr-git-automation.md
> +For instance, if we take one of our argument reading block, it would look like:
```suggestion
For instance, if we take one of our argument reading blocks, it would look like:
```

2024-01-15 15:50 UTC, emmasofiah2o commented on src/posts/2024-01-10-ember-guides-fr-git-automation.md
> +to commit them in a working branch. Once it's done, we are officially
```suggestion
to commit them in a working branch. Once that's done, we are officially
```

2024-01-15 15:50 UTC, emmasofiah2o commented on src/posts/2024-01-10-ember-guides-fr-git-automation.md
> +  non-translated English files targetted by the remaining diff blocks.
```suggestion
  non-translated English files targeted by the remaining diff blocks.
```

2024-01-15 15:50 UTC, emmasofiah2o commented on src/posts/2024-01-10-ember-guides-fr-git-automation.md
> +need. There's one case though we didn't mention at all. What if some of the
```suggestion
need. There's one case though, we didn't mention at all. What if some of the
```

2024-01-15 15:50 UTC, emmasofiah2o commented on src/posts/2024-01-10-ember-guides-fr-git-automation.md
> +"changed" files are new files that have been added to the latest Ember docs? so
```suggestion
"changed" files are new files that have been added to the latest Ember docs and
```

2024-01-15 15:50 UTC, emmasofiah2o commented on src/posts/2024-01-10-ember-guides-fr-git-automation.md
> +they don't exist at all in our current branch.
```suggestion
that don't exist at all in our current branch?
```

2024-01-15 15:50 UTC, emmasofiah2o commented on src/posts/2024-01-10-ember-guides-fr-git-automation.md
> +`git apply` success or failure, it also depends on the existence of the file in
```suggestion
`git apply`'s success or failure, it also depends on the existence of the file in
```

2024-01-15 15:50 UTC, emmasofiah2o commented on src/posts/2024-01-10-ember-guides-fr-git-automation.md
> +should be posted.
```suggestion
need to be posted.
```

2024-01-15 15:50 UTC, emmasofiah2o commented on src/posts/2024-01-10-ember-guides-fr-git-automation.md
> +`fs` and use the function called `existsSync`. We'll learn more about `fs`
```suggestion
`fs` and use the function called `existsSync`. We'll learn more about the `fs`
```

2024-01-15 15:50 UTC, emmasofiah2o commented on src/posts/2024-01-10-ember-guides-fr-git-automation.md
> +missing file and therefore false the value.
```suggestion
missing file and therefore compromise the value.
```

2024-01-16 09:14 UTC, emmasofiah2o commented on src/posts/2024-01-10-ember-guides-fr-git-automation.md
> +when a new version of the docs is released. However, such a manual process is
Yeah, "such" indicates the process. There is no need to specify further. You are free to not use my suggestions when they are style-related tho (like this one) :)

2024-01-16 11:18 UTC, emmasofiah2o requested changes
Final review ✅.

**Overall impressions:** the post is well-written and very informative. 
I like how you took the time to explain each and every step so that your process is understandable, even without a lot of previous knowledge on the topic. 
It is long, but I wouldn't try to shorten it. You included everything from the introduction to the conclusion and the structuring is very well done, too. 

Great work! 😊

2024-01-16 11:18 UTC, emmasofiah2o commented on src/posts/2024-01-10-ember-guides-fr-git-automation.md
> +- In revenge, if a patch file cannot be aplied automatically, we'll reuse its
```suggestion
- On the contrary, if a patch file cannot be applied automatically, we'll reuse its
```

2024-01-16 11:18 UTC, emmasofiah2o commented on src/posts/2024-01-10-ember-guides-fr-git-automation.md
> +like `./list.diff`. Also, note that `./` is not the location of `catchup.mjs`
```suggestion
like `./list.diff`. Also, note that `./` is not the location of the `catchup.mjs`
```

2024-01-16 11:18 UTC, emmasofiah2o commented on src/posts/2024-01-10-ember-guides-fr-git-automation.md
> +script but it’s from where we are running the script. It means that if we are at
```suggestion
script, but it’s from where we are running the script. It means that if we are at
```

2024-01-16 11:18 UTC, emmasofiah2o commented on src/posts/2024-01-10-ember-guides-fr-git-automation.md
> +the root of the `ember-fr-guides-source` folder then we use the command
```suggestion
the root of the `ember-fr-guides-source` folder and we use the command
```

2024-01-16 11:18 UTC, emmasofiah2o commented on src/posts/2024-01-10-ember-guides-fr-git-automation.md
> +The content of `list.diff` contains one line per file name, using a
```suggestion
The content of `list.diff` contains one line per file name: using a
```

2024-01-16 11:18 UTC, emmasofiah2o commented on src/posts/2024-01-10-ember-guides-fr-git-automation.md
> +The patch files are created in `scripts/patches` folder. Once the file is
```suggestion
The patch files are created in the `scripts/patches` folder. Once the file is
```

2024-01-16 11:18 UTC, emmasofiah2o commented on src/posts/2024-01-10-ember-guides-fr-git-automation.md
> +-Every `<input>` element should have an associated `<label>` element. To do this, the `<input>` element's `id` attribute value should be the same as the `for` attribute value on the `<label>`, like t
```suggestion
```

2024-01-16 11:18 UTC, emmasofiah2o commented on src/posts/2024-01-10-ember-guides-fr-git-automation.md
> +`shorterFilename` is just a way to remove `guides` from the filename to cut a
```suggestion
`shorterFilename` is just a way to remove `guides` from the filename to cut the issue title
```

2024-01-16 11:18 UTC, emmasofiah2o commented on src/posts/2024-01-10-ember-guides-fr-git-automation.md
> +bit the issue title. We can obtain it with a simple
```suggestion
down a bit. We can obtain it with a simple
```

2024-01-16 11:18 UTC, emmasofiah2o commented on src/posts/2024-01-10-ember-guides-fr-git-automation.md
> +we just want to show the diff on GitHub without it's necessarily a valid patch
```suggestion
we just want to show the diff on GitHub without it being necessarily a valid patch
```

2024-01-16 11:18 UTC, emmasofiah2o commented on src/posts/2024-01-10-ember-guides-fr-git-automation.md
> +Owww but wait a second 🙀 Earlier in this blog post, we introduced async
```suggestion
Owww but wait a second 🙀. Earlier in this blog post, we introduced async
```

2024-01-16 11:18 UTC, emmasofiah2o commented on src/posts/2024-01-10-ember-guides-fr-git-automation.md
> +- `Promise` constructor takes a function in argument. The core of this function
```suggestion
- The `Promise` constructor takes a function in argument. The core of this function
```

2024-01-16 11:18 UTC, emmasofiah2o commented on src/posts/2024-01-10-ember-guides-fr-git-automation.md
> +In the big lines, this is it!
```suggestion
This is it!
```

I don't think "in the big lines" exists as an expression in English...

2024-01-16 11:18 UTC, emmasofiah2o commented on src/posts/2024-01-10-ember-guides-fr-git-automation.md
> +separated from the rest of the logs. We could also switch back to `master` or
```suggestion
separated from the rest of the logs. We could also switch back to the `master` or
```

2024-01-16 11:18 UTC, emmasofiah2o commented on src/posts/2024-01-10-ember-guides-fr-git-automation.md
> +actions. In terms of clean-up, we could also remove `scripts/patches` folder and
```suggestion
actions. In terms of clean-up, we could also remove the `scripts/patches` folder and
```

2024-01-16 11:18 UTC, emmasofiah2o commented on src/posts/2024-01-10-ember-guides-fr-git-automation.md
> +does what we think it does. In case you wonder, such tests don't exist when I am
```suggestion
does what we think it does. In case you wonder, such tests don't exist yet as I am
```

2024-01-16 11:18 UTC, emmasofiah2o commented on src/posts/2024-01-10-ember-guides-fr-git-automation.md
> +looks like, I did what I usually do: manual process first, then automation will
```suggestion
looks like, I did what I usually do: manual process first, then switch to the automation
```

2024-01-16 11:18 UTC, emmasofiah2o commented on src/posts/2024-01-10-ember-guides-fr-git-automation.md
> +come when I am clear with what I want. I created a sandbox project that contains
```suggestion 
when I am clear with what I want. I created a sandbox project that contains
```

2024-01-16 11:18 UTC, emmasofiah2o commented on src/posts/2024-01-10-ember-guides-fr-git-automation.md
> +You can see the final version of the script in `ember-fr-guides-source`
```suggestion
You can see the final version of the script in the `ember-fr-guides-source`
```

2024-01-16 11:18 UTC, emmasofiah2o commented on src/posts/2024-01-10-ember-guides-fr-git-automation.md
> +As said at the beginning of this article, none of this answers the question how
```suggestion
As said at the beginning of this article, none of this answers the question "how
```

2024-01-16 11:18 UTC, emmasofiah2o commented on src/posts/2024-01-10-ember-guides-fr-git-automation.md
> +to bootstrap a translation project, what's the best approach to use? But all the
```suggestion
to bootstrap a translation project, what's the best approach to use?". However, all the
```

2024-01-16 11:18 UTC, emmasofiah2o commented on src/posts/2024-01-10-ember-guides-fr-git-automation.md
> +above may have convinced you that maintenance automation is not a so big deal.
```suggestion
above may have convinced you that maintenance automation is not that big of a deal.
```

2024-01-16 11:18 UTC, emmasofiah2o commented on src/posts/2024-01-10-ember-guides-fr-git-automation.md
> +And it's an iterative process. I could have started using this script to
```suggestion
And it's an iterative process, too. I could have started using this script to
```

2024-01-16 11:18 UTC, emmasofiah2o commented on src/posts/2024-01-10-ember-guides-fr-git-automation.md
> +it's complete, there are certainly improvements to make, but it doesn't prevent
```suggestion
that it's complete, there are certainly improvements to make, but it doesn't prevent
```

2024-01-16 11:18 UTC, emmasofiah2o commented on src/posts/2024-01-10-ember-guides-fr-git-automation.md
> +me from using the script and saving time today 😉
```suggestion
me from using the script and saving time today 😉.
```

2024-01-16 15:39 UTC, BlueCutOfficial commented on src/posts/2024-01-10-ember-guides-fr-git-automation.md
> +committed to GitHub inadvertently. Along with this file, an `.env_example` which
```suggestion
committed to GitHub inadvertently. Along with this file, an `.env.example`, which
```

2024-01-16 15:44 UTC, BlueCutOfficial commented on src/posts/2024-01-10-ember-guides-fr-git-automation.md
> +Let's remove that `console.log` now the check is done. Once the `token` variable
It's more like: we checked it works using `console.log`, so we can remove the `console.log` now. Maybe I can just remove the second part.

```suggestion
Let's remove that `console.log`. Once the `token` variable
```

2024-01-16 16:08 UTC, emmasofiah2o commented on src/posts/2024-01-10-ember-guides-fr-git-automation.md
> +Let's remove that `console.log` now the check is done. Once the `token` variable
I think it works with your second version :)

2024-01-16 16:13 UTC, BlueCutOfficial commented on src/posts/2024-01-10-ember-guides-fr-git-automation.md
> +-Every `<input>` element should have an associated `<label>` element. To do this, the `<input>` element's `id` attribute value should be the same as the `for` attribute value on the `<label>`, like t
This one is part of a diff file so it's supposed to be here. The two lines prefixed with `-` and `+` are not exactly the same. I removed the first part to make them shorter and the diff easier to see, though the way the article shows is not perfect.

2024-01-17 08:05 UTC, marcoow reviewed
This is a nice overview – didn't have the time now to go through it completely but will continue later

2024-01-17 08:05 UTC, marcoow commented on src/posts/2024-01-10-ember-guides-fr-git-automation.md
> +title: "Automating the maintenance of the Ember Guides FR"
```suggestion
title: "Automating the maintenance of the Ember Guides in French"
```

might be clearer…

2024-01-17 08:05 UTC, marcoow commented on src/posts/2024-01-10-ember-guides-fr-git-automation.md
> +    One of the main blockers to translation projects is the overwhelming question: how do you maintain it? The tool you're building is already big, and the English docs for this tool are generally a
I'd add a sentence in the beginning to introduce the fact that you work on translating the Ember guides to french, maybe with a link? Not everyone reading this is going to be familiar with the project

2024-01-17 08:05 UTC, marcoow commented on src/posts/2024-01-10-ember-guides-fr-git-automation.md
> +- [Table of contents](#table-of-contents)
```suggestion
```

I don't think this is necessary?

2024-01-17 08:05 UTC, marcoow commented on src/posts/2024-01-10-ember-guides-fr-git-automation.md
> +#### a. Running a mjs script
```suggestion
#### a. Running an mjs script
```

2024-01-17 08:05 UTC, marcoow commented on src/posts/2024-01-10-ember-guides-fr-git-automation.md
> +const currentEmberVersion = `${argv.from}`;
```suggestion
const currentEmberVersion = argv.from;
```

isn't `args.from` a string already?

2024-01-17 08:05 UTC, marcoow commented on src/posts/2024-01-10-ember-guides-fr-git-automation.md
> +  process.exit(9);
Why 9?

2024-01-17 08:05 UTC, marcoow commented on src/posts/2024-01-10-ember-guides-fr-git-automation.md
> +const getRequestHeaders = () => {
Should this receive the token as an argument or read it from `ENV`? I guess the way it works now is it just relies on the variable being defined in the parent context but I'm not sure that's recommendable…

2024-01-17 08:05 UTC, marcoow commented on src/posts/2024-01-10-ember-guides-fr-git-automation.md
> +  process.exit(9);
Ah, I see it's explained below – might be good to add a note here, not only in the second occurence

2024-01-17 08:05 UTC, marcoow commented on src/posts/2024-01-10-ember-guides-fr-git-automation.md
> +is empty.
I don't understand – the above code awaits both operations so they run sequentially to completion and are guaranteed to complete one after the other?

2024-01-17 08:05 UTC, marcoow commented on src/posts/2024-01-10-ember-guides-fr-git-automation.md
> +```
I don't understand this part about async and exit codes tbh… If any of the arguments are invalid you wouldn't event kick off any async operations? Also parsing and checking the arguments is non-async anyway?

2024-01-17 09:29 UTC, BlueCutOfficial commented on src/posts/2024-01-10-ember-guides-fr-git-automation.md
> +const getRequestHeaders = () => {
Yes, for now, it relies on the variable `token` declared at the beginning of the script. It's a standalone script that reads `process.env`, it doesn't export any class or anything. Do you think that could be a problem?

2024-01-17 09:33 UTC, BlueCutOfficial commented on src/posts/2024-01-10-ember-guides-fr-git-automation.md
> +is empty.
I guess the snippet I wrote doesn't match what I wanted to express, it's supposed to be non-sequential 🙈 I'll change it to something more clear.

2024-01-17 09:51 UTC, BlueCutOfficial commented on src/posts/2024-01-10-ember-guides-fr-git-automation.md
> +```
I had a hard time with this part because I wanted to keep the article organized and easy to follow by separating the different main themes: Node.js generalities, then git commands, then managing files... but the benefits of assigning `process.exitCode` rather than exiting the process in this script has not appeared yet at this point of the article.

If any of the arguments are invalid I exit right away, but later, if I already have async operations in progress, I generally don't want to kill the script at a random moment that prevents me from knowing exactly what it had time to do or not do. I can maybe just make this part more abstract and not try to show a real example linked to the script.

2024-01-17 12:54 UTC, marcoow commented on src/posts/2024-01-10-ember-guides-fr-git-automation.md
> +const getRequestHeaders = () => {
No, not a big deal but it's easy to fix by simply adding the argument and that would make it clearer as well I think.

2024-01-17 12:55 UTC, marcoow commented on src/posts/2024-01-10-ember-guides-fr-git-automation.md
> +```
Tbh, it feels like you can this entire part about exit code and asynchronicity our to simplify things? I don't get the impression it's really relevant?

2024-01-17 13:20 UTC, BlueCutOfficial commented on src/posts/2024-01-10-ember-guides-fr-git-automation.md
> +```
I could simplify it and not go that deep into implementation details. I feel like I should mention somewhere that before calling `process.exit()` directly you should think carefully about the consequences, `process.exit()` _vs_ `process.exitCode =` is part of the basics to me. I'll see if I can condense the idea in the previous section maybe, I'll give it a try.

2024-01-17 13:34 UTC, marcoow commented on src/posts/2024-01-10-ember-guides-fr-git-automation.md
> +```
I still don't really get it tbh – I think the real problem is you don't want to start any non-awaited async operations?

2024-01-17 14:18 UTC, marcoow commented on src/posts/2024-01-10-ember-guides-fr-git-automation.md
> +let files;
I think it's confusing to declare this here and fill it later. I guess it's easier (and results in better code as well) to declare and define it in the `try`/`catch` at the bottom and pass it into `applyPatches` as an argument?

2024-01-17 14:18 UTC, marcoow commented on src/posts/2024-01-10-ember-guides-fr-git-automation.md
> +        console.log(`"git apply" command failed for ${diffName}`); // we prefer console.log over console.warn, because failure is part of the normal process
Should there be a TODO here saying this is the point where we'll create a GH issue later on?

2024-01-17 14:18 UTC, marcoow commented on src/posts/2024-01-10-ember-guides-fr-git-automation.md
> ++ let filesToPost = [];
again, might be clearer to return this from `applyPatches` instead of using a global variable.

2024-01-17 14:18 UTC, marcoow commented on src/posts/2024-01-10-ember-guides-fr-git-automation.md
> ++ let hasPendingDiff = false;
see above – I think mixing global variables and functions is bad advice.

2024-01-17 14:18 UTC, marcoow commented on src/posts/2024-01-10-ember-guides-fr-git-automation.md
> +});
I think starting un-awaited operations like this is bad. I understand now why you need the part about async and exit codes above if you want to do things like this but I think the approach is wrong already tbh. With this, you end up in a mixed success/error state where maybe everything worked perfectly but some files end up not being deleted end you might exit with an error code. I don't think the goal should be making this possible but avoiding this – when that situation isn't possible, you don't need the entire logic for un-awaited async operations and exit codes like I explained above.

2024-01-17 14:18 UTC, marcoow commented on src/posts/2024-01-10-ember-guides-fr-git-automation.md
> +case is a problem or not.
and more importantly, it will make the command succeed if there is **no** `scripts` folders – it's the same as `mkdir -p` essentially

2024-01-17 14:18 UTC, marcoow commented on src/posts/2024-01-10-ember-guides-fr-git-automation.md
> +folder in the scripts folder:
Typically, what I'd recommend doing in these cases would be to create a tmp folder that's automatically going to be cleaned up by the OS – see https://nodejs.org/api/os.html#ostmpdir etc.

2024-01-17 14:18 UTC, marcoow commented on src/posts/2024-01-10-ember-guides-fr-git-automation.md
> +functions:
I'd strongly recommend using `Promise.all` and `await` that so that **all** of the async operations **run in parallel** but you **don't move on before all of them have completed** – see my comments above.

Also, generally you don't want to use callback functions at all in modern JS/Node and always default to `async`/`await`.

2024-01-17 14:18 UTC, marcoow commented on src/posts/2024-01-10-ember-guides-fr-git-automation.md
> ++     return new Promise((resolve) => {
I don't think you need to explicitly return a `Promise` here – you can just make the callback passed to `map` async?

2024-01-17 14:18 UTC, marcoow commented on src/posts/2024-01-10-ember-guides-fr-git-automation.md
> ++   return Promise.all(writePromises).then((results) => {
```suggestion
+   let results = await Promise.all(writePromises);
```

I'd recommend avoiding `then`

2024-01-17 16:26 UTC, BlueCutOfficial commented on src/posts/2024-01-10-ember-guides-fr-git-automation.md
> +folder in the scripts folder:
Thanks for the link. The reason it was intuitive to me to use a classic folder is that I wanted to be able to use it at a later time. When I iterated on the script, I didn't design it to "do everything" or "do nothing". For instance, let's say I want to post 3 issues to GitHub and for some reason, GitHub API responds with an error for only 1 request. The 2 other issues now exist on GitHub and today, even if I figure out what went wrong, the easiest way for me to finish the sync is to manually open the missing issue. If I still have the patch file available on the catchup branch, I can do that very easily, which won't be the case if I clean up everything.

The way I built the script for real isn't necessarily the way I built it in the blog post, which is probably why some choices may look confusing at first glance. But also the script is very recent and I didn't have the opportunity to take a step back, so I am sure there are many improvements to make.

2024-01-17 16:48 UTC, marcoow commented on src/posts/2024-01-10-ember-guides-fr-git-automation.md
> +folder in the scripts folder:
Yes, I see – I think some of that history and addtl. context leaks into the blog post now though making it more complex and harder than it needs to be… At the same time, like this it presents some patterns I'd actually say are not ones we'd recommend to anyone…

2024-01-17 17:25 UTC, BlueCutOfficial commented on src/posts/2024-01-10-ember-guides-fr-git-automation.md
> +});
File deletion is not super relevant for the script anyway, so I can drop that part.

2024-01-17 17:33 UTC, BlueCutOfficial commented on src/posts/2024-01-10-ember-guides-fr-git-automation.md
> +let files;
I can change that, sure. Using global variables was just more readable to me in that case.

2024-01-19 18:24 UTC, BlueCutOfficial commented on src/posts/2024-01-10-ember-guides-fr-git-automation.md
> ++     return new Promise((resolve) => {
In the previous version with callback functions, the usage of `resolve` was simpler to control when the `Promise` was fulfilled. I rewrote everything with `fs/promises` (I wasn't aware there were two different APIs for the files) so I could drop `Promise`.

2024-01-25 09:45 UTC, BlueCutOfficial commented
I iterated on the code to use `fs/promises` and remove globals. I also removed non-essential parts to simplify. Overall, all the comments were considered.

2024-01-26 10:28 UTC, marcoow approved these changes
🙌

2024-01-30 08:29 UTC, emmasofiah2o approved these changes

2024-01-30 09:11 UTC, merged