Add rail europe featured case study
mainmatter/mainmatter.com pull request #2301
Opened 2024-01-18 16:00 UTC by yaigrie

2024-01-18 16:03 UTC, yaigrie commented
- [ ] add screenshots of the rail europe platform

2024-01-30 07:47 UTC, SaeLLo commented on src/cases/rail-europe.md
> +    <h3 class="h4">Rail Europe was founded in 1931 and is looking back at an impressive history of 90+ years in the travel economy. Over the years, the company established itself as the go-to brand f
Wouldn't be "Industry" the right word (instead of "Economy")?

2024-01-30 07:48 UTC, SaeLLo commented
I was wondering if we should also add the tag "development"?

2024-01-30 07:49 UTC, SaeLLo commented
@marcoow Can you also review so we can merge this?

2024-01-30 16:52 UTC, marcoow reviewed
Let's feature this at the top of the Work page and shift all the others down? I'd also put Jürgen's image next to the quote and place the quote somewhere inside of the text maybe vs. at the bottom under the image? We should also add Rail Europe to the "Work" list in the footer (and maybe remove Timify and Expedition from there) and we could feature the case study on the Svelte page as well. Finally, we **could** replace one of the featured case studies on the home page with the RE case (I'd suggest replacing mvb).

2024-01-31 16:50 UTC, yaigrie commented
@marcoow Are therentwo other case studies we could feature on the svelte page, so we can have three?
right now, there are only blog posts on the technology pages, can we find three case studies for each one?

2024-02-01 07:02 UTC, marcoow commented
We only have this one for Svelte for now. We need to have design options though that allow us to work with that as well. For the Rust and Elixir pages I think we also only have one each, for Ember it's no problem to find 3.

2024-02-02 16:52 UTC, marcoow requested changes
Just one more thing I just recognized: now the small description of our work for RE is right below the teaser for this new case study. Let's switch the positions of the RE and Sage small descriptions on the /work page

2024-02-05 09:20 UTC, marcoow commented on src/index.njk
> +{% set clients = ['qonto', 'experteer', 'trainline', 'rail-europe'] %}
@yaigrie let's replace Experteer with Aleph Alpha (in a separate PR)

2024-02-05 09:22 UTC, marcoow approved these changes

2024-02-05 09:22 UTC, merged