Embroider sponsors
mainmatter/mainmatter.com pull request #2308
Opened 2024-01-26 14:25 UTC by yaigrie

2024-01-26 15:03 UTC, marcoow approved these changes

2024-01-26 15:04 UTC, marcoow requested changes
The image in the background of the teaser on the Ember landing page needs to be updated as well: https://deploy-preview-2308--objective-northcutt-37494c.netlify.app/ember-consulting/

2024-01-26 16:58 UTC, yaigrie commented
@marcoow I added the new image, but the preview doesn't update it - did I do something wrong?

2024-01-30 16:47 UTC, marcoow commented
There's problems with caching in Netlify sometimes – I rebuilt with clean cache

2024-02-04 15:59 UTC, marcoow approved these changes

2024-02-04 16:12 UTC, merged