Energy update
mainmatter/mainmatter.com pull request #2311
Opened 2024-01-30 15:34 UTC by yaigrie

2024-01-30 15:48 UTC, yaigrie commented
- [ ] fix mobile font-sizes
- [ ] check mobile for bugs
- [ ] add images to consulting pages
- [ ] add icons to blogposts
- [ ] add gradient to all cards
- [ ] fix links on cards
- [ ] add links to tags/author etc on cards
- [ ] add icons for topics not related to programming languages
- [ ] test other gradients for buttons
- [ ] rework workshop pages

2024-02-01 16:12 UTC, yaigrie commented
@marcoow Hey :) Sadly this is taking me a bit longer than I thought (I hope I will get better at estimating times with more experience ;) )
But I think it's in a state where you could already take a look and tell me your thoughts :)

2024-02-02 08:02 UTC, marcoow commented
Just had a quick looks – generally I think this is good! Some things I noticed:

* The spacing doesn't feel quite right – things look a bit more crammed than on the current site and it seems we're losing a bit of the stringency and sophistication of the current design. I think it's good that some things get bigger but not sure font sizes and spacing overall are quite right yet?
* I think for the hover effect we'd need a transition – it's a bit harsh on the buttons and in particular for larger areas like the case study teasers (also there, the white logos load lazily on hover which means there's a delay which makes it seem slightly broken…)
* On the contact page, we should keep the form at the top – that's the most important thing on that page.
* In the services popover menu, we should definitely include the subtexts for each service (e.g. _"Accelerate delivery and overcome challenges"_ for "Team Reinforcement"), also the services list seems like it needs more spacing around the items?
* I think making bold text purple makes it look like links? ![Bildschirmfoto 2024-02-02 um 08 55 49](https://github.com/mainmatter/mainmatter.com/assets/1510/929e2e0c-7295-4ce8-bfd7-0e13e89167da)
* Generally, I think (but that's likely due to this being in-progress) some elements now look a bit out of place, e.g. the links with the black underlines don't really seem to fit in with the rest of the design anymore…
* I'm not sure we should maybe keep the background images at least for the header sections? The home page now looks much blander than the live version?

| Live | PR |
|-----|----|
| ![Bildschirmfoto 2024-02-02 um 08 58 00](https://github.com/mainmatter/mainmatter.com/assets/1510/751d3c12-2e24-450e-98b8-fac165628f0b)| ![Bildschirmfoto 2024-02-02 um 08 57 58](https://github.com/mainmatter/mainmatter.com/assets/1510/5e5b0512-0d4f-4bbb-bb8f-a41e3a1d22ab)|

* I think in the current live version, the header sections are always `min-height: 100vh` which I guess we should keep (look at the little white bar at the bottom of the homepage in this PR in the screenshot above)
* I don't think the hover effect with the numbered lists works quite well atm unless you scroll super slow; might be better to just leave it out?
* I think we should use the opportunity to make larger areas linked like not only the "Learn more" in this case but maybe the entire element? I always find it annoying having to hover over a specific text when really the whole element is a teaser to go somewhere?

![Bildschirmfoto 2024-02-02 um 09 00 58](https://github.com/mainmatter/mainmatter.com/assets/1510/5477b672-3111-46ef-a9f3-d286bb40d835)

Let me know if you want an in-depth review, e.g. I haven't really looked at mobile yet but I guess it's too early for that at this stage anyway.

2024-02-08 13:21 UTC, yaigrie commented
- [ ] add case studies to startup page
- [ ] find/create hero images

2024-02-08 13:49 UTC, yaigrie commented
@marcoow What kind of hero images would you like to use? I tried an abstract gradient-background on the index, let me know what you think about that. I think it could be hard to find playful ones like we're using now within the content, as they probably won't work well in terms of readability 
Another option would be just keeping the old ones, but those are very stocky

2024-02-08 14:03 UTC, marcoow commented
Hm, yeah – not too easy maybe. I think we can also use a bit more abstract ones (e.g. the one we use for Aleph Alpha works quite well I think: https://mainmatter.com/cases/aleph-alpha/, or the one for the Playbook: https://mainmatter.com/playbook/)

Also I'd like to keep the background graphics for the big teasers on the work page as well – I think that looks much better overall? https://mainmatter.com/work/

Some other, small things:

* the hover effects on all the teasers don't work (in Safari) – everything just completely disappears on hover; also the text is being replaced immediately while the background animates which looks a bit strange?
* I don't think the sizing of things quite works – e.g. on https://deploy-preview-2311--objective-northcutt-37494c.netlify.app/work/, the images for the small cases are too small in relation to the text (also the link to the service should maybe have an arrow?)
* In the services menu, can we vertically center the list? Also, can we link each point entirely, not just the title? Also, should we keep the other elements we currently have in the menu, or is there not enough space?
* on the start page "Why mainmatter" – Mainmatter needs to be capitalized
* I can't say exactly why but overall, font sizes, line heights, and spacing seem more consistent and better looking on the current site
* On the services pages, we need some quotes etc. – otherwise it's too text-heavy, in particular between "We’ll work with you to:" and the next image on e.g. this page: https://deploy-preview-2311--objective-northcutt-37494c.netlify.app/services/team-reinforcement/
* I'm not surew the design of the events page (in particular the events) still fits in very well? https://deploy-preview-2311--objective-northcutt-37494c.netlify.app/events/

2024-02-08 15:44 UTC, yaigrie commented
- [ ] small case logos bigger
- [ ] add arrow to case tags
- [ ] look into full screen menu
- [ ] look into events page
- [ ] adjust service pages

2024-02-08 16:47 UTC, yaigrie commented
@marcoow Thank you for your feedback!! :) 

I simply changed it back to the old typography 🙂 Does it feel better now? 
With the smaller body text I felt that the intro sections on the service pages don't make much sense anymore, so I put those into the hero, but also repositioned the images, which should loosen up the text a bit? But we can of course still add quotes too.
It seems like Safari interprets the screen blend mode different than Chrome, I adjusted it slightly so that it's not THAT broken anymore, but I will look into finding a substitute gradient background ;( 
I think I would get rid of the other content in the menu, to have it not scroll, but I can put it back in if it's more important to have it in there than the menu not scrolling (I guess we can't prevent it from scrolling on smaller devices anyway)

I will also work on the event page :)

2024-02-08 17:22 UTC, marcoow commented
I think we can make the text larger – it just didn't feel consistent overall, e.g. it didn't seem we still had the same ratio between font size, line height, padding, etc.? Everything seemed much more condensed?

I'm not 100% about the gradient tbh – it's a completely new element I'm not sure fits in really well with the branding…

2024-02-13 09:49 UTC, yaigrie commented
@marcoow Can you please tell me your thoughts about the new hero images, hover effects and font sizes? :) Thank you!

2024-02-13 11:55 UTC, marcoow commented
I will tonight on the train

2024-02-13 18:40 UTC, marcoow commented
* I think the font sizes look good but I'm not sure they are a little too big now, e.g. for some pages not all of the headline fits in the viewport (at least not unless you make the browser window huge), e.g.:

![Bildschirmfoto 2024-02-13 um 19 38 53](https://github.com/mainmatter/mainmatter.com/assets/1510/17a3c814-e7cf-4eb3-850a-402ab4f88817)

Have a look at some of our competitors – they all use smaller text and thus can display more at once:

  * https://thoughtbot.com
  * https://dockyard.com

* for the hover effect, I think generally it works but
  * for some elements, the background overlay that comes in from the left just disappears when I hover out (for others, it correctly moves out to the left again)
  * for the elements that also have the changing text I wouldn't use it at all – it's just too much movement then
  * also I wouldn't use that grey overlay that just makes the background color a bit darker, that's a bit boring – maybe we use a different color instead (e.g. green button gets purple overlay in the back or something – just an idea, might be bad :) and you might have better ideas – I just don't think that grey colors adds to the overall energy)?
* I think the background images for the hero sections work – I'd review again regarding which exact image we're using for what page but overall I think it works

2024-02-14 09:01 UTC, yaigrie commented
- [ ] make font sizes just a little bit smaller 🙂
- [ ] remove hover from case studies
- [ ] find alternative for grey overlay
- [ ] figure out why hover out sometimes doesn't work

2024-02-14 11:35 UTC, marcoow commented
@yaigrie let's not introduce new shared of our standard colors. Also, I thought the purple background for e.g. the Qonto case on the landing page worked well? The teal color feels a bit more out of place there since the overlay on the background image is purple already and then solid purple feels more consistent?

2024-02-14 11:52 UTC, yaigrie commented
@marcoow I'm having trouble to think of a good solution to only use existing colors for the hover effect, as we're likely to reproduce to current problem with e.g. hovering an aqua button on a purple background - if the hover color is purple too, then it looks weird. 
I agree though that using those filtered colors as a hover effect for different colors doesn't look good, too

2024-02-14 12:37 UTC, marcoow commented
maybe we just put an arrow in the buttons similar to the one we use for links anyway and then animate that somehow?

2024-02-14 12:39 UTC, marcoow commented
For the overlay, I think what you had before made sense btw: the background coming in from the left would be the same color that's also used for overlaying the photo, e.g. purple for the aleph alpha case but black for the trainline case here: https://deploy-preview-2311--objective-northcutt-37494c.netlify.app/work/

2024-02-14 14:50 UTC, yaigrie commented
The arrows are a great idea as they work on each background, thank you! Should we leave the old hover effect for the case studies?

2024-02-14 14:56 UTC, marcoow commented
I think the hover effect for the case study teasers is good as it is now (with different colors for the different background images). Let me know when I should do a full review.

2024-02-14 14:58 UTC, yaigrie commented
@marcoow I just adjusted the font sizes a bit, I think you can start with the full review :)

2024-02-14 16:11 UTC, marcoow reviewed
Overall I like it – I think this is a good update!

The hover effect on the "Contact" looks a bit strange:

https://github.com/mainmatter/mainmatter.com/assets/1510/85498bc3-3e09-4289-9ed4-864d6feb12ad

compare that to hovering over "Services" in the menu which looks much better:

https://github.com/mainmatter/mainmatter.com/assets/1510/f33b63c7-b360-4b64-b7c1-59bbbb806f43


Something doesn't seem right with the multiple arrows on the starting page, in particular when hovering over them fast:

https://github.com/mainmatter/mainmatter.com/assets/1510/a7495fa1-4a72-4224-a7ec-b8f873201239

Same with the case study on the landing page (generally, it seems all the "unhover" animations start from 100% and will never work when the un-hovering happens before the "hover" animation is complete?): 

https://github.com/mainmatter/mainmatter.com/assets/1510/4a3a87c6-40e1-40df-8e7d-9d671d64311d

I don't think the text fading works well – it's a bit messy while the one text fades out and the other fades in. Maybe we should think about the replacement text sliding in from the left like the background color on the teaser above? That way it would also be more consistent? Also, the same problem as for the other animations when you hover out before the hover in animation has completed:

https://github.com/mainmatter/mainmatter.com/assets/1510/ab1e66cf-0d14-4905-9490-af47f4aa62ea

The Elixir and Phoenix teaser is missing the image: 

![Bildschirmfoto 2024-02-14 um 16 28 47](https://github.com/mainmatter/mainmatter.com/assets/1510/8eb79238-6520-4e7d-9cc2-ca60eb827e2d)

Let's make all of these linked and react to hover, not just the bold text: 
![Bildschirmfoto 2024-02-14 um 16 29 38](https://github.com/mainmatter/mainmatter.com/assets/1510/1c12908b-237b-4a54-9670-88b4d0c31ede)

For "technologies" on the Tech Modernization page, we should only show Ember, Ruby on Rails, Elixir & Phoenix.

On the individual workshop pages, the content is escaped (see `<code>` tags which should not be rendered but be actual tags in the source): ![Bildschirmfoto 2024-02-14 um 16 33 42](https://github.com/mainmatter/mainmatter.com/assets/1510/79154afe-3d92-4d48-bfac-b0b65e84163d)

2 Twitter links for the workshop mentor: 
![Bildschirmfoto 2024-02-14 um 16 34 33](https://github.com/mainmatter/mainmatter.com/assets/1510/14e04651-061f-4301-b40d-f9c3ee40f665)

When loading the page, the arrow animations play once:

https://github.com/mainmatter/mainmatter.com/assets/1510/0b18f8a9-82c5-47e1-8dbb-181bd9714c4e

On the blog, the arrow for the "Previous" link points in the wrong direction: 
![Bildschirmfoto 2024-02-14 um 16 36 55](https://github.com/mainmatter/mainmatter.com/assets/1510/b5701678-ff51-44f5-92fd-14833c71090d)

* The "Download our playbook" button looks a little out of place (also double underline on hover): 
![Bildschirmfoto 2024-02-14 um 16 37 48](https://github.com/mainmatter/mainmatter.com/assets/1510/52daef4f-00f6-4d18-96a2-9e5edce90f79)

* Let's only keep the lower "Download our playbook" link here:  ![Bildschirmfoto 2024-02-14 um 16 38 45](https://github.com/mainmatter/mainmatter.com/assets/1510/571d69c9-09c8-4a2b-af9c-f8c8b23c7c7a)

* Since the entire block is linked, can we make the entire block react to hovering over (same for other, similar blocks of course)? ![Bildschirmfoto 2024-02-14 um 16 39 41](https://github.com/mainmatter/mainmatter.com/assets/1510/a599662f-7f1f-41a6-aa69-044356478161)

* I think this looks a bit all-over-the-place – should we put the logos on a background color? 
![Bildschirmfoto 2024-02-14 um 16 40 46](https://github.com/mainmatter/mainmatter.com/assets/1510/bc434c2b-c173-4776-86f0-d13124944d23)

* Can we make the individual elements aligned vertically (this looks a bit messy)?  ![Bildschirmfoto 2024-02-14 um 16 41 31](https://github.com/mainmatter/mainmatter.com/assets/1510/47cbb83c-66aa-44ad-bf9a-03dcced77d7f)

* The small text on the left and the big link on the right in the same line looks a bit strange to me… ![Bildschirmfoto 2024-02-14 um 16 43 11](https://github.com/mainmatter/mainmatter.com/assets/1510/4120d08d-5faa-4269-bb0e-2873cd03479d)

* Let's only have the Rust Foundation logo here: ![Bildschirmfoto 2024-02-14 um 16 44 25](https://github.com/mainmatter/mainmatter.com/assets/1510/7aae5ef7-563c-4dd9-88a3-c4f864265628)
* For the background images in the header hero sections, let not use CSS background images but the approach we had before where the image appears in the HTML source as that's much more efficient and the image doesn't load in lazily only after the page has loaded. You should be able to reuse the code we have there.
* Should we make the "Send message" on the contact form a button now?
* The submission confirmation overlay after the contact form doesn't seem to be sticky anymore so that the "X" isn't in the top right of the viewport anymore but in the top right of the page now so I have to scroll up to see it. That should be fixed, otherwise people end up being lost.
* Let's use a background image for the header on the "Events" page: https://deploy-preview-2311--objective-northcutt-37494c.netlify.app/events/
* The title of the top post on the blog page should be linked so I don't have to scroll down to fine the "Read more" button: https://deploy-preview-2311--objective-northcutt-37494c.netlify.app/blog/
* These shifted-to-the-left headlines on the case studies look a little out-of-place now: 
![Bildschirmfoto 2024-02-14 um 16 52 23](https://github.com/mainmatter/mainmatter.com/assets/1510/1e3175bb-b00a-4894-8546-3ee8a182fdc5) – should we just use regular sub-headlines to make it consistent with the rest of the site?
* Let's find a clearer style for links that appear in body text – it's not obvious at all that "playbook" is a link here: 
![Bildschirmfoto 2024-02-14 um 16 54 40](https://github.com/mainmatter/mainmatter.com/assets/1510/29711004-c611-4b09-9448-6536e49bce5f)
* The mobile menu is still the old one: 
![Bildschirmfoto 2024-02-14 um 16 56 40](https://github.com/mainmatter/mainmatter.com/assets/1510/cdc3569a-d5b5-4b4e-b4b1-97a79c8083ba)
* The Mainmatter logo seems slightly mis-aligned on mobile (way more space to the left than to the top): ![Bildschirmfoto 2024-02-14 um 16 57 20](https://github.com/mainmatter/mainmatter.com/assets/1510/8a6a886c-8357-430c-8a9d-df37d80d9788)
* in the mobile menu, the header of the section and the first entry, aren't vertically aligned: ![Bildschirmfoto 2024-02-14 um 16 59 11](https://github.com/mainmatter/mainmatter.com/assets/1510/5dd29a93-2c8c-4aa3-a76f-70d311e2312d)
* On the blog, let's use the same size for body text and code: 
![Bildschirmfoto 2024-02-14 um 17 00 27](https://github.com/mainmatter/mainmatter.com/assets/1510/1282111c-ea2b-48a9-b5d8-5b53cc60c215)

**Generally, let's not forget to merge all the new `-energy.*` files back into the original files before merging this PR.**

2024-02-14 16:11 UTC, marcoow commented on src/_data/services.json
> +  "embroider": [
Where is this used?

2024-02-14 16:11 UTC, marcoow commented on src/blog.njk
> +
👀

2024-02-14 16:11 UTC, marcoow commented
I haven't really reviewed content yet but those things I can also fix later myself

2024-02-15 14:38 UTC, yaigrie commented on src/_data/services.json
> +  "embroider": [
This is the first section on the embroider-initiative page (it uses the same layout as the featured services, so I thought why not use that)

<img width="1046" alt="image" src="https://github.com/mainmatter/mainmatter.com/assets/39055470/e2620e03-92e7-4026-95d2-8eec9a78c320">

2024-02-15 15:41 UTC, marcoow commented on src/_data/services.json
> +  "embroider": [
ah, I see – I'd use a separate file for this then though, otherwise it gets a bit confusing

2024-02-16 08:54 UTC, yaigrie commented
@marcoow Could you take a look again? :) Thank you!

2024-02-16 09:30 UTC, marcoow reviewed
The animation for the link arrows is missing on the start page (and I think for all link arrows), at least in Safari: 

https://github.com/mainmatter/mainmatter.com/assets/1510/ffab2184-9e29-46ef-865b-b0f36755d1e1

The animation of the arrows feels a bit janky for these boxes (at least in Safari) – it feels like the arrow moving to the right but also slightly upwards: ![Bildschirmfoto 2024-02-16 um 10 11 26](https://github.com/mainmatter/mainmatter.com/assets/1510/6441ac43-159a-422e-a5f6-838327a9f430)

Can we make the entire overlay sticky so it doesn't scroll at all (see current live site for comparison): 
![Bildschirmfoto 2024-02-16 um 10 15 28](https://github.com/mainmatter/mainmatter.com/assets/1510/597f1d7e-ee19-457a-983e-01b21b6b02d0)

The button is attached to the bottom which looks strange. Let's maybe not have the first video larger anyway and just use the same square view for all: 
![Bildschirmfoto 2024-02-16 um 10 16 45](https://github.com/mainmatter/mainmatter.com/assets/1510/6ed6e569-07c1-4f91-81c4-70dc820f4bd1)

This whole block reacts to hovering over which looks a bit strange – I think in this case we only want the link to turn purple: ![Bildschirmfoto 2024-02-16 um 10 18 25](https://github.com/mainmatter/mainmatter.com/assets/1510/f1eab60c-ebe8-4d31-b63e-ac9c9b7a3efe)

Let's properly align these vertically: 
![Bildschirmfoto 2024-02-16 um 10 20 25](https://github.com/mainmatter/mainmatter.com/assets/1510/ae654f75-38b3-4fae-a40f-4fd7d419b3b5)

In the mobile menu we need the sub-texts for the services as well: 
![Bildschirmfoto 2024-02-16 um 10 22 01](https://github.com/mainmatter/mainmatter.com/assets/1510/e8ec79dc-8375-46c4-a314-4ea6d25e0756)

I'd disable the hover effect for these on mobile – there's no hover there anyway and worst case this is triggered on click for a few ms: 
![Bildschirmfoto 2024-02-16 um 10 22 54](https://github.com/mainmatter/mainmatter.com/assets/1510/82026c40-a7f9-406f-b0f2-932ea468e1da)

2024-02-16 09:30 UTC, marcoow commented on netlify.toml
TODO for myself: we'll need to redirect the old service pages to the new ones as well, e.g.:

```toml
[[redirects]]
  from = "/services/team-augmentation-and-training/"
  to = "/services/strategic-advice/"
```

2024-02-16 09:30 UTC, marcoow commented on src/components/color-hero.njk
> +  "subheading": "lorem Ipsum",
debug leftover?

2024-02-16 15:09 UTC, marcoow commented
OI just recognized the vertical alignment of the previous/next blog post links isn't right:

![Bildschirmfoto 2024-02-16 um 16 06 17](https://github.com/mainmatter/mainmatter.com/assets/1510/fb3419e8-c3cc-42d4-8acd-f50a1d95b4af)

Also, another thing: let's change the quotes so that we can display company logos – for the wide ones like

![Bildschirmfoto 2024-02-16 um 16 08 13](https://github.com/mainmatter/mainmatter.com/assets/1510/779b4d4a-1e8d-4658-9d97-9f0872acd878)

as well as for the narrow variation like

![Bildschirmfoto 2024-02-16 um 16 08 56](https://github.com/mainmatter/mainmatter.com/assets/1510/d26adec7-9e8c-4f0c-808f-dab7719af243)

2024-02-17 11:22 UTC, marcoow commented
@yaigrie there's a bug on the tech modernization page where the overlay doesn't extend all the way to the top:

![Bildschirmfoto 2024-02-17 um 12 21 08](https://github.com/mainmatter/mainmatter.com/assets/1510/1986c88b-14e9-4c71-985b-dbec19a8562b)

Also, the overlay moves on scroll but I think we're removing that effect entirely and could remove the functionality anyway?

2024-02-17 13:46 UTC, marcoow reviewed
Let's add the service sub-titles  in the service list on the start page:

![Bildschirmfoto 2024-02-17 um 13 57 47](https://github.com/mainmatter/mainmatter.com/assets/1510/e08be592-7b96-4660-96a8-2867f3e67cab)

I think there's a bit too much space between the top menu and the titles of the page sometimes – in this case so much that part of the title is hidden. I think the space should depend on the size of the viewport as well:

![Bildschirmfoto 2024-02-17 um 14 02 12](https://github.com/mainmatter/mainmatter.com/assets/1510/7c1b7de4-44fe-48b9-8b39-bc47b6bd375c)

For workshops with a shorter title, the horizontal alignment of the title is off – this is shifted to the right and not aligned on the left with the rest of the content:

![Bildschirmfoto 2024-02-17 um 14 06 43](https://github.com/mainmatter/mainmatter.com/assets/1510/8053ec55-24b6-480b-8d58-0b92a02e8fe0)
![Bildschirmfoto 2024-02-17 um 14 06 47](https://github.com/mainmatter/mainmatter.com/assets/1510/525db17b-332b-4523-87e3-37c278712075)

Some of the overlays on images appear blue, not purple, e.g. this one (there are others as well, this is just one example):

![Bildschirmfoto 2024-02-17 um 14 09 31](https://github.com/mainmatter/mainmatter.com/assets/1510/a6df821a-403c-4ba9-907b-150dc8541991)

The fact that this text on the Playbook page is so narrow looks a bit strange?

![Bildschirmfoto 2024-02-17 um 14 15 14](https://github.com/mainmatter/mainmatter.com/assets/1510/a6c2846e-63a2-4b60-942f-f3ae64d731d8)

Let's remove the featured post from the blog page – it looks like you're on the page to read just that single post. Let's rather put a standard header there with a title and a paragraph of text, then list all posts below. If you prepare the header with placeholder text, I can put that in later.

![Bildschirmfoto 2024-02-17 um 14 20 54](https://github.com/mainmatter/mainmatter.com/assets/1510/91af45c5-ab94-49af-92e4-a9461e92357e)

I think these are a bit huge. Should we use a similar layout to the one we use for the video cards below?

![Bildschirmfoto 2024-02-17 um 14 25 42](https://github.com/mainmatter/mainmatter.com/assets/1510/b09242e1-4748-4d5a-a6b2-e9e210dbbadf)

This image right there looks bad I think and is a bit out of context in that place as well. I'd use it as a background for the header where it also makes sense as the title is "burth through the bottleneck".

![Bildschirmfoto 2024-02-17 um 14 27 40](https://github.com/mainmatter/mainmatter.com/assets/1510/c2a09a11-12b1-4a47-a17e-84bc102500c2)

Should the subtitles (e.g. "accelerate delivery…") be a bit smaller and less bold compared to the service names like they are in the services menu so they are easier identifiable as sub-titles?

![Bildschirmfoto 2024-02-17 um 14 32 21](https://github.com/mainmatter/mainmatter.com/assets/1510/fb65523c-78a6-4475-ace7-9c60794ff27c)

The layout of the author details on the mobile view of blog posts seems broken:

![Bildschirmfoto 2024-02-17 um 14 37 24](https://github.com/mainmatter/mainmatter.com/assets/1510/8dc17809-9c1e-4183-96de-9f1c3d3d0fdb)

same for workshop mentors:

![Bildschirmfoto 2024-02-17 um 14 38 59](https://github.com/mainmatter/mainmatter.com/assets/1510/7513318e-da69-445c-b530-22a03b8efff9)

The alignment of workshop titles for workshops with short names seems broken on mobile (this should be more to the left so it's horizontally aligned with the main content on the page):

![Bildschirmfoto 2024-02-17 um 14 39 30](https://github.com/mainmatter/mainmatter.com/assets/1510/9ee2f523-3163-4b49-9281-8cd6bc63c770)

2024-02-23 16:03 UTC, marcoow reviewed
On the Ruby expertise page, let's add an image between these 2 sections?

![Bildschirmfoto 2024-02-23 um 16 46 15](https://github.com/mainmatter/mainmatter.com/assets/1510/58532e19-0bc5-43c4-9b9c-69cc1637a32e)

Let's use a different photo – this is a bit scary:

![Bildschirmfoto 2024-02-23 um 16 55 04](https://github.com/mainmatter/mainmatter.com/assets/1510/5dd5b7bc-54e7-4f2a-ad8c-c4ccd1cdc891)

2024-02-23 16:03 UTC, marcoow commented on src/embroider-initiative.njk
> +{{ colorHero('purple', content) }}
This should have a background image

2024-03-01 14:13 UTC, yaigrie commented
@marcoow I put some new og images in sketch https://www.sketch.com/s/066e539c-c206-4261-aafb-9634ab577579/p/2DFAF93B-3DEA-489C-9FB5-5BD438E49FB4/canvas (on the right, in the pink border)

Do you like these?
And if so, what other og images do we need? Should I redo the blog post ones too, or the latest few?

2024-03-01 16:27 UTC, marcoow commented
I think those are good, yes – I'll leave some detailed comments in Sketch. Yes, let's redo the past 10 blog posts or so as well plus the 10 that get the most traffic (see Plausible)

2024-03-08 13:00 UTC, marcoow requested changes
Looks good overall but there's some issues left still:

* the arrow animation on links doesn't seem to work in most places (it does in some but in most places, the arrow movement isn't animated)
* the contact form overlay that we show when the form is submitted, shouldn't scroll - it should be positioned sticky
* We should disable the animation where the text scrolls out of the container and the other text scrolls in on mobile. Otherwise it is triggered on click on mobile and you see half of it before the browser navigates away – that looks like a bug.

![Bildschirmfoto 2024-03-08 um 13 51 19](https://github.com/mainmatter/mainmatter.com/assets/1510/89f99dc4-3598-4912-bcf3-685a5d92ec6c)

* We should position the "X" on the contact form overlay with some padding to the top and right so it's in the same position as the toggle to open the menu on mobile and the contact us button on desktop:

![deploy-preview-2311--objective-northcutt-37494c netlify app_contact_(iPhone XR)](https://github.com/mainmatter/mainmatter.com/assets/1510/a08f0fcf-fdb3-454b-a66f-5426e8bace82)

* on the `og:image`s for blog posts, let's say "Blog Post" instead of the tag in the top left
* On the Embroider initiative page, I guess the logos should be in white?

![Bildschirmfoto 2024-03-08 um 12 56 04](https://github.com/mainmatter/mainmatter.com/assets/1510/26234797-c30e-4e12-a08b-87971f57c1cc)

* The alignment of the previous/next links on the blog seems strange on mobile?

![Bildschirmfoto 2024-03-08 um 12 51 14](https://github.com/mainmatter/mainmatter.com/assets/1510/0c8afdeb-e8e9-4b0c-967e-13037b1ea78d)

* Also, the previous/next links on the blog page and the talks page are inverted, next goes to the previous page and previous goes to the next page…
* The alignment of the load more button on the talks page on mobile seems off (missing padding to the right)?

![Bildschirmfoto 2024-03-08 um 12 50 00](https://github.com/mainmatter/mainmatter.com/assets/1510/4387b385-6d27-4ecb-8f91-cd40b4f8dec7)

* The events we currently have scheduled look pretty bad. We should either find a different design or use different images:

![Bildschirmfoto 2024-03-08 um 12 47 01](https://github.com/mainmatter/mainmatter.com/assets/1510/e8157cbe-dd25-4116-a0bb-acea889ee304)

* Let's remove the featured video and make it look like the others:

![Bildschirmfoto 2024-03-08 um 12 48 13](https://github.com/mainmatter/mainmatter.com/assets/1510/b5418276-f64f-45e1-95bd-9520f64560ba)

* The header image on the talks page is missing an overlay color:

![Bildschirmfoto 2024-03-08 um 12 50 24](https://github.com/mainmatter/mainmatter.com/assets/1510/3995f11d-6fb5-48fe-809f-99bee27486bc)

* The header sections on mobile don't quite work yet. In some cases, we don't have enough vertical spacing, e.g.:

![deploy-preview-2311--objective-northcutt-37494c netlify app_services_team-reinforcement_(iPhone XR)](https://github.com/mainmatter/mainmatter.com/assets/1510/ad1a8189-3e72-45a3-8112-916b77db9e38)

  and in some cases we have too much spacing (I don't think we should use `min-height: 100vh` on mobile like we do on desktop):

![deploy-preview-2311--objective-northcutt-37494c netlify app_events_(iPhone XR)](https://github.com/mainmatter/mainmatter.com/assets/1510/dbd22b50-41db-487d-b973-10a498015469)

  Please go over all of them and compare to the currently live mainmatter.com – I think it works quite well there

2024-03-08 13:51 UTC, marcoow commented on src/components/color-hero.njk
> +  "subheading": "lorem Ipsum",
nvm, I see this is an example

2024-03-08 14:04 UTC, marcoow commented on src/components/content/embroider-sponsors.njk
> +</div>
Would it not be easier to just use 1 big image here?

2024-03-08 14:04 UTC, marcoow commented on src/components/recent-posts.njk
> +        <h2 class="">{{ title }}</h2>
```suggestion
        <h2>{{ title }}</h2>
```

2024-03-08 14:04 UTC, marcoow commented on src/components/svg/elixir.njk
> +<img src="/assets/images/services/elixir-tech_black.png">
Let's not hide a PNG in an `.njk` in an `svg` folder :)

2024-03-08 14:23 UTC, yaigrie commented on src/components/content/embroider-sponsors.njk
> +</div>
I think it depends on the purpose of the image? It feels wrong to me to put actual content in an image, so if we want to inform visitors about the actual sponsors, then I guess a list would be better, but if we just want to tell the user, look, we already have many sponsors, then a decorative image should be fine. 
But I'm currently stuck on how to make these images white?! ;( 
So I'm inclined to just use an image, yes :D

2024-03-08 14:34 UTC, yaigrie commented on src/components/svg/elixir.njk
> +<img src="/assets/images/services/elixir-tech_black.png">
Do you have any idea where I could get these two logos (elixir and phoenix) as .svg?

2024-03-08 14:34 UTC, marcoow commented on src/components/content/embroider-sponsors.njk
> +</div>
What you say makes sense actually. I don't have strong feelings here – although making the SVGs white should be straight forward? If we need them in black as well elsewhere, we can just have 2 copies?

2024-03-08 14:36 UTC, marcoow commented on src/components/svg/elixir.njk
> +<img src="/assets/images/services/elixir-tech_black.png">
Hm, no and I think PNG is fine – I'd just move this out of the SVG folder then. Also, everywhere where we use images, we should use the `image` helper that will put a proper `<picture>` element with different sizes, it will preprocess the images, etc.

2024-03-08 14:38 UTC, yaigrie commented on src/components/svg/elixir.njk
> +<img src="/assets/images/services/elixir-tech_black.png">
I think we'd need a svg for this one, as the color has to adapt to the different background colors - I will try to just create it myself. I guess that's what I originally planned for this one

2024-03-08 14:40 UTC, yaigrie commented on src/components/content/embroider-sponsors.njk
> +</div>
Yeah I'm very confused, because when I open these svgs on my machine they are white, they aren't even needed in black elsewhere. I will need to figure out why they still get displayed as black images....

2024-03-08 14:44 UTC, marcoow commented on src/components/content/embroider-sponsors.njk
> +</div>
Hm, might be caching – I'll rebuild on Netlify with cleared caches

2024-03-15 11:47 UTC, nickschot commented
<img width="825" alt="Screenshot 2024-03-15 at 12 46 27" src="https://github.com/mainmatter/mainmatter.com/assets/334789/f6506a7e-c576-4ea5-beed-3ffa95047fbb">

Seems there's some (font) coloring issues on the blog here with purple on purple.

https://deploy-preview-2311--objective-northcutt-37494c.netlify.app/blog/2023/11/16/embroider-initiative-progress-update/

2024-03-15 12:50 UTC, beerinho commented
Ideally the message after submitting the contact form should be inline to help with accessibility, failing that I think it should be a modal instead of just an overlay that is scrollable (it is also stops at the footer, see screenshot). If we don't want a modal either, then I think there needs to be a bit more scroll padding as it feels a bit squashed to the top at the moment
<img width="1713" alt="image" src="https://github.com/mainmatter/mainmatter.com/assets/38084194/8e091bd7-5852-4ede-b732-8432a32ee952">

"Team Augmentation" vs "Team Reinforcement" - there are some places that still mention "Team Augmentation", did we want to update that to be the same everywhere?

In some areas (`/work`) the arrow doesn't move at all on hover
<img width="786" alt="image" src="https://github.com/mainmatter/mainmatter.com/assets/38084194/1399c265-e1ed-4909-bb2a-1e8cbf8e2e20">

I personally don't like the images on the homepage, I think they are too loud and I don't feel like the fit the brand. But that's just my opinion so feel free to ignore it :)

2024-03-15 13:00 UTC, marcoow commented
> "Team Augmentation" vs "Team Reinforcement" - there are some places that still mention "Team Augmentation", did we want to update that to be the same everywhere?

fixed

2024-03-15 13:20 UTC, emmasofiah2o commented
- Random "r" on the left side in open-source posts.
<img width="1440" alt="Screenshot 2024-03-15 at 14 10 14" src="https://github.com/mainmatter/mainmatter.com/assets/83696750/ce5dff00-2c94-403a-aa06-728049c02847">
- Not a bug, but I think "Listen to our customers" is not very effective. I'd probably use something like "Our customers say about us" or similar
<img width="740" alt="Screenshot 2024-03-15 at 14 12 57" src="https://github.com/mainmatter/mainmatter.com/assets/83696750/818ece44-4910-43dc-a182-9f9ac926ea86">
- I'd also change the arrows here for bullet points. I thought it was a button because we use this format in the services menu tab as well (/playbook).
<img width="959" alt="Screenshot 2024-03-15 at 14 15 40" src="https://github.com/mainmatter/mainmatter.com/assets/83696750/324db23d-82b2-4077-b812-26435e2c901b">
- This section is aligned left with less margin than the rest of the website's content. Idk if it's a mistake or not (/svelte-consulting)
<img width="724" alt="Screenshot 2024-03-15 at 14 18 45" src="https://github.com/mainmatter/mainmatter.com/assets/83696750/ddbaa4e4-ac92-4624-aec5-8c5266219402">

Tested on Desktop + Chrome

2024-03-15 14:21 UTC, KevinBongart commented
- Inconsistent capitalization in the services (Team **R**einforcement stands out compared to the other headers)
- "user-focus**s**ed" in the Exporter work example, I think it's sometimes accepted in British English but quite rare compared to the more common spelling "focused"
- the background of the homepage header ("Your expert guides for the journey ahead") is blue, which was a bit jarring when the purple background image eventually loaded (while on the train's slow wifi). A purple background color would probably be a smoother transition (admittedly low priority)
- In https://deploy-preview-2311--objective-northcutt-37494c.netlify.app/services/tech-modernization/, Sage and mobi.MED have a logo in the top-right corner but Camilyo doesn't:

<img width="1414" alt="Screenshot 2024-03-15 at 3 16 24 PM" src="https://github.com/mainmatter/mainmatter.com/assets/154600/6030b4e6-e225-4f0a-9acf-8debdfe096c7">

- In https://deploy-preview-2311--objective-northcutt-37494c.netlify.app/services/launch-your-idea/, "Handover the project to your internal team" could benefit from a reassuring bit about how we'd help grow the team capacity and skills adequately before just handing off the project.

2024-03-15 15:43 UTC, BlueCutOfficial commented
I guess that's new but there's an issue with the arrows on the current preview:

<img width="541" alt="Capture d’écran 2024-03-15 à 16 25 09" src="https://github.com/mainmatter/mainmatter.com/assets/22059380/c4aeaea3-0a17-4bd5-939c-24df8e5e55cd">

Aside from that, the website is nice and I didn't notice anything significant, I have 2 comments:

When navigating with the keyboard from colored panel to color panel, I am a bit confused by the absence of a visual mark or effect when the panel itself is focused (and not the link inside):
<img width="1357" alt="Capture d’écran 2024-03-15 à 16 30 31" src="https://github.com/mainmatter/mainmatter.com/assets/22059380/2d41afc2-5096-4582-ae70-160efcc2dfc1">

I have my doubts about a few of the images that illustrate the pages (but that’s of course personal opinion):
- The puppets on the team reinforcement page are a bit scary.
- The woman hidden behind the balloon on the home page and the parrots on the workshop page are living beings that contrast a bit with the other illustrations of the same type (colored toys and objects), and the latter feels a bit like we compare attendees to parrots.
- On the second balloon image on the main page I see more sad faces than happy faces so it feels a bit negative to me.

2024-04-12 13:54 UTC, yaigrie commented
@marcoow I need your support here :) The lint check wants me to put the stuff from the blog.njk header into the same column, but if I do that the blog breaks somehow and doesn't display any posts - can you help me fix that?

2024-04-12 14:05 UTC, marcoow commented
@yaigrie fixed it

2024-04-12 16:22 UTC, marcoow reviewed
Nice 🙌  I'm afraid there are some issues left though 😬 

* the header image on the work page has a black overlay on mouse over: https://deploy-preview-2311--objective-northcutt-37494c.netlify.app/work/ (in fact that seems to be triggered by hovering over any of the colored boxes further below; it's the same on the Rust landing page)
* Can we keep the large, 2 column wide teasers for the featured case studies on the work page (I mean the element we're using e.g. for the Qonto case here: https://deploy-preview-2311--objective-northcutt-37494c.netlify.app/services/team-reinforcement/)
* the photos of Chris, Nick, any myself on this page aren't styled: https://deploy-preview-2311--objective-northcutt-37494c.netlify.app/ember-consulting/
* also the YouTube logo on the above page seems too large? Same for Luca's image here: https://deploy-preview-2311--objective-northcutt-37494c.netlify.app/rust-consulting/
![Bildschirmfoto 2024-04-12 um 17 55 27](https://github.com/mainmatter/mainmatter.com/assets/1510/6389444f-1919-40e4-9bb6-84b62fdd0de1)

 * On the events page https://deploy-preview-2311--objective-northcutt-37494c.netlify.app/events/, can we find a way to include the event logos in the boxes for the upcoming events? Maybe we can reuse the approach we have for the technology teaser boxes where the logo is in the background
 * We seem to be mixing bold black and bold purple links, e.g. on this page https://deploy-preview-2311--objective-northcutt-37494c.netlify.app/cases/aleph-alpha/ (StackIt, lapin, sqlx) – I'm not sure what the different colors mean but maybe all links should be purple (or all should be black – I guess purple looks much more like a link though while bold black just looks bold)?
* > Let's use a different photo – this is a bit scary:
  Let's still change that image with the glass skull on the "Modernize your Tech stack" page

2024-04-19 13:44 UTC, marcoow approved these changes
let's get this out 🙌

2024-04-19 13:44 UTC, merged