Introducing Svelte Promise Modals blog post
mainmatter/mainmatter.com pull request #2352
Opened 2024-03-28 10:25 UTC by zeppelin

2024-04-02 10:21 UTC, emmasofiah2o requested changes
Just a few corrections :)

2024-04-02 10:21 UTC, emmasofiah2o commented on src/posts/2024-03-22-introducing-svelte-promise-modals.md
> +> TL;DR: Mainmatter released a library to implement modals in a few lines of
This could be used for the tagline :)

2024-04-02 10:21 UTC, emmasofiah2o commented on src/posts/2024-03-22-introducing-svelte-promise-modals.md
> +we tend to forget sometimes how hard life were when all we had were callbacks.
```suggestion
we tend to forget sometimes how hard life was when all we had were callbacks.
```

2024-04-02 10:21 UTC, emmasofiah2o commented on src/posts/2024-03-22-introducing-svelte-promise-modals.md
> +![Comparison of asyncness of sending a request and opening a modal dialog](/assets/images/posts/2024-03-22-introducing-svelte-promise-modals/async-comparison.png)
```suggestion
![Comparison of asynchronism of sending a request and opening a modal dialog](/assets/images/posts/2024-03-22-introducing-svelte-promise-modals/async-comparison.png)
```

2024-04-02 10:21 UTC, emmasofiah2o commented on src/posts/2024-03-22-introducing-svelte-promise-modals.md
> +Despite all similarities in async-ness, their implementation differ greatly. Why
```suggestion
Despite all the similarities in asynchronism, their implementation differs greatly. Why
```

2024-04-02 10:21 UTC, emmasofiah2o commented on src/posts/2024-03-22-introducing-svelte-promise-modals.md
> +users: what is one of the most common usability or accessibility issue with
```suggestion
users: what is one of the most common usability and accessibility issues with
```

2024-04-02 10:21 UTC, emmasofiah2o commented on src/posts/2024-03-22-introducing-svelte-promise-modals.md
> +modal dialogs? I think the answer is without doubt the lack of well-constrained
```suggestion
modal dialogs? The answer is, without a doubt, the lack of well-constrained
```

2024-04-02 10:21 UTC, emmasofiah2o commented on src/posts/2024-03-22-introducing-svelte-promise-modals.md
> +the next focusable element is likely will be in the document, _underneath the
```suggestion
the next focusable element will likely be in the document, _underneath the
```

2024-04-02 10:21 UTC, emmasofiah2o commented on src/posts/2024-03-22-introducing-svelte-promise-modals.md
> +really shouldn't be in that moment. Luckily, this fundamental use-case is
```suggestion
really shouldn't be in that moment. 
Luckily, this fundamental use-case is
```

2024-04-02 10:21 UTC, emmasofiah2o commented on src/posts/2024-03-22-introducing-svelte-promise-modals.md
> +input is, well, _trapped_ by using the excellent library called `focus-trap`, to
```suggestion
input is _"trapped"_ by using the excellent library called `focus-trap`, which
```

2024-04-02 10:21 UTC, emmasofiah2o commented on src/posts/2024-03-22-introducing-svelte-promise-modals.md
> +ensure navigation between form elements won't accidentally leave our users
```suggestion
ensures navigation between form elements won't accidentally leave our users
```

2024-04-02 10:21 UTC, emmasofiah2o commented on src/posts/2024-03-22-introducing-svelte-promise-modals.md
> +With both the developer and the user end of dealing with modal dialogs are
```suggestion
With both the developer and the user end of working with modal dialogs being
```

2024-04-02 10:21 UTC, emmasofiah2o commented on src/posts/2024-03-22-introducing-svelte-promise-modals.md
> +are tons of stuff that's not covered in this blog post, so be sure to check out
```suggestion
are several topic that are not covered in this blog post, so be sure to check out
```

2024-04-02 10:21 UTC, emmasofiah2o commented on src/posts/2024-03-22-introducing-svelte-promise-modals.md
> +modern, usable and accessible, we think you'll love Svelte Promise Modals. There
```suggestion
modern, usable and accessible, we think you'll love Svelte Promise Modals. 
There
```

2024-04-02 12:33 UTC, emmasofiah2o commented
@yaigrie could you please check if the bg picture I used for the header and og-image is fine? I am also not sure if the size is big enough for the header visual, I could only download it as a jpeg (source: https://unsplash.com/de/fotos/menschliche-hand-formt-herzform-VPVfg1_wyNg)

2024-04-02 13:00 UTC, yaigrie commented
@emmasofiah2o I think the sizes are fine, for the visual the original only already had that weird blur which made it look a bit pixelated? I uploaded a different one, maybe that works better?

2024-04-02 14:30 UTC, emmasofiah2o commented
> @emmasofiah2o I think the sizes are fine, for the visual the original only already had that weird blur which made it look a bit pixelated? I uploaded a different one, maybe that works better?

I still see the old visual. I'll try changing the file name, sometimes that's the issue - or do you see the new one in the preview already?

2024-04-08 11:32 UTC, emmasofiah2o commented on src/posts/2024-04-08-introducing-svelte-promise-modals.md
> +  following the async patterns that are already in your Svelte app"
```suggestion
  following the async patterns that are already in your Svelte app."
```

2024-04-08 11:33 UTC, emmasofiah2o commented on src/posts/2024-04-08-introducing-svelte-promise-modals.md
> +  "Mainmatter released a library to implement modals in a few lines of code,
```suggestion
  "Gabor Babicz presents Mainmatter's svelte-promise-modals, a library to implement modals in a few lines of code,
```

2024-04-08 11:38 UTC, emmasofiah2o commented on src/posts/2024-04-08-introducing-svelte-promise-modals.md
> +# Introducing Svelte Promise Modals
Are you sure you want to repeat the title here? Maybe make it a h2? It feels a bit off since it's already at the top of the page

2024-04-08 11:45 UTC, zeppelin commented on src/posts/2024-04-08-introducing-svelte-promise-modals.md
> +# Introducing Svelte Promise Modals
No, that's a leftover making a comeback, removing. Thanks!

2024-04-08 14:40 UTC, emmasofiah2o approved these changes

2024-04-08 14:47 UTC, merged