Add Paolo's talk from Svelte Summit Spring 2024
mainmatter/mainmatter.com pull request #2382
Opened 2024-04-30 11:36 UTC by emmasofiah2o

- Add appearence
- Add link with timestamp
- Add visual

2024-04-30 11:56 UTC, marcoow commented on src/appearances/2024-04-27-fullstack-testing.md
> +title: "Fullstack Testing"
```suggestion
title: "Fullstack Testing SvelteKit apps"
```

2024-04-30 15:29 UTC, marcoow approved these changes

2024-04-30 15:31 UTC, marcoow requested changes

2024-04-30 15:31 UTC, marcoow commented on src/appearances/2024-04-27-fullstack-testing.md
> +url: https://www.youtube.com/live/gkJ09joGBZ4?si=7-Bw68oUe8qKens0
```suggestion
url: https://youtube.com/watch?v=gkJ09joGBZ4&t=6840
```

Since this is the entire stream, let's please link to the correct time index

2024-04-30 16:44 UTC, emmasofiah2o commented on src/appearances/2024-04-27-fullstack-testing.md
> +url: https://www.youtube.com/live/gkJ09joGBZ4?si=7-Bw68oUe8qKens0
I wanted to link to before the presenter's introduction, but I copied the wrong link. I think the correct timestamp is 6705. So https://www.youtube.com/live/gkJ09joGBZ4&t=6705

2024-05-02 06:27 UTC, marcoow commented on src/appearances/2024-04-27-fullstack-testing.md
> +url: https://www.youtube.com/live/gkJ09joGBZ4?si=7-Bw68oUe8qKens0
It would have to be https://youtube.com/watch?v=gkJ09joGBZ4&t=6705 then though – your link above doesn't work

2024-05-02 06:28 UTC, marcoow commented on src/appearances/2024-04-27-fullstack-testing.md
> +url: https://www.youtube.com/live/gkJ09joGBZ4?si=7-Bw68oUe8qKens0
https://youtube.com/watch?v=gkJ09joGBZ4&t=6752

is the correct link

2024-05-02 11:08 UTC, marcoow approved these changes

2024-05-02 11:40 UTC, merged