Blog post: may 2024 embroider update
mainmatter/mainmatter.com pull request #2419
Opened 2024-05-22 16:21 UTC by BlueCutOfficial

2024-05-22 16:26 UTC, BlueCutOfficial commented on src/posts/2024-05-24-embroider-update.md
> +default experience for all Ember users.
Do we want to tease Chris' talk at EmberConf next week?

2024-05-23 11:03 UTC, BlueCutOfficial commented on src/posts/2024-05-24-embroider-update.md
> +    This post covers the progress over the last six months on [the Embroider project](https://github.com/embroider-build/embroider) that has been made through Mainmatter's [Embroider Initiative](http
Change links to HTML

2024-05-23 12:23 UTC, emmasofiah2o requested changes

2024-05-23 12:23 UTC, emmasofiah2o commented on src/posts/2024-05-24-embroider-update.md
> +[November 2023 blog post](https://mainmatter.com/blog/2023/11/16/embroider-initiative-progress-update/),
```suggestion
[blog post from November 2023](https://mainmatter.com/blog/2023/11/16/embroider-initiative-progress-update/),
```

2024-05-23 12:23 UTC, emmasofiah2o commented on src/posts/2024-05-24-embroider-update.md
> +If this is the first time you have heard about Embroider, we encourage you to
```suggestion
If this is the first time you hear about Embroider, we encourage you to
```

2024-05-23 12:23 UTC, emmasofiah2o commented on src/posts/2024-05-24-embroider-update.md
> +The main goal that we laid out in the last blog was to get our Ember apps
```suggestion
The main goal that was set in the last blog was to get our Ember apps
```

2024-05-23 12:23 UTC, emmasofiah2o commented on src/posts/2024-05-24-embroider-update.md
> +building with Vite, not only have we achieved that landmark we have moved onto
```suggestion
building with Vite. Not only have we achieved that landmark, but we have moved onto
```

2024-05-23 12:23 UTC, emmasofiah2o commented on src/posts/2024-05-24-embroider-update.md
> +the next phase which all about brining the wonderful DX improvments that Vite
```suggestion
the next phase, which brings the wonderful DX improvements that Vite
```

2024-05-23 12:23 UTC, emmasofiah2o commented on src/posts/2024-05-24-embroider-update.md
> +Now that our challenge is no longer to get Ember working with Vite we need to
```suggestion
Now that our challenge is no longer to get Ember working with Vite, we need to
```

2024-05-23 12:23 UTC, emmasofiah2o commented on src/posts/2024-05-24-embroider-update.md
> +classic features. To understand how to optimize, we need to dive into the
```suggestion
classic features. To find a solution, we need to dive into the
```

2024-05-23 12:23 UTC, emmasofiah2o commented on src/posts/2024-05-24-embroider-update.md
> +challenge that an Ember build presents to us
```suggestion
challenge that an Ember build presents.
```

2024-05-23 12:23 UTC, emmasofiah2o commented on src/posts/2024-05-24-embroider-update.md
> +if you generated an Ember app using the default blueprint, and you will get a
```suggestion
if you generated an Ember app using the default blueprint, you will get a
```

2024-05-23 12:23 UTC, emmasofiah2o commented on src/posts/2024-05-24-embroider-update.md
> +are automatically provided by the Ember addons you use, but that files doesn’t
```suggestion
are automatically provided by the Ember addons you use. However, those files don’t
```

2024-05-23 12:23 UTC, emmasofiah2o commented on src/posts/2024-05-24-embroider-update.md
> +exist in your repo. Your `app/index.html` points to a file that is literally
```suggestion
exist in your repo: your `app/index.html` points to a file that is literally
```

2024-05-23 12:23 UTC, emmasofiah2o commented on src/posts/2024-05-24-embroider-update.md
> +nowhere in your app files. At build time Ember will go through all the active
```suggestion
nowhere in your app files. At build time, Ember will go through all the active
```

2024-05-23 12:23 UTC, emmasofiah2o commented on src/posts/2024-05-24-embroider-update.md
> +point in the build pipeline. But this is an Ember-specific behavior that Vite
```suggestion
point in the build pipeline. This is an Ember-specific behavior that Vite
```

2024-05-23 12:23 UTC, emmasofiah2o commented on src/posts/2024-05-24-embroider-update.md
> +different from the initial Ember app, in a way it can be consumed by Vite. For
```suggestion
different from the initial Ember app in that it can be consumed by Vite. For
```

2024-05-23 12:23 UTC, emmasofiah2o commented on src/posts/2024-05-24-embroider-update.md
> +with Vite, but it has performance (and other) downsides: Vite prebuilds the app
```suggestion
with Vite, but also carries performance (and other) downsides: Vite prebuilds the app
```

2024-05-23 12:23 UTC, emmasofiah2o commented on src/posts/2024-05-24-embroider-update.md
> +the Ember app that need to be reflected in the rewritten app imply changes in a
```suggestion
the Ember app that need to be reflected in the rewritten app, imply changes in a
```

2024-05-23 12:23 UTC, emmasofiah2o commented on src/posts/2024-05-24-embroider-update.md
> +unable to resolve Ember-specific things, it asks Embroider to return the
```suggestion
unable to resolve Ember-specific issues, it asks Embroider to return the
```

2024-05-23 12:23 UTC, emmasofiah2o commented on src/posts/2024-05-24-embroider-update.md
> +that starts with `@embroider`. For instance: `@embroider/core/vendor.css`. Then
```suggestion
that starts with `@embroider`. For instance: `@embroider/core/vendor.css`. Then,
```

2024-05-23 12:23 UTC, emmasofiah2o commented on src/posts/2024-05-24-embroider-update.md
> +functionalities like content-for to work with Vite. A wide part of this work is
```suggestion
functionalities like content-for to work with Vite. A wide part of this work has
```

2024-05-23 12:23 UTC, emmasofiah2o commented on src/posts/2024-05-24-embroider-update.md
> +done already: all the app entrypoints are virtualized, the new authoring format
```suggestion
already been done: all the app entry points are virtualized, the new authoring format
```

2024-05-23 12:23 UTC, emmasofiah2o commented on src/posts/2024-05-24-embroider-update.md
> +assert each functionality behaves as expected in build mode and dev mode: the
```suggestion
assert that each functionality behaves as expected in build mode and dev mode: the
```

2024-05-23 12:23 UTC, emmasofiah2o commented on src/posts/2024-05-24-embroider-update.md
> +you want to verify made it into the build.
I don't get this last sentence, what were you trying to say? "you don’t know how Rollup is going to
organize the files, so you don’t know where to look for a specific piece of code
you want to verify **made it into the build**."

2024-05-23 12:23 UTC, emmasofiah2o commented on src/posts/2024-05-24-embroider-update.md
> +authorHandle: academierenards
Judging by the concluding lines of the second-last paragraph, might we want to include more than one author in this post? Or was it just you, @BlueCutOfficial?

2024-05-23 13:14 UTC, KevinBongart commented on src/posts/2024-05-24-embroider-update.md
> +the contents of the build, e.g. you don’t know how Rollup is going to
```suggestion
production. Using this new audit system also allows us to more easily investigate
the content of the build, e.g. you don’t know how Rollup is going to
```

2024-05-23 13:19 UTC, KevinBongart commented on src/posts/2024-05-24-embroider-update.md
> +you want to verify made it into the build.
While I proposed a fix for two typos above, I also don't get that sentence. Is the situation where Rollup organize the files randomly the current situation, and improving the audit system fixes that by organizing the content of the build in a way that can be investigated? If so, it should be phrased explicitly, for instance:

"Before this improvement, Rollup would organize the files seemingly at random, which made it difficult to investigate the content of the build. With this new audit system, files are exactly where you'd expect them, so you can do x and y."

2024-05-23 13:19 UTC, KevinBongart commented on src/posts/2024-05-24-embroider-update.md
> +default experience for all Ember users.
YES

2024-05-23 13:20 UTC, KevinBongart commented on src/posts/2024-05-24-embroider-update.md
> +default experience for all Ember users.
We can update the blog post later with a link to Chris' talk, too

2024-05-23 13:22 UTC, KevinBongart commented on src/posts/2024-05-24-embroider-update.md
> +## Last words
```suggestion
## Next steps
```

Maybe less ominous? :D

2024-05-23 13:22 UTC, KevinBongart commented on src/posts/2024-05-24-embroider-update.md
> +default experience for all Ember users.
This section could use one more link to https://mainmatter.com/embroider-initiative/

2024-05-23 13:24 UTC, BlueCutOfficial commented on src/posts/2024-05-24-embroider-update.md
> +authorHandle: academierenards
Yes, we could include Chris to make it less weird, his version of the second-last paragraph is more enthusiastic than what I wrote initially XD 
If it's technically possible to have several authors, let's do that 👍

2024-05-23 13:35 UTC, BlueCutOfficial commented on src/posts/2024-05-24-embroider-update.md
> +you want to verify made it into the build.
In that context "the build" is the output ready-for-production folder that our pipeline _builds_ out of the source code. So it means "you want to verify a specific piece of code that is present in your source code was indeed written somewhere in the build by the pipeline (but you can't know the name of the file it was written in)". Literally, imagine a piece of code moving from one place to made it to somewhere else ^^ 

Note that Chris phrased the sentence this way, it was part of his suggestion, and as a developer, I didn't have any trouble with it, but if you think it can be a problem maybe we can try to change it a little bit.

2024-05-23 15:22 UTC, BlueCutOfficial commented on src/posts/2024-05-24-embroider-update.md
> +are automatically provided by the Ember addons you use, but that files doesn’t
```suggestion
are automatically provided by the Ember addons you use. However, this file doesn’t
```

2024-05-23 15:26 UTC, BlueCutOfficial commented on src/posts/2024-05-24-embroider-update.md
> +unable to resolve Ember-specific things, it asks Embroider to return the
```suggestion
unable to resolve Ember-specific requests, it asks Embroider to return the
```

2024-05-23 15:29 UTC, BlueCutOfficial commented on src/posts/2024-05-24-embroider-update.md
> +the Ember app that need to be reflected in the rewritten app imply changes in a
I am not sure about this one 🤔 
If you delete the part that qualified the changes (), it would just be: 
"changes in the Ember app (...) imply changes in the rewritten app"

2024-05-23 15:32 UTC, BlueCutOfficial commented on src/posts/2024-05-24-embroider-update.md
> +## Last words
But I've already used that expression in "Progress and next steps", my writer's brain doesn't like repetition 🤔 Let me think about it, I'll find something :)

2024-05-23 16:55 UTC, BlueCutOfficial commented on src/posts/2024-05-24-embroider-update.md
> +authorHandle: academierenards
So with the current code, it's not possible to co-author a blog post, it's only possible to have several mentors for a workshop, but it doesn't rely on the same page template (I don't think it would be hard to implement, so we could suggest that change for a later time).

Do you think I should write the paragraph as a quote? 👇  

<img width="512" alt="Capture d’écran 2024-05-23 à 18 53 27" src="https://github.com/mainmatter/mainmatter.com/assets/22059380/937ea860-130d-4838-84c8-424316bcef87">

2024-05-23 17:19 UTC, BlueCutOfficial commented on src/posts/2024-05-24-embroider-update.md
> +default experience for all Ember users.
I added one last paragraph, what do you think?

2024-05-23 17:33 UTC, BlueCutOfficial commented on src/posts/2024-05-24-embroider-update.md
> +you want to verify made it into the build.
@emmasofiah2o, @KevinBongart, I tried a different phrasing. Is it better?

2024-05-24 08:35 UTC, emmasofiah2o commented on src/posts/2024-05-24-embroider-update.md
> +authorHandle: academierenards
I think a quote would look better, yes!

2024-05-24 09:07 UTC, emmasofiah2o approved these changes

2024-05-24 09:11 UTC, emmasofiah2o commented on src/posts/2024-05-24-embroider-update.md
> +you want to verify made it into the build.
My issue is with this part of the sentence, where 4 different verbs are used. I can't tell what the subjects are and it sounds very confusing. Maybe you can try typing it in French? I am not sure how to fix it either because I don't really understand the context. 

"so you **don’t know** where to look for a specific piece of code
you **want** to **verify** **made it** into the build."

2024-05-24 09:11 UTC, emmasofiah2o commented on src/posts/2024-05-24-embroider-update.md
> +you want to verify made it into the build.
I think just adding a "when" might fix it. Like so you don’t know where to look for a specific piece of code
when you want to verify that it made it into the build."

2024-05-24 09:25 UTC, BlueCutOfficial commented
Task list:
- @KevinBongart will get in touch with Marco to clarify the unannounced sponsor issue for the header visual, we are not confident to publish otherwise.
- @emmasofiah2o will check the blog post presentation (I added the images).
- @KevinBongart & @emmasofiah2o will check **the very last paragraph** that I added to answer the suggestions.

I am away on Monday, so if any action has to be done on Monday, please feel free to modify this PR as you like and merge it, you don't need me ;)

2024-05-24 09:32 UTC, emmasofiah2o commented on src/posts/2024-05-24-embroider-update.md
> +on May 31th.
```suggestion
on May 31st.
```

2024-05-24 09:36 UTC, emmasofiah2o commented on src/posts/2024-05-24-embroider-update.md
> +files, so you don’t know what file to look in to assert the code is present: the
```suggestion
files, so you don’t know what file to look into to verify that the code is present: the
```

2024-05-24 09:36 UTC, emmasofiah2o commented on src/posts/2024-05-24-embroider-update.md
> +audit system is designed to figure this out for you, so you can focus your test
```suggestion
audit system is designed to figure this out for you, so you can focus on your test's
```
```suggestion
audit system is designed to figure this out for you, so you can focus your test
```

2024-05-28 12:11 UTC, KevinBongart commented on static/assets/images/posts/2024-05-24-embroider-update/header.jpg
@emmasofiah2o Would you be able to replace this image with the new one with the Auditboard and Emergent Tree logos?

2024-05-28 14:16 UTC, emmasofiah2o commented on static/assets/images/posts/2024-05-24-embroider-update/header.jpg
✅

2024-05-29 08:56 UTC, emmasofiah2o commented
Can I merge @BlueCutOfficial ?

2024-05-29 09:50 UTC, merged