Js dependencies
mainmatter/mainmatter.com pull request #246
Opened 2018-11-22 13:13 UTC by wadie

Reopened a new PR to merge when your changes over at #241 are done. 👍

2018-11-22 13:27 UTC, marcoow requested changes
Is any of the gulp code going to run during the normal Jekyll build?

2018-11-22 13:27 UTC, marcoow commented on _includes/head.html
> +    <link href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/styles/default.min.css" rel="stylesheet" type="text/css">
Can we load this *only* for the blog layout? It's not needed on any other page.

2018-11-22 13:27 UTC, marcoow commented on _includes/head.html
> +    <link href="/js/main.js">
This should be

```html
<script src="/js/main.js"></script>
```

2018-11-23 09:38 UTC, ghislaineguerin commented
@wadie I've changed the base to redesign as we no longer have the CSS-refactor branch

2018-11-23 15:30 UTC, marcoow commented
this should not be needed anymore after #248

2018-11-23 15:30 UTC, closed without merging