Add Luca's Panel from Rust for the Web Barcelona
mainmatter/mainmatter.com pull request #2472
Opened 2024-06-26 11:51 UTC by IdeliaRisella

- Add the talk to appearances
- Add the rustweb barcelona channel

To do: add thumbnail

2024-07-01 06:39 UTC, marcoow requested changes

2024-07-01 06:39 UTC, marcoow commented on src/channels/rustweb-barcelona.md
> +“Rust for the web” is an event organized by the Mainmatter team in collaboration
```suggestion
“Rust for the web” Barcelona was an event organized by the Mainmatter team in collaboration
```

this was a one-off event

2024-09-11 12:35 UTC, IdeliaRisella commented
@marcoow I tried changing the thumbnail on this PR, as well as another one, and it seems like it's not quiet right as the checks were not successful. I tried doing what Emma explained to me before. I am not sure where exactly I missed. Would you please help and explain to me what I need to pay attention to so I can work on the rest of the thumbnail, or maybe I should go to Xenia to help me learn more?

2024-09-11 14:43 UTC, marcoow commented
There was a lint error (I fixed) and the branch was branched off of an old ref which lead to the visual changes reported by Percy. Bart or Gabor should have some time maybe to explain in more detail.

The Netlify error was random and unrelated to your changes…

2024-09-11 14:50 UTC, marcoow approved these changes

2024-09-11 14:51 UTC, marcoow commented
let's make sure we get these things on the website a bit quicker after the events have occurred in the future :pray:

2024-09-11 14:51 UTC, merged

2024-09-12 06:44 UTC, IdeliaRisella commented
Hi Marco,

I just want to let you know that there is another open PR made by Emma that
hasn't been merged yet. I think the same problem happened like this one.
The PR was undone because the new thumbnail was not available in July, and
I seemed to have lost track of this task. But I'm planning to get this done
this week, as well as changing all the thumbnails. I'll contact Bart or
Gabor for further explanation, thank you again.

Best regards,
Idelia Risella

On Wed, Sep 11, 2024 at 4:51 PM Marco Otte-Witte ***@***.***>
wrote:

> let's make sure we get these things on the website a bit quicker after the
> events have occurred in the future 🙏
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/mainmatter/mainmatter.com/pull/2472#issuecomment-2343902732>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BJI5TZ7GSZVO37EU5MFJJNLZWBKHRAVCNFSM6AAAAABJ5XFMMOVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDGNBTHEYDENZTGI>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>