introduce the Ember initiative
mainmatter/mainmatter.com pull request #2485
Opened 2024-07-08 10:10 UTC by marcoow

This

* changes the Embroider initiative landing page to the Ember initiative landing page
* adds a blog post introducing the Ember initiative

## TODO

- [x] add `og:image` for Ember Initiative page (I created this in Sketch but can't figure out how to get the hamster photo to work with the purple overlay)

2024-07-08 12:38 UTC, mansona requested changes
Mostly this is good, there is nothing in here that I wouldn't be happy merging now so all of my suggestions are just to make it a bit better.

I do need an answer on the guinea ping "hamsters" thing before I remove my request changes tho 😂 happy for it to be a joke but I want to make sure that we know this

2024-07-08 12:38 UTC, mansona commented on src/ember-initiative.njk
> +  advance the Ember ecosystem and secury its members' investments in Ember.js. We build on top of the success of the Embroider initiative.",
```suggestion
  advance the Ember ecosystem and secure its members' investments in Ember.js. We build on top of the success of the Embroider initiative.",
```

2024-07-08 12:38 UTC, mansona commented on src/ember-initiative.njk
> +  "text": "We upgrades clients' apps to Embroider and Vite – get instant rebuilds while your team stays focused on shipping business value!",
```suggestion
  "text": "We upgrade clients' apps to Embroider and Vite – get instant rebuilds while your team stays focused on shipping business value!",
```

2024-07-08 12:38 UTC, mansona commented on src/posts/2024-07-08-the-embroider-initiative-becomes-the-ember-initiative.md
> +  Ember version to follow it to the end.</p> <p>While the Embroider initiative
> version to follow it to the end

I don't know what this is supposed to mean 🤔 Maybe something like "Most teams just need to update their apps to the latest Ember version to try out Vite for themselves"

2024-07-08 12:38 UTC, mansona commented on src/posts/2024-07-08-the-embroider-initiative-becomes-the-ember-initiative.md
> +imageAlt: "A group of hamsters"
This is not true 😂 these are guinea pigs in the photo. I don't know if it's intended to be a placeholder, if it's a mistake, or a joke.

2024-07-08 12:38 UTC, mansona commented on src/posts/2024-07-08-the-embroider-initiative-becomes-the-ember-initiative.md
> +  accessible for the wider Ember community.
```suggestion
- **Documentation:** While building Ember apps with Vite should be an
  out-of-the-box experience, some documentation  will need to be updated 
  before it can be the default experience for the wider Ember community.
```

2024-07-08 12:38 UTC, mansona commented on src/posts/2024-07-08-the-embroider-initiative-becomes-the-ember-initiative.md
> +  Embroider and Vite compatible with Ember 4.x.
I find the "we suggest" phrasing a bit strange here 🤔 I think we could go with something like: 

```suggestion
- **Backwards compatibility:** Making Vite builds work with older Ember versions
  will make it easier for many teams to switch. The current plan is to for Embroider
  with Vite to support as far back as Ember 4.x.
```

But I don't know if this suggestion is a bit clunky

2024-07-08 12:38 UTC, mansona commented on src/posts/2024-07-08-the-embroider-initiative-becomes-the-ember-initiative.md
> +  support for these addons or documenting alternatives.
I think this isn't a great proposition. Again similar to my above suggestion, I think it should be a plan or a proposal. And "these add-ons" is a bit noncommittal so how about something like: 

```suggestion
- **Opening upgrade paths for the most popular addons:** Ember apps rely heavily
  on addons, but not all widely used ones work with Vite. We propose that we add support
  or document alternatives for the top 100 most used addons in the Ember ecosystem.
```

2024-07-08 12:38 UTC, mansona commented on src/posts/2024-07-08-the-embroider-initiative-becomes-the-ember-initiative.md
> +little progress in recent years (the topic was recently removed from Polaris,
"the topic" hasn't been removed, it has been downsized. The thing that has been removed is that we're not doing the whole new router. I feel that we need to clarify here or people might have a backlash that might obscure the good things in this post

2024-07-08 13:40 UTC, marcoow commented on src/posts/2024-07-08-the-embroider-initiative-becomes-the-ember-initiative.md
> +  Ember version to follow it to the end.</p> <p>While the Embroider initiative
> but the path to Vite is open. Most teams just need to update their apps to the latest Ember version to follow it to the end.

in "follow it to the end", the "it" refers to the "path to Vite"

2024-07-08 13:40 UTC, marcoow commented on src/posts/2024-07-08-the-embroider-initiative-becomes-the-ember-initiative.md
> +imageAlt: "A group of hamsters"
Ha, we've been using this photo with that alt text on other pages forever. I'd say most people won't know and for the ones who know it's a joke then :)

2024-07-08 13:40 UTC, marcoow commented on src/posts/2024-07-08-the-embroider-initiative-becomes-the-ember-initiative.md
> +  Embroider and Vite compatible with Ember 4.x.
it's very clunky I'd say

2024-07-08 13:40 UTC, marcoow commented on src/posts/2024-07-08-the-embroider-initiative-becomes-the-ember-initiative.md
> +  support for these addons or documenting alternatives.
```suggestion
- **Opening upgrade paths for the most popular addons:** Ember apps rely heavily
  on addons, but not all widely used ones work with Vite. We propose that we add
  support or document alternatives for the most used addons in the Ember ecosystem.
```

2024-07-08 13:42 UTC, mansona commented on src/posts/2024-07-08-the-embroider-initiative-becomes-the-ember-initiative.md
> +  support for these addons or documenting alternatives.
yep that works 👍

2024-07-08 13:46 UTC, marcoow commented on src/posts/2024-07-08-the-embroider-initiative-becomes-the-ember-initiative.md
> +  Embroider and Vite compatible with Ember 4.x.
I change the sentence. We can't say _"The current plan"_ as the sponsors will get a say on the plan as well – we're suggesting a plan but it's not set in stone as we suggest it.

2024-07-08 13:47 UTC, marcoow commented on src/posts/2024-07-08-the-embroider-initiative-becomes-the-ember-initiative.md
> +little progress in recent years (the topic was recently removed from Polaris,
rephrased

2024-07-08 13:47 UTC, mansona commented on src/posts/2024-07-08-the-embroider-initiative-becomes-the-ember-initiative.md
> +  Ember version to follow it to the end.</p> <p>While the Embroider initiative
I mean I don't doubt that it does 😂 It's just that it's not very clear (in my opinion) when reading the sentence. Other reviewers could have a different opinion so I'm not insisting that it is fixed or anything (if I could even do something like that 😂 )

2024-07-08 13:49 UTC, mansona approved these changes
Enough of my comments have been covered that I'm happy to approve now 👍 the the "hamster" issue has at least been addressed 😂

2024-07-08 13:52 UTC, marcoow commented on src/posts/2024-07-08-the-embroider-initiative-becomes-the-ember-initiative.md
> +  Ember version to follow it to the end.</p> <p>While the Embroider initiative
rephrased

2024-07-08 14:12 UTC, SaeLLo approved these changes

2024-07-09 08:03 UTC, BlueCutOfficial approved these changes

2024-07-09 08:46 UTC, KevinBongart approved these changes

2024-07-09 09:06 UTC, merged