Add Chris's Talk EmberConf 2024
mainmatter/mainmatter.com pull request #2523
Opened 2024-09-12 13:53 UTC by IdeliaRisella

This is the new PR (previously opened by Emma) to add Chris's talk to the website; using new thumbnail

2024-09-12 16:11 UTC, marcoow requested changes
The little images in the top right are duplicated now: one built into the thumbnail itself, one on top of that. Please remove the ones from the thumbnails.

Also, these little icons should be all-white, not colored.

![Bildschirmfoto 2024-09-12 um 17 10 15](https://github.com/user-attachments/assets/ef069393-5c73-4704-8ba8-7ba34730a738)

2024-09-26 14:38 UTC, marcoow requested changes

2024-09-26 14:38 UTC, marcoow commented on src/appearances/2024-09-13-rust-opensource-more.md
> +Mainmatter’s Founder @marcoow was on the Linux Inlaws podcast to discuss #rustlang, open source, foundations, #eurorust and more
```suggestion
Mainmatter’s Founder Marco Otte-Witte was on the Linux Inlaws podcast to discuss Rust, open source, foundations, EuroRust and more.
```

Neither @ mentions or hashtags work in this text

2024-09-27 11:25 UTC, marcoow approved these changes

2024-09-27 14:03 UTC, IdeliaRisella commented
@marcoow I don't know how to fix the Percy and Gravity. Would you help? I'll ask Bart if maybe I can do it myself next time.

2024-09-27 15:52 UTC, merged