add category colors
mainmatter/mainmatter.com pull request #254
Opened 2018-11-26 15:27 UTC by wadie

Added the category colors that Marco [suggested](https://github.com/simplabs/simplabs.github.io/pull/219#issuecomment-441285403)

2018-11-26 15:35 UTC, marcoow requested changes
the colors for the `js` category seem wrong:

<img width="343" alt="bildschirmfoto 2018-11-26 um 16 31 42" src="https://user-images.githubusercontent.com/1510/49024195-39fd6c00-f199-11e8-9069-5b626870658b.png">

2018-11-26 15:50 UTC, wadie commented
It works now, but I don't think the color looks good. maybe a darker yellow ?

2018-11-26 15:56 UTC, marcoow commented
Those are the official colors for the respective frameworks and languages though - I think it'll be good to use them. What do you think @ghislaineguerin?

This contains a bunch of unrelated changes now - can you rebase on `blog-refactor` and remove 48688add41bfd6a3362971622b6c46f127e7b0b0 from this PR (as well as the changes to `Gemfile`/`Gemfile.lock` - I don't remember the exact reason but we can't use Ruby 2.5 for now)?

2018-11-26 16:18 UTC, ghislaineguerin commented
@marcoow We can always darken the official colors if they are breaking the background contrast accessibility requirements. Otherwise, we should always use the official colors.

2018-11-26 16:21 UTC, ghislaineguerin commented
![image](https://user-images.githubusercontent.com/845767/49027076-aa0ef080-f19f-11e8-97dc-77c8cf78b31d.png)
This is the same color with lower luminosity.

2018-11-26 18:09 UTC, ghislaineguerin commented
@marcoow I think we can merge this once you approve the changes.

2018-11-26 18:09 UTC, ghislaineguerin approved these changes

2018-11-27 09:09 UTC, marcoow requested changes
This still contains some unrelated changes and I think one error (`js`/`javascript`). Also there are lots of commits while in reality I think there should only be one - read up here on rewriting commit history to clean up commits before merging:

* https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History
* https://hackernoon.com/mastering-git-why-rebase-is-amazing-a954485b128a
* https://backlog.com/git-tutorial/rewriting-history/

2018-11-27 09:09 UTC, marcoow commented on stylesheets/components/blog.scss
> +        }
I think all of these changes are unrelated?

2018-11-27 09:09 UTC, marcoow commented on stylesheets/components/blog.scss
> +.blog-js,
Will this actually be used? The category of the posts is `javascript` so I'd assume this will not actually be used (but then if might not be necessary at all - same for the other ones)?

2018-11-28 14:29 UTC, ghislaineguerin requested changes
I think this will now conflict with what's currently on blog-refactor. I suggest starting from a new branch and adding the missing colors and classes.

2018-11-28 18:05 UTC, closed without merging