Add Ember Europe Q4 to calendar
mainmatter/mainmatter.com pull request #2542
Opened 2024-10-17 12:09 UTC by IdeliaRisella

2024-10-17 13:24 UTC, marcoow requested changes

2024-10-17 13:24 UTC, marcoow commented on src/calendar/2024-11-19-embereuropeq4-remote.md
> +url: https://www.meetup.com/ember-europe/
```suggestion
url: https://www.meetup.com/ember-europe/events/301437560/
```

should link directly to the event

2024-11-04 09:43 UTC, IdeliaRisella commented
@marcoow putting the Rust workshop at ADC in Regensburg in this PR along with Ember Europe for easier review

2024-11-04 10:31 UTC, marcoow approved these changes

2024-11-04 10:31 UTC, merged