add Chris' talk at ViteConf to Appearance
mainmatter/mainmatter.com pull request #2554
Opened 2024-10-31 15:51 UTC by IdeliaRisella

2024-10-31 16:47 UTC, marcoow requested changes

2024-10-31 16:47 UTC, marcoow commented on src/appearances/2024-10-03-viteconf.md
> +At ViteConf, Senior Developer Chris Manson, a member of the EmberJS Core Learning and Tooling Teams, presented on the effective integration of Vite with EmberJS, focusing on practical applications an
```suggestion
At ViteConf, our Ember expert Chris Manson, member of the Ember.js Core Learning and Tooling Teams, presented Ember's move to Vite for its new Embroider build system that sets the foundation for Ember's future.
```

this sounded like written by ChatGPT tbh – many words but no real meaning 😬

2024-10-31 16:47 UTC, marcoow commented on src/channels/viteconf-2024.md
> +“ViteConf” is a conference focused on Vite, a modern build tool and development server that enhances the front-end development experience with fast performance and a streamlined workflow.
```suggestion
ViteConf is a conference focused on Vite, the modern build tool and development server that enhances the front-end development experience with fast performance and a streamlined workflow.
```

2024-11-04 10:13 UTC, mansona approved these changes
Looks good to me!

2024-11-04 10:29 UTC, marcoow approved these changes

2024-11-04 10:29 UTC, merged