March update first draft
mainmatter/mainmatter.com pull request #282
Opened 2019-02-28 16:34 UTC by mrmrcoleman

2019-02-28 16:34 UTC, Turbo87 commented on blog/_posts/2019-03-01-march-monthly-update.md
> +And last but my no means least, [Tobias Bieniek](https://twitter.com/tobiasbieniek) asked the question [_Help! How do you let others know what’s going on when you’re 8000 feet up in the air in a plan
```suggestion
And last but my no means least, [Tobias Bieniek](https://twitter.com/tobiasbieniek) asked the question [_Help! How do you let others know what’s going on when you’re 8000 feet up in the air in a plane without an engine?!_](http://bangbangcon.com/west/speakers/#tobias-bieniek) at [!!Con West](https://twitter.com/bangbangconwest)!
```

2019-02-28 17:44 UTC, mansona commented on blog/_posts/2019-03-01-march-monthly-update.md
> +[Chris Manson](https://www.twitter.com/real_ate) has a busy month ahead over in Dublin. On March 5th he's co-organizing the DublinJS meetup at [Workday](https://twitter.com/workday). Full line up wit
```suggestion
[Chris Manson](https://www.twitter.com/real_ate) has a busy month ahead over in Dublin. On March 5th he's co-organizing the DublinJS meetup at [Workday](https://twitter.com/workday). Full line up with [Gabriel Costa](https://twitter.com/gcgoncalves) and [Luciano Mammino](https://twitter.com/loige) [**here**](https://www.meetup.com/DublinJS/events/fbllfpyzfbhb/).
```

2019-02-28 17:44 UTC, mansona commented on blog/_posts/2019-03-01-march-monthly-update.md
> +In January and February we were very pleased to sponsor [Ricardo Mendes](https://twitter.com/locks) from the Ember.js Core Team. Chris Manson spent his 20% time pairing with Ricardo on [Guidemaker](h
```suggestion
In January and February we were very pleased to sponsor [Ricardo Mendes](https://twitter.com/locks) from the Ember.js Core Team. Chris Manson spent his 20% time pairing with Ricardo on [Guidemaker](https://github.com/empress/guidemaker) to add features to help the Ember Octane documentation process and released a 1.0 of Guidemaker!
```

2019-03-01 08:18 UTC, marcoow reviewed
I think this is pretty cool in general! Also seeing how much stuff we actually do is pretty great - I guess surfacing it like that even brings it to our own attention much better!

In general, I'd like us to keep a bit of a more formal tone in our communications - not overly formal but this reads a bit too informal and bullet-point-list-like to me. I'm not the one to tell the native speakers how to write english of course and maybe what I say doesn't even make sense? ;)

Ah, another thing: maybe we should get some logos in there to make it more visually appealing? @ghislaineguerin might have thoughts about that?

2019-03-01 08:18 UTC, marcoow commented on blog/_posts/2019-03-01-march-monthly-update.md
> +##Upcoming Events
```suggestion
## Upcoming Events
```

The space is needed as otherwise the formatting breaks

2019-03-01 08:18 UTC, marcoow commented on blog/_posts/2019-03-01-march-monthly-update.md
> +##Looking back
```suggestion
## Looking back
```

2019-03-01 08:18 UTC, marcoow commented on blog/_posts/2019-03-01-march-monthly-update.md
> +At Simplabs we follow Google's 20% rule where each person gets to 1 day per week on a project of their choice.
```suggestion
At simplabs we follow Google's 20% rule where each person gets to 1 day per week for open source, supporting the projects that we leverage in our client projects.
```

_"simplabs"_ should be lowercase - not sure the other change is well written english but I think we should make clear that a good part of these 20% of our time goes into supporting the projects we rely on. Also to be fair, 20% is not totally of everyone's choice - doing something that's totally unrelated to what simplabs is doing would at least require upfront discussion and might then be deemed not appropriate for 20% time.

2019-03-04 13:35 UTC, marcoow requested changes

2019-03-04 13:35 UTC, marcoow commented on blog/_posts/2019-03-04-march-monthly-update.md
> +title: "Simplabs monthly update - March 2019"
_"simplabs"_ should always be lowercase

2019-03-04 13:50 UTC, marcoow approved these changes

2019-03-07 13:18 UTC, marcoow requested changes
I like it! Only the headlines need to be changed as otherwise the layout is a bit off.

2019-03-07 13:18 UTC, marcoow commented on blog/_posts/2019-03-07-march-monthly-update.md
> +# News
```suggestion
## News
```

2019-03-07 13:18 UTC, marcoow commented on blog/_posts/2019-03-07-march-monthly-update.md
> +### Ricardo Mendes from the Ember.js Core Team joins simplabs
```suggestion
#### Ricardo Mendes from the Ember.js Core Team joins simplabs
```

2019-03-07 13:18 UTC, marcoow commented on blog/_posts/2019-03-07-march-monthly-update.md
> +### EmberConf 2019
```suggestion
#### EmberConf 2019
```

2019-03-07 13:18 UTC, marcoow commented on blog/_posts/2019-03-07-march-monthly-update.md
> +### Ember.js film premiere
```suggestion
#### Ember.js film premiere
```

2019-03-07 13:18 UTC, marcoow commented on blog/_posts/2019-03-07-march-monthly-update.md
> +# Events
```suggestion
## Events
```

2019-03-07 13:18 UTC, marcoow commented on blog/_posts/2019-03-07-march-monthly-update.md
> +### Upcoming events
```suggestion
#### Upcoming events
```

2019-03-07 13:18 UTC, marcoow commented on blog/_posts/2019-03-07-march-monthly-update.md
> +### Past Events
```suggestion
#### Past Events
```

2019-03-07 14:22 UTC, marcoow approved these changes

2019-03-07 14:24 UTC, merged