Blog style fixes
mainmatter/mainmatter.com pull request #352
Opened 2019-04-23 14:59 UTC by ghislaineguerin

2019-04-23 15:26 UTC, marcoow commented on lib/generate-blog-components/lib/files/start-page/component-css-block.hbs
> +}
Can we move this into `src/ui/styles/blocks/blog-post.block.css`? We should not have any style definitions in this block at all ideally. This does not seem to be based on the latest `new-simplabs` btw - I think you'll want to rebase.

2019-04-24 09:16 UTC, ghislaineguerin commented
@marcoow @pichfl Please review. Thanks!

2019-04-24 09:40 UTC, pichfl requested changes

2019-04-24 09:40 UTC, pichfl commented on src/ui/styles/blocks/typography.block.css
> +  font-size: 2.4rem;
At 2.4rem this headline would be rendered smaller than a regular paragraph which is 2.5rem. I see the need for additional headline levels, but I'd recommend using at least the paragraph size.

```css
font-size: 2.5rem; /* ~= 20px at 1440px screen width */
line-height: 1.6; /* ~= 32px / 4rem at 1440px screen width */
```

2019-04-24 09:40 UTC, pichfl commented on src/ui/styles/blocks/typography.block.css
> +  text-decoration: underline;
Yes!

2019-04-24 09:40 UTC, pichfl commented on src/ui/styles/blocks/typography.block.css
> +  color: var(--link-color);
I added new variables for colors in `screen.block.css` which are namespaced, making `--color-link` the preferred variable. I'll make a PR unifying the usage later on anyway, but I think it would be good when newer stuff uses these right away.

2019-04-24 10:54 UTC, ghislaineguerin commented
@pichfl I have included the requested changes. Please review.

2019-04-24 12:24 UTC, pichfl approved these changes

2019-04-24 12:25 UTC, merged