add client descriptions
mainmatter/mainmatter.com pull request #361
Opened 2019-04-25 15:45 UTC by marcoow

This adds descriptions for all of the clients that we list on the work page and a brief summary of what we did for them. I didn't add the ones we have success stories for anyway as that seemed repetitive to me.

closes #312

2019-04-25 15:51 UTC, marcoow commented
@mrmrcoleman can you review this as well and check whether the wording makes sense? See preview here: https://deploy-preview-361--gallant-hawking-42050a.netlify.com/work

2019-04-25 15:54 UTC, marcoow commented on src/ui/styles/blocks/grid-block.block.css
> -  height: 15em;
This of course affects and likely breaks other parts of the page as well but defining an arbitrary height in a generic CSS block seems wrong anyway?

2019-04-25 17:29 UTC, pichfl commented on src/ui/styles/blocks/grid-block.block.css
> -  height: 15em;
Given that it's specified in `em` is a sign that it's something I haven't updated to the new system yet, so removing the value should be fine. We should consider using CSS grids for this specific layout anyway.

2019-04-29 08:23 UTC, marcoow commented on src/ui/styles/blocks/grid-block.block.css
> -  height: 15em;
> We should consider using CSS grids for this specific layout anyway.

do you want me to change anything?

2019-04-29 09:48 UTC, pichfl commented on src/ui/styles/blocks/grid-block.block.css
> -  height: 15em;
I'll be taking care of this as part of #367

2019-04-30 14:48 UTC, pichfl commented
@marcoow can you rebase this PR?

2019-04-30 15:10 UTC, marcoow commented
@pichfl: rebased; I'd like for @mrmrcoleman to have a quick look at this as well before merging though.

2019-04-30 16:36 UTC, mrmrcoleman commented
"We have a track record of successful projects for international clients" sounds odd for some reason, perhaps because it sounds like only some of them are successful.

For the title I would instead use "A proven track record of successful projects for international clients."

2019-04-30 16:37 UTC, mrmrcoleman commented
The text "Read about Trainline" is obscured on my screen.

![Screen Shot 2019-04-30 at 5 36 54 PM](https://user-images.githubusercontent.com/2339682/56978060-93196380-6b6e-11e9-981c-f076b1314288.png)

2019-04-30 16:39 UTC, mrmrcoleman commented
Text for Timify is also obscured and shows the trainline logo
![Screen Shot 2019-04-30 at 5 38 53 PM](https://user-images.githubusercontent.com/2339682/56978220-ed1a2900-6b6e-11e9-949d-215baec0f620.png)

2019-04-30 16:50 UTC, mrmrcoleman commented
For cardstack I would change to this:

"Cardstack builds the experience layer for a decentralized internet. simplabs helped them complete their Card UI system and validate its abilities in various prototype projects, identifying and fixing some issues in their core framework along the way."

2019-04-30 16:51 UTC, mrmrcoleman commented
Generali:

"Generali approached simplabs when they were looking for support with an internal Ember.js project. We guided their team during the course of the project by teaching and establishing best practices until the project's successful completion."

2019-04-30 16:53 UTC, mrmrcoleman commented
xbAV:

"xbAV makes pensions accessible for employees, employers and agents. They approached simplabs when they were looking for support releasing a number of critical features. Our technology experts joined xbAV's internal team, increasing the available workforce while boosting their expertise."

2019-04-30 16:54 UTC, mrmrcoleman commented
Experteer:

"Experteer is Europe's leading executive career service. simplabs has supported them in various ways over the years, building custom web apps, reviewing their code as well as providing architecture and process consulting."

2019-04-30 17:03 UTC, mrmrcoleman requested changes
Minor typos and English tweaks.

2019-04-30 17:03 UTC, mrmrcoleman commented on src/ui/components/PageWork/template.hbs
> +            Cardstack builds the experience layer for a decentralized internet. simplabs helped them completing their Card UI system and validate its abilities in various prototype projects, identify
Cardstack builds the experience layer for a decentralized internet. simplabs helped them complete their Card UI system and validate its abilities in various prototype projects, identifying and fixing some issues in their core framework along the way.

2019-04-30 17:03 UTC, mrmrcoleman commented on src/ui/components/PageWork/template.hbs
> +            Generali approached simplabs when they were looking for support with an internal Ember.js project. We guided their team during the course of the project, taught and established best pract
Generali approached simplabs when they were looking for support with an internal Ember.js project. We guided their team during the course of the project by teaching and establishing best practices until the project's successful completion.

2019-04-30 17:03 UTC, mrmrcoleman commented on src/ui/components/PageWork/template.hbs
> +            xbAV makes pensions accessible for employees, employers and agents. They approached simplabs when they were looking for support releasing a number of critical features. Our technology exp
xbAV makes pensions accessible for employees, employers and agents. They approached simplabs when they were looking for support releasing a number of critical features. Our technology experts joined xbAV's internal team, increasing the available workforce while boosting their expertise.

2019-04-30 17:03 UTC, mrmrcoleman commented on src/ui/components/PageWork/template.hbs
> +            Experteers is Europe's leading executive career service. simplabs has supported them in various ways ov the years, building custom web apps, reviewing their code as well as providing arch
Experteer is Europe's leading executive career service. simplabs has supported them in various ways over the years, building custom web apps, reviewing their code as well as providing architecture and process consulting.

2019-04-30 17:03 UTC, mrmrcoleman commented on src/ui/components/PageWork/template.hbs
> +            mvb provides marketing solutions for the german book industry. They approached simplabs when they were looking for external expertise. simplabs performed a workshop, leveling up the team'
mvb provides marketing solutions for the german book industry. They approached simplabs when they were looking for external expertise. simplabs performed a workshop, leveling up the team's expertise and guided the project until its successful completion.

2019-04-30 17:03 UTC, mrmrcoleman commented on src/ui/components/PageWork/template.hbs
> +            Dim3 delivers software allowing hospitals manage and optimize their patients' nutrition plans. They approached simplabs when they faced severe performance problems in their app. We identi
Dim3 delivers software allowing hospitals to manage and optimize their patients' nutrition plans. They approached simplabs when they faced severe performance problem in their app. We identified and fixed these issues and also found and solved some potential future problems along the way.

2019-05-06 12:47 UTC, marcoow commented
@pichfl if you applied Mark's requested changes, feel free to approve and merge

2019-05-06 15:28 UTC, pichfl approved these changes

2019-05-06 15:28 UTC, merged