Button hover styling
mainmatter/mainmatter.com pull request #382
Opened 2019-04-29 15:43 UTC by pichfl

closes #364

2019-04-29 15:53 UTC, marcoow reviewed
Can we make this subtly animated? I'd generally like to have some subtle animations on the page.

2019-04-29 16:12 UTC, pichfl commented
Sure, will update.

2019-04-30 07:20 UTC, marcoow requested changes
This only changes the foreground color: https://deploy-preview-382--gallant-hawking-42050a.netlify.com

Also, the build fails.

2019-04-30 09:43 UTC, marcoow approved these changes

2019-04-30 11:10 UTC, merged