Timify case study
mainmatter/mainmatter.com pull request #416
Opened 2019-05-09 14:16 UTC by pichfl

closes #393

2019-05-10 14:38 UTC, marcoow requested changes
Looks good but we need to replace the teaser for the breethe case.

2019-05-10 14:38 UTC, marcoow commented on src/ui/components/PageCaseStudyTimify/template.hbs
> +  <ShapeFeatureBreethe />
This needs to be replaced with a teaser for either the trainline or dd-wrt cases. We don't actually have the breethe case yet.

2019-05-10 14:43 UTC, pichfl commented
Switched case study teaser and rebased.

2019-05-10 14:59 UTC, marcoow commented on src/ui/components/PageCaseStudyTimify/template.hbs
> +  <ShapeFeatureTrainline />
This doesn't seem to exist?

2019-05-10 15:19 UTC, pichfl commented on src/ui/components/PageCaseStudyTimify/template.hbs
> +  <ShapeFeatureTrainline />
Forgot to include it in commit. Pushed.

2019-05-10 15:26 UTC, marcoow commented on src/ui/components/PageCaseStudyTimify/template.hbs
> +  <ShapeFeatureTrainline />
hm, this doesn't seem right though: 
<img width="1626" alt="Bildschirmfoto 2019-05-10 um 17 25 54" src="https://user-images.githubusercontent.com/1510/57538439-b3080e80-7348-11e9-85ab-1927c3f86034.png">

2019-05-10 15:27 UTC, marcoow reviewed
I realized another thing: in the big image we're only showing a little part of the UI - might make sense to switch the image horizontally so that the screen of the notebook is on the right and thus users see more?

<img width="1626" alt="Bildschirmfoto 2019-05-10 um 17 27 16" src="https://user-images.githubusercontent.com/1510/57538527-e5197080-7348-11e9-809f-d77f2d29329f.png">

2019-05-10 15:31 UTC, pichfl commented
Yes, neither image is perfect. I'll talk to @ghislaineguerin about it

2019-05-13 07:40 UTC, ghislaineguerin commented
@pichfl I will work on the images after I'm done adding design to #385

2019-05-15 11:37 UTC, marcoow reviewed
The timify screenshot still doesn't seem ideal. This one looks better I think: https://share.goabstract.com/cc5a7205-6b8e-44a3-bc13-7bfbae929f2f?mode=design&sha=53ab853d29a56eaceb1d86448c6206f86fe2bb94

2019-05-15 13:33 UTC, pichfl commented
The mockup doesn't position the image in a repeatable way, which means I would need to allow for individual alignments. 

@ghislaineguerin is there a macbook facing the other direction in your library? Maybe that would bring the screen more to the right side and show more in that component.

I also realized I haven't accounted for another alignment case on the work page. Will update.

2019-05-16 14:06 UTC, ghislaineguerin commented
@pichfl on the staged link some of the images are in low quality, they don't look as sharp. Could you save with 2x the size maybe? 
![image](https://user-images.githubusercontent.com/845767/57860087-7b8bdd00-77f4-11e9-9b23-4072bde14000.png)

2019-05-20 08:42 UTC, pichfl commented
@marcoow updated again, made the ShapeWork image sizing easier to understand: it tries to fit the image fed to it into a container that's sized at 1200x900 and is positioned to fit into the shape, which makes it easier for @ghislaineguerin to position the contents.

2019-05-20 08:51 UTC, marcoow reviewed
LGTM - just a few minor remarks.

2019-05-20 08:51 UTC, marcoow commented on src/ui/components/PageCaseStudyTimify/component.ts
> +export default class PageCaseStudyTimify extends Component {}
This is not needed

2019-05-20 08:51 UTC, marcoow commented on src/ui/components/ShapeWork/stylesheet.css
>  }
Is this class still needed at all then?

2019-05-20 08:51 UTC, marcoow commented on src/ui/components/ShapeWork/stylesheet.css
>  }
Can this whole class be removed?

2019-05-20 08:51 UTC, marcoow commented on src/ui/components/PageCaseStudyTimify/template.hbs
> +        <Card @title="Learn about our sprint based approach" @src="/assets/images/card/playbook.svg">
We deliberately do not actually say _"sprint"_ - let's use the same card we're using here instead: https://deploy-preview-416--gallant-hawking-42050a.netlify.com/services/

2019-05-20 09:11 UTC, marcoow commented on src/ui/components/PageCaseStudyTimify/component-test.ts
>  });
I guess this was moved instead of copied by accident?

2019-05-20 09:11 UTC, marcoow commented on src/ui/components/CardPlaybook/template.hbs
> +</Card>
Can we have a `component-test.ts` for this as well?

2019-05-20 09:11 UTC, marcoow commented on src/ui/components/PageCaseStudyTimify/component.ts
> +export default class PageCaseStudyTimify extends Component {}
Can this file be deleted?

2019-05-20 09:38 UTC, marcoow commented on src/ui/components/CardPlaybook/component-test.ts
>    });
This moves the `CardUpcomingTest` test case (leaving that component without a test case) - I think you meant to copy instead.

2019-05-20 09:44 UTC, marcoow approved these changes

2019-05-20 09:53 UTC, merged