Updated layout for expedition case study
mainmatter/mainmatter.com pull request #418
Opened 2019-05-09 15:30 UTC by pichfl

Merge after #416 

closes #394

2019-05-10 15:36 UTC, marcoow commented
@pichfl can you resolve the conflict?

2019-05-13 10:30 UTC, marcoow commented
@pichfl can we merge this to `new-simplabs` please? We should never cross-merge branches (`new-simplabs` **is** our `master` in this case).

2019-05-20 12:20 UTC, marcoow requested changes
This looks good but there are some minor things we should change. Also, can you take the latest content from `new-simplabs` (https://gallant-hawking-42050a.netlify.com/cases/expedition) plus the first paragraph that#s currently missing there?

_"Expedition is an online travel magazine for global citizens. It lets travellers experience the world's best destinations through the eyes of a local."_

2019-05-20 12:20 UTC, marcoow commented on src/ui/components/PageCaseStudyExpedition/template.hbs
> +            <a class="typography.title-link" href="#">
this is missing the link

2019-05-20 12:20 UTC, marcoow commented on src/ui/components/PageCaseStudyExpedition/template.hbs
> +        <Card @label="Our Expertise" @src="/assets/images/card/elixir.svg">
This is showing the Phoenix logo only (despite the file name). I think we don't actually need to show that one at all but should show the Elixir one.

2019-05-20 12:20 UTC, marcoow commented on src/ui/components/PageCaseStudyExpedition/template.hbs
> +              </ArrowLink>
I'm not sure where this is supposed to link? Can probably be removed?

2019-05-20 13:15 UTC, pichfl commented on src/ui/components/PageCaseStudyExpedition/template.hbs
> +        <Card @label="Our Expertise" @src="/assets/images/card/elixir.svg">
I put what we had in the mockup. A quick search shows that Elixir itself doesn't provide an SVG based logo.

Either we use the logo that's on the official website or @ghislaineguerin needs to create an SVG version. I'd go with the former.

2019-05-20 13:15 UTC, pichfl commented on src/ui/components/PageCaseStudyExpedition/template.hbs
> +              </ArrowLink>
Oversight on my end, can be removed 🙂

2019-05-20 13:17 UTC, marcoow commented on src/ui/components/PageCaseStudyExpedition/template.hbs
> +        <Card @label="Our Expertise" @src="/assets/images/card/elixir.svg">
We have an SVG version that we can use already: https://gallant-hawking-42050a.netlify.com/cases/expedition

2019-05-20 14:11 UTC, pichfl commented on src/ui/components/PageCaseStudyExpedition/template.hbs
> +        <Card @label="Our Expertise" @src="/assets/images/card/elixir.svg">
Totally missed that one, compressed and updated.

2019-05-20 14:14 UTC, marcoow reviewed
I think leaving the first paragraph in would be good:

_"Expedition is an online travel magazine for global citizens. It lets travellers experience the world's best destinations through the eyes of a local."_

It looks very empty at the top otherwise: 
<img width="1529" alt="Bildschirmfoto 2019-05-20 um 16 14 39" src="https://user-images.githubusercontent.com/1510/58028136-64156280-7b1a-11e9-9132-4b419f9edf27.png">

2019-05-20 14:24 UTC, pichfl commented
Like so?

2019-05-20 14:39 UTC, marcoow commented
@pichfl I restructured a bit - let me know what you think.

2019-05-20 14:49 UTC, pichfl commented
Looks good 👍

2019-05-20 14:51 UTC, marcoow approved these changes

2019-05-20 15:26 UTC, merged