Blog: New features for ember-test-selectors
mainmatter/mainmatter.com pull request #52
Opened 2017-01-12 16:14 UTC by Turbo87

2017-01-12 16:21 UTC, pangratz submitted a review, later dismissed
Awesome writeup!! 💯 👍 

Since the post is quite long, I think a TL;DR at the beginning might be a good idea... 🤔

2017-01-12 16:21 UTC, pangratz commented on blog/_posts/2017-01-12-ember-test-selectors.md
> +  <h1 data-test-selector="post-title">{{post.title}}</h1>
This should be `data-test-post-title` to work with the selector below...

2017-01-12 16:21 UTC, pangratz commented on blog/_posts/2017-01-12-ember-test-selectors.md
> +AST, that we get from the template parser. This can be accomplished using by
`s/using//`

2017-01-12 16:21 UTC, pangratz commented on blog/_posts/2017-01-12-ember-test-selectors.md
> +[AST explorer](https://astexplorer.net/#/5ZDpdTbKwL).
❤️

2017-01-12 16:21 UTC, pangratz commented on blog/_posts/2017-01-12-ember-test-selectors.md
> +official [ember-cli-htmlbars-inline-precompile](https://github.com/ember-cli/ember-cli-htmlbars-inline-precompile/blob/master/index.js#L64-L69)
I think we should use a permalink here...

2017-01-12 16:21 UTC, pangratz commented on blog/_posts/2017-01-12-ember-test-selectors.md
> +official [ember-cli-htmlbars-inline-precompile](https://github.com/ember-cli/ember-cli-htmlbars-inline-precompile/blob/master/index.js#L64-L69)
Can be achieved by by pressing `y` when viewing the above link

2017-01-12 16:23 UTC, marcoow commented
@Turbo87: need to add you [picture](https://github.com/simplabs/simplabs.github.io/tree/master/images/authors) here as well so it renders corretly at the bottom.

2017-01-12 16:46 UTC, marcoow reviewed
Great post!

2017-01-12 16:46 UTC, marcoow commented on blog/_posts/2017-01-12-ember-test-selectors.md
> +While `v0.1.0` does not sound like much has changed, the addon has actually
I think we should not include the `v` prefix in the version numbers in the text actually - it's basically just the tags that use the prefix while users will always deal with the bare versions.

2017-01-12 16:46 UTC, marcoow commented on blog/_posts/2017-01-12-ember-test-selectors.md
> +... so that you can use these as CSS/jQuery selectors in your acceptance and integration tests:
I'd just say _"you can use these as selectors"_

2017-01-12 16:46 UTC, marcoow commented on blog/_posts/2017-01-12-ember-test-selectors.md
> +only includes both folders if we are in testing mode.
I think we should be clearer about the fact that this is not only for testing mode but for all modes that we're not stripping in, e.g. also `development` env. Otherwise that might lead people to believe they wouldn't get these things in `development` neither.

2017-01-12 16:46 UTC, marcoow commented on blog/_posts/2017-01-12-ember-test-selectors.md
> +makes sense to also use them inside the class as *computed* properties.
I'd say sth. like _"While one way of assigning data attributes to a component is in the template, data attributes can also be defined as properties on the component context. Data attributes defined that way are now auto-bound as well and of course also need to be stripped for production (or production-like) builds."_

Your wording sounds a bit like we're suggesting to define data attributes on the template context instead of the template which I don't think we should do. For acceptance and integration tests your perspective is actually more centered on the template instead of the context and it's probably simpler in most cases to define the data attributes there as well then.

2017-01-12 16:46 UTC, marcoow commented on blog/_posts/2017-01-12-ember-test-selectors.md
> +existing JavaScript processing pipeline using [Babel](http://babeljs.io/).
_"There now is a property definition inside of the template context that will not be stripped by the Handlebars AST transform described above as it is defined in JS actually. At this point we could have used a similar strategy a…"_

2017-01-12 16:49 UTC, Turbo87 commented on blog/_posts/2017-01-12-ember-test-selectors.md
> +only includes both folders if we are in testing mode.
I tried to make this clearer in the "testing in production" section. Mentioning this including all the details everywhere will probably make it harder to read.

2017-01-12 16:51 UTC, marcoow commented on blog/_posts/2017-01-12-ember-test-selectors.md
> +only includes both folders if we are in testing mode.
I guess you could just say sth. like _"…only includes both folders unless building for production or a production-like environment where none of ember-test-selector's code should be present."_.

2017-01-13 09:54 UTC, Turbo87 commented
updated the PR with the suggestions

2017-01-13 10:01 UTC, marcoow requested changes

2017-01-13 10:01 UTC, marcoow commented on blog/_posts/2017-01-12-ember-test-selectors.md
> +----
We shouldn't be using `<hr>`s in the content as that conflicts with the layout

2017-01-13 10:21 UTC, marcoow approved these changes

2017-01-13 10:22 UTC, merged

2017-01-13 10:23 UTC, pangratz commented on blog/_posts/2017-01-13-ember-test-selectors.md
> +features.
IMHO we should have a TL;DR here with a summary of what happened:

- binding of `data-test-*` attributes within components in templates and JS files
- stripping of `data-test-*` attributes within templates and JS files
- simplified import of test selector

2017-01-13 10:24 UTC, marcoow commented on blog/_posts/2017-01-13-ember-test-selectors.md
> +features.
Sorry, had dismissed your review a second earlier. This sounds like a good idea though. @Turbo87: want to create a follow-up PR adding this?