baseline.css
mainmatter/mainmatter.com pull request #579
Opened 2019-05-31 09:10 UTC by pichfl

Moving basic typographic styles out of CSS Blocks removes a lot of noise from the HTML of components and pages like the blog posts. 

Closes #569

2019-05-31 10:06 UTC, marcoow reviewed
This leads to a few visual changes which I'm not sure we actually want, e.g.

* imprint and privacy links now are blue on hover
* the buttons now show an underline under the text on hover
* the links and button in the cookie teaser are now blue
* the header links in the footer now show an underline on hover
* email, phone number etc. on the contact page are now indented
* header links on services page now show underlines on hover

…and potentially others - have only looked on the home page for now

2019-05-31 10:06 UTC, marcoow commented on lib/generate-blog/lib/templates/author/stylesheet.hbs
> +@block o from "../../styles/blocks/offset.block.css";
Let's name things properly please - seeing something like `o.class` in the template basically makes it impossible to understand what that is about.

2019-05-31 10:06 UTC, marcoow commented on src/ui/components/FormContact/component.ts
> -      this.errors = {};
Thy is this needed? Also seems unrelated?

2019-05-31 10:11 UTC, pichfl commented on src/ui/components/FormContact/component.ts
> -      this.errors = {};
That was not intended for this PR, but it is no longer required and generates a warning in the build process. This was most likely an artifact from my attempt to do the validations manually.

2019-05-31 10:15 UTC, pichfl commented on lib/generate-blog/lib/templates/author/stylesheet.hbs
> +@block o from "../../styles/blocks/offset.block.css";
I took inspiration for that from the CSS Blocks fixtures, but I agree with preferring speaking names in general, will update.

2019-05-31 10:16 UTC, marcoow commented on src/ui/components/FormContact/component.ts
> -      this.errors = {};
let's keep separate things separate though 🙏

2019-05-31 10:23 UTC, pichfl commented
> * imprint and privacy links now are blue on hover

Intended change

> * the buttons now show an underline under the text on hover

Bug, will update

> * the links and button in the cookie teaser are now blue

Unintended change, will update.

> * the header links in the footer now show an underline on hover

Intended change.

> * email, phone number etc. on the contact page are now indented

Oversight, will update.

> * header links on services page now show underlines on hover

Intended change.
 
> …and potentially others - have only looked on the home page for now

Thanks for all of these, it's hard to see that stuff when you're reiterating that often.

2019-05-31 10:39 UTC, pichfl commented on src/ui/components/FormContact/component.ts
> -      this.errors = {};
Done. See #584

2019-05-31 12:58 UTC, marcoow commented on src/ui/styles/blocks/list.block.css
>  }
Do we still need the class if it is now empty anyway?

2019-05-31 12:58 UTC, marcoow commented on src/ui/components/ShapeAcross/stylesheet.css
> +@block containerBlock from "../../styles/blocks/container.block.css";
I'd name this just `container` everywhere for consistency.

2019-05-31 13:04 UTC, marcoow requested changes
I found some more things that now show the wrong way (all Safari):

* text color is wrong in case studies:

<img width="819" alt="Bildschirmfoto 2019-05-31 um 14 59 45" src="https://user-images.githubusercontent.com/1510/58707403-1f5cb780-83b5-11e9-8849-6175752ca5dd.png">
<img width="926" alt="Bildschirmfoto 2019-05-31 um 14 59 36" src="https://user-images.githubusercontent.com/1510/58707409-24ba0200-83b5-11e9-9047-cd737a1499f3.png">

* missing space after paragraph in form submission confirmation text:

<img width="641" alt="Bildschirmfoto 2019-05-31 um 15 00 17" src="https://user-images.githubusercontent.com/1510/58707427-34d1e180-83b5-11e9-82c1-e98e5f7def68.png">

* mobile menu items have wrong color and are displaced when hovering:

<img width="616" alt="Bildschirmfoto 2019-05-31 um 15 00 35" src="https://user-images.githubusercontent.com/1510/58707441-461aee00-83b5-11e9-8774-2fa62b62816c.png">
<img width="616" alt="Bildschirmfoto 2019-05-31 um 15 00 39" src="https://user-images.githubusercontent.com/1510/58707442-461aee00-83b5-11e9-9240-ec6bc278b65a.png">

* text underline is strangely broken on mobile blog index when hovering:

<img width="616" alt="Bildschirmfoto 2019-05-31 um 15 01 33" src="https://user-images.githubusercontent.com/1510/58707464-559a3700-83b5-11e9-96e1-d21c08276829.png">

2019-05-31 18:08 UTC, pichfl commented on src/ui/styles/blocks/list.block.css
>  }
I'm hunting down empty ones, good catch.

2019-05-31 18:09 UTC, pichfl commented on src/ui/components/ShapeAcross/stylesheet.css
> +@block containerBlock from "../../styles/blocks/container.block.css";
Sadly no, there is a class "container" in the local scope, so I had to rename. This will most likely go away when the responsive shape refactoring is done.

2019-06-05 10:45 UTC, ghislaineguerin approved these changes
👍 excellent, thanks!

2019-06-05 11:26 UTC, merged