Improved shapes
mainmatter/mainmatter.com pull request #596
Opened 2019-06-17 13:38 UTC by ghislaineguerin

2019-06-17 15:07 UTC, ghislaineguerin commented
Update:

A white frame and border are now used to enhance mobile view. This will simplify the responsiveness of most shapes.

![localhost_4200_ (1)](https://user-images.githubusercontent.com/845767/59615121-4f7cb800-9122-11e9-8322-f9554aa2c1f3.png)
![localhost_4200_](https://user-images.githubusercontent.com/845767/59615123-4f7cb800-9122-11e9-8f0a-0bc6bdc7efe1.png)

2019-06-24 10:06 UTC, marcoow commented
> A white frame and border are now used to enhance mobile view. This will simplify the responsiveness of most shapes.

Hm, is this what you agreed on? I'm not a huge fan tbh - I think it should be possible to implement the design we have on abstract.com?

2019-06-24 11:10 UTC, ghislaineguerin commented
@marcoow I've added the white frame to simplify the implementation. Florian was away. I have now fixed most issues so I think I can focus on mobile. I will fix it to look like the abstract version.

2019-06-24 11:12 UTC, marcoow commented
Hm, I'd say let's try and simplify the implementation without changing the design (unless that turns out to be impossible for some reason of course). Do you think that makes sense?

2019-06-24 11:21 UTC, ghislaineguerin commented
@marcoow Sure, I can do that.

2019-07-03 08:16 UTC, ghislaineguerin commented
@pichfl looks great, mobile it's also working fine for me.

2019-07-04 12:51 UTC, marcoow requested changes
I found some issues on some pages:

* Services -> Full Stack Engineering:

<img width="1428" alt="Bildschirmfoto 2019-07-04 um 14 41 20" src="https://user-images.githubusercontent.com/1510/60667447-dabbb480-9e69-11e9-811f-d5d3adfa7eaf.png">

* Elixir & Phoenix:

<img width="1428" alt="Bildschirmfoto 2019-07-04 um 14 44 26" src="https://user-images.githubusercontent.com/1510/60667623-4271ff80-9e6a-11e9-896e-bbc045c1cea2.png">

* pages are too wide on mobile now - don't know whether that's because of the shapges:

<img width="559" alt="Bildschirmfoto 2019-07-04 um 14 47 26" src="https://user-images.githubusercontent.com/1510/60667804-b6140c80-9e6a-11e9-9e89-a79ef63faf51.png">

* trainline shape on work page doesn't work on mobile:

<img width="559" alt="Bildschirmfoto 2019-07-04 um 14 48 53" src="https://user-images.githubusercontent.com/1510/60667881-e360ba80-9e6a-11e9-9268-5414ad24c7cb.png">

* not sure Timify shape is broken on mobile or as intended?

<img width="559" alt="Bildschirmfoto 2019-07-04 um 14 49 42" src="https://user-images.githubusercontent.com/1510/60667929-02f7e300-9e6b-11e9-9d3c-9f2ee9199bff.png">

* Timify shape in the success story is broken:

<img width="559" alt="Bildschirmfoto 2019-07-04 um 14 50 12" src="https://user-images.githubusercontent.com/1510/60667949-130fc280-9e6b-11e9-8a78-e4db4a57dce1.png">

* same in the trainline case:

<img width="559" alt="Bildschirmfoto 2019-07-04 um 14 50 44" src="https://user-images.githubusercontent.com/1510/60667968-228f0b80-9e6b-11e9-82e8-eaaa3bd19f77.png">

2019-07-04 13:00 UTC, marcoow reviewed
Also, the changed images are all bigger than before and some new ones are huge - I think they all need compression.

2019-07-04 13:00 UTC, marcoow commented on src/ui/components/PageHomepage/stylesheet.css
> +
👀

2019-07-04 13:00 UTC, marcoow commented on src/ui/components/ShapeAcross/component.ts
> +  public maskId = null;
Should this not be private or protected?

2019-07-04 13:00 UTC, marcoow commented on src/ui/components/ShapeAcross/component.ts
> +      .substr(2);
This is problematic as it will be different in the SSR pre-render and the actual render in the browser. Can we have something that is stable?

2019-07-04 13:00 UTC, marcoow commented on src/ui/components/ShapeBold/component.ts
> +    .substr(2);
see above - we shouldn't have anything random in the DOM

2019-07-04 13:00 UTC, marcoow commented on src/ui/components/ShapeBold/component.ts
> +    return [...style.entries()].map(([key, value]) => `${key}:${value}`).join(';');
I'm not sure why we need `[...style.entries()]` here as we **know** `style.entries()` is going to be unique (`'--shape-color-a'`, `'--shape-color-b'`)?

2019-07-04 13:00 UTC, marcoow commented on src/ui/components/ShapeFeature/component.ts
> +  }
What about

```typescript
get bottomImageStyle() {
  if (this.args.image) {
    return `background-image: url(${this.args.image})`;
  }
}
```

?

2019-07-04 13:00 UTC, marcoow commented on src/ui/components/ShapeFeature/stylesheet.css
> +}
are these empty blocks needed?

2019-07-04 13:00 UTC, marcoow commented on src/ui/styles/blocks/offset.block.css
> +
👀

2019-07-04 13:11 UTC, pichfl commented on src/ui/components/PageHomepage/stylesheet.css
> +
Took me until now to realize that prettier isn't run for CSS files, added PR #606 for that. Will rebase once merged.

2019-07-04 13:11 UTC, pichfl commented on src/ui/components/ShapeAcross/component.ts
> +  public maskId = null;
No reason not to do it.

2019-07-04 13:16 UTC, pichfl commented on src/ui/components/ShapeAcross/component.ts
> +      .substr(2);
This is only the latest implement of that code, it's used all across the components. 
Sadly I can not use a static string for those ids as they would clash if a component is reused twice on a page, which can and does happen.

It's used in `ShapeBase` and any Shape* class that has inline SVG references. 

I was hoping that a changing id wouldn't actually have any impact on the pre-render as they are used only locally in that component, which in turn makes a strong argument for changing those fields to private.

2019-07-04 13:21 UTC, pichfl commented on src/ui/components/ShapeBold/component.ts
> +    return [...style.entries()].map(([key, value]) => `${key}:${value}`).join(';');
Overengineering at it's finest. Will replace with a less computationally offensive solution. There is absolutely no need for the `Map` in the first place.

Sidennote: The `[...style.entries()].map` call is not used for uniqueness, but as the only way to map the entries inside a Map, since the Map object does not support `.map()` itself.

2019-07-04 13:22 UTC, pichfl commented on src/ui/components/ShapeFeature/component.ts
> +  }
Tried to keep the method signature similar to the code above, I'm not attached to that bit, will refactor.

2019-07-04 13:29 UTC, marcoow commented on src/ui/components/ShapeAcross/component.ts
> +  public maskId = null;
not sure what you mean

2019-07-04 13:30 UTC, marcoow commented on src/ui/components/ShapeAcross/component.ts
> +      .substr(2);
Yeah, only recognized that now - we should have a separate issue to handle this. Can you create one?

2019-07-04 15:55 UTC, pichfl commented on src/ui/components/ShapeAcross/component.ts
> +  public maskId = null;
Sorry. Meant to say: Will change to private and update similar props in other components as well.

2019-07-04 15:58 UTC, pichfl commented on src/ui/components/ShapeAcross/component.ts
> +      .substr(2);
Done, see #608

2019-07-04 16:04 UTC, pichfl commented on src/ui/components/ShapeAcross/component.ts
> +  public maskId = null;
Actually, if I make these private, I get warnings in TSLint about props that are never read, as the linter doesn't know about the templates. Should I still do that and add a comment to disable that warning?

2019-07-05 07:41 UTC, marcoow commented on src/ui/components/ShapeAcross/component.ts
> +  public maskId = null;
I'd say let's just not specify `private`/`public` at all.

2019-07-05 08:49 UTC, pichfl commented on src/ui/components/ShapeAcross/component.ts
> +  public maskId = null;
It gets inserted by the formatter task automatically

2019-07-08 16:13 UTC, marcoow reviewed
This looks very good in general but the content still seems a bit too wide (tested in iPhone 6 simulator but same on my iPhone XS): 

<img width="559" alt="Bildschirmfoto 2019-07-08 um 18 05 46" src="https://user-images.githubusercontent.com/1510/60825097-360fde80-a1ab-11e9-872a-f66d8f2e549c.png">

Also the images are all growing in size significantly which is probably wrong. Have a look at https://imageoptim.com/mac for a good compression tool.

2019-07-08 16:13 UTC, marcoow commented on src/ui/components/ShapeAcross/component.ts
> +    return style;
I'd simplify the method to

```es6
get backgroundStyle() {
  if (this.args.background) {
    return `--shape-color: ${this.args.background}`;
  }
}
```

2019-07-08 16:39 UTC, pichfl commented
Everything is compressed with ImageOption and where possible with ImageAlpha as well. For the overlapping images we have to rely on pngs (at least for stable solution) so while unfortunate, there is no other option here 😞

2019-07-09 07:09 UTC, marcoow commented
@pichfl can we check we can shrink the image dimensions a bit maybe? 350KB is pretty huge…

2019-07-09 12:41 UTC, marcoow approved these changes
🎉

2019-07-09 12:41 UTC, merged