Blog post: Design Workflow: Naming in design files
mainmatter/mainmatter.com pull request #631
Opened 2019-07-17 13:33 UTC by pichfl

I think this will be the start of a series, more is detailed in #615 

Any feedback is highly appreciated.

2019-07-24 05:27 UTC, ghislaineguerin commented
@pichfl should we hold review until you've added the post images?

2019-07-24 05:30 UTC, ghislaineguerin requested changes
@pichfl the button image seems to be overflowing. It's also missing the sketch screenshots. Is this blocked by blog layout fixes?

2019-07-31 11:03 UTC, marcoow reviewed
I think this kind of content is a great addition to our blog. I don't follow everything in the post but I think that's likely due to the fact that I'm not really familiar with the matter in general.

2019-07-31 11:03 UTC, marcoow commented on _posts/2019-08-01-design-workflow-naming-in-design-files.md
> +Besides having an actual name, most elements in a design will have a current condition which might change on external factors and will most likely require variations to show all possible states.
I don't really understand this - that's likely partly due to the fact that I don't really know much about the design process but also I think the wording needs to be changed at least slightly so this conveys the meaning you're aiming for.

2019-07-31 11:03 UTC, marcoow commented on _posts/2019-08-01-design-workflow-naming-in-design-files.md
> +So you create symbols for these variations and now you have a new problem: you need a strategy for naming those.
Would it make sense to explain all of this using an example from the beginning (or is this all much clearer for someone more familiar with the matter than me anyway)?

2019-07-31 11:03 UTC, marcoow commented on _posts/2019-08-01-design-workflow-naming-in-design-files.md
> +![Illustration of the eight expected states of our button](/assets/images/posts/2019-08-01-design-workflow-naming-in-design-files/figure-1-button.png)
Did you make this image?

2019-07-31 11:03 UTC, marcoow commented on _posts/2019-08-01-design-workflow-naming-in-design-files.md
> +Using Titlecase as in trying to start with a uppercase letter really isn't necessary. Using camelCase to make it easier to read long names comes in handy. Try to stay away from spaces for the names,
What about `PascalCase` (`camelCase` but starting with an uppercase letter)?

2019-07-31 11:03 UTC, marcoow commented on _posts/2019-08-01-design-workflow-naming-in-design-files.md
> +Using Titlecase as in trying to start with a uppercase letter really isn't necessary. Using camelCase to make it easier to read long names comes in handy. Try to stay away from spaces for the names,
I don't understand what the _"use them for:"_ refers to as when describing modifiers you're not actually showing any that use spaces?

2019-07-31 11:03 UTC, marcoow commented on _posts/2019-08-01-design-workflow-naming-in-design-files.md
> +| `@`    | Screen sizes like @small``@wide`       |
```suggestion
| `@`    | Screen sizes like `@small`,`@wide`       |
```

2019-07-31 11:03 UTC, marcoow commented on _posts/2019-08-01-design-workflow-naming-in-design-files.md
> +| `#`    | States like `#hover` `#error` `#empty` |
```suggestion
| `#`    | States like `#hover`, `#error`, `#empty` |
```

2019-07-31 11:03 UTC, marcoow commented on _posts/2019-08-01-design-workflow-naming-in-design-files.md
> +| `+`    | Variants like `+primary` `+large`      |
```suggestion
| `+`    | Variants like `+primary`, `+large`      |
```

2019-07-31 12:35 UTC, pichfl commented on _posts/2019-08-01-design-workflow-naming-in-design-files.md
> +![Illustration of the eight expected states of our button](/assets/images/posts/2019-08-01-design-workflow-naming-in-design-files/figure-1-button.png)
Yup 🙂

2019-07-31 12:35 UTC, pichfl commented on _posts/2019-08-01-design-workflow-naming-in-design-files.md
> +Using Titlecase as in trying to start with a uppercase letter really isn't necessary. Using camelCase to make it easier to read long names comes in handy. Try to stay away from spaces for the names,
Personal preference, mostly to always start with a lowercase letter

2019-07-31 12:36 UTC, pichfl commented on _posts/2019-08-01-design-workflow-naming-in-design-files.md
> +Using Titlecase as in trying to start with a uppercase letter really isn't necessary. Using camelCase to make it easier to read long names comes in handy. Try to stay away from spaces for the names,
Yes, needs rephrasing. Spaces should only be delimiters between the name and the modifiers.

2019-07-31 12:40 UTC, pichfl commented on _posts/2019-08-01-design-workflow-naming-in-design-files.md
> +Besides having an actual name, most elements in a design will have a current condition which might change on external factors and will most likely require variations to show all possible states.
Since that post should work for people who have not much existing knowledge on the topic, I'll have to change it and make it less complex in general. I read too many articles on semantics and language recently.

2022-11-11 06:56 UTC, closed without merging