July monthly update first draft
mainmatter/mainmatter.com pull request #639
Opened 2019-07-22 11:34 UTC by mrmrcoleman

2019-07-22 12:09 UTC, mansona requested changes
Feel free to keep the thing about "May I Ask a Question" but we need to update the thing about Empress 👍

2019-07-22 12:09 UTC, mansona commented on _posts/2019-07-23-july-monthly-update.md
> +In other news [Chris Manson](https://twitter.com/real_ate/) and [Jen Weber](https://twitter.com/jwwweber/) released [another episode](https://twitter.com/real_ate/status/1126760948260204549) of 'May
I would probably just remove this update because it highlights the delay in the update post 🙈 "**May** I Ask A Question" is a pun on the fact that we answer Stack Overflow questions in **May**

2019-07-22 12:09 UTC, mansona commented on _posts/2019-07-23-july-monthly-update.md
> +On July 31st [Chris Manson](https://twitter.com/real_ate/) will be speaking about [Empress](https://github.com/hodgesmr/Empress), the bootstrapped blogging template that leverages EmberJS and Github,
So that link isn't the Empress that I'm working on 😂 (but thanks for pointing out the name clash, I'll reach out to them now) 

The Official Empress is over here: https://github.com/empress and I would use the following as a short intro: "speaking about Empress, which is the technology behind [empress-blog](https://github.com/empress/empress-blog) and [Guidemaker](https://github.com/empress/guidemaker) which powers the current Ember guides" 

Feel free to rephrase as you see fit

2019-07-22 12:24 UTC, marcoow requested changes

2019-07-22 12:24 UTC, marcoow commented on _posts/2019-07-23-july-monthly-update.md
> +Welcome to the fourth installment of our monthly update. This one is  later than expected but still packed with all the events and activities that have been happening at simplabs along with the thing
```suggestion
Welcome to the fourth installment of our monthly update. This one is later than expected but still packed with all the events and activities that have been happening at simplabs along with the things we're looking forward to. Enjoy.
```

2019-07-22 12:24 UTC, marcoow commented on _posts/2019-07-23-july-monthly-update.md
> +#### New simplabs website
```suggestion
### New simplabs website
```

2019-07-22 12:24 UTC, marcoow commented on _posts/2019-07-23-july-monthly-update.md
> +#### New blog post from Tobias Bieniek
```suggestion
### New blog post from Tobias Bieniek
```

2019-07-22 12:24 UTC, marcoow commented on _posts/2019-07-23-july-monthly-update.md
> +#### New version of ember-intl-analyzer released
```suggestion
### New version of ember-intl-analyzer released
```

2019-07-22 12:24 UTC, marcoow commented on _posts/2019-07-23-july-monthly-update.md
> +#### Other news
```suggestion
### Other news
```

2019-07-22 12:24 UTC, marcoow commented on _posts/2019-07-23-july-monthly-update.md
> +#### EmberFest - October 17th & 18th
```suggestion
### EmberFest - October 17th & 18th
```

2019-07-22 12:24 UTC, marcoow commented on _posts/2019-07-23-july-monthly-update.md
> +#### Chris Manson at Leeds JS
```suggestion
### Chris Manson at Leeds JS
```

2019-07-22 12:24 UTC, marcoow commented on _posts/2019-07-23-july-monthly-update.md
> +#### Ember.js Berlin - Javascript for Beginners
```suggestion
### Ember.js Berlin - Javascript for Beginners
```

2019-07-22 12:24 UTC, marcoow commented on _posts/2019-07-23-july-monthly-update.md
> +#### Jessica Jordan at JSConfEU
```suggestion
### Jessica Jordan at JSConfEU
```

2019-07-22 12:24 UTC, marcoow commented on _posts/2019-07-23-july-monthly-update.md
> +#### Ricardo Mendes talking at Commit Porto
```suggestion
### Ricardo Mendes talking at Commit Porto
```

2019-07-22 12:24 UTC, marcoow commented on _posts/2019-07-23-july-monthly-update.md
> +#### Jessica speaking at FullStackCon London
```suggestion
### Jessica speaking at FullStackCon London
```

2019-07-22 12:24 UTC, marcoow commented on _posts/2019-07-23-july-monthly-update.md
> +We recently recreated our website in [Glimmer](https://glimmerjs.com/) which describes itself as "Fast and light-weight UI components for the web, with the attention to detail you've come to expect f
```suggestion
We recently recreated our website in [Glimmer.js](https://glimmerjs.com/), the fast and light-weight UI components library, based on Ember.js' rendering engine. We will have a blog post online going into more details soon.
```

2019-07-22 12:24 UTC, marcoow commented on _posts/2019-07-23-july-monthly-update.md
> +ember-intl-analyzer now has support or JS decorators and will warn about missing translations.
```suggestion
ember-intl-analyzer now has support for JS decorators and will warn about missing translations.
```

2019-07-22 12:24 UTC, marcoow commented on _posts/2019-07-23-july-monthly-update.md
> +#### EmberFest - October 17th & 18th
We should also be saying that the CfP closes on August 1st so people should get their submissions in now. Also we announced that https://twitter.com/chancancode will be speaking.

2019-07-22 12:24 UTC, marcoow commented on _posts/2019-07-23-july-monthly-update.md
> +On May 24th and 25th [Jessica Jordan](https://twitter.com/jjordan_dev) ran a very succcessful Javascript for beginners workshop. in Berlin.
actually @jessica-jordan @sdebarros and @mansona

2019-07-22 12:24 UTC, marcoow commented on _posts/2019-07-23-july-monthly-update.md
> +On May 24th and 25th [Jessica Jordan](https://twitter.com/jjordan_dev) ran a very succcessful Javascript for beginners workshop. in Berlin.
```suggestion
On May 24th and 25th [Jessica Jordan](https://twitter.com/jjordan_dev) ran a very succcessful Javascript for beginners workshop in Berlin.
```

2019-07-22 12:24 UTC, marcoow commented on _posts/2019-07-23-july-monthly-update.md
> +Day 1 was an installation party to make sure that everybody was set up for day 2 when attendees were guided through creating their first web application using EmberJS! The workshop is open to women a
Hm, this doesn't really make sense. Also, we should be saying that we'll do it again in the future.

2019-07-22 12:24 UTC, marcoow commented on _posts/2019-07-23-july-monthly-update.md
> +On the 1st of June [Jessica Jordan](https://twitter.com/jjordan_dev) spoke at [JSConfEU](https://2019.jsconf.eu/) with her talk "Crafting Comics for Literally Everyone" in which she highlighted how y
We should link here (1st video at the top): https://simplabs.com/talks/

2019-07-23 13:01 UTC, mrmrcoleman commented on _posts/2019-07-23-july-monthly-update.md
> +In other news [Chris Manson](https://twitter.com/real_ate/) and [Jen Weber](https://twitter.com/jwwweber/) released [another episode](https://twitter.com/real_ate/status/1126760948260204549) of 'May
Aha, ok understood. Will remove.

2019-07-23 13:04 UTC, mrmrcoleman commented on _posts/2019-07-23-july-monthly-update.md
> +Day 1 was an installation party to make sure that everybody was set up for day 2 when attendees were guided through creating their first web application using EmberJS! The workshop is open to women a
Ah my bad, I'll fix that now.

2019-07-23 14:03 UTC, mansona requested changes

2019-07-23 14:03 UTC, mansona commented on _posts/2019-07-23-july-monthly-update.md
> +And last but not least, [Jessica Jordan](https://twitter.com/jjordan_dev) spoke at [FullStackConf](https://skillsmatter.com/conferences/11213-fullstack-london-2019-the-conference-on-javascript-node-a
```suggestion
And last but not least, [Jessica Jordan](https://twitter.com/jjordan_dev) spoke at [FullStackConf](https://skillsmatter.com/conferences/11213-fullstack-london-2019-the-conference-on-javascript-node-and-internet-of-things) in London with her talk "Crafting Comics for Literally Everyone".
```
I never notice typos but I saw this when I was double checking my parts

2019-07-23 14:13 UTC, mansona approved these changes

2019-07-23 14:20 UTC, marcoow commented on _posts/2019-07-23-july-monthly-update.md
> +The CFP closes on August 1st so if you'd like to give a presentation remember to get your submission on time [here](https://cfp.emberfest.eu/events/emberfest-2019).
```suggestion
The CFP closes on August 1st so if you'd like to give a presentation remember to get your submission in on time [here](https://cfp.emberfest.eu/events/emberfest-2019).
```

?

2019-07-23 14:22 UTC, marcoow commented on _posts/2019-07-23-july-monthly-update.md
> +You can sign up [here.](https://simplabs.com/webinars/modern-web/)
```suggestion
You can sign up [here.](/webinars/modern-web/)
```

2019-07-23 14:34 UTC, marcoow approved these changes

2019-07-23 14:39 UTC, Turbo87 commented on _posts/2019-07-23-july-monthly-update.md
> +On August 12th at 6pm UTC+2 we're running a webinar to help forward-looking marketers understand recent changes in web technology and how they can be used to create incredible experiences for their u
`UTC+2` is hard to parse for me. can we replace that with `CEST`?

```suggestion
On August 12th at 6pm CEST we're running a webinar to help forward-looking marketers understand recent changes in web technology and how they can be used to create incredible experiences for their users.
```

2019-07-23 15:38 UTC, marcoow commented
@pichfl can you merge this once you're happy?

2019-07-23 15:43 UTC, pichfl commented
@marcoow I added the webinar ad to the post so it has little more color, but found that I need to fix a layout bug to do so. See #641 

Will rebase and publish once that is merged.

2019-07-23 15:51 UTC, marcoow commented on _posts/2019-07-23-july-monthly-update.md
> +[![Upcoming webinar - The ultimate marketers guide to modern web apps and why users are demanding more](/assets/images/posts/2019-07-23-july-monthly-update/simplabs-webinar-modern-web-apps-for-market
clicking on this takes me to the home page 🤔

2019-07-23 16:19 UTC, pichfl commented on _posts/2019-07-23-july-monthly-update.md
> +[![Upcoming webinar - The ultimate marketers guide to modern web apps and why users are demanding more](/assets/images/posts/2019-07-23-july-monthly-update/simplabs-webinar-modern-web-apps-for-market
Can reproduce. I think I uncovered an error in the way we handle internal links:

https://github.com/simplabs/simplabs.github.io/blob/c3d3099785a95c4e0e7de2a3b74331a3cc91cad0/src/ui/components/Simplabs/component.ts#L143-L147

that `target` in L147 should be `link`

2019-07-23 16:47 UTC, pichfl commented
As discussed with @mrmrcoleman we will publish this first thing tomorrow. Updating the date of the blog post.

2019-07-24 08:22 UTC, merged