Improve blog layout
mainmatter/mainmatter.com pull request #652
Opened 2019-07-26 09:20 UTC by pichfl

Closes #561

2019-07-26 10:26 UTC, marcoow requested changes
There's now a lot of whitespace between the excerpt and author info on each post on the list page:

<img width="621" alt="Bildschirmfoto 2019-07-26 um 12 23 15" src="https://user-images.githubusercontent.com/1510/61945436-3d532c80-afa0-11e9-86ee-43896addecbf.png">

There's also still too much whitespace between the tag and the title of the featured post on the list page:

<img width="810" alt="Bildschirmfoto 2019-07-26 um 12 24 10" src="https://user-images.githubusercontent.com/1510/61945460-5956ce00-afa0-11e9-8179-3faa942d395b.png">

Big pictures don't work on mobile:

<img width="803" alt="Bildschirmfoto 2019-07-26 um 12 25 24" src="https://user-images.githubusercontent.com/1510/61945550-8efbb700-afa0-11e9-89aa-6665b7be95e7.png">

Should there be a bit more space between the author info and the first paragraph on mobile?

<img width="349" alt="Bildschirmfoto 2019-07-26 um 12 25 53" src="https://user-images.githubusercontent.com/1510/61945579-a175f080-afa0-11e9-9778-fce86b6c54bc.png">

2019-07-26 10:33 UTC, marcoow commented on _posts/2018-07-24-from-spa-to-pwa.md
> +[Google Gears](<https://en.wikipedia.org/wiki/Gears_(software)>). Gears was
what does this change do?

2019-07-26 10:33 UTC, marcoow commented on lib/generate-blog/lib/templates/author/template.hbs
> +  <Header @active="blog" @noContent="true" />
Is there no [`hasBlock`](https://api.emberjs.com/ember/3.11/classes/Ember.Templates.helpers/methods/hasBlock?anchor=hasBlock) in Glimmer.js?

2019-07-26 10:33 UTC, marcoow commented on lib/generate-blog/lib/templates/author/template.hbs
> +        Blog<span class="typography.hidden">:</span>
Why do we need this hidden `:`?

2019-07-26 10:40 UTC, pichfl commented on _posts/2018-07-24-from-spa-to-pwa.md
> +[Google Gears](<https://en.wikipedia.org/wiki/Gears_(software)>). Gears was
Seems to be the way Prettier wants to escape that link as it contains parenthesis. I had run Prettier on these files by accident and must have missed that one when reverting.

2019-07-26 10:43 UTC, pichfl commented on lib/generate-blog/lib/templates/author/template.hbs
> +  <Header @active="blog" @noContent="true" />
None that I know of. Trying to use `hasBlock` inside a template halts rendering.

2019-07-26 10:44 UTC, pichfl commented on lib/generate-blog/lib/templates/author/template.hbs
> +        Blog<span class="typography.hidden">:</span>
It's not part of the design (ending a label in punctuation doesn't look quite as good) but part of the written semantics for screen readers.

2019-07-26 11:05 UTC, marcoow commented on _posts/2018-07-24-from-spa-to-pwa.md
> +[Google Gears](<https://en.wikipedia.org/wiki/Gears_(software)>). Gears was
ah ok 👍

2019-07-26 11:07 UTC, marcoow commented on lib/generate-blog/lib/templates/author/template.hbs
> +        Blog<span class="typography.hidden">:</span>
ah ok

2019-07-26 11:09 UTC, marcoow commented on lib/generate-blog/lib/templates/author/template.hbs
> +  <Header @active="blog" @noContent="true" />
Hm, this seems to add it though: https://github.com/glimmerjs/glimmer-vm/pull/112

2019-07-26 13:06 UTC, pichfl commented on lib/generate-blog/lib/templates/author/template.hbs
> +  <Header @active="blog" @noContent="true" />
😯 thanks for digging there. Turns out you have to use the helper like this: `{{#if (has-block)}}`.

2019-07-26 14:21 UTC, pichfl commented on lib/generate-blog/lib/templates/author/template.hbs
> +  <Header @active="blog" @noContent="true" />
While has-block exists, it doesn't seem to work 😞 it's always true, even for self closing invocations.

2019-07-26 14:47 UTC, marcoow commented on lib/generate-blog/lib/templates/author/template.hbs
> +  <Header @active="blog" @noContent="true" />
Isn't it a problem though that with this aproach we always have 2 `<header>` elements on all blog pages now?

<img width="474" alt="Bildschirmfoto 2019-07-26 um 16 41 33" src="https://user-images.githubusercontent.com/1510/61959692-3fc77d80-afc4-11e9-9331-4dcad9b650d7.png">

I guess if we have different scenarios for the `<Header>` component now it would make sense to break up the header and header content up like so

```js
<Header @active="services" />
  <HeaderContent @label="Services" @title="Full-Stack Engineering" />
</Header>
```

Then in the blog we could do something like this:

```js
<Header @active="blog" />
  <h1 class="typography.display">
      <small class="typography.small">
        Blog<span class="typography.hidden">:</span>
      </small>
      Posts by
      {{name}}
    </h1>
</Header>
```

I think the problem we have here (besides `has-block` not working correctly of course) is that the `<Header>` component is too big and not flexible enough for what we want.

2019-07-26 15:16 UTC, pichfl commented on lib/generate-blog/lib/templates/author/template.hbs
> +  <Header @active="blog" @noContent="true" />
The additional header doesn't hurt us semantically, we could even add an additional `<section>` to the blog to make the separation more distinct.

I agree on the Header being rather too big though, but I'm not sure ho to split it as it has to have some part of it's markup for the navigation to work as expected.

2019-07-26 15:22 UTC, marcoow commented on lib/generate-blog/lib/templates/author/template.hbs
> +  <Header @active="blog" @noContent="true" />
So what I'm suggesting is to move

```hbs
<div class="content" state:flex-content={{@flex-content}}>
  {{#if @title}}
    <h1 class="typography.display">
      {{#if @label}}
        <small class="typography.small">
          {{@label}}<span class="typography.hidden">:</span>
        </small>
      {{/if}}
      {{@title}}
    </h1>
  {{/if}}
  {{yield}}
</div>
```

into a new `<HeaderContent>` component so we'd call the header as

```hbs
<Header @active="services" />
  <HeaderContent @label="Services" @title="Full-Stack Engineering" />
</Header>
```

in most cases while in the blog we do:

```hbs
<Header @active="blog" />
  <h1 class="typography.display">
    <small class="typography.small">
      Blog<span class="typography.hidden">:</span>
    </small>
    Posts by
    {{name}}
  </h1>
</Header>
```

The `<navbar>` can remain in the header as we **always** want that - we're only moving the part out that we only want in most but not all cases.

2019-07-26 15:36 UTC, ghislaineguerin approved these changes

2019-07-26 15:41 UTC, pichfl commented on lib/generate-blog/lib/templates/author/template.hbs
> +  <Header @active="blog" @noContent="true" />
The problem here is that this will still nest the contents that need to be after the header into the header. Doing that will make it much harder to use the existing CSS grid to layout the author badge. I think it's time for me to make a small codepen to test this out.

2019-07-30 12:36 UTC, pichfl commented
@marcoow can we consider merging this right now and make a separate issue for the header refactoring?

2019-07-30 14:19 UTC, marcoow commented
We could do that but I'd say we should work on that right away then and leave #561 open as well. I'd say during the course of working on this we discovered the current structure doesn't really support this scenario and thus is the refactoring now part of this issue as it is required to resolve it properly.

2019-07-30 15:17 UTC, pichfl commented
Good point. Went ahead and refactored as suggested.

2019-07-31 09:38 UTC, marcoow requested changes
Looks good - there's only 1 thing left: there's still too much vertical spacing between the excerpt and the author and date on the blog index:

<img width="629" alt="Bildschirmfoto 2019-07-31 um 11 16 35" src="https://user-images.githubusercontent.com/1510/62201434-b3340b00-b387-11e9-962c-7b07e1ab5846.png">

2019-07-31 14:28 UTC, marcoow approved these changes

2019-07-31 14:28 UTC, merged