Better handling of title tag and related meta tags
mainmatter/mainmatter.com pull request #662
Opened 2019-07-30 19:37 UTC by marcoow

This is a bit of cleanup related to the work on #627. Previously we were setting the title tag and related tags in the `Simplabs` component's source which meant we had to have the title etc. in the route map. As we're aiming to have more page-component specific meta tags like `meta[name="description"]` with that solution we would have had all these tags and their content in the routes map as well which would have gotten messy quickly and would have grown the JSON we're injecting in every page to get the route map into the running app quite a bit. With this approach we're simply using the  new `<HeadTag>` component to render tags in the `<head>` which we can invoke from any template - that way we get the same  functionality but can keep all of the tags attributes and content in the templates where it belongs.

2019-07-30 22:06 UTC, pichfl requested changes
Small nitpick, but I hope it would be worth the change.

2019-07-30 22:06 UTC, pichfl commented on src/ui/components/Header/template.hbs
> +  <HeadTag @name="title" @content={{this.pageTitle}} />
`documentTitle` would be more idiomatic considering the browser and web api in general

2019-07-31 08:36 UTC, marcoow commented on src/ui/components/Header/template.hbs
> +  <HeadTag @name="title" @content={{this.pageTitle}} />
yep, good point - changed 👍

2019-07-31 10:29 UTC, pichfl commented
The blog index somehow lost its headline.

2019-07-31 10:32 UTC, marcoow commented
@pichfl yes, fixed that already

2019-07-31 10:47 UTC, pichfl approved these changes

2019-07-31 10:47 UTC, merged