Add open graph images
mainmatter/mainmatter.com pull request #699
Opened 2019-08-26 10:51 UTC by ghislaineguerin

Closes #421

2019-08-26 11:31 UTC, ghislaineguerin commented
@pichfl The og:image property is still showing blank content. Do you have any idea why?

2019-08-27 06:45 UTC, marcoow requested changes
* public/assets/images/posts/2018-12-10-assert-your-style/og-image.png 

The post isn't really about Percy - I think the best fit for the logo might be the CSS logo https://www.google.com/search?q=css+logo&client=safari&rls=en&source=lnms&tbm=isch&sa=X&ved=0ahUKEwjwhuTLuaLkAhUEPFAKHWdAAgsQ_AUIESgB&biw=1250&bih=706 - @jessica-jordan what do you think?

Overall the images look pretty big both in terms of dimensions and in terms of file size. If we need these dimensions (I guess there's some kind of spec or best practice), can we run them through ImageOptim?

2019-08-27 08:22 UTC, ghislaineguerin commented
@marcoow I am using the default size for open graph but saving as 2x for retina displays, not sure if this is necessary so I will look into that. I agree that we must optimize them.
As for the logo, I can switch that to a CSS one.

2019-08-27 09:45 UTC, marcoow requested changes
public/assets/images/posts/2018-07-24-from-spa-to-pwa/og-image.png 

I think that images needs to be run through ImageOptim.

Also 1 more thing that needs to be changed: we don't want the og images to end up in the service worker and should exclude them here: https://github.com/simplabs/simplabs.github.io/blob/master/lib/service-workers/lib/worker-builder.js#L36 - I can do that

2019-08-27 10:03 UTC, marcoow commented
@ghislaineguerin I made the fixes for the service worker

2019-08-27 10:12 UTC, marcoow requested changes

2019-08-27 10:12 UTC, marcoow commented on lib/generate-blog/lib/templates/post/template.hbs
> +  <HeadTag @name='meta' @keys=\{{hash property="og:image"}} @values=\{{hash content="{{og.image}}"}} />
I assume this needs to be an absolute URL

2019-08-27 10:44 UTC, ghislaineguerin commented
@marcoow I've run the images through img optim. I will try again and see if it makes a difference.

2019-08-27 11:47 UTC, marcoow commented on lib/generate-blog/lib/templates/post/template.hbs
> +  <HeadTag @name='meta' @keys=\{{hash property="og:image"}} @values=\{{hash content="{{og.image}}"}} />
I fixed it

2019-08-27 11:48 UTC, marcoow approved these changes

2019-08-27 12:02 UTC, merged