Remove EmberFest 2019 card from upcoming events
mainmatter/mainmatter.com pull request #730
Opened 2019-10-24 17:25 UTC by pichfl

Drops upcoming events from various pages.

Re #726

2019-10-28 20:34 UTC, marcoow requested changes
The build fails. We should really replace this with some new content anyway though.

2019-10-30 11:33 UTC, marcoow requested changes

2019-10-30 11:33 UTC, marcoow commented on src/ui/components/CardEmberSponsors/template.hbs
> +    of the Ember.js project along with international brands like LinkedIn and Apple.
```suggestion
    of the Ember.js project along with international brands like LinkedIn and Yahoo.
```

Apple is not a sponsor of the project.

2019-10-30 11:33 UTC, marcoow commented on src/ui/components/CardEmberSponsors/template.hbs
> +    </a>
The link displays as `block`:

<img width="431" alt="Bildschirmfoto 2019-10-30 um 12 29 02" src="https://user-images.githubusercontent.com/1510/67854616-eca81e00-fb10-11e9-8907-bda01ae3e2c6.png">

2019-10-30 11:33 UTC, marcoow commented on src/ui/components/CardEmberSponsors/template.hbs
> +    We have been recognized as official
```suggestion
    We recently have been recognized as an official
```

2019-10-30 11:33 UTC, marcoow commented on src/ui/components/CardEmberSponsors/template.hbs
> +      sponsors
```suggestion
      sponsor
```

2019-10-30 11:33 UTC, marcoow commented on src/ui/components/PageWhySimplabs/template.hbs
> -  </div>
This breaks the layout:

<img width="1456" alt="Bildschirmfoto 2019-10-30 um 12 31 39" src="https://user-images.githubusercontent.com/1510/67854787-3d1f7b80-fb11-11e9-8fb4-3d377b5ce7d9.png">

2019-10-30 11:33 UTC, marcoow commented on src/ui/components/PageWhySimplabs/template.hbs
> -  </div>
I guess we could maybe use the playbook sidebar teaser here?

2019-10-30 11:33 UTC, marcoow commented on src/ui/components/PageWhySimplabs/template.hbs
> -  </div>
Or maybe even better we can create a teaser saying we co-organize EmberFest (which could also resolve #448 )?

2019-10-30 11:43 UTC, pichfl commented on src/ui/components/PageWhySimplabs/template.hbs
> -  </div>
I like that second idea 👍

2019-11-05 08:34 UTC, marcoow commented
@pichfl any progresso on this? We still have the _"Meet us at EmberFest"_ on the site, almost 3 weeks after the event.

2019-11-06 08:22 UTC, marcoow requested changes
There's one new little thing and one open and yet unaddressed issues from before.

2019-11-06 08:22 UTC, marcoow commented on src/ui/components/PageWhySimplabs/template.hbs
> +        We organize EmberFest, the European Community Ember Conference.
```suggestion
        We co-organize EmberFest, the European Community Ember Conference.
```

2019-11-06 11:05 UTC, pichfl commented on src/ui/components/CardEmberSponsors/template.hbs
> +    of the Ember.js project along with international brands like LinkedIn and Apple.
🤦‍♂  of course. I was thinking in terms of usage, which do not apply here.

2019-11-06 11:26 UTC, marcoow approved these changes
only CI left to fix

2019-11-06 13:15 UTC, merged