WIP: oss post
mainmatter/mainmatter.com pull request #737
Opened 2019-10-29 18:06 UTC by jessica-jordan

2019-10-30 09:42 UTC, marcoow commented
@jessica-jordan the build failed - you can run `yarn format` to fix the markdown formatting

2019-10-30 10:28 UTC, jessica-jordan commented
@marcoow Sounds good and thank you for the heads up! I want to take care of the formatting once the reviews are in and this is already good to be merged :+1:

2019-10-30 11:01 UTC, marcoow reviewed
Awesome post @jessica-jordan 🎉 

I only have 2 points:

* I wonder why you're using the more scientific way of linking to sources over just regular inline links? Of course the post is kind of scientific (and that's cool), I just thought regular links might be easier for the reader?
* One point about contributing back that I think is important as well is that when you're relying on a particular open source project for your product or whatever you have a strong interest of this project being sustainable, evolve and not get abandoned and by contributing, companies can help keeping a project alive, in good shape etc. Maybe that's something to consider adding.

2019-10-30 11:01 UTC, marcoow commented on _posts/2019-10-30-why-companies-invest-in-oss.md
> +This blog post highlights on which levels contribution to open-source provides value to businesses and demonstrates why paying your team to spend time on OSS might be the best business decision you w
pretty catchy intro 💣

2019-10-30 11:01 UTC, marcoow commented on _posts/2019-10-30-why-companies-invest-in-oss.md
> +## Investment in OSS Is an Investment in Team Development
```suggestion
## Investment in OSS is an Investment in Team Development
```

2019-10-30 11:01 UTC, marcoow commented on _posts/2019-10-30-why-companies-invest-in-oss.md
> +Finally, when following an intrinsic motivation to contribute to OSS, engineering teams can benefit from open-source work in regards to well-being. Apart from an investment into their own professiona
```suggestion
Finally, when following an intrinsic motivation to contribute to OSS, engineering teams can benefit from open-source work in regards to well-being. Apart from an investment into their own professional capital by widening their skill set, participation in OSS communities oftentimes has altruistic motives - the ambition to give back to the community from which developers already have benefitted. A sense of belonging to a particular OSS community and wanting to be an active part of it as well as the recognition by community peers are driving factors for OSS contributions to developers [[6](https://aisel.aisnet.org/cgi/viewcontent.cgi?article=1559&context=jais)].
```

2019-10-30 11:01 UTC, marcoow commented on _posts/2019-10-30-why-companies-invest-in-oss.md
> +The 20% time method allocates a fifth of an engineer's compensated working time for open-source projects and related activities, including development, community management, writing technical blog po
```suggestion
The 20% time method allocates a fifth of an engineer's compensated working time for open-source projects and related activities, including development, community management or writing blog posts. At simplabs we ensure that each IT and design professional has access to 20% time and makes use of it on a weekly basis: this boils down to 4 days of client work and 1 day of 20% time in a regular work week. Projects that our consultants work on generate tangible outcomes which are shared with the team or the wider open-source community regularly; as addon releases, blog posts, newsletter or workshop materials.
```

2019-10-30 11:01 UTC, marcoow commented on _posts/2019-10-30-why-companies-invest-in-oss.md
> +If you have any questions on how to get started with contributing to open-source at your company, [send us a message](https://simplabs.com/contact/). You can also book our [contributor workshop for y
> You can also book our contributor workshop for your engineering team

This sounds a bit like we had a concrete offering that is then not to be found on the linked page. Maybe this should be rephrased slightly to be more general, e.g. _"You can also book a workshop for your engineering team to get started contributing…"_ or something like that.

2019-10-30 12:54 UTC, arthurp1 reviewed
@jessica-jordan Great blog post that is very relevant for a tech and non-tech audience! The amount of references to external sources are great as well. See my comments for suggestions.

2019-10-30 12:54 UTC, arthurp1 commented on _posts/2019-10-30-why-companies-invest-in-oss.md
> +Even though the open-source development model can be applied to many different types of products, this post will only focus on the open-source development of **software** (OSS) specifically.
You could alternatively use 'I will...'  instead of 'This post will...'. -  it will make it sound more personal.

2019-10-30 12:54 UTC, arthurp1 commented on _posts/2019-10-30-why-companies-invest-in-oss.md
> +title: "Why Companies Invest In OSS"
I suggest to use 'Open Source'  or 'Open Source Software (OSS)' instead of just 'OSS', as open source is a better keyword to rank for and clearer for people that don't directly know what OSS means. Alternative titles that might give higher click through rates on social media and google:

"Why Companies Invest In Open Source Software (OSS), and Yours Should Too" OR
"Why Software Companies Should Invest in Open Source"

Not sure if these alternative titles suit our tone of voice.

2019-10-30 12:54 UTC, arthurp1 commented on _posts/2019-10-30-why-companies-invest-in-oss.md
> +The so-called **OSS acquisition** [[3](https://core.ac.uk/reader/41824081)]- the mere usage of OSS  - has already established itself as a commonly accepted practice for businesses since the rewards a
It's not fully clear if OSS acquisition is a new concept you are introducing here or just means 'contributing to OSS'. If it's something different it would be good to define it here directly.

2019-10-30 12:54 UTC, arthurp1 commented on _posts/2019-10-30-why-companies-invest-in-oss.md
> +As active members of OSS communities, developers may hone their **organisational skill set** by managing open-source projects, collaborating with globally distributed teams both online and offline an
I suggest to use 'open source communities' instead of 'OSS communities' as it might be a better keyword that people search for.

2019-10-30 12:54 UTC, arthurp1 commented on _posts/2019-10-30-why-companies-invest-in-oss.md
> +As a consulting company, **simplabs** also operates under time and project constraints. Still, open-source is at the heart of our company's work and besides contributing to EmberJS via our core team
Should we add that we also maintain packages for Ruby and Elixir? That we're founding sponsors of the Erlang Ecosystem Foundation might be less relevant?

2019-10-30 12:54 UTC, arthurp1 commented on _posts/2019-10-30-why-companies-invest-in-oss.md
> +The 20% time method allocates a fifth of an engineer's compensated working time for open-source projects and related activities, including development, community management, writing technical blog po
Maybe we could also mention the benefits of all the other types of community contributions in their 20% time. Or use simplabs as an example.
- Visiting and giving talks at major international tech conferences including EmberConf, ReactiveConf and JSConf.eu. Many developers value time spend among their peers and sharing their work.
- Writing blog posts about the open source work we do are good for our companies visibility on social media and Google search.
- Giving back feels good. Organizing conferences and meetups. Simplabs co-organizes the EmberFest conference and a number of meetups. Supporting RailsGirls for years, run workshops series teaching women to code in Ember.js

2019-10-30 12:54 UTC, arthurp1 commented on _posts/2019-10-30-why-companies-invest-in-oss.md
> +## If Your Business Contributes to OSS, You Are in Good Company
It would be good to have a quote (or case) of a famous business or simplabs, saying that investing in open source is actually worth it. Also doing some name dropping or giving examples how some companies are benefitting hugely from open source (Google/Facebook?)

2019-10-30 12:54 UTC, arthurp1 commented on _posts/2019-10-30-why-companies-invest-in-oss.md
> +## So Should You Pay Your Team to Work on OSS?
I miss the costs and downsides of doing open source. Or counter arguments against the earlier mentioned perceived downsides of OSS integration: Less productivity, missed project deadlines and wasted money.

2019-10-30 12:54 UTC, arthurp1 commented on _posts/2019-10-30-why-companies-invest-in-oss.md
> +The 20% time method allocates a fifth of an engineer's compensated working time for open-source projects and related activities, including development, community management, writing technical blog po
Another big benefit for simplabs has been hiring developers next to retention. For B2B companies that have as market other software companies it also helps with brand awareness and client acquisition, like for simplabs.

2019-10-30 12:54 UTC, arthurp1 commented on _posts/2019-10-30-why-companies-invest-in-oss.md
> +## So Should You Pay Your Team to Work on OSS?
Maybe we could do a cost benefit analysis of investing in open source integration as a conclusion. Either as text or as infographic which could also be a nice image for this blog post.

2019-10-30 12:54 UTC, arthurp1 commented on _posts/2019-10-30-why-companies-invest-in-oss.md
> +## If Your Business Contributes to OSS, You Are in Good Company
Why are so many businesses doing it, and others not?

2019-10-30 14:51 UTC, jessica-jordan commented on _posts/2019-10-30-why-companies-invest-in-oss.md
> +## Investment in OSS Is an Investment in Team Development
I'd like to have my titles in title case and according to [this website](https://titlecase.com/) it's this writing style indeed:

```Investment in OSS Is an Investment in Team Development```

2019-10-30 15:07 UTC, marcoow commented on _posts/2019-10-30-why-companies-invest-in-oss.md
> +## Investment in OSS Is an Investment in Team Development
Ok, was assuming it'd be lowercase as _"in"_, _"an"_ etc. are lowercase as well.

2019-10-30 15:18 UTC, jessica-jordan commented on _posts/2019-10-30-why-companies-invest-in-oss.md
> +If you have any questions on how to get started with contributing to open-source at your company, [send us a message](https://simplabs.com/contact/). You can also book our [contributor workshop for y
Yes that makes sense and sounds good :+1:

2019-10-30 15:21 UTC, jessica-jordan commented on _posts/2019-10-30-why-companies-invest-in-oss.md
> +This blog post highlights on which levels contribution to open-source provides value to businesses and demonstrates why paying your team to spend time on OSS might be the best business decision you w
🙇‍♀

2019-10-30 15:25 UTC, jayjayjpg commented on _posts/2019-10-30-why-companies-invest-in-oss.md
> +title: "Why Companies Invest In OSS"
Sounds good, I can update it to:

```
Why Companies Invest In Open-Source and Why Yours Should, Too
```

2019-10-30 15:26 UTC, jessica-jordan commented on _posts/2019-10-30-why-companies-invest-in-oss.md
> +The so-called **OSS acquisition** [[3](https://core.ac.uk/reader/41824081)]- the mere usage of OSS  - has already established itself as a commonly accepted practice for businesses since the rewards a
I tried to explain it with the hyphenated comment (`The so-called **OSS acquisition** [[3](https://core.ac.uk/reader/41824081)]- the mere usage of OSS  -`) but I can make it more clear with a separate sentence :+1:

2019-10-30 15:50 UTC, jessica-jordan commented on _posts/2019-10-30-why-companies-invest-in-oss.md
> +As a consulting company, **simplabs** also operates under time and project constraints. Still, open-source is at the heart of our company's work and besides contributing to EmberJS via our core team
I couldn't find so many actively maintained Ruby and Elixir packages in our Github repo, so I'd rather stick to mention the JavaScript ones here as they seem to be our open-source focus recently. What do you think?

2019-10-30 15:51 UTC, jessica-jordan commented on _posts/2019-10-30-why-companies-invest-in-oss.md
> +The 20% time method allocates a fifth of an engineer's compensated working time for open-source projects and related activities, including development, community management, writing technical blog po
I think both points make a lot of sense, I will try and expand on that :+1:

2019-10-30 15:58 UTC, jessica-jordan commented on _posts/2019-10-30-why-companies-invest-in-oss.md
> +## If Your Business Contributes to OSS, You Are in Good Company
I think in the context of this blog post, I'd find it better to leave the question open to the reader why a particular group of companies decides to invest in open-source and another large group of businesses decides against it. I believe the post already shows well why we at simplabs do it (and as you said we could expand more on the aspect of e.g. brand awareness and client acquisition, too to emphasize the benefits for simplabs even more) and the readers might come to the conclusion themselves why what works for us might also work for them. including a quote from a company like Google or Facebook to make a point that in itself can already be argued well on its own feels a bit off to me

What are your thoughts?

2019-10-30 16:00 UTC, jessica-jordan commented on _posts/2019-10-30-why-companies-invest-in-oss.md
> +## So Should You Pay Your Team to Work on OSS?
I could definitely add a section with a few counter arguments against contributing to OSS, but I have the feeling a cost benefit analysis exceeds my competence as a business analyst and possibly also the scope of this blog post. What are your thoughts?

2019-10-30 16:09 UTC, marcoow commented on _posts/2019-10-30-why-companies-invest-in-oss.md
> +As a consulting company, **simplabs** also operates under time and project constraints. Still, open-source is at the heart of our company's work and besides contributing to EmberJS via our core team
We could also be saying _"…we maintain over a dozen tools and libraries for JavaScript and other languages which are well-adopted in the open-source community…"_ - we have https://github.com/simplabs/rails_api_auth and https://github.com/simplabs/breethe-server at least…

2019-10-31 14:37 UTC, jessica-jordan commented on _posts/2019-10-30-why-companies-invest-in-oss.md
> +## So Should You Pay Your Team to Work on OSS?
i added another section on the cost factor of OSS with a few arguments against contributions further above :+1:

2019-10-31 15:40 UTC, jayjayjpg commented
@marcoow @arthurp1 Thank you for all the suggestions - I updated the post according to your comments so far and am ready to update the post's date once this is ready for release from your side :+1:

2019-10-31 19:05 UTC, marcoow commented
@jessica-jordan any feedback on https://github.com/simplabs/simplabs.github.io/pull/737#pullrequestreview-309096314 ?

I'd like @pichfl and @ghislaineguerin to get involved as well and the 3 of you to discuss where/how we could add some graphics of any kind maybe to make this visually more exciting. That should always be the last step before releasing a post now - content is king of course but I think we should make sure we're adding visual elements if we can so in particular long posts like this are easier to read for visitors.

2019-10-31 19:26 UTC, jessica-jordan commented
@marcoow Sounds good and in regards to the previous comments:

> I wonder why you're using the more scientific way of linking to sources over just regular inline links? Of course the post is kind of scientific (and that's cool), I just thought regular links might be easier for the reader?

I prefer this way of quoting and would like to try it out in the scope of this blog post. Does this work for you, too?

> One point about contributing back that I think is important as well is that when you're relying on a particular open source project for your product or whatever you have a strong interest of this project being sustainable, evolve and not get abandoned and by contributing, companies can help keeping a project alive, in good shape etc. Maybe that's something to consider adding.

That's a good point, too and I added another note about companies wanting to either open-source internal software or contribute to projects that are also of interest to themselves and other companies in the "cost vs benefit" section of the post. I think this should imply that companies have an inherent interest in keeping projects alive and maintaining them and I would like this to suffice. Also personally, I do not want to make this post longer since I already spent a lot of hours writing it and I already feel very happy with it. I'd be happy to see anyone else elaborating further on this point in their own blog post anytime though if someone feels up for it!

> I'd like @pichfl and @ghislaineguerin to get involved as well and the 3 of you to discuss where/how we could add some graphics of any kind maybe to make this visually more exciting. That should always be the last step before releasing a post now - content is king of course but I think we should make sure we're adding visual elements if we can so in particular long posts like this are easier to read for visitors.

@pichfl @ghislaineguerin I'm happy with any suggestion that you have and don't have any specific preferences to any particular imagery. If you have any illustration ideas for the post, feel free to ping me and/or send a PR to this feature branch anytime - thank you!

2019-11-08 08:48 UTC, ghislaineguerin commented
@marcoow @jessica-jordan  should I include the illustrations on this same PR?

2019-11-08 08:53 UTC, jessica-jordan commented
> @marcoow @jessica-jordan should I include the illustrations on this same PR?
@ghislaineguerin That'd be super :+1:

2019-11-08 09:58 UTC, ghislaineguerin commented
@pichfl could you take a look at the last commit? We currently don't have full width image option for before the break. I think this is blocked until we have that?

2019-11-08 10:03 UTC, pichfl commented
@ghislaineguerin we can not have an image before the break. Content before the break is used on the overview pages and handled differently, I can not recommend putting an image there.

2019-11-08 10:12 UTC, jessica-jordan commented on _posts/2019-10-30-why-companies-invest-in-oss.md
> +[![team benefits open source investment](/assets/images/posts/2019-10-30-why-companies-invest-in-oss/oss-team-investment-illustration.png)]()
One thing I noticed is that the images are currently rendered as links:

```
<a href="" target="_blank" rel="noopener" class="">
  <img src="/assets/images/posts/2019-10-30-why-companies-invest-in-oss/oos-illustration.png" alt="invest time open source illustration" class="">
</a>
```
Is this intended? If not, I think the markup would be

```suggestion
![team benefits open source investment](/assets/images/posts/2019-10-30-why-companies-invest-in-oss/oss-team-investment-illustration.png)
```

What are your thoughts?

2019-11-08 10:13 UTC, marcoow requested changes

2019-11-08 10:13 UTC, marcoow commented on _posts/2019-10-30-why-companies-invest-in-oss.md
> +[![invest time open source illustration](/assets/images/posts/2019-10-30-why-companies-invest-in-oss/oos-illustration.png)]()
I don't think this is the correct syntax - there are links on the images with this: https://deploy-preview-737--objective-northcutt-37494c.netlify.com/blog/2019/10/30/why-companies-invest-in-oss/

2019-11-08 10:13 UTC, jessica-jordan commented on _posts/2019-10-30-why-companies-invest-in-oss.md
> +[![invest time open source illustration](/assets/images/posts/2019-10-30-why-companies-invest-in-oss/oos-illustration.png)]()
To be able to render this as an image without a wrapper `a` tag, I think it'd be:

```suggestion
![invest time open source illustration](/assets/images/posts/2019-10-30-why-companies-invest-in-oss/oos-illustration.png)
```

What do you think?

2019-11-08 10:51 UTC, pichfl commented on _posts/2019-10-30-why-companies-invest-in-oss.md
> +[![invest time open source illustration](/assets/images/posts/2019-10-30-why-companies-invest-in-oss/oos-illustration.png)]()
Yes, the link is not necessary. I just made it possible for posts to be more designed and provided a way to remove the border and background color from the figure element, see my changes.

2019-11-08 10:52 UTC, pichfl commented on _posts/2019-10-30-why-companies-invest-in-oss.md
> +[![invest time open source illustration](/assets/images/posts/2019-10-30-why-companies-invest-in-oss/oos-illustration.png)]()
It isn't. With my recent edit we also have a way to span this image the full page width.

2019-11-08 10:54 UTC, ghislaineguerin commented
@pichfl it looks great 👍

2019-11-08 11:25 UTC, marcoow requested changes
post looks great - can we only move the JS/CSS changes into a separate PR please?

see https://github.com/simplabs/playbook/tree/master/workflow/engineering#feature-branchespull-requests

2019-11-08 11:32 UTC, pichfl commented
Will extract.

2019-11-08 11:58 UTC, pichfl commented
@marcoow done, see #743

2019-11-08 12:45 UTC, marcoow approved these changes

2019-11-08 12:55 UTC, jessica-jordan commented on _posts/2019-10-30-why-companies-invest-in-oss.md
> +[![invest time open source illustration](/assets/images/posts/2019-10-30-why-companies-invest-in-oss/oos-illustration.png)]()
```suggestion
![invest time open source illustration](/assets/images/posts/2019-10-30-why-companies-invest-in-oss/oos-illustration.png#full)
```

2019-11-08 12:56 UTC, jessica-jordan commented on _posts/2019-10-30-why-companies-invest-in-oss.md
> +[![team benefits open source investment](/assets/images/posts/2019-10-30-why-companies-invest-in-oss/oss-team-investment-illustration.png)]()
```suggestion
![team benefits open source investment](/assets/images/posts/2019-10-30-why-companies-invest-in-oss/oss-team-investment-illustration.png)
```

2019-11-11 13:00 UTC, merged

2019-11-12 11:52 UTC, marcoow commented
@pichfl @ghislaineguerin I just realized we didn't add an `og:image` for this post (see https://app.abstract.com/projects/c2d6fda0-836d-4507-92b5-635b3e333b4d/branches/master/files/322C962E-9A7E-45DA-B2F2-E7D76C3DF85A) - can you add one please and add that to your design checklist for blog posts so we don't forget again?

2019-11-12 12:09 UTC, ghislaineguerin commented
@marcoow I'll add this.