Wording fixes
mainmatter/mainmatter.com pull request #75
Opened 2017-03-14 14:33 UTC by marcoow

This fixes and improves some of the wording on simplabs.com

2017-03-14 16:10 UTC, Turbo87 commented on about/index.html
> +          <h3>International Engineering</h3>
"International Engineering" sounds a little strange. I think I'd keep the previous title here.

2017-03-14 16:10 UTC, Turbo87 commented on about/index.html
> +          <p>Our team will regularly be present at <strong>international conferences</strong>. We give talks, engage in the community and help by sponsoring conferences like <a href="http://emberconf
"Our team is regularly present ..."

2017-03-14 16:10 UTC, Turbo87 commented on about/index.html
> +          <p>Our team will regularly be present at <strong>international conferences</strong>. We give talks, engage in the community and help by sponsoring conferences like <a href="http://emberconf
"local user groups"

2017-03-14 16:10 UTC, Turbo87 commented on clients/index.html
> +        <p>We have a track record of <strong>projects for international clients</strong> from small startups to big enterprises.</p>
I like the old wording better here

2017-03-14 16:10 UTC, Turbo87 commented on trainings/index.html
> +          <p>We offer a <strong>variety of Developer Trainings</strong> to help teams advance their skills in many frontend and backend topics. Professional Developer trainings can <strong>dramatical
> we're usually told between 8% and 20%

can that actually be quantified like this? I'd probably leave that part out

2017-03-14 16:10 UTC, Turbo87 commented on work/index.html
> +          <p><strong>Ember.js, Phoenix and Ruby on Rails</strong> are what we work with most of the time. The <strong>conventional approach</strong> that they all share make them a great fit for succ
"once we left" sounds strange, I'd probably leave that part out.

2017-03-14 16:10 UTC, Turbo87 commented on work/index.html
> +          <p>We will however choose whatever technology is best suited to get a particular job done, which in some cases might not be one of the above three. We keep our eyes open and <strong>love to
"love to explore" -> "love exploring"

2017-03-14 16:10 UTC, Turbo87 commented on work/index.html
> +          <p>We are <strong>enthusiastic about agile practices</strong> and a flexible development process. While we don't think planning is evil per se, <strong>we don't overplan and aim to keep the
"on the same page and from that continue with one or two week" -> "on the same page and continue with one or two week"

2017-03-14 16:17 UTC, marcoow commented on about/index.html
> +          <h3>International Engineering</h3>
Hm, we're actually more international than bavarian though - both in terms of team as well as in terms of clients.

2017-03-14 16:19 UTC, marcoow commented on clients/index.html
> +        <p>We have a track record of <strong>projects for international clients</strong> from small startups to big enterprises.</p>
I think it's important though to mention we work for international clients - people might have the feeling we're a local german company while that's not actually the case. If we leave _"successful"_ in, the text is actually too long and breaks into 3 lines which doesn't work with the current layout. Also we shouldn't have to say the projects were successful?

2017-03-14 16:20 UTC, marcoow commented on trainings/index.html
> +          <p>We offer a <strong>variety of Developer Trainings</strong> to help teams advance their skills in many frontend and backend topics. Professional Developer trainings can <strong>dramatical
That's taken from https://mike.works actually. I think it's important to explain why investments in trainings are almost always worth the money but there might be better ways to do that of course…

2017-03-14 16:21 UTC, marcoow commented on work/index.html
> +          <p><strong>Ember.js, Phoenix and Ruby on Rails</strong> are what we work with most of the time. The <strong>conventional approach</strong> that they all share make them a great fit for succ
I think this is an important point though - explain why clients don't depend on us forever which is usually one of the biggest fears when hiring an external consultancy. Maybe there's a better way to put it?

2017-03-14 16:23 UTC, marcoow commented on work/index.html
> +          <p>We are <strong>enthusiastic about agile practices</strong> and a flexible development process. While we don't think planning is evil per se, <strong>we don't overplan and aim to keep the
What about _"get everybody on the same page and then iterate in one or two week long sprints"_?

2017-03-14 16:56 UTC, Turbo87 commented on about/index.html
> +          <h3>International Engineering</h3>
sure. but you'd also label something "Made in Germany" even if 90% were produced in Asia :P

2017-03-14 16:57 UTC, Turbo87 commented on clients/index.html
> +        <p>We have a track record of <strong>projects for international clients</strong> from small startups to big enterprises.</p>
yeah, maybe it's just because of seeing the diff that I missed the "successful"

2017-03-15 11:40 UTC, oliverbarnes requested changes

2017-03-15 11:40 UTC, oliverbarnes commented on _config.yml
> +  - title: Trainings
Training, singular

2017-03-15 11:40 UTC, oliverbarnes commented on about/index.html
> +          <h3>International Engineering</h3>
I see Tobi's point, but I think stating the company is based in Munich gets the point across

2017-03-15 11:40 UTC, oliverbarnes commented on services/index.html
> +          <p>We offer consulting services to <strong>help clients to successfully implement their own projects</strong> based on decisions and designs that we help make and validate.</p>
`help clients successfully` is better, I think - the `to` isn't needed

2017-03-15 11:40 UTC, oliverbarnes commented on work/index.html
> +          <p><strong>Ember.js, Phoenix and Ruby on Rails</strong> are what we work with most of the time. The <strong>conventional approach</strong> that they all share make them a great fit for succ
"once we leave" or "once we have left"

2017-03-15 17:03 UTC, marcoow commented
@oliverbarnes: addressed all your remarks, can you have another look?

2017-03-15 17:08 UTC, oliverbarnes approved these changes

2017-03-15 17:09 UTC, oliverbarnes commented
Looks great 👍

2017-03-15 17:09 UTC, merged