Update shape component
mainmatter/mainmatter.com pull request #777
Opened 2019-12-16 06:32 UTC by ghislaineguerin

closes #752

2019-12-17 09:14 UTC, ghislaineguerin commented
@marcoow @pichfl 
I'd like to get your suggestion on how to fix 2 things for this PR

![image](https://user-images.githubusercontent.com/845767/70981495-86259200-20b5-11ea-8494-39485ce9f030.png)
I get some pixels outside of the mask as seen on the above image.

![image](https://user-images.githubusercontent.com/845767/70981607-bf5e0200-20b5-11ea-8333-4f13fb5984d4.png)
![image](https://user-images.githubusercontent.com/845767/70981654-d69cef80-20b5-11ea-84ef-d9c192b4ed5d.png)
I'd like to have a slightly darker background around the edges without having to add a white background to every component and horizontal padding, unless that's the only solution.

2019-12-17 10:15 UTC, marcoow commented
@ghislaineguerin the lines on the left and right are the background of the `div` shining through - if you make the `svg` have `width: 101%;` for example they go away on the right. That wouldn't be a proper fix anyway of course - just as an explanation. Would it not be possible to have the `clip-path` on the `div` directly btw so we wouldn't need the SVG at all?

2019-12-17 11:45 UTC, ghislaineguerin commented
@marcoow I'll try with clip path, thanks.

2019-12-17 12:52 UTC, ghislaineguerin commented
![localhost_4200_ (1)](https://user-images.githubusercontent.com/845767/70997013-59cd3e00-20d4-11ea-9158-6e6d3f59c61a.png)
![localhost_4200_ (2)](https://user-images.githubusercontent.com/845767/70997014-59cd3e00-20d4-11ea-8def-7997434b5b99.png)

@marcoow I've tried clip-path and path is not supported yet, so I used polygon, problem is we cannot maintain aspect ratio. We'll have to go with the svg mask.

2019-12-17 13:30 UTC, marcoow commented
@ghislaineguerin what do you mean `clip-path` is not supported? It should be relatively widely supported: https://caniuse.com/#search=clip-path

2019-12-17 13:32 UTC, ghislaineguerin commented
@marcoow I mean clip-path: path(), I've used polygon, but I think that's not what causes the aspect ratio issues, because the div would still need a set height, which is not the case for using svg.

2019-12-17 13:35 UTC, marcoow commented
Hm, the SVG has a fixed height as well though: https://github.com/simplabs/simplabs.github.io/pull/777/files#diff-9d15c7be363a433981215e4e283ae6faR6

2019-12-17 13:36 UTC, ghislaineguerin commented
@marcoow I've found a solution, will push in a moment.

2019-12-17 13:47 UTC, ghislaineguerin commented
@marcoow I've pushed the clip-path solution, basically I've used the width to calculate the proportional height so it works now. However, because of anti-aliasing I do have to add a 1px negative margin, otherwise we see a gap at some resolutions.

2019-12-17 14:46 UTC, marcoow requested changes
The solution using `clip-path` makes things a lot simpler I think so that's 👍 Also I agree the new shape works better. A lot of the changes in the CSS seem unrelated though as they are only introducing newlines, reorder things etc.? Can those be reverted as they add a lot of noise to this PR and make it really hard to understand what is an actual change and what is not.

Also, I think the image on the trainline shape looks much better in Abstract:

<img width="1158" alt="Bildschirmfoto 2019-12-17 um 15 45 21" src="https://user-images.githubusercontent.com/1510/71005622-40cc8900-20e4-11ea-92ba-e330acce169d.png">

than it does on the page with this branch:

<img width="1719" alt="Bildschirmfoto 2019-12-17 um 15 45 44" src="https://user-images.githubusercontent.com/1510/71005658-517cff00-20e4-11ea-8631-2d821570f880.png">

Also I think the other client logos should be part of the shape now?

2019-12-17 14:46 UTC, marcoow commented on src/ui/components/ShapeFeature/template.hbs
> +  <!--bottom-->
Let's not add these comments - they don't add value really I think?

2019-12-20 14:00 UTC, ghislaineguerin commented
@marcoow 
I've fixed the image, but unfortunately the shape I had in abstract doesn't work very well when trying to keep the proportions balanced, seems we need to have straight edges. 
As for the row of logos, I've tried and it doesn't look too good, I will modify the abstract design to match.

2019-12-20 14:24 UTC, marcoow requested changes
I think this looks good in general but I found a few glitches:

<img width="69" alt="Bildschirmfoto 2019-12-20 um 15 19 04" src="https://user-images.githubusercontent.com/1510/71261048-afa41f00-233c-11ea-87de-84f993da3d90.png">
<img width="221" alt="Bildschirmfoto 2019-12-20 um 15 19 10" src="https://user-images.githubusercontent.com/1510/71261049-afa41f00-233c-11ea-968e-8accca834881.png">
<img width="77" alt="Bildschirmfoto 2019-12-20 um 15 19 23" src="https://user-images.githubusercontent.com/1510/71261050-b03cb580-233c-11ea-895b-4155669acad9.png">

Also I'm not sure we want the margin around the shape on mobile?

![localhost_4200_(iPhone 4) (1)](https://user-images.githubusercontent.com/1510/71261108-d06c7480-233c-11ea-8c81-62701131752a.png)

2019-12-20 14:24 UTC, marcoow commented on src/ui/components/ShapeFeature/template.hbs
> +  <!--top-->
Can we remove these comments please?

2019-12-20 14:24 UTC, marcoow commented on src/ui/components/ShapeFeature/template.hbs
>  <div style={{this.shapeStyle}} state:hasImage={{@src}}>
Is the `shapeStyle` style still necessary?

2019-12-20 14:24 UTC, marcoow commented on src/ui/components/ShapeFeature/template.hbs
>  </div>
I think the `component.ts` for this component can probably be deleted.

2020-01-13 09:18 UTC, ghislaineguerin commented
@marcoow I've removed the negative margins that caused the glitches but there's an antialias issue causing a white line between shapes, I am investigating a fix for that.

2020-01-13 12:43 UTC, ghislaineguerin commented
@marcoow the only way I've found to fix this is by scaling up the shapes enough to cover the gap, however I don't think this is a sustainable approach. Only option left I think is too go back to svg.

2020-01-14 11:55 UTC, marcoow commented
@ghislaineguerin I think the problem with the white lines is that between the `.top`, `.middle` and `.bottom` `div`s is that we're using a relative `padding-bottom` (of `15%` in this example) which can result in fractions (as opposed to full numbers), e.g. `137.578`. At least Chrome supports sub-pixel rendering and will correctly render that as not a full pixel so that the white line appears.

2020-01-14 11:56 UTC, ghislaineguerin commented
@marcoow thanks, will try that.

2020-01-14 12:26 UTC, ghislaineguerin commented
@marcoow We'll have to use svg then, it seems there's no way to maintain the div's aspect ratio without percentages :(

2020-01-14 12:31 UTC, marcoow commented
Hm, let's look at that together tomorrow - there should be some sort of solution.

2020-01-15 12:53 UTC, ghislaineguerin commented
@marcoow 
I've added 90 deg angles to the shapes so that I can overlap without breaking the edges.

![image](https://user-images.githubusercontent.com/845767/72435451-62ca3180-379e-11ea-93bd-9c98b6e63c0b.png)

2020-01-15 12:56 UTC, marcoow commented
@ghislaineguerin now we have the same problem that we had with the relative height before with the relative width around the left and right edges:

<img width="155" alt="Bildschirmfoto 2020-01-15 um 13 56 02" src="https://user-images.githubusercontent.com/1510/72435641-d9ffc580-379e-11ea-8099-b3a85cc42f1b.png">

2020-01-15 14:17 UTC, ghislaineguerin commented
@marcoow last change looks great. Thanks!

2020-01-17 11:05 UTC, ghislaineguerin commented
@marcoow I've removed the typography changes. Please review.

2020-01-17 12:48 UTC, marcoow submitted a review, later dismissed
I think this looks good in general but I found 2 small glitches:

* text has wrong color:

<img width="367" alt="Bildschirmfoto 2020-01-17 um 13 47 43" src="https://user-images.githubusercontent.com/1510/72613519-0bf46180-3930-11ea-8b6e-7febd6a2a1c0.png">

* edges are sort of parallel but not exactly:

<img width="761" alt="Bildschirmfoto 2020-01-17 um 13 47 36" src="https://user-images.githubusercontent.com/1510/72613535-157dc980-3930-11ea-95a8-7bf1b3ed346c.png">

2020-01-17 12:48 UTC, marcoow commented on lib/global-css/css/baseline.css
>    h2 {
Are the changes in this file actually intentional? I'd assume they change everything on the entire site?

2020-01-17 12:53 UTC, marcoow commented
@ghislaineguerin I rebased this on the latest `website-revamp` but there need to be 2 responsive versions of the new JPG now

2020-01-17 13:35 UTC, ghislaineguerin commented on lib/global-css/css/baseline.css
>    h2 {
@marcoow I have fixed this now.

2020-01-17 16:10 UTC, marcoow commented
@ghislaineguerin I rebased on `website-revamp` again and this is now also running the Percy check.

2020-01-17 16:40 UTC, ghislaineguerin commented
@marcoow looking at percy it seems this affects some other instances of this same shape used in other pages. Do you think those should be fixed as part of this PR?

2020-01-17 16:52 UTC, marcoow commented
Yes, we should not merge this unless it either does not affect these other shapes or correctly changes the other shapes.

2020-01-20 10:24 UTC, ghislaineguerin commented
@marcoow I have fixed the other shape instances. Please review.

2020-01-20 11:17 UTC, locks approved these changes
Checked locally and everything seemed fine 👍

2020-01-21 11:24 UTC, merged