add december blog post
mainmatter/mainmatter.com pull request #784
Opened 2019-12-17 13:27 UTC by locks

2019-12-17 14:11 UTC, marcoow reviewed
Nice post! I just left a few comments but in general this reads very well. Here's some other notes:

- you need to add your photo:

<img width="230" alt="Bildschirmfoto 2019-12-17 um 15 09 48" src="https://user-images.githubusercontent.com/1510/71002322-4c698100-20df-11ea-98e4-c44e41e0d2a9.png">

- the post ends a bit abruptly, it might be good to have a closing sentence of some sort?
- this will need an illustration and an `og:image`

2019-12-17 14:11 UTC, marcoow commented on _posts/2019-12-23-clarity-in-templates.md
> +As a framework that values stability and providing its users solid upgrade paths, Ember has accrued its fair share of idiosyncrasies. One of the more demonstrable consequences of this is the so calle
I think the link is malformed - at least it shows up wrong on the rendered page:

<img width="360" alt="Bildschirmfoto 2019-12-17 um 14 54 15" src="https://user-images.githubusercontent.com/1510/71001225-1e833d00-20dd-11ea-881c-4a7af11bd0aa.png">

I guess it'd be nicer for the reader anyway when the phrase _"opening keynote of EmberConf 2019"_ was linked anyway?

2019-12-17 14:11 UTC, marcoow commented on _posts/2019-12-23-clarity-in-templates.md
> +```
I'm not sure I understand why this template is introduced when you're introducing the `@` in the previously used template then?

2019-12-17 14:11 UTC, marcoow commented on _posts/2019-12-23-clarity-in-templates.md
> +We have improved our template a further step. Now we can tell properties, named arguments, and local variables or helpers/components apart.
I think _"helpers/components"_ are not actually covered at this point?

2019-12-17 14:11 UTC, marcoow commented on _posts/2019-12-23-clarity-in-templates.md
> +Note that `@model` was introduced by RFC #523 [[x](https://emberjs.github.io/rfcs/0523-model-argument-for-route-templates.html)] so that you can refer directly to the model that was passed to a route
I'd expand this a bit to make it clearer. The point is that the mechanism for separating named arguments obviously only works for components as those are the only templates in Ember that can receive arguments at all and with RFC #523 that mechanism is made available for route templates as well, effectively treating the route's model like a named argument for the template. Of course that's clear to us but I'm not sure this analogy is obvious to all Ember developers.

2019-12-17 14:11 UTC, marcoow commented on _posts/2019-12-23-clarity-in-templates.md
> +After the last change, it would be nice to have a way to disambiguate component invocations from other kinds of dynamic interpolations. Fortunately, a new syntax was introduced called angle bracket i
> called angle bracket invocation syntax [[x](https://emberjs.github.io/rfcs/0311-angle-bracket-invocation.html)]

I'm generally not a fan of this linking style but tbh I think when using _"x"_ vs. numbers it becomes completely pointless?

2019-12-17 14:11 UTC, marcoow commented on _posts/2019-12-23-clarity-in-templates.md
> +After the last change, it would be nice to have a way to disambiguate component invocations from other kinds of dynamic interpolations. Fortunately, a new syntax was introduced called angle bracket i
> It also allows us to distinguish between named arguments and HTML attributes when invoking components, but that will be covered in a future post.

You're introducing the concept of named arguments in the previous paragraph though? I understand you're referring to applying HTML attributes in the component here but this reads a bit strange as you think "he just explained named arguments?".

2019-12-17 14:11 UTC, marcoow commented on _posts/2019-12-23-clarity-in-templates.md
> +- `Comment` is a component invocation
```suggestion
- `<Comment />` is a component invocation
```

2019-12-17 14:11 UTC, marcoow commented on _posts/2019-12-23-clarity-in-templates.md
> +## Handling DOM events
I assume this section should be removed?

2019-12-17 14:15 UTC, locks commented on _posts/2019-12-23-clarity-in-templates.md
> +## Handling DOM events
Confirm, replacing with an ending.

2019-12-17 14:27 UTC, locks commented on _posts/2019-12-23-clarity-in-templates.md
> +```
The idea was the same as introducing the class file in the properties section, to show that you need to consult a different file to understand what might be passed in, adding a bit more contex to `post` and `onReportComments`.

2019-12-17 14:27 UTC, locks commented on _posts/2019-12-23-clarity-in-templates.md
> +We have improved our template a further step. Now we can tell properties, named arguments, and local variables or helpers/components apart.
I mentioned them in the intro:

> Looking only at the template, can we be certain where `title` comes from? Whether `post-body` and `comment` are helpers or components? We can generously assume that `comment` is a component as it is receiving an action, but when scanning the file it is indistinguishable from `if`, `each`, and other templating constructs.

Is there something I can clarify?

2019-12-17 14:27 UTC, locks commented on _posts/2019-12-23-clarity-in-templates.md
> +After the last change, it would be nice to have a way to disambiguate component invocations from other kinds of dynamic interpolations. Fortunately, a new syntax was introduced called angle bracket i
I've updated the link style.

2019-12-17 14:48 UTC, marcoow commented on _posts/2019-12-23-clarity-in-templates.md
> +```
Ah, so you're saying the above template **is** the `blog/post` component and here you're showing the invocation? That makes sense but I don't think it's clear necessarily when reading through the text - might be worth adding a sentence here explaining that.

2019-12-17 14:49 UTC, marcoow commented on _posts/2019-12-23-clarity-in-templates.md
> +We have improved our template a further step. Now we can tell properties, named arguments, and local variables or helpers/components apart.
Yes, what I mean is we can only tell helpers/component apart from local variables with angle bracket invocation which hasn't been introduced at this point.

2019-12-18 08:15 UTC, marcoow reviewed
Nice - made just one more comment about something I'm not sure about.

2019-12-18 08:15 UTC, marcoow commented on _posts/2019-12-23-clarity-in-templates.md
> +We can see that when calling the component, we are passing in `post` and `onReportComment`. The syntax to mark them as named argument is a `@` prefix, so let us update our template:
Will this actually work with the invocation shown above that does **not** use the `@` prefix?

2019-12-18 17:37 UTC, locks commented on _posts/2019-12-23-clarity-in-templates.md
> +We can see that when calling the component, we are passing in `post` and `onReportComment`. The syntax to mark them as named argument is a `@` prefix, so let us update our template:
I believe so. In `@ember/component` passed in arguments are reflected as properties so  `this.onReportComment`, `onReportComment` and `@onReportComment` are roughly equivalent. With `@onReportComment` being directly the value passed in.

2019-12-19 09:08 UTC, marcoow commented on _posts/2019-12-23-clarity-in-templates.md
> +We can see that when calling the component, we are passing in `post` and `onReportComment`. The syntax to mark them as named argument is a `@` prefix, so let us update our template:
Yep, this works indeed - just checked: https://ember-twiddle.com/a961c72d6959a5d36fe91e65f8d3323a?openFiles=templates.components.my-component.hbs%2Ctemplates.components.my-component.hbs

2019-12-19 09:09 UTC, marcoow approved these changes

2019-12-19 16:37 UTC, marcoow commented
@locks: can you add your photo, the images that @ghislaineguerin created and update the date to tomorrow so we can get this out?

2019-12-20 14:04 UTC, marcoow requested changes
@locks can you make your profile image smaller? Smaller dimensions should be sufficient. Also can you run images through https://imageoptim.com/mac and fix CI (I think you're just missing `yarn format`)?

2019-12-20 15:10 UTC, locks commented
@marcoow I've shrunken my profile image to 200x200 like the others and ran the png through imageoptim. `yarn format` is also applied.

2019-12-20 15:41 UTC, marcoow approved these changes

2019-12-20 15:53 UTC, merged