WIP: workshops sorted by weight, added to every post
mainmatter/mainmatter.com pull request #81
Opened 2017-03-21 14:08 UTC by EmanuelaTrabaldoLena

Every post has a weight now so it's possible to sort them as wanted

2017-03-21 14:17 UTC, marcoow requested changes
The weight approach is good but I think we should auto-assign a weight based on the workshop title in the update script (otherwise we have to manually add the weights again every time we update the workshops). I'd make it so that we assign a weight of 1 for all workshops that have _"ember"_ in the title, 2 for all that have _"elixir"_ or _"phoenix"_ in the title and 3 for all others (make sure that the match is case-insensitive).

2017-03-28 16:30 UTC, marcoow reviewed
I think it would be easier to do this in the [update script](https://github.com/simplabs/simplabs.github.io/blob/master/script/update-workshops#L29) so that we don't have to add logic to the templates:

```rb
weight = if title =~ /ember/i
  1
else if title =~ /elixir|erlang|phoenix/
  2
else
  3
end

course_yaml = {
  layout:      'workshop',
  title:       title,
  weight: weight,
  permalink:   "/training/#{slug}",
  category:    category,
  description: description,
  image:       "/#{image_name}"
}
```

2017-03-28 16:30 UTC, marcoow commented on _config.yml
> +    width: 144
These changes seem unrelated?

2017-04-03 09:04 UTC, EmanuelaTrabaldoLena commented
closes #74

2017-04-04 09:08 UTC, marcoow approved these changes

2017-04-04 09:10 UTC, merged