Blog Post: "How to over-engineer a static page"
mainmatter/mainmatter.com pull request #826
Opened 2020-01-20 20:03 UTC by marcoow

closes #809

2020-01-24 09:01 UTC, ghislaineguerin approved these changes

2020-01-24 09:20 UTC, arthurp1 commented on _posts/2020-01-19-how-to-over-engineer-a-static-page.md
> +title: 'How to over-engineer a static page'
It's not a

2020-01-24 09:26 UTC, marcoow commented on _posts/2020-01-19-how-to-over-engineer-a-static-page.md
> +title: 'How to over-engineer a static page'
I don't understand

2020-01-24 10:10 UTC, Turbo87 approved these changes

2020-01-24 10:10 UTC, Turbo87 commented on _posts/2020-01-19-how-to-over-engineer-a-static-page.md
> +description: 'TODO'
🙃

2020-01-24 10:10 UTC, Turbo87 commented on _posts/2020-01-19-how-to-over-engineer-a-static-page.md
> +page work offline. The service worker loads of the JavaScript bundles described
> and make the page work offline.

I just tried this in Chrome and it didn't work for me 😅

2020-01-24 10:10 UTC, Turbo87 commented on _posts/2020-01-19-how-to-over-engineer-a-static-page.md
> +![Screenshot](/assets/images/posts/2020-01-19-how-to-over-engineer-a-static-page/lighthouse.png#@900-1800)
there is quite a bit of German on that screenshot. might be worth it to get one with English locale maybe :D

2020-01-24 10:10 UTC, Turbo87 commented on _posts/2020-01-19-how-to-over-engineer-a-static-page.md
> +couldn't cove in this article but that should be considered best practices when
```suggestion
couldn't cover in this article but that should be considered best practices when
```

2020-01-24 10:10 UTC, Turbo87 commented on _posts/2020-01-19-how-to-over-engineer-a-static-page.md
> +![Screenshot](/assets/images/posts/2020-01-19-how-to-over-engineer-a-static-page/lighthouse.png#@900-1800)
also, the screenshot shows that apparently not the requested page was audited, but the frontpage instead 🤔

2020-01-24 10:26 UTC, marcoow commented on _posts/2020-01-19-how-to-over-engineer-a-static-page.md
> +description: 'TODO'
🤦‍♂

2020-01-24 10:28 UTC, marcoow commented on _posts/2020-01-19-how-to-over-engineer-a-static-page.md
> +page work offline. The service worker loads of the JavaScript bundles described
ouch, yes - seems to have broken 😞

2020-01-24 10:32 UTC, marcoow commented on _posts/2020-01-19-how-to-over-engineer-a-static-page.md
> +page work offline. The service worker loads of the JavaScript bundles described
Hm, it **does** work when I turn off my Wifi but it **does not** work when I simulate offline in the Inspector's Network tab…

2020-01-24 10:32 UTC, marcoow commented on _posts/2020-01-19-how-to-over-engineer-a-static-page.md
> +page work offline. The service worker loads of the JavaScript bundles described
Hm, it does work when I turn off my Wifi but it does not work when I simulate offline in the Inspector's Network tab…

2020-01-24 10:34 UTC, marcoow commented on _posts/2020-01-19-how-to-over-engineer-a-static-page.md
> +title: 'How to over-engineer a static page'
This is kind of a joke, it translates to _"How to do something stupid"_ which is also why I say things like _"letting go of reason"_ etc. - it's actually a clickbait-y title (or that's the idea at least)

2020-01-24 10:48 UTC, marcoow commented on _posts/2020-01-19-how-to-over-engineer-a-static-page.md
> +title: 'How to over-engineer a static page'
This is kind of a joke, it translates to _"How to do something stupid"_ which is also why I say things like _"letting go of reason"_ etc. - it's actually a click-baity title

2020-01-24 10:48 UTC, marcoow commented on _posts/2020-01-19-how-to-over-engineer-a-static-page.md
> +![Screenshot](/assets/images/posts/2020-01-19-how-to-over-engineer-a-static-page/lighthouse.png#@900-1800)
ah yes, forgot to fix that yesterday - done 👍

2020-01-24 10:51 UTC, marcoow commented on _posts/2020-01-19-how-to-over-engineer-a-static-page.md
> +description: 'TODO'
✅

2020-01-24 12:35 UTC, arthurp1 commented on _posts/2020-01-19-how-to-over-engineer-a-static-page.md
> +title: 'How to over-engineer a static page'
Yes, it's a good title. I just had to mention the trade-off for google searches.

2020-01-24 12:37 UTC, arthurp1 commented on _posts/2020-01-19-how-to-over-engineer-a-static-page.md
> +description:
It might be interesting to mention a list of all the technologies we use here:
Bundles and Caching
Statically Prerendering
Service workers

2020-01-24 12:38 UTC, arthurp1 commented on _posts/2020-01-19-how-to-over-engineer-a-static-page.md
> +description:
Or somewhere else at the beginning of the blog post, so that people know they can learn about new technologies to use in combination with a static site.

2020-01-24 12:43 UTC, arthurp1 commented on _posts/2020-01-19-how-to-over-engineer-a-static-page.md
> +title: 'How to over-engineer a static page'
maybe add 'for maximum performance' so that people know what they can learn from it. Or leave it to keep it short and snappy.

2020-01-24 14:50 UTC, marcoow commented on _posts/2020-01-19-how-to-over-engineer-a-static-page.md
> +title: 'How to over-engineer a static page'
I'll put something about performance in the description so we can leave the title short and snappy.

2020-01-24 14:59 UTC, marcoow commented on _posts/2020-01-19-how-to-over-engineer-a-static-page.md
> +description:
done

2020-01-24 15:01 UTC, marcoow commented
@ghislaineguerin this will also require an illustration and og:image - I guess everything that relates to performance and speed might be an obvious fit or maybe you have other ideas of course.

2020-01-28 12:39 UTC, locks requested changes
Some inline comments and github suggestions.

2020-01-28 12:39 UTC, locks commented on _posts/2020-01-19-how-to-over-engineer-a-static-page.md
> +considerations (and reason you could say) and dive deep into what was
I am a bit confused reading this sentence, specifically "and dive deep into what was technically possible to build something" seems like two different sentences?

2020-01-28 12:39 UTC, locks commented on _posts/2020-01-19-how-to-over-engineer-a-static-page.md
> +recommend anyone following our example as your time is most likely spent better
```suggestion
recommend anyone following our example as your time is most likely better spent
```

2020-01-28 12:39 UTC, locks commented on _posts/2020-01-19-how-to-over-engineer-a-static-page.md
> +- we wanted to update the rather
```suggestion
- We wanted to update the rather
```

2020-01-28 12:39 UTC, locks commented on _posts/2020-01-19-how-to-over-engineer-a-static-page.md
> +- we wanted to keep creating and maintaining content for the site as simple as
```suggestion
- We wanted to keep creating and maintaining content for the site as simple as
```

2020-01-28 12:39 UTC, locks commented on _posts/2020-01-19-how-to-over-engineer-a-static-page.md
> +  which are to be covered in a separate, future post)
```suggestion
  which are to be covered in a separate, future post).
```

2020-01-28 12:39 UTC, locks commented on _posts/2020-01-19-how-to-over-engineer-a-static-page.md
> +  [adding a new Markdown file with some front matter](https://github.com/simplabs/simplabs.github.io/pull/826)
```suggestion
  [adding a new Markdown file with some front matter](https://github.com/simplabs/simplabs.github.io/pull/826).
```

2020-01-28 12:39 UTC, locks commented on _posts/2020-01-19-how-to-over-engineer-a-static-page.md
> +- although we are huge fans of Elixir and Phoenix we did not want to create an
```suggestion
- Although we are huge fans of Elixir and Phoenix we did not want to create an
```

2020-01-28 12:39 UTC, locks commented on _posts/2020-01-19-how-to-over-engineer-a-static-page.md
> +  ever needs to be calculated dynamically on the server
```suggestion
  ever needs to be calculated dynamically on the server.
```

2020-01-28 12:39 UTC, locks commented on _posts/2020-01-19-how-to-over-engineer-a-static-page.md
> +- we wanted to have best in class performance so that the site would load as
```suggestion
- We wanted to have best in class performance so that the site would load as
```

2020-01-28 12:39 UTC, locks commented on _posts/2020-01-19-how-to-over-engineer-a-static-page.md
> +  as well as offline of course
```suggestion
  as well as offline of course.
```

2020-01-28 12:39 UTC, locks commented on _posts/2020-01-19-how-to-over-engineer-a-static-page.md
> +[TTFB](https://en.wikipedia.org/wiki/Time_to_first_byte). As the pages were
We don't want to take people out of the post unless necessary, so I suggest we write the acronym in full the first time:

```suggestion
Time to First Byte ([TTFB](https://en.wikipedia.org/wiki/Time_to_first_byte)). As the pages were
```

2020-01-28 12:39 UTC, locks commented on _posts/2020-01-19-how-to-over-engineer-a-static-page.md
> +[FCP](https://developers.google.com/web/tools/lighthouse/audits/first-contentful-paint).
```suggestion
First Contentful Paint ([FCP](https://developers.google.com/web/tools/lighthouse/audits/first-contentful-paint)).
```

2020-01-28 12:39 UTC, locks commented on _posts/2020-01-19-how-to-over-engineer-a-static-page.md
> +[TTI](https://developers.google.com/web/tools/lighthouse/audits/time-to-interactive)
```suggestion
Time to Interactive ([TTI](https://developers.google.com/web/tools/lighthouse/audits/time-to-interactive))
```

2020-01-28 12:39 UTC, locks commented on _posts/2020-01-19-how-to-over-engineer-a-static-page.md
> +However, one of the advantages of client side rendering is that all subsequent
```suggestion
However, one of the advantages of client-side rendering is that all subsequent
```

2020-01-28 12:39 UTC, locks commented on _posts/2020-01-19-how-to-over-engineer-a-static-page.md
> +side without the need for making (and waiting for the response to) any
```suggestion
side without the need to make (and wait for the response to) any
```

2020-01-28 12:39 UTC, locks commented on _posts/2020-01-19-how-to-over-engineer-a-static-page.md
> +pre-rendered HTML documents, we wrote the site as a single page app so that the
```suggestion
pre-rendered HTML documents, we wrote the site as a single-page app so that the
```

2020-01-28 12:39 UTC, locks commented on _posts/2020-01-19-how-to-over-engineer-a-static-page.md
> +document from the CDN. In that sense, the client side app
```suggestion
document from the CDN. In that sense, the client-side app
```

2020-01-28 12:39 UTC, locks commented on _posts/2020-01-19-how-to-over-engineer-a-static-page.md
> +client side and instant, if it is not (yet) running, clicks on links will simply
```suggestion
client-side and instant, if it is not (yet) running, clicks on links will simply
```

2020-01-28 12:39 UTC, locks commented on _posts/2020-01-19-how-to-over-engineer-a-static-page.md
> +Since we are huge fans of Ember.js and are heavily connected with the community
```suggestion
Since we are huge fans of Ember.js and are heavily connected with the community,
```

2020-01-28 12:39 UTC, locks commented on _posts/2020-01-19-how-to-over-engineer-a-static-page.md
> +[appointment scheduling systems](/cases/timify/) though that implement
Repeated "though" in "though that implement significant client side logic though" seems a mistake.

2020-01-28 12:39 UTC, locks commented on _posts/2020-01-19-how-to-over-engineer-a-static-page.md
> +[Glimmer.js](https://glimmerjs.com) provides exactly what we need though which
```suggestion
[Glimmer.js](https://glimmerjs.com) provides exactly what we need though, which
```

2020-01-28 12:39 UTC, locks commented on _posts/2020-01-19-how-to-over-engineer-a-static-page.md
> +The only client side state that our application maintains is the currently
```suggestion
The only client-side state that our application maintains is the currently
```

2020-01-28 12:39 UTC, locks commented on _posts/2020-01-19-how-to-over-engineer-a-static-page.md
> +Statically pre-rendering a client side app at build time is relatively straight
```suggestion
Statically pre-rendering a client-side app at build time is relatively straight
```

2020-01-28 12:39 UTC, locks commented on _posts/2020-01-19-how-to-over-engineer-a-static-page.md
> +had with the previous Jekyll based site, we did not want to give up the easy
```suggestion
had with the previous Jekyll-based site, we did not want to give up the easy
```

2020-01-28 12:39 UTC, locks commented on _posts/2020-01-19-how-to-over-engineer-a-static-page.md
> +computed on demand on the server as all of it is indeed static and known up
```suggestion
computed on demand on the server as all of it is indeed static and known upfront.
```

2020-01-28 12:39 UTC, locks commented on _posts/2020-01-19-how-to-over-engineer-a-static-page.md
> +front. Leveraging Glimmer.js' Broccoli based build pipeline, we set up a process
```suggestion
Leveraging Glimmer.js' Broccoli-based build pipeline, we set up a process
```

2020-01-28 12:39 UTC, locks commented on _posts/2020-01-19-how-to-over-engineer-a-static-page.md
> +to build time, much like what the [Jamstack](https://jamstack.org) propagates
"propagates" doesn't seem like the proper word here. Advocates? Proposes?

2020-01-28 12:39 UTC, locks commented on _posts/2020-01-19-how-to-over-engineer-a-static-page.md
> +  its own so I won't go into any details here
```suggestion
  its own so I won't go into any details here.
```

2020-01-28 12:39 UTC, locks commented on _posts/2020-01-19-how-to-over-engineer-a-static-page.md
> +- images and their formats are a huge topic as well when it comes to performance
```suggestion
- Images and their formats are a huge topic as well when it comes to performance
```

2020-01-28 12:39 UTC, locks commented on _posts/2020-01-19-how-to-over-engineer-a-static-page.md
> +  huge payloads on small viewports
```suggestion
  huge payloads on small viewports.
```

2020-01-28 12:39 UTC, locks commented on _posts/2020-01-19-how-to-over-engineer-a-static-page.md
> +- third-parties can have a significant negative impact on a site's performance
```suggestion
- Third-parties can have a significant negative impact on a site's performance
```

2020-01-28 12:39 UTC, locks commented on _posts/2020-01-19-how-to-over-engineer-a-static-page.md
> +  [serve fonts from your own domain](https://github.com/simplabs/simplabs.github.io/pull/833))
```suggestion
  [serve fonts from your own domain](https://github.com/simplabs/simplabs.github.io/pull/833)).
```

2020-01-28 12:39 UTC, locks commented on _posts/2020-01-19-how-to-over-engineer-a-static-page.md
> +- optimizing for performance is an ongoing project and not a one-off effort;
```suggestion
- Optimizing for performance is an ongoing project and not a one-off effort;
```

2020-01-28 12:39 UTC, locks commented on _posts/2020-01-19-how-to-over-engineer-a-static-page.md
> +- knowing is better than guessing and if you really care about your site's
```suggestion
- Knowing is better than guessing and if you really care about your site's
```

2020-01-28 12:39 UTC, locks commented on _posts/2020-01-19-how-to-over-engineer-a-static-page.md
> +  [RUM](https://en.wikipedia.org/wiki/Real_user_monitoring)
```suggestion
  [RUM](https://en.wikipedia.org/wiki/Real_user_monitoring).
```

2020-01-28 12:40 UTC, locks requested changes
Some inline comments and github suggestions.

2020-01-28 15:39 UTC, marcoow commented on _posts/2020-01-19-how-to-over-engineer-a-static-page.md
> +considerations (and reason you could say) and dive deep into what was
I split that into 2 sentences.

2020-01-28 15:41 UTC, marcoow commented on _posts/2020-01-19-how-to-over-engineer-a-static-page.md
> +[TTFB](https://en.wikipedia.org/wiki/Time_to_first_byte). As the pages were
yes, makes sense 👍

2020-01-28 15:41 UTC, marcoow commented on _posts/2020-01-19-how-to-over-engineer-a-static-page.md
> +[FCP](https://developers.google.com/web/tools/lighthouse/audits/first-contentful-paint).
👍

2020-01-28 15:42 UTC, marcoow commented on _posts/2020-01-19-how-to-over-engineer-a-static-page.md
> +[TTI](https://developers.google.com/web/tools/lighthouse/audits/time-to-interactive)
👍

2020-01-28 15:47 UTC, marcoow commented on _posts/2020-01-19-how-to-over-engineer-a-static-page.md
> +[appointment scheduling systems](/cases/timify/) though that implement
fixed 👍

2020-01-28 15:49 UTC, marcoow commented on _posts/2020-01-19-how-to-over-engineer-a-static-page.md
> +to build time, much like what the [Jamstack](https://jamstack.org) propagates
fixed - I think this works in german but not in english

2020-01-28 17:52 UTC, locks approved these changes

2020-01-30 09:33 UTC, ghislaineguerin commented
@marcoow I have pushed the illustration and og-image

2020-01-30 09:38 UTC, marcoow commented
@ghislaineguerin can we use a different icon on the `og:image`? This post is not really specific to Glimmer.js after all which could make it interesting for a wider audience. We could use something like in the illustration maybe that just stands for _"static site"_ and _"engineering"_?

2020-01-30 13:30 UTC, ghislaineguerin commented
@marcoow I've tried adding an icon to show that optimization aspect, as we are not pointing out to any specific technology

2020-01-31 13:15 UTC, merged