update footer component
mainmatter/mainmatter.com pull request #828
Opened 2020-01-21 13:19 UTC by ghislaineguerin

Closes #820

2020-01-24 11:38 UTC, ghislaineguerin commented
![image](https://user-images.githubusercontent.com/845767/73066419-2c7b6900-3ea6-11ea-9143-eb9bd8cb711f.png)

@marcoow I'm struggling to find a good solution to this gap between bottom shape and the image. I cannot make the entire footer container a clip path as the proportions won't be kept but then overlapping the image seems to not work for some reason. Ideally I wouldn't want to use absolute positioning.

2020-01-24 12:45 UTC, marcoow commented
@ghislaineguerin I'd guess you'd have to have the image as a background image on the wrapper div that wraps the `.top` etc. diffs and have the `clip-path` on that as well - I cannot really think of an alternative.

2020-01-27 09:43 UTC, ghislaineguerin commented
We can work on #839 as part of post-launch improvements

2020-01-27 09:45 UTC, marcoow requested changes
This looks good in general - just left some comments on smaller things.

Also there are 2 visual things we should fix:

* let's not use my image in all of the footers but images of different people
* the image is cut off on the sides for medium viewport sizes:

<img width="1256" alt="Bildschirmfoto 2020-01-27 um 10 40 02" src="https://user-images.githubusercontent.com/1510/73164388-2a0d4f00-40f2-11ea-9959-72211d79f8bc.png">

2020-01-27 09:45 UTC, marcoow commented on src/ui/components/Footer/template.hbs
> +  <div class="container layout">
Is it possible to not have these wrapper `div`s and make the `footer` the `.container.layout`?

2020-01-27 09:45 UTC, marcoow commented on src/ui/components/WorkWithUs/stylesheet.css
> +  background: #f8f8fa;
Should we use CSS variables for the colors used in this file?

2020-01-27 09:47 UTC, ghislaineguerin commented on src/ui/components/Footer/template.hbs
> +  <div class="container layout">
@marcoow I'll try that.

2020-01-28 09:10 UTC, ghislaineguerin commented on src/ui/components/Footer/template.hbs
> +  <div class="container layout">
@marcoow I get this error: Cannot put Block classes on the Block's root element.

2020-01-28 09:11 UTC, ghislaineguerin commented
@marcoow is there a way we can randomize the team member that shows on the footer? Or set a default when nothing is defined

2020-01-28 10:27 UTC, marcoow commented on src/ui/components/Footer/template.hbs
> +  <div class="container layout">
I see  - can we somehow apply the classes to the root element using any of the css-blocks mechanisms like `@composes` or so? I'm just wondering whether we can somehow get the same result without having to wrap the `<footer>`

2020-01-28 10:29 UTC, marcoow commented
We cannot randomize the team member (that has to do with the static pre-rendering where we must make sure the pre-render results in the same DOM that we get when the app boots up in the browser). I'd envision an API like

```hbs
<Footer @photo="ghislaine" />
```

where we can just pick who we want to show when invoking the component.

2020-01-29 13:23 UTC, locks approved these changes

2020-01-29 13:28 UTC, marcoow requested changes
The images are now cut off on large viewports as well which I think looks weird:

<img width="1277" alt="Bildschirmfoto 2020-01-29 um 14 27 59" src="https://user-images.githubusercontent.com/1510/73360620-a2ffd880-42a3-11ea-8d9a-d5198d11d3f4.png">
<img width="1277" alt="Bildschirmfoto 2020-01-29 um 14 28 09" src="https://user-images.githubusercontent.com/1510/73360621-a2ffd880-42a3-11ea-8af6-99d3aaa7127e.png">

Also, do we have photos of more people than you, Chris and me so we could have more variety?

2020-01-29 13:28 UTC, marcoow commented on src/ui/components/PageCaseDdWrt/template.hbs
> +   />
Can we move these values into the component so we don't have to repeat so many details over and over? If we can invoke the component just with

```hbs
<WorkWithUs @teamMember="ghislaine"/>
```

I think that would be much easier.

2020-01-29 13:28 UTC, marcoow commented on src/ui/components/PageCaseDdWrt/template.hbs
> +    @color="#007DF6"
Is this not static and thus wouldn't have to be passed like this?

2020-01-30 08:30 UTC, ghislaineguerin commented on src/ui/components/PageCaseDdWrt/template.hbs
> +   />
@marcoow so that means I can do something like  photos/@teamMember@604.png  ? how would this work?

2020-01-30 08:31 UTC, ghislaineguerin commented on src/ui/components/PageCaseDdWrt/template.hbs
> +    @color="#007DF6"
@marcoow I don't know why color is being passed there. I will remove it.

2020-01-30 09:15 UTC, marcoow commented on src/ui/components/PageCaseDdWrt/template.hbs
> +   />
You would have a property in the component's `.ts` file that maps short names to the actual values for `srcset` etc. - something like

```typescript
srcSets: {
  ghislaine: '/assets/images/photos/ghislaine@604.png 604w, /assets/images/photos/ghislaine@1208.png 1208w'
},

srcSizes: {
  ghislaine: '(max-width: 887px) 604px, 1208px'
},

imageAlts: {
  …
}
```

@locks will be able to help set that up if you're having problems with that.

2020-01-30 10:09 UTC, ghislaineguerin commented
@marcoow most didn't do the individual portraits. I only have Jessica, but the picture with the right aspect ratio are w/ eyes closed. We need to plan to take more during winter event.

2020-01-30 11:12 UTC, marcoow commented
@ghislaineguerin ok, we should be able to take pictures when we all meet in the hotel at 19:00 - can you bring/prepare everything for that?

2020-01-30 11:13 UTC, marcoow commented on src/ui/components/WorkWithUs/stylesheet.css
> +  background: #f8f8fa;
@ghislaineguerin this is still open

2020-01-30 11:17 UTC, marcoow requested changes
Hm, I think some things still need to be done:

* there are 4 different images for Chris and Ghislaine while the component will only ever use 2
* the images are huge, some almost 2MB
* none of the images actually render, e.g.:

<img width="1456" alt="Bildschirmfoto 2020-01-30 um 12 16 50" src="https://user-images.githubusercontent.com/1510/73445184-693dd900-435a-11ea-9bcd-883216afc30c.png">

2020-01-30 11:17 UTC, marcoow commented on src/ui/components/WorkWithUs/template.hbs
> +      <img class="img" srcset="/assets/images/photos/{{@teamMember}}@604.png 604w, /assets/images/photos/{{@teamMember}}@1208.png 1208w" sizes="(max-width: 887px) 604px, 1208px" alt="{{@teamMember}}"
I think we should capitalize the `alt` text which means we need a property on the component context (the `.ts` file).

2020-01-30 11:17 UTC, marcoow commented on src/ui/components/WorkWithUs/template.hbs
> +      <img class="img" srcset="/assets/images/photos/{{@teamMember}}@604.png 604w, /assets/images/photos/{{@teamMember}}@1208.png 1208w" sizes="(max-width: 887px) 604px, 1208px" alt="{{@teamMember}}"
Also, this only works when all of the team pictures actually have same sizes (604px width and 1208px width) - is that certainly going to be the case?

2020-01-30 11:20 UTC, ghislaineguerin commented on src/ui/components/WorkWithUs/template.hbs
> +      <img class="img" srcset="/assets/images/photos/{{@teamMember}}@604.png 604w, /assets/images/photos/{{@teamMember}}@1208.png 1208w" sizes="(max-width: 887px) 604px, 1208px" alt="{{@teamMember}}"
@marcoow I'd need help with this part. I'm not sure how to make this component reusable. I'll fix all the other issues.

2020-01-30 13:16 UTC, marcoow commented on src/ui/components/WorkWithUs/template.hbs
> +      <img class="img" srcset="/assets/images/photos/{{@teamMember}}@604.png 604w, /assets/images/photos/{{@teamMember}}@1208.png 1208w" sizes="(max-width: 887px) 604px, 1208px" alt="{{@teamMember}}"
@locks can you help?

2020-01-30 14:18 UTC, locks commented on src/ui/components/WorkWithUs/template.hbs
> +      <img class="img" srcset="/assets/images/photos/{{@teamMember}}@604.png 604w, /assets/images/photos/{{@teamMember}}@1208.png 1208w" sizes="(max-width: 887px) 604px, 1208px" alt="{{@teamMember}}"
working on it!

2020-02-03 17:50 UTC, ghislaineguerin commented
@locks I have fixed some styling issues and removed some redundant images. However some tests are failing, please review.

2020-02-04 11:43 UTC, marcoow requested changes
- Some of the mobile views are broken - I left comments on Percy.
- Also can we get the team photos smaller? They are still pretty massive with ca. 800KB for some of them - I'd say none of them should be above 150KB or so.
- there's still and unaddressed comment from a previous review

2020-02-04 12:03 UTC, locks commented on src/ui/components/WorkWithUs/template.hbs
> +      <img class="img" srcset="/assets/images/photos/{{@teamMember}}@604.png 604w, /assets/images/photos/{{@teamMember}}@1208.png 1208w" sizes="(max-width: 887px) 604px, 1208px" alt="{{@teamMember}}"
`alt` is now capitalized.

2020-02-04 15:09 UTC, ghislaineguerin commented
@marcoow It seems we don't really need the large pngs as the image doesn't grow beyond 604px. Please review. I also can't reproduce the mobile bugs from Percy. We have changed the service pages so I'm not sure it's worth fixing now?

2020-02-04 15:30 UTC, marcoow reviewed
@ghislaineguerin I cannot reproduce the broken mobile pages on Percy neither - approved. There's one thing we can optimize in the code though (see comment). Also, regarding the images, I suppose we can use JPGs with a grey background now that the photos never extend beyond the grey container anyway which should shrink the images quite significantly?

2020-02-04 15:30 UTC, marcoow commented on src/ui/components/WorkWithUs/template.hbs
> +        srcset="{{this.teamMemberPhoto}}"
We can just use a regular `src` without `srcset` and `sizes`.

2020-02-04 16:01 UTC, locks commented on src/ui/components/WorkWithUs/template.hbs
> +        srcset="{{this.teamMemberPhoto}}"
Link directly to `@604px` then? Updating.

2020-02-05 05:02 UTC, ghislaineguerin commented
@marcoow I'd like to keep the transparency of the images as I still might adjust colors/shade before release.

2020-02-05 08:39 UTC, marcoow approved these changes

2020-02-05 08:40 UTC, marcoow commented
@ghislaineguerin ok, sure let's keep the PNGs then. Only the failing test preventing this from merging then

2020-02-05 09:31 UTC, merged