[Services] Update content for team augmentation page
mainmatter/mainmatter.com pull request #843
Opened 2020-01-29 13:47 UTC by locks

2020-01-29 15:00 UTC, ghislaineguerin requested changes

2020-01-29 15:00 UTC, ghislaineguerin commented on src/ui/components/PageTeamAugmentation/template.hbs
> +    <h2 class="typography.h3">
any reason why we don't use h2 styling or just change tag to h3?

2020-01-29 15:37 UTC, locks commented on src/ui/components/PageTeamAugmentation/template.hbs
> +    <h2 class="typography.h3">
I went with `h2` to keep the "document hierarchy", since they don't have an h2 in common.

2020-01-30 11:47 UTC, ghislaineguerin approved these changes

2020-01-30 11:48 UTC, merged