Add Product Development page
mainmatter/mainmatter.com pull request #864
Opened 2020-02-05 14:37 UTC by marcoow

This adds the page for product development. It **only** adds the page and text content – styling and addition of images etc. is still needed to be done in a follow-up PR.

closes #862

2020-02-05 15:56 UTC, locks requested changes
Left some inline comments.

2020-02-05 15:56 UTC, locks commented on src/ui/components/PageProductDevelopment/template.hbs
> +    <HeaderContent @label="Product Development" @headline="Engineering excellence means building things to last">
I'm not sure if single quote cuts it here or if it should be smart quotes.

```suggestion
    <HeaderContent @label="Product Development" @headline="Engineering excellence means 'building things to last'">
```

2020-02-05 15:56 UTC, locks commented on src/ui/components/PageProductDevelopment/template.hbs
> +        simplabs has its origins in engineering and development. We obsess over crafting the absolute best products we can, built on architectures that are easy to extend, update and maintain. Our pr
```suggestion
        Simplabs has its origins in engineering and development. We obsess over crafting the absolute best products we can, built on architectures that are easy to extend, update and maintain. Our process depends on close collaboration between designers and developers to release well-tested products in dynamic, fast-paced iterations.
```

2020-02-05 15:56 UTC, locks commented on src/ui/components/PageProductDevelopment/template.hbs
> +    <p class="typography.lead">
Should we create a card to style this list as in the mockup?

2020-02-05 15:56 UTC, locks commented on src/ui/components/PageProductDevelopment/template.hbs
> +  </div>
"Learn How We Work" link missing

2020-02-05 15:56 UTC, locks commented on src/ui/components/PageProductDevelopment/template.hbs
> +    <h2>
The mockup does not include this section @ghislaineguerin, does it need updating?

2020-02-05 16:03 UTC, marcoow commented on src/ui/components/PageProductDevelopment/template.hbs
> +        simplabs has its origins in engineering and development. We obsess over crafting the absolute best products we can, built on architectures that are easy to extend, update and maintain. Our pr
_"simplabs"_ is always lowercase

2020-02-05 16:03 UTC, marcoow commented on src/ui/components/PageProductDevelopment/template.hbs
> +    <p class="typography.lead">
So my understanding was these issues are about adding the pages and raw content **only**?

2020-02-05 16:04 UTC, marcoow commented on src/ui/components/PageProductDevelopment/template.hbs
> +    <h2>
This text is in Basecamp - I think it's missing in the mockup?

2020-02-05 16:07 UTC, marcoow commented on src/ui/components/PageProductDevelopment/template.hbs
> +  </div>
added

2020-02-05 16:07 UTC, marcoow commented on src/ui/components/PageProductDevelopment/template.hbs
> +    <HeaderContent @label="Product Development" @headline="Engineering excellence means building things to last">
I left that out intentially as I think it's a bit strange. If we want quotes I think we should be using proper ones but then what do we say by putting it in quotes anyway - to me that would indicate we're implying that nothing ever lasts or so which I'm not sure why we want to be implying that.

2020-02-06 09:18 UTC, ghislaineguerin commented on src/ui/components/PageProductDevelopment/template.hbs
> +    <p class="typography.lead">
@locks @marcoow I think we should create a card to style the lists.

2020-02-06 09:19 UTC, ghislaineguerin commented on src/ui/components/PageProductDevelopment/template.hbs
> +    <h2>
I will check and update the mockup if needed.

2020-02-06 09:26 UTC, marcoow commented on src/ui/components/PageProductDevelopment/template.hbs
> +    <p class="typography.lead">
I think I'm not clear what the intention of the issue is. Is is about adding the page and content only or also styling it? If so, can we do that without even having the shapes for the images etc., e.g. will the card not need to change potentially once we have the image shapes?

Anyway, I don't think we want a component to style this but a CSS block that we can apply?

2020-02-06 10:39 UTC, locks approved these changes

2020-02-06 11:11 UTC, ghislaineguerin approved these changes

2020-02-06 11:11 UTC, merged