implement Timify quote shape
mainmatter/mainmatter.com pull request #899
Opened 2020-02-19 10:58 UTC by locks

2020-02-26 09:57 UTC, locks commented
Needs new image.

2020-02-27 11:47 UTC, ghislaineguerin commented
Here's the image file. Can you add it to the PR and then I can adjust cropping?
![image](https://user-images.githubusercontent.com/845767/75442112-0a6e7e00-595f-11ea-99d8-4f1ebd8df2c7.png)
Abstract Link:
https://share.goabstract.com/9ed22beb-d90c-414c-863e-67efd28b16a4?mode=design&sha=c428d39bd14a3de12f9a173409e5a9b19c14c47f

2020-02-27 12:12 UTC, locks commented
Here's how it currently looks:

<img width="1488" alt="image" src="https://user-images.githubusercontent.com/32344/75443911-52d76d00-595a-11ea-9264-2042e68ba701.png">

2020-02-27 12:14 UTC, ghislaineguerin commented
@locks looks pretty good to me.

2020-02-27 12:33 UTC, marcoow requested changes
The image is 4.5MB 🐘

2020-02-27 12:34 UTC, marcoow commented on src/ui/components/ShapeQuoteTimify/template.hbs
> +    ANDREAS KNÜRR, TIMIFY CEO
Wouldn't it be better to do the up-casing via CSS?

2020-02-27 13:29 UTC, locks commented on src/ui/components/ShapeQuoteTimify/template.hbs
> +    ANDREAS KNÜRR, TIMIFY CEO
`small` already does it, HTML corrected!

2020-02-27 13:44 UTC, locks commented
@marcoow image shrunken to 600x and compressed to jpg in accordance to similar images that do not require alpha channel.

2020-02-27 14:11 UTC, marcoow commented on src/ui/components/ShapeQuoteTimify/template.hbs
> +<ShapeFeature @srcset="/assets/images/work/timify-quote.jpg">
This is not actually a prope `srcset` – see https://github.com/simplabs/simplabs.github.io/blob/9fde3763e97c2c65ca2348214b9937a888ad3d07/src/ui/components/ShapeFeatureTimify/template.hbs for an example

2020-02-28 12:02 UTC, marcoow approved these changes

2020-02-28 12:03 UTC, marcoow commented
I compressed the images. I recommend always running https://imageoptim.com/mac on all images.

2020-02-28 12:06 UTC, locks commented
I thought I did, maybe I missed the final jpg's 🤔 Thank you!

2020-02-28 12:46 UTC, merged