Blog post: emberjs.com from RFC to website
mainmatter/mainmatter.com pull request #904
Opened 2020-02-27 09:59 UTC by pichfl

This is a draft for my February blog post. I know I'm a bit late, but after seeing the ember website online, I really wanted to talk about the small changes I made, simply to show even a small portion of the work that went into this massive effort.

I'll create images tonight and use my 20% time tomorrow to finish everything, but I would love any feedback you have.

2020-02-27 11:38 UTC, marcoow commented
@pichfl people need to have time tomorrow to review this so it needs to be ready after our call so you can also address the feedback and we can get it out by the end of the day tomorrow.

2020-02-27 11:46 UTC, pichfl commented
I'll finish it up tonight, sorry for the tight schedule.

2020-02-28 10:04 UTC, marcoow reviewed
I think this is nice – just left some relatively minor comments. Also 2 additional points:

* breaking lines after 80 characters makes review **much** easier
* I think it'd be nice highlighting some of the components of the design system as examples so people get an understanding of what elements the pages are composed of and what it means to extract and define those?

2020-02-28 10:04 UTC, marcoow commented on _posts/2020-02-29-emberjs-website-rfc-to-launch.md
> +  image: /assets/images/posts/2020-02-29-emberjs-website-rfc-to-launch/og-image.png
This image is > 4MB 😱

2020-02-28 10:04 UTC, marcoow commented on _posts/2020-02-29-emberjs-website-rfc-to-launch.md
> +title: 'emberjs.com from RFC to website'
Should this be

```suggestion
title: 'emberjs.com: from RFC to website'
```

?

2020-02-28 10:04 UTC, marcoow commented on _posts/2020-02-29-emberjs-website-rfc-to-launch.md
> +description: 'Florian Pichler highlights details of the just released overhaul of the landing page for Ember.js, looking at the very details that make it possible to have consistant design in a distr
```suggestion
description: 'Florian Pichler highlights details of the just released overhaul of the landing page for Ember.js, looking specifically at how a distributed team of volunteers can achieve consistent design.'
```

?

2020-02-28 10:04 UTC, marcoow commented on _posts/2020-02-29-emberjs-website-rfc-to-launch.md
> +Shortly after I joined simplabs, Chris Manson (@mansona) approached me to become part of the team that was in charge of bringing the new landing page for Ember.js to fruition. Besides development, th
Should _"Chris Manson (@mansona)"_ link to Chris' Twitter?

2020-02-28 10:04 UTC, marcoow commented on _posts/2020-02-29-emberjs-website-rfc-to-launch.md
> +Shortly after I joined simplabs, Chris Manson (@mansona) approached me to become part of the team that was in charge of bringing the new landing page for Ember.js to fruition. Besides development, th
_"…into an actual page and design components that can be reused across the big universe for which the landing page is only the doorway…"_

maybe better say something like

_"…into a full-featured design system with elements and components that can be reused across the big universe for which the landing page is only the doorway…"_

2020-02-28 10:04 UTC, marcoow commented on _posts/2020-02-29-emberjs-website-rfc-to-launch.md
> +![Side by side comparison of the original website mockup from the rfc and the final mockup created by me](/assets/images/posts/2020-02-29-emberjs-website-rfc-to-launch/before-after.jpg)
let's use `srcset` here – see https://github.com/simplabs/simplabs.github.io/blob/master/_posts/2020-01-31-how-to-over-engineer-a-static-page.md for examples

2020-02-28 11:08 UTC, pichfl commented on _posts/2020-02-29-emberjs-website-rfc-to-launch.md
> +  image: /assets/images/posts/2020-02-29-emberjs-website-rfc-to-launch/og-image.png
That would be the full res comparison which isn't linked anywhere. The og-image is <40k

2020-02-28 11:57 UTC, marcoow commented on _posts/2020-02-29-emberjs-website-rfc-to-launch.md
> +![Side by side comparison of the original website mockup from the rfc and the final mockup created by me](/assets/images/posts/2020-02-29-emberjs-website-rfc-to-launch/before-after.jpg#full@680-1200-
We can only have 2 sizes per image

2020-02-28 11:57 UTC, marcoow commented on _posts/2020-02-29-emberjs-website-rfc-to-launch.md
> +![Side by side comparison of the original website mockup from the rfc and the final mockup created by me](/assets/images/posts/2020-02-29-emberjs-website-rfc-to-launch/before-after.jpg#full@680-1200-
Also the original version of this image has more than 4MB and we don't seem to be using it anyway.

2020-02-28 12:26 UTC, pichfl commented on _posts/2020-02-29-emberjs-website-rfc-to-launch.md
> +![Side by side comparison of the original website mockup from the rfc and the final mockup created by me](/assets/images/posts/2020-02-29-emberjs-website-rfc-to-launch/before-after.jpg#full@680-1200-
Fixed

2020-02-28 12:27 UTC, pichfl commented on _posts/2020-02-29-emberjs-website-rfc-to-launch.md
> +Shortly after I joined simplabs, Chris Manson (@mansona) approached me to become part of the team that was in charge of bringing the new landing page for Ember.js to fruition. Besides development, th
I removed that sentence, it wasn't a good start anyway.

2020-02-28 12:33 UTC, pichfl commented
> * I think it'd be nice highlighting some of the components of the design system as examples > so people get an understanding of what elements the pages are composed of and what it means to extract and define those?

I agree, but we are not quite finished with those components and / or their documentation, so this should be part of a separate post. For now, I wanted to just give a quick tour and highlight things that might be missed otherwise such as the new font.

2020-02-28 13:14 UTC, marcoow commented
@pichfl would it not be possible to show some of the elements you're **currently** using in a screenshot or so just as an example?

2020-02-28 13:18 UTC, marcoow commented
@pichfl: fyi, I ran the images through https://imageoptim.com/mac

2020-02-28 13:26 UTC, marcoow commented on _posts/2020-02-29-emberjs-website-rfc-to-launch.md
> +<small>You can also download a [full sized comparision, side by side](/assets/images/posts/2020-02-29-emberjs-website-rfc-to-launch/before-after-full.jpg). Be warned, it is nearly 5 MB.</small>
We cannot do this currently as this will end up in the bundle that the service worker preloads. You'd have to keep this outside of this repo.

2020-02-28 13:26 UTC, marcoow commented on _posts/2020-02-29-emberjs-website-rfc-to-launch.md
> +title: 'The little changes that helped to transform a RFC into emberjs.com'
```suggestion
title: 'The little changes that helped to transform an RFC into emberjs.com'
```

2020-02-28 13:26 UTC, marcoow commented on _posts/2020-02-29-emberjs-website-rfc-to-launch.md
> +Besides development, there is the task of converting the initial design mockup
```suggestion
Besides development, there was the task of converting the initial design mockup
```

?

2020-02-28 13:26 UTC, marcoow commented on _posts/2020-02-29-emberjs-website-rfc-to-launch.md
> +Metric fonts by Klimt, but it was necessary to find a solution that is Open
```suggestion
Metric fonts by Klimt, but it was necessary to find a solution that is open
```

2020-02-28 13:26 UTC, marcoow commented on _posts/2020-02-29-emberjs-website-rfc-to-launch.md
> +Source and does not involve licensing costs. After testing eight or more other
```suggestion
source and does not involve licensing costs. After testing eight or more other
```

2020-02-28 13:26 UTC, marcoow commented on _posts/2020-02-29-emberjs-website-rfc-to-launch.md
> +alternatives, we settled on an excellent Open Source font:
```suggestion
alternatives, we settled on an excellent open source font:
```

2020-02-28 13:26 UTC, marcoow commented on _posts/2020-02-29-emberjs-website-rfc-to-launch.md
> +symbolize that Ember's strength is represented by an amazing community and is
```suggestion
symbolize that Ember's strength is lies in its amazing community and its
```

2020-02-28 13:26 UTC, marcoow commented on _posts/2020-02-29-emberjs-website-rfc-to-launch.md
> +there for business.
```suggestion
reliability for businesses.
```

?

2020-02-28 13:26 UTC, marcoow commented on _posts/2020-02-29-emberjs-website-rfc-to-launch.md
> +doorway.
Might be worth considering starting with a bit of prose describing the background? "In 2018 there was an RFC for updating the website, there was just a mockup for the website, we needed to turn this into a design system" and so on – currently it seems you're diving in directly but most readers will have none of the background info.

2020-02-28 13:26 UTC, marcoow commented on _posts/2020-02-29-emberjs-website-rfc-to-launch.md
> +My allocated time donated by simplabs allowed me and others to bring the
```suggestion
Allocated time donated by simplabs allowed me and others to bring the
```

2020-02-28 14:05 UTC, jayjayjpg reviewed
This reads great! I left a few more suggestions for wording / phrase changes - feel free to apply any that you find useful

2020-02-28 14:05 UTC, jayjayjpg commented on _posts/2020-02-29-emberjs-website-rfc-to-launch.md
> +be reused across the big universe for which the landing page is only the
What do you think about the following wording to make it even more specific?

```suggestion
be reused across the Ember ecosystem even beyond the recently designed landing page which is only the
```

2020-02-28 14:05 UTC, jayjayjpg commented on _posts/2020-02-29-emberjs-website-rfc-to-launch.md
> +doorway.
```suggestion
beginning.
```

2020-02-28 14:05 UTC, jessica-jordan commented on _posts/2020-02-29-emberjs-website-rfc-to-launch.md
> +This post highlights some of the changes I proposed and made it to the final
```suggestion
This post highlights some of the changes I proposed and which made it to the final
```

2020-02-28 14:05 UTC, jessica-jordan commented on _posts/2020-02-29-emberjs-website-rfc-to-launch.md
> +![Side by side comparison of the original website mockup from the rfc and the final mockup created by me](/assets/images/posts/2020-02-29-emberjs-website-rfc-to-launch/before-after.jpg#full@1200-2761
I think this would be

```suggestion
![Side by side comparison of the original website mockup from the RFC and the final mockup created by me](/assets/images/posts/2020-02-29-emberjs-website-rfc-to-launch/before-after.jpg#full@1200-2761)
```

2020-02-28 14:05 UTC, jessica-jordan commented on _posts/2020-02-29-emberjs-website-rfc-to-launch.md
> +After discussion with the Learning team, the "Try out" section was removed.
I think it'd be

```suggestion
After a discussion with the Ember Learning Core team, the "Try out" section was removed.
```

2020-02-28 14:05 UTC, jessica-jordan commented on _posts/2020-02-29-emberjs-website-rfc-to-launch.md
> +settled yet and will become part of the second run of changes to the Ember.js
I think it'd be something like

```suggestion
settled yet and will become part of the second pass of changes to the Ember.js
```

2020-02-28 14:05 UTC, jessica-jordan commented on _posts/2020-02-29-emberjs-website-rfc-to-launch.md
> +Beyond the purely visual aspecs of the design, I also introduced some
```suggestion
Beyond the purely visual aspects of the design, I also introduced some
```

2020-02-28 14:05 UTC, jessica-jordan commented on _posts/2020-02-29-emberjs-website-rfc-to-launch.md
> +Some of them were inspired by [Tailwind](), while others are explicitly narrow
I think this still misses a link to the docs or the Github repo:

```suggestion
Some of them were inspired by [Tailwind](xxxxx), while others are explicitly narrow
```

2020-02-28 14:49 UTC, pichfl commented on _posts/2020-02-29-emberjs-website-rfc-to-launch.md
> +<small>You can also download a [full sized comparision, side by side](/assets/images/posts/2020-02-29-emberjs-website-rfc-to-launch/before-after-full.jpg). Be warned, it is nearly 5 MB.</small>
😓 I guess I'll just remove it then, not sure where to put it otherwise.

2020-02-28 14:57 UTC, pichfl commented on _posts/2020-02-29-emberjs-website-rfc-to-launch.md
> +doorway.
I wanted to express that the landing page is only the starting point for most of the other parts of the website such as the docs, guides, etc. Not sure if this change will have the same meaning.

2020-02-28 14:58 UTC, pichfl commented on _posts/2020-02-29-emberjs-website-rfc-to-launch.md
> +doorway.
Good point, will add something to explain where we started.

2020-02-28 17:04 UTC, marcoow commented
@pichfl can you rename the md file and images folder to have today's date and match the title of the post?

2020-02-28 17:14 UTC, marcoow requested changes

2020-02-28 17:14 UTC, marcoow commented on _posts/2020-02-29-emberjs-website-rfc-to-launch.md
> +![Examples for components created for the Ember Style Guide project](/assets/images/posts/2020-02-29-emberjs-website-rfc-to-launch/bcomponents.png#full@860-1720)
```suggestion
![Examples for components created for the Ember Style Guide project](/assets/images/posts/2020-02-29-emberjs-website-rfc-to-launch/components.png#full@860-1720)
```

The typo results in a broken image: 

<img width="1295" alt="Bildschirmfoto 2020-02-28 um 18 13 42" src="https://user-images.githubusercontent.com/1510/75569811-20ab3580-5a56-11ea-9276-cac92276bada.png">

2020-02-28 17:18 UTC, pichfl commented
@marcoow updated paths and fixed the typo

2020-02-28 17:19 UTC, marcoow approved these changes

2020-02-28 17:33 UTC, merged